paparazzi/paparazzi

sw/airborne/arch/stm32/mcu_arch.c
sw/airborne/arch/stm32/mcu_periph/i2c_arch.c

Reason is just to get the fix for usb control callbacks so luftboot works again:
https://github.com/libopencm3/libopencm3/commit/922d8f7079efd232c736e84df49214cec13fb9ea
Since rcc_ppre1_frequency and rcc_ppre2_frequency were also renamed in the meantime, make appropriate changes.

Update locm3 to get usb control callback fix for luftboot

---

conf/Makefile.linux

Make sure we link with same float abi (softfp, vfp) as we compile.
This *should* fix errors like
```
/usr/bin/ld: error: ap.elf uses VFP register arguments, foo.o does not
/usr/bin/ld: failed to merge target specific data of file foo.o
```
Not tested...

[build] use same float_abi for linking as for compiling

---

sw/ground_segment/cockpit/gcs.ml
sw/ground_segment/cockpit/live.ml
sw/ground_segment/cockpit/page_settings.ml
sw/ground_segment/cockpit/page_settings.mli
sw/ground_segment/cockpit/papgets.ml
sw/ground_segment/cockpit/papgets.mli
sw/ground_segment/tmtc/settings.ml
sw/lib/ocaml/papget.ml
sw/lib/ocaml/papget.mli
sw/lib/ocaml/papget_renderer.ml
sw/lib/ocaml/widgets.glade

Makes papgets working with several aircraft. If no target A/C specified, behavior is the same then before.
This will close #181 and a part of #1056

improve Papgets with multi aircraft support

---

conf/firmwares/subsystems/rotorcraft/navigation.makefile
conf/flight_plans/rotorcraft_basic.xml
sw/airborne/firmwares/rotorcraft/navigation.c
sw/airborne/firmwares/rotorcraft/navigation.h
sw/airborne/subsystems/navigation/waypoints.c
sw/airborne/subsystems/navigation/waypoints.h
sw/tools/generators/gen_flight_plan.ml

- each waypoint is a struct with multiple representations and flags (e.g. if absolute/global)
- factor out waypoints in separate files so it can be shared between firmwares later
- if a waypoint is defined with lat/lon instead of x/y in the flight plan, it is marked as an absolute/global waypoint and not moved upon GeoInit
Only for rotorcraft so far...

[navigation] implement global waypoints for rotorcraft

---

sw/airborne/arch/stm32/usb_ser_hw.c

- update libopencm3 so we have desig in F4 lib
- use desig_get_unique_id_as_string from libopencm3 instead of our own function

[stm32] use desig_get_unique_id from libopencm3

---

sw/ground_segment/cockpit/gcs.ml
sw/ground_segment/cockpit/live.ml
sw/ground_segment/cockpit/live.mli
sw/ground_segment/tmtc/messages.ml
sw/ground_segment/tmtc/server.ml
sw/lib/ocaml/pprz.ml
sw/lib/ocaml/pprz.mli

Improving efficiency of Ivy with simpler attached regexp by default (no timestamp), and by only waiting for ALIVE to detect new plane in 'messages'.
When using timespampped messages (or `-local_timestamp` option of link), other programs (GCS, server, messages) have to run with the `-timestamp` option.
When messages is used with something else than an autopilot (or anything sending the `ALIVE` message), but still sending telemetry message, the option `-force` can be used to force waiting on all messages to find new senders.
Tested and working in sim and real link. CPU and network usage slightly improved, even with a single aircraft.

Improvement of Ivy efficiency

---

conf/modules/meteo_stick.xml
conf/modules/module.dtd
sw/airborne/arch/linux/mcu_periph/spi_arch.c
sw/airborne/arch/lpc21/mcu_periph/spi_arch.c
sw/airborne/mcu_periph/spi.h
sw/airborne/modules/meteo/meteo_stick.c
sw/airborne/modules/meteo/meteo_stick.h
sw/airborne/modules/meteo/meteo_stick_calib.c
sw/airborne/modules/meteo/meteo_stick_calib.h
sw/airborne/peripherals/eeprom25AA256.c
sw/airborne/peripherals/eeprom25AA256.h
sw/tools/generators/gen_aircraft.ml

Update meteo stick module.
The main purpose of the pull request is to cross-check that the changes in SPI input/ouput_length index (from uint8 to uint16) is okay.

Meteo stick

---

sw/airborne/arch/linux/subsystems/settings_arch.c
sw/airborne/arch/lpc21/subsystems/settings_arch.c
sw/airborne/arch/sim/subsystems/settings_arch.c
sw/airborne/arch/stm32/subsystems/settings_arch.c
sw/airborne/subsystems/settings.c
sw/airborne/subsystems/settings.h

Write persistent settings to a binary file (by default `pprz_persistent_settings.binary` in same directory).
On loading it also check the file size matches the PersistentSettings struct size to detect if persistent settings were added/removed). While this doesn't catch all errors (like replacing a setting of same size), it should be good enough for most cases...
Should close #969

implement persistent settings for linux arch

---

sw/simulator/nps/nps_fdm_jsbsim.cpp

not the best implementation, but should work with current
paparazzi-jsbsim package (from 2012) and latest jsbsim version

[nps] update nps_fdm_jsbsim to be compatible with latest jsbsim

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_float.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_int.c

Use quat_of_eulers instead of quat_from_rpy_cmd to match what users expect from attitude_set_rpy_setpoint.
Specifically actually make the attitude primitive in the flight plan work as expected.

[rotorcraft] fix attitude_set_rpy_setpoint

---

conf/airframes/ENAC/fixed-wing/merlin.xml
conf/airframes/LAAS/mmlaas_N1.xml
conf/airframes/LAAS/mmlaas_N2.xml
conf/airframes/LAAS/mmlaas_N3.xml
conf/airframes/examples/delta_wing_minimal.xml
conf/airframes/examples/easy_glider.xml
conf/airframes/examples/easystar.xml
conf/airframes/examples/easystar_ets.xml
conf/airframes/examples/funjet.xml
conf/airframes/examples/funjet_cam.xml
conf/airframes/examples/microjet.xml
conf/airframes/examples/twinjet.xml
conf/airframes/examples/twinstar.xml
conf/airframes/twinjet_overo.xml
conf/airframes/usb_test.xml
conf/firmwares/subsystems/fixedwing/ahrs_infrared.makefile
conf/modules/ahrs_infrared.xml
conf/modules/infrared_adc.xml
conf/modules/infrared_i2c.xml
sw/airborne/arch/sim/sim_ir.c
sw/airborne/firmwares/fixedwing/main_ap.c
sw/airborne/modules/ahrs/ahrs_infrared.c
sw/airborne/modules/ahrs/ahrs_infrared.h
sw/airborne/subsystems/sensors/infrared.c

Since we want to get rid of the explicit AHRS calls in main and want to convert them to modules with ABI bindings, start with the simple ahrs_infrared, which already depends on the infrared_adc|i2c module anyway...
Uses `GPS_TRIGGERED_FUNCTION` to call `ahrs_infrared_update_gps`

convert AHRS infrared to module

---

CHANGELOG.md
conf/Makefile.linux
sw/airborne/arch/linux/mcu_periph/sys_time_arch.c
sw/airborne/arch/linux/mcu_periph/sys_time_arch.h
sw/airborne/arch/linux/rt_priority.h
sw/airborne/boards/ardrone/baro_board.c
sw/airborne/boards/ardrone/navdata.c
sw/airborne/boards/ardrone/navdata.h
sw/airborne/subsystems/imu/imu_ardrone2_raw.h

Since using SIGALRM to call the sys_tick_handler (via `setitimer`) can cause problems like interrupting some other syscalls (i.e. read,write, ioctl), setup a separate thread and use timer_fd instead.
That is a Linux-specific set of functions that presents POSIX timers as file descriptors rather than signals.
If the thread runs with a normal priority it can happen that some timer events are missed (and hence sys_time not updated in time). So added a function to set a higher prio for that thread (needs root rights or properly set up limits for the user).
In some simple tests no events were missed when running with prio 29 via SCHED_FIFO, even if events would be missed, the sys_tick_handler is called the appropriate number of times (so that the time is correct again after)...

[arch/linux] sys time thread

---

conf/firmwares/subsystems/shared/udp.makefile
sw/airborne/arch/linux/mcu_periph/udp_arch.c
sw/airborne/arch/linux/mcu_periph/udp_arch.h
sw/airborne/arch/linux/udp_socket.c
sw/airborne/arch/linux/udp_socket.h

Only create one socket for sending and receiving, instead of two where you use one only to send and the other only to receive.
There should be no reason/need to create two separate ones...
Also add udp_socket.[ch] to make it easier to use only the UDP sockets without the UART like mcu_periph/udp interface around it.
Provides the functions:
- `udp_socket_create`
- `udp_socket_send`
- `udp_socket_recv`
- `udp_socket_recv_dontwait`
Which should make it easy to replace the other udp socket wrappers used in e.g. modules/computer_vision and hence address #1079

Single udp socket

---

conf/firmwares/rotorcraft.makefile
conf/firmwares/setup.makefile
conf/firmwares/subsystems/fixedwing/autopilot.makefile
conf/firmwares/test_progs.makefile
sw/airborne/arch/linux/mcu_periph/sys_time_arch.c

Instead of simply adding up the sys_time ticks, seconds, get current time from CLOCK_MONOTONIC and directly set sys_time from that (difference to clock monotonic time at startup).

[arch/linux] sys_time: get time from CLOCK_MONOTONIC

---

conf/airframes/ENAC/fixed-wing/jp.xml
conf/firmwares/subsystems/fixedwing/fdm_crrcsim.makefile
conf/simulator/jsbsim/aircraft/YardStik.xml
conf/simulator/jsbsim/aircraft/easystar.xml
sw/airborne/subsystems/ins/ins_float_invariant.c
sw/simulator/nps/nps_fdm.h
sw/simulator/nps/nps_fdm_crrcsim.c
sw/simulator/nps/nps_fdm_jsbsim.cpp
sw/simulator/nps/nps_sensor_accel.c
sw/simulator/nps/nps_sensor_gyro.c

Use `body_accel` (from `GetAccelBody` in case of JSBSim FDM) instead of accel wrt. ECEF frame.
While here also use the angular velocity wrt. inertial frame to simulate gyro.

[nps] fix accelerometer and gyroscope sensor simulation

---

.travis.yml
Makefile.ac
sw/tools/generators/gen_aircraft.ml
tests/examples/01_compile_all_aircrafts.t

Mostly interesting for running the tests (e.g. compiling all aircrafts in a given conf.xml).
If the CONF_XML environment variable is set, use that conf.xml file instead of the standard $PAPARAZZI_HOME/conf/conf.xml
Meaning you can run tests for a different conf without changing the conf.xml symlink, e.g.
`CONF_XML=$PAPARAZZI_HOME/conf/conf_tests.xml prove tests/examples`

Possibilty to specify conf.xml file for building aircrafts

---

sw/ground_segment/cockpit/Makefile
sw/ground_segment/cockpit/gcs.ml
sw/lib/ocaml/Makefile
sw/lib/ocaml/http.ml

Should fix #1133 and the change in lablgtk2 2.18 that resulted in:
```
File "gcs.ml", line 654, characters 23-29:
Error: This expression has type int32 but an expression was expected of type
Gdk.native_window
```

[OCaml] use camlp4 to ifdef around netclient/lablgtk version differences

---

sw/airborne/math/pprz_algebra_int.h
sw/airborne/subsystems/ins/ins_int.c

If INS_BODY_TO_GPS_X|Y|Z is defined (in cm!) use it to correct for this offset in the INS gps position update.
start solving #1060
Todo:

[ins] consider BODY_TO_GPS translation

---

sw/lib/ocaml/myocamlbuild.ml

Instead of hardcoding the gtk include paths for the pprz lib c stub we
now run pkg-config to get them. It probably could be more efficient
and/or safer if we did some more checks.

[ocaml] Use pkg-config for gtk cflags.

---

conf/airframes/bebop.xml
conf/conf_example.xml
conf/conf_tests.xml
sw/airborne/boards/baro_board_ms5611_i2c.c
sw/airborne/boards/baro_board_ms5611_spi.c
sw/airborne/boards/bebop/baro_board.h
sw/airborne/modules/sensors/baro_ms5611_i2c.c
sw/airborne/modules/sensors/baro_ms5611_spi.c
sw/airborne/peripherals/ms5611.c
sw/airborne/peripherals/ms5611.h
sw/airborne/peripherals/ms5611_i2c.c
sw/airborne/peripherals/ms5611_i2c.h
sw/airborne/peripherals/ms5611_spi.c
sw/airborne/peripherals/ms5611_spi.h

The MS5607 has half the resolution of the MS5611.
- added ms5607_calc function for it
- added an extra parameter to init (set it to TRUE if the baro is really a MS5611)
- the baro_board wrappers take a BB_MS5611_TYPE_MS5607 define (set to TRUE for bebop)
Now I get correct baro measurements on the Bebop ;-)

[peripherals] ms5611 driver now also supports ms5607

---

sw/airborne/subsystems/gps/gps_furuno.c
sw/airborne/subsystems/gps/gps_nmea.c
sw/airborne/subsystems/gps/gps_nmea.h

- parse GSV message to get satellite information
- only populating svinfos with 12 channels of GPS sat info (not saving GLONASS sat info)
- get geoid separation and calculate gps altitude (above ellipsoid) accordingly

GPS NMEA parser improvements

---

sw/airborne/subsystems/gps/gps_furuno.c
sw/airborne/subsystems/gps/gps_nmea.c
sw/airborne/subsystems/gps/gps_nmea.h

The init function of the furuno GPS tried to add all settings messages to the transmit buffer in one go.
Since the uart buffer can't hold that many chars, only the first 4 or so config sentences were actually sent.
- Added nmea_configure function that is called in GpsEvent until configuration is finished.
- updated settings, enabled GSV message

Fix GPS furuno (Bebop)

---

conf/settings/nps.xml
sw/simulator/nps/nps_autopilot.h
sw/simulator/nps/nps_autopilot_fixedwing.c
sw/simulator/nps/nps_autopilot_rotorcraft.c
sw/simulator/nps/nps_ivy_common.c
sw/simulator/nps/nps_ivy_fixedwing.c
sw/simulator/nps/nps_ivy_mission_commands.c
sw/simulator/nps/nps_ivy_rotorcraft.c
sw/simulator/nps/nps_sensor_accel.c
sw/simulator/nps/nps_sensor_accel.h
sw/simulator/nps/nps_sensor_baro.c
sw/simulator/nps/nps_sensor_baro.h
sw/simulator/nps/nps_sensor_gps.c
sw/simulator/nps/nps_sensor_gps.h
sw/simulator/nps/nps_sensor_gyro.c
sw/simulator/nps/nps_sensor_gyro.h
sw/simulator/nps/nps_sensor_mag.c
sw/simulator/nps/nps_sensor_mag.h
sw/simulator/nps/nps_sensor_sonar.c
sw/simulator/nps/nps_sensor_sonar.h
sw/simulator/nps/nps_sensors.c
sw/simulator/nps/nps_sensors_utils.c
sw/simulator/nps/nps_sensors_utils.h

It is a bit of a hack, especially we can't disable changing settings if datalink is disabled,
since we need to parse that to enable the datalink via settings again.
Also previously datalink_time was never reset to 0...
Nevertheless it should suffice for most cases and close #934

[NPS] add possibility to simulate loss of datalink/downlink

---

sw/airborne/subsystems/datalink/telemetry.c
sw/airborne/subsystems/datalink/telemetry.h
sw/airborne/subsystems/datalink/telemetry_common.h
sw/tools/generators/gen_periodic.ml

Make sure that the msg names are stored in rom (.text) and not ram (.data) by making them const.
Since the callbacks are not const, replace the telemetry_msg struct by typedef for only the name and separate callback array.
This saves ~ 2.5k of RAM with a standard telemetry file, which is really nice if you try to run Paparazzi on a low end board like the CC3D with only 20k RAM.

[telemetry] store periodic telemetry msg names as const to save ram

---

conf/messages.xml
sw/airborne/modules/air_data/air_data.c
sw/airborne/modules/air_data/air_data.h

On piloted aircraft, the CAS (actually IAS) is used as a flight indication and thus is the controlled airspeed.
I suggest to use EAS (very close to CAS for us and easier to compute) for airspeed (the value updating the state interface) and compute TAS (the "real" airspeed) as an extra indication, especially in message instead of tas_factor.
One of the reason is that to get a correct TAS you need P, T and P_diff, while EAS/CAS only requires P_diff. Today I flew with an uncalibrated temperature sensor (it was their but not needed) and the result is that my airspeed was completely wrong.
http://en.wikipedia.org/wiki/Calibrated_airspeed
http://en.wikipedia.org/wiki/Indicated_airspeed
http://en.wikipedia.org/wiki/Equivalent_airspeed

[air_data] use CAS/EAS for airspeed and send TAS in message

---

conf/simulator/jsbsim/aircraft/Eternity.xml

JSBSIM model of Eternity aircraft to be used with NPS simulation. There are still some missing minor additions, but detailled enough to be used as a base. Most of the coefficients are coming from either wind-tunnel measurements or AVL numerical calculations.

JSBSIM model of Eternity A/C

---

conf/Makefile.linux
conf/Makefile.lpc21
conf/Makefile.nps
conf/Makefile.stm32

-ggdb3 make slightly bigger .elf files, but allows gdb to understand
macros, which paparazzi uses somewhat extensively.
Make this the default, since it only impacts the size of the debug sections and
not the size of the flashed binary (in the lpc21/stm32 case).
On the linux system we really don't care about these few more bytes...

[build] use -ggdb3 DEBUG_FLAGS by default

---

sw/airborne/state.c

as is the normal case in the fixedwing firmware.
While this fixes the immediate issue of making stateGetPositionLla_i() usable in fixedwing firmware,
we really need to properly fix/implement UTM support in the state interface.
That means removing the HACK that ENU = UTM!
See also #455 and #641

[state interface] fix LLA calculation if only UTM origin initialized

---

sw/ground_segment/cockpit/gcs.ml
sw/ground_segment/cockpit/live.ml
sw/ground_segment/cockpit/live.mli

the parameter needs to be a comma separated list of aircraft ids, e.g.
$ ground_segment/cockpit/gcs -ac_ids 11,22
$ ground_segment/cockpit/gcs -ac_ids 33
to display the Aircrafts with IDs 11 and 22 in first GCS, and only the aircraft with ID 33 in the second one.
Should close #1056

[gcs] add -ac_ids option to specify list of displayed aircrafts

---

conf/airframes/examples/quadrotor_lisa_m_2_pwm_spektrum.xml
conf/airframes/examples/quadrotor_lisa_mx.xml
sw/airborne/subsystems/actuators/motor_mixing.h
sw/airborne/subsystems/actuators/motor_mixing_types.h
sw/tools/motor_mixing.py

The intention is to make it easier to configure for common multitrotor configurations.
Motor counting/numbering order is always clockwise, starting with the front motor (for + frame) or left front motor (x frame). This first motor always turns CW, and alternates from there...
Also define `MOTOR_<position>` (e.g. `MOTOR_FRONT_LEFT`) for each motor to be able to use that in the command laws.

[rotorcraft] predefined motor_mixing for common configurations

---

sw/tools/calibration/calibration_utils.py
sw/tools/calibration/report_imu_scaled.py

A reporting tool to quickly analyze and report scaled IMU data. Useful when building multiple aircraft frames and need to quickly profile vibration benchmarks.
```
$ ./report_imu_scaled.py -h
Usage: report_imu_scaled.py [options] log_filename.data
Run report_imu_scaled.py --help to list the options.
Options:
-h, --help            show this help message and exit
-i AC_ID, --id=AC_ID  aircraft id to use
-p, --plot            Show sensor plots
-s START, --start=START
start time in seconds
-e END, --end=END     end time in seconds
-v, --verbose         
```
Invocation without any options:
```
./report_imu_scaled.py ../../paparazzi/var/logs/15_05_30__17_12_41.data
ACCEL : Time Range(26.457 : 168.714)
ax      ay      az
Min   [-27.173 -22.560 -94.397] m/s2
Max   [ 28.475  15.217  63.792] m/s2 …
```

Report tool for IMU Scaled messages

---

conf/flight_plans/dynamic_sectors.xml
conf/flight_plans/flight_plan.dtd
sw/ground_segment/cockpit/live.ml
sw/lib/ocaml/mapFP.ml
sw/lib/ocaml/mapFP.mli
sw/tools/generators/gen_flight_plan.ml

Allow dynamic sectors (#643)
Currently, it is activated by adding the attribute `type="dynamic"` since it is very experimental code.
But it should work with concave hulls.

Dynamic sectors

---

sw/airborne/arch/linux/mcu_periph/i2c_arch.c
sw/airborne/subsystems/imu/imu_bebop.c
sw/airborne/subsystems/imu/imu_mpu60x0_i2c.c

fixes #1210
needs to be tested as I do not have any Linux target (Bebop, BBB)

[linux] use 8 bit I2C address scheme for all drivers

---

sw/airborne/subsystems/actuators/motor_mixing.c

Calculate the amount of yaw authority left after applying roll, pitch and throttle commands.
Then limit the yaw command to that.
Simple first shot at improving the priorities in the saturation case, see #385.
Calculating the mean_cmd should not not actually be necessary for symmetric airframes without any trims set.
But it shouldn't hurt....
Should (tm) result in zero saturation failures like this, but might severly limit yaw authority.
Maybe find some sort of compromise, e.g. use MOTOR_MIXING_MAX_SATURATION_OFFSET when bounding yaw or allow to give less throttle to get more yaw authority....
Not tested in real flight, meant as a basis for discussion/tests...

[rotorcraft] try to improve motor mixing priorities

---

conf/settings/nps.xml
sw/simulator/gaia.ml
sw/simulator/nps/nps_atmosphere.c
sw/simulator/nps/nps_atmosphere.h
sw/simulator/nps/nps_fdm.h
sw/simulator/nps/nps_fdm_crrcsim.c
sw/simulator/nps/nps_fdm_jsbsim.cpp
sw/simulator/nps/nps_ivy_common.c
sw/simulator/nps/nps_main.c
sw/simulator/nps/nps_main.h

Listen to WORLD_ENV message from gaia environment simulator.
So you can use the gaia gui to adjust the wind dir/speed, gps_availability and time factor in the NPS sim.
This means you can now also more easily adjust the time factor during runtime (without needing to interrupt NPS with CTRL-Z)
Also added a slider for wind up to the gaia gui.

[NPS] support gaia environment simulator

---

conf/flight_plans/rotorcraft_basic.xml
sw/airborne/firmwares/rotorcraft/navigation.h

This make the `heading` flight plan primitive usable for rotorcrafts.
It has a different behaviour than for fixedwings (where you basically specify a course to fly).
For rotorcrafts this sets the heading/yaw.

[rotorcraft] make the heading privitive usable for rotorcrafts

---

conf/airframes/ardrone2_indi.xml
conf/firmwares/subsystems/rotorcraft/stabilization_indi.makefile
conf/messages.xml
conf/settings/control/stabilization_att_indi.xml
conf/telemetry/default_rotorcraft.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_indi.h

This is a slightly simplified version of the Incremental Nonlinear Dynamic Inversion (INDI) controller I made for quadrotor attitude control. I tried to condense it to a form where it can be useful and understandable for others.
I submitted a paper to the journal of guidance, control and dynamics which covers all the details. In short: By measuring the angular acceleration (which is obtained by deriving and filtering it from the gyroscope) we can measure how much the actual angular acceleration differs from the desired angular acceleration. By multiplying this with the inverse of the actuator effectiveness we get the correct increment of the input that will result in the desired increment in angular acceleration. The main benefit is that disturbances can be rapidly compensated and …

INDI simplified

---

conf/control_panel_example.xml
sw/supervision/pc_control_panel.ml

When you use #AIRCRAFT# as a constant parameter to a program in your
session, it will be automatically replaced by the name selected in the
A/C dropdown combo box of the Paparazzi Center. This makes it possible
to create generic sessions that start programs which need to know which
aircraft is of interest. For example settings.
This is a possible solution to the #1215 issue.

[PPRZ Center] Add #AIRCRAFT# placeholder constant.

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_int.c

This should (tm) result in less of a quantization error for the integral part (less static offset).
Reduce the GAIN_PRESCALER_I accordingly so that the gains set in the airframe file keep same scale.
While here also simplify the fb command prescalers/scaling...

stabilization quat_int IERROR scale fix

---

conf/control_panel_example.xml

These sessions open real time plotters with curves and constants prepopulated. Also it locates the windows more or less nicely on the screen.
When we add positioning parameter to messages and settings we could put those windows in predefined places too.
After starting one of the two sessions you only have to switch to the correct message set using the settings app. And you should :tm: be good to go! :smile_cat:

[pprz center] Added Raw and Scaled sensor session examples.

---

conf/control_panel_example.xml
sw/ground_segment/tmtc/messages.ml
sw/ground_segment/tmtc/settings.ml

You can now provide for example ```-g 300x400-0-200``` to settings and messages agents to set the position and size of the window on launch. Useful if you want to recreate a session exactly. Useful for sessions with a lot of windows like the Raw Sensors and Scaled Sensor sessions.

[ground segment] Added geometry param to messages and settings agents.

---

conf/boards/ardrone2.makefile
conf/boards/bebop.makefile
sw/airborne/firmwares/rotorcraft/main.c

This is a kludge until we can better leverage threads and have real events.
Without this limit the event flags will constantly polled as fast as possible,
resulting on 100% cpu load on boards with an (RT)OS.
On bare metal boards this is not an issue, as you have nothing else running anyway.
Enable this for the bebop and ardrone2 by default.
Alternative to #1239 and should fix #1233

[rotorcraft][linux] limit main/event loop to 1kHz

---

sw/airborne/subsystems/actuators/motor_mixing_types.h

Define `MOTOR_MIXING_REVERSE` to TRUE to reverse the yaw (motor rotation directions)
- flag works on all types
- removing X_CCW type

Add a flag to default motor_mixing types to reverse direction

---

sw/ground_segment/cockpit/live.ml

This fixes the
```
Fatal error: exception Failure("File not found: /tmp/airframe.dtd")
```
problem when serving the airframe file via http (starting server with `-http` option).
Since it downloads the airframe file to `/tmp` it can't find the airframe.dtd there...

[gcs] don't prove airframe dtd if served via http

---

sw/ground_segment/tmtc/kml.ml
sw/ground_segment/tmtc/kml.mli
sw/ground_segment/tmtc/server.ml
sw/ground_segment/tmtc/server_globals.ml

Use the port and hostname for serving config xml files via http.

[server] set http port: replace -kml_port option with -port

---

conf/control_panel_example.xml
sw/supervision/pc_control_panel.ml

Add possibility to launch global commands from tools menu.
Prefixing a program command in control_panel.xml with `$` will strip the `$` and then execute the command.
This makes it possible to start programs without knowing their absolute path.
Already used to start a simple http server from python.
Also parse the args from the programs section of control_panel.xml when starting them from the tools menu.
This makes it possible to specify default args.

[pprz center] improve handling of programs from control_panel.xml

---

conf/airframes/ardrone2.xml
conf/airframes/ardrone2_indi.xml
conf/airframes/ardrone2_opticflow_hover.xml
conf/airframes/bebop.xml
conf/airframes/examples/quadrotor_lisa_m_2_pwm_spektrum.xml
conf/airframes/examples/quadrotor_navgo.xml
conf/conf_example.xml

This will change the effect of the gains (depending on the type), but should be finally correct.
Especially the yaw commands have about half the effect now...
Needs testing on ardrone and bebop, and probably some adjustment of the gains.

[airframes] use standard motor mixing types for some quads

---

conf/boards/ardrone2.makefile
conf/boards/bebop.makefile
conf/firmwares/rotorcraft.makefile
sw/airborne/boards/ardrone/board.c
sw/airborne/boards/ardrone/electrical.c
sw/airborne/boards/bebop/board.c
sw/airborne/mcu.c
sw/airborne/mcu.h

and call it at the end of mcu_init
This should be used to init board functions like killing other processes on the Parrot drones
or initializing other onboard peripherals like the cmos cam chips.
So we use this instead of killing progs in electrical_init.
Replaces #1251 and is related to #1252

[boards] add an optional board_init() function

---

conf/settings/control/ctl_yaw.xml
sw/airborne/firmwares/fixedwing/stabilization/stabilization_adaptive.h

just found a typo due to the renaming of by to ny in the .h

[stab] fixedtypo in .h and reset max value to something resonable

---

sw/lib/python/pprz_msg/message.py
sw/lib/python/pprz_msg/messages_xml_map.py
sw/lib/python/pprz_msg/pprz_transport.py
sw/lib/python/serial_msg_interface.py

Add some utilities and a serial link interface to decode/encode PPRZ messages over a serial link in Python

Python pprz msg

---

conf/messages.xml
sw/airborne/arch/linux/mcu_periph/i2c_arch.c
sw/airborne/arch/stm32/mcu_periph/i2c_arch.c
sw/airborne/mcu_periph/i2c.c
sw/airborne/mcu_periph/i2c.h
sw/airborne/test/subsystems/test_imu.c

- remove unused i2c error vars and actually count entry of i2c_error irq on STM32
- I2C: add watchdog reset counter to i2c_errors
- on STM32 increment wd_reset_cnt when the watchdog resets the bus
- send this counter in I2C_ERRORS
- arch/linux: inc error counters if read/write failed (better use some existing ones with not quite matching names than no reports)

[I2C] cleanup error counters and reports

---

conf/settings/control/rotorcraft_guidance.xml
conf/settings/control/stabilization_att_float_euler.xml
conf/settings/control/stabilization_att_float_quat.xml
conf/settings/control/stabilization_att_int.xml
conf/settings/control/stabilization_att_int_quat.xml
conf/settings/control/stabilization_rate.xml
conf/settings/estimation/body_to_imu.xml
conf/settings/nps.xml
conf/settings/rotorcraft_basic.xml
conf/settings/settings.dtd
conf/settings/test_settings.xml
sw/lib/ocaml/gen_common.ml
sw/lib/ocaml/gen_common.mli
sw/lib/ocaml/gtk_tools.ml
sw/lib/ocaml/gtk_tools.mli
sw/supervision/paparazzicenter.ml
sw/supervision/pc_aircraft.ml
sw/tools/generators/gen_aircraft.ml
sw/tools/generators/gen_settings.ml

If not target attribute is given, the settings are added for all targets like before.
This makes it easier to add settings files to the conf that are only valid for some targets like nps or some that you don't want when using the test progs.
Beware of: if you compile a target that unloads some settings or modules (e.g. the sim) after you uploaded to the ap, the `var/aircrafts/<ac>/settings.xml` file that has all usable settings combined will change ~~~and the hence the wrong ones used in GCS and settings prog~~~.
Now the calculation of the MD5sum is taking unloaded settings into account, meaning it will change and warn the user if the last compiled target has different settings.

[settings] add optional target attribute to settings

---

sw/ground_segment/misc/natnet2ivy.c

The new version of Motive comes with quite some benefits, so we updated our optitrack system software. That requires these natnet changes to make it work.

update natnet to version 2.7

---

sw/ground_segment/multimon/filter-i386.h
sw/ground_segment/multimon/filter.h

extern inline has different meaning in gnu11 (C99).
We want static inline here, which works in both old and new versions.
See also https://gcc.gnu.org/gcc-5/porting_to.html

[multimon] fix compilation on gcc 5.x

---

conf/messages.xml
sw/airborne/firmwares/demo/demo_ahrs_actuators.c
sw/airborne/firmwares/fixedwing/datalink.c
sw/airborne/firmwares/rotorcraft/datalink.c
sw/airborne/firmwares/rotorcraft/main.c
sw/airborne/modules/datalink/extra_pprz_dl.h
sw/airborne/subsystems/datalink/datalink.h
sw/airborne/subsystems/datalink/downlink.c
sw/airborne/test/mcu_periph/test_adc.c
sw/airborne/test/peripherals/test_ami601.c
sw/airborne/test/peripherals/test_lis302dl_spi.c
sw/airborne/test/peripherals/test_ms2100.c
sw/airborne/test/subsystems/test_ahrs.c
sw/airborne/test/subsystems/test_imu.c
sw/airborne/test/subsystems/test_radio_control.c
sw/airborne/test/subsystems/test_settings.c
sw/airborne/test/test_baro_board.c
sw/airborne/test/test_can.c
sw/airborne/test/test_datalink.c
sw/airborne/test/test_telemetry.c
sw/ground_segment/tmtc/link.ml
sw/ground_segment/tmtc/server.ml

this type stuff in OCaml is such a pain...
Fix sending of LINK_REPORT message in link so that server can properly report TELEMETRY_STATUS for each link.
Also actually fill `tx_msgs` and add `datalink_nb_msgs`.
should fix #1278
~~~ping times still seem to be wrong...~~~

[link] try to fix sending LINK_REPORT

---

sw/airborne/arch/linux/rt_priority.h
sw/airborne/modules/computer_vision/viewvideo.c

A simple attempt to slightly improve the scheduling, so that taking a shot doesn't block the rest so much.
This sets the computer vision thread nice level to 10, so that the main "thread" should get a little more.
It does in no way guarantee that something in the cv thread (like taking a pic) will not block the main functions like estimation, stabilization.
A better long term solution would probably be to run both the main program/thread and this module with the FIFO scheduler and give the cv thread a really low prio.
Not tested due to lack of hardware right now...
Making a pull request to ease testing, documentation and discussion about this...

[modules] viewvideo: be nice to other threads

---

sw/airborne/arch/linux/mcu_periph/uart_arch.c
sw/airborne/arch/lpc21/mcu_periph/uart_arch.c
sw/airborne/arch/stm32/mcu_periph/uart_arch.c
sw/airborne/firmwares/setup/usb_tunnel.c
sw/airborne/link_mcu_usart.c
sw/airborne/mcu_periph/uart.c
sw/airborne/mcu_periph/uart.h
sw/airborne/mcu_periph/udp.c
sw/airborne/mcu_periph/udp.h
sw/airborne/modules/hott/hott.c
sw/airborne/modules/loggers/direct_memory_logger.c
sw/airborne/modules/loggers/high_speed_logger_direct_memory.c
sw/airborne/subsystems/ahrs/ahrs_gx3.c
sw/airborne/subsystems/imu/imu_um6.c
sw/airborne/test/generic_uart_tunnel.c
sw/airborne/test/mcu_periph/test_uart.c
sw/airborne/test/mcu_periph/test_uart_echo.c
sw/airborne/test/mcu_periph/test_uart_send.c

Since these functions only add one byte to the tx buffer but don't necessarily already send that byte, rename them to better reflect the functionality.

Rename uart/udp_transmit to uart/udp_put_byte

---

conf/messages.xml
sw/airborne/subsystems/gps.c

In an attempt to reduce confusion and make debugging easier, add hmsl to the GPS_LLA message.

Message gps lla with hmsl

---

sw/airborne/arch/linux/mcu_periph/uart_arch.c

if the serial port can't be openend (e.g. because the device is wrong/doesn't exist), set the reg_addr to NULL and properly check that everywhere
should close #1296

[arch/linux] uart: fix crash if device is wrong

---

sw/tools/flash_scripts/bmp_jtag_flash.scr
sw/tools/flash_scripts/bmp_swd_flash.scr

This should fix situations where it is impossible to program a target
using JTAG or SWD as the target can not be found.
Also added comments and a check if the load was successful.

[BMPM] Tell Black Magic probe to use the reset pin before scanning

---

sw/airborne/arch/stm32/apogee.ld
sw/airborne/arch/stm32/elle0.ld
sw/airborne/arch/stm32/krooz.ld
sw/airborne/arch/stm32/lisa-mx.ld
sw/airborne/arch/stm32/navstik.ld
sw/airborne/arch/stm32/stm32f4_discovery.ld
sw/airborne/arch/stm32/subsystems/settings_arch.c

This should fix #600
To make things simple we always use the last page of the flash. We also assume for the F4 cores that all pages are the same size. This means the current code will likely brake for very small flash sizes under 256kb. Which we are not very likely to use but it needs to be kept in mind.

[STM32F4] Added support for persistent settings on STM32F4.

---

sw/airborne/subsystems/electrical.c

As shown by Thomas, there was a possibility of this calculation failing if the command was larger than max... did not test this on a drone but should work

fix non-real number possibility in current calculation

---

sw/airborne/subsystems/electrical.c

This change allows to define MILLIAMP_AT_ZERO_THROTTLE, which is the current estimation when the motors are running, but zero throttle is applied (this is relevant for rotorcrafts). This makes it possible to calibrate for a change in the magnetic field caused by starting the motors.
By default, MILLIAMP_AT_ZERO_THROTTLE is set to 0, so there is no change needed for existing airframe configurations.
Additionally, the range of x, which represents the throttle command, is now limited to [0, 1] in both directions to prevent math errors.

Implemented MILLIAMP_AT_ZERO_THROTTLE in current estimation

---

conf/airframes/examples/setup_apogee.xml
conf/firmwares/test_progs.makefile
sw/airborne/test/test_baro_board.c
sw/airborne/test/test_baro_board_imu.c
sw/airborne/test/test_baro_board_imu.h

The airframe manifest + improved test programs allowed us verifying basic functionality of the board without jumping straight into the aircraft firmware - which maybe undecided for a particular user. 
Let me know if everything complies with paparazzi's standards or should be redone.
Jan

IMU testing + test airframe for apogee

---

conf/airframes/BR/bebop_default.xml
conf/airframes/BR/bebop_indi.xml
conf/airframes/ENAC/quadrotor/ard2_base_digit.xml
conf/airframes/ENAC/quadrotor/ard2_base_vision.xml
conf/airframes/TUDelft/conf.xml
conf/airframes/examples/ardrone2.xml
conf/airframes/examples/bebop.xml
conf/boards/pc.makefile
conf/modules/digital_cam_video.xml
conf/modules/video_exif.xml
conf/modules/video_rtp_stream.xml
conf/modules/video_thread.xml
sw/airborne/modules/computer_vision/cv.c
sw/airborne/modules/computer_vision/cv.h
sw/airborne/modules/computer_vision/video_thread.c
sw/airborne/modules/computer_vision/video_thread.h
sw/airborne/modules/computer_vision/video_thread_nps.c
sw/airborne/modules/computer_vision/viewvideo.c
sw/airborne/modules/computer_vision/viewvideo.h

instead of having many new copies of the same, a computer vision framework is initiated:
video_thread
which can run one or more computer vision modules (e.g. rtp_stream or qrcode or opticflow)

Computer vision framework

---

conf/airframes/BR/bebop_indi_frog.xml
conf/modules/exception_flags.xml
sw/airborne/modules/exception_flags/exception_flags.c
sw/airborne/modules/exception_flags/exception_flags.h

We experienced an issue where exceptions (battery low) would keep triggering and did not allow the normal flow of the flight plan (landing).
These flags can be used to check if the exception already triggered. Some ocaml code is still needed to allow setting the flags to 1 on exception triggering

exception flags module to use in the flight plan

---

sw/tools/generators/gen_flight_plan.ml

so you can execute arbitrary statements instead of only derouting to a block
(like calling a function or setting a variable)

[flight plans] add exec attr to exceptions

---

sw/airborne/firmwares/fixedwing/guidance/energy_ctrl.c

energy control should not read anything from the global IMU struct, as that is not always available (e.g. when using CHIMU and is supposed to go away anyway...)
So grab the data directly via ABI instead...

[fixedwing] energy_ctrl: use ABI instead of imu struct

---

sw/supervision/paparazzicenter.ml
sw/tools/generators/gen_flight_plan.ml

Print a warning if a waypoint has an altitude below the ground altitude provide by SRTM (if available).
Could be extended to check if the alt specified in `vmode="alt"` is also ok according to SRTM data.
This requires knowing the waypoint pos in the `output_mode` function...
@gautierhattenberger maybe you want to improve this a bit?

[generators] gen_flightplan: check waypoint altitude against SRTM

---

conf/airframes/flixr/flixr_lisa_mx.xml
conf/modules/air_data.xml
conf/settings/control/rotorcraft_guidance.xml
conf/settings/control/stabilization_att_float_euler.xml
conf/settings/control/stabilization_att_float_quat.xml
conf/settings/control/stabilization_att_indi.xml
conf/settings/control/stabilization_att_int.xml
conf/settings/control/stabilization_att_int_quat.xml
conf/settings/control/stabilization_rate.xml
conf/settings/estimation/ahrs_float_cmpl.xml
conf/settings/estimation/ahrs_float_mlkf.xml
conf/settings/estimation/ahrs_int_cmpl_euler.xml
conf/settings/estimation/ahrs_int_cmpl_quat.xml
conf/settings/estimation/body_to_imu.xml
conf/settings/estimation/ins_neutrals.xml

Mark a lot of settings as persistent (like gains and body_to_imu, ...) so they can be saved to flash if `USE_PERSISTENT_SETTINGS` is set to TRUE

[conf] make more settings persistent

---

sw/airborne/arch/stm32/mcu_periph/adc_arch.h

This needs to be tested first, but it solves the problem with having to use ```ADC2_1``` if you want to use a higher ADC channel from ADC2. Same problem occurs with ADC3.

[arch] Fix stm32 ADC bug

---

conf/modules/logger_spi_link.xml

The spi sd card logger did not compile any more after the changes to the configuration file. With this fix it does compile and work

fixed spi logger module compile error

---

sw/airborne/firmwares/rotorcraft/autopilot.c
sw/airborne/firmwares/rotorcraft/autopilot.h

If RADIO_AUTO_MODE channel is defined:
RADIO_MODE switch just selectes between MANUAL and AUTO.
If not MANUAL, the RADIO_AUTO_MODE switch selects between AUTO1 and AUTO2.
This is mainly a cludge for entry level radios with no three-way switch,
but two available two-way switches which can be used.

[rotorcraft] possibility to use two 2way switches for mode

---

sw/airborne/subsystems/gps/gps_piksi.c

As the driver sits currently, it does not report the correct fix if it
had previously been RTK/DGPS back to 3D. 
- added get_fix_mode() to report fix based on current/last gps fix
- added timeout to report GPS_FIX_NONE when not receiving messages from piksi at all
- tested using piksi simulation

[gps] gps_piksi: report correct gps fix

---

sw/airborne/arch/sim/sim_ap.c
sw/airborne/subsystems/datalink/downlink.c

call DlCheckAndParse instead of dl_parse_msg so that datalink_time (uplink_lost_time) is reset and datalink_nb_msgs is counted up

[sim] fix datalink_time

---

sw/airborne/boards/bebop/actuators.c

this removes the saturation bit from the rpm values for the bebop, with thanks to @fvantienen

[fix] remove saturation information from rpm measurement

---

sw/lib/python/ivy_msg_interface.py
sw/tools/generators/gen_messages.ml

The `DL_<MESSAGE>_<field>` get macros should only be needed for receiving datalink messages on the airborne side.
So only generate those for messages of the datalink class...
This part currently can't handle multiple variable length arrays per message.
In principle it should not be a problem to have multiple variable length arrays in telemetry messages though...

[messages] support multiple variable length arrays in telemetry

---

sw/airborne/arch/stm32/mcu_periph/spi_arch.c
sw/airborne/subsystems/datalink/bluegiga.c
sw/airborne/subsystems/datalink/bluegiga.h

I finally identified and fixed the error of the missing first byte in the spi message. The dma buffer copies the first byte of the tx buffer into the spi peripheral immediately when the register for slave transaction command is called, that was not immediately clear. I added a comment to the spi_arch to reflect this fact.
After fixing this I found another small "feature" in the send_message function in bluegiga which improves the responsiveness of the tx flow.
I also added code for transactions with the spi3 slave peripheral, compiles but not tested.
I removed the software slave management code. As was implemented if spi2 slave management was set to software all spi slaves would also use software management...
Last and not least I added the firmware needed to run onboard the bluegiga …

[datalink] Extended bluegiga spi message to 20 bytes

---

sw/airborne/arch/stm32/subsystems/radio_control/spektrum_arch.c
sw/airborne/arch/stm32/subsystems/radio_control/spektrum_arch.h
sw/airborne/subsystems/radio_control/superbitrf_rc.c

Values on the transmitter screen are the opposite of paparazzi. It should be:
1 - throttle
2 - X (roll right positive)
3 - Y (pitch up positive)
4 - Z (yaw right positive)
Nowadays in 2015 every radio can reverse channels: why have minus signs everywhere in paparazzi.

radio-control signs conform paparazzi 

---

conf/airframes/TUDelft/airframes/mavshot.xml
conf/airframes/TUDelft/conf.xml
conf/firmwares/subsystems/shared/actuators_asctec_v2_new.makefile
conf/settings/control/stabilization_att_indi.xml
conf/settings/modules/config_asctec_v2_new.xml
sw/airborne/subsystems/actuators/actuators_asctec_v2_new.c
sw/airborne/subsystems/actuators/actuators_asctec_v2_new.h

The i2c protocol to communicate with asctec escs has changed. The escs are still called v2, so I am not sure if I should make an actuators_asctec_v2_new.c file with another settings file, or make a define that switches between protocols within the actuators_asctec_v2.c file. What is preferred?

New asctec ESC i2c protocol

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_indi.c

Setting attitude from the flightplan was spinning when the heading is not perfectly north.
@EwoudSmeur: is this OK?

INDI - flightplan attitude fix

---

conf/airframes/ENAC/fixed-wing/mythe.xml
conf/airframes/ENAC/quadrotor/booz2_g1.xml
conf/airframes/OPENUAS/openuas_mentor.xml
conf/airframes/OPENUAS/openuas_moksha.xml
conf/airframes/OPENUAS/openuas_vivify.xml
conf/airframes/TUDelft/airframes/quadshot_pylons.xml
conf/airframes/examples/MentorEnergy.xml
conf/airframes/examples/Twinstar_energyadaptive.xml
conf/airframes/examples/quadrotor_navstik.xml
conf/airframes/examples/quadshot_asp21_spektrum.xml
conf/modules/airspeed_amsys.xml
conf/modules/airspeed_ets.xml
conf/modules/baro_amsys.xml
conf/modules/baro_bmp.xml
conf/modules/baro_ets.xml
conf/modules/baro_hca.xml
conf/modules/baro_ms5611_i2c.xml
conf/modules/baro_ms5611_spi.xml
conf/modules/baro_scp_i2c.xml
conf/modules/digital_cam_i2c.xml
conf/modules/ezcurrent.xml
conf/modules/generic_com.xml
conf/modules/humid_htm_b71.xml
conf/modules/imu_mpu9250.xml
conf/modules/ins_vn100.xml
conf/modules/mag_hmc5843.xml
conf/modules/mag_hmc58xx.xml
conf/modules/osd_max7456.xml
conf/modules/temp_temod.xml
sw/airborne/modules/enose/enose.h

To make things easier to use and more consistent...
Always use `configure` for `I2C_DEV`, `SPI_DEV` and `SPI_SLAVE`, no need to add `USE_SPIx`, etc explicitly in airframe file anymore...
Should close #1410 unless I missed some...

use `configure` for all SPI and I2C options in modules

---

conf/modules/mavlink.xml
sw/airborne/modules/datalink/mavlink.c
sw/airborne/modules/datalink/mavlink.h
sw/airborne/modules/datalink/missionlib/blocks.c
sw/airborne/modules/datalink/missionlib/blocks.h
sw/airborne/modules/datalink/missionlib/mission_manager.c
sw/airborne/modules/datalink/missionlib/mission_manager.h
sw/airborne/modules/datalink/missionlib/waypoints.c
sw/airborne/modules/datalink/missionlib/waypoints.h
sw/tools/generators/gen_flight_plan.ml

Add extra functionality of #1407 to current mavlink module.
- fix sending of some mavliink messages (MAVLinkSendMessage() was missing)
- send GPS_STATUS and VFR_HUD
- and actually fill in more fields
- parse MISSION_ITEM message to update waypoints
- only for rotorcraft (since it used the waypoint interface, see https://github.com/paparazzi/paparazzi/issues/981)
- actually take the frame into account
- add the Paparazzi specific SCRIPT_ITEM messages
Looks to me like this now added the same functionality as #1407 with two minor differences:
- ~~no time-outs on the mission or script protocol, don't see how they would be relevant anyway since you can only change existing waypoints/blocks~~
- ~~MISSION_ITEM message is sending waypoint in `MAV_FRAME_LOCAL_ENU` instead of `MAV_FRAME_GLOBAL`~~ …

Mavlink additions

---

docker/run.sh

- OSX readlink doesn't have the -f or -m options, require correct PAPARAZZI_SRC to be set already for now
- using xauth with docker on OSX doesn't work, so we use socat to forward the socket via TCP
- see https://github.com/docker/docker/issues/8710
- no (pulse)audio on OSX...
- find on OSX doesn't have the -printf option... so use exec echo instead
this will hopefully fix #1421

[docker] fix run.sh for OSX with access to X

---

.gitignore
conf/airframes/TUDelft/airframes/walkera_genius_v2.xml
conf/airframes/TUDelft/conf.xml
conf/modules/logger_sd_spi_direct.xml
conf/telemetry/rotorcraft_with_logger.xml
sw/airborne/modules/loggers/sdlogger_spi_direct.c
sw/airborne/modules/loggers/sdlogger_spi_direct.h
sw/airborne/peripherals/sdcard_spi.c
sw/airborne/peripherals/sdcard_spi.h
sw/logalizer/Makefile
sw/logalizer/sdlogger_download.c
sw/logalizer/sdlogger_get_setting_id.py

This module provides a tool for high-speed logging where weight- and size-limitations play part.
It only requires a micro-SD card which is soldered directly to the SPI-bus, for example on a lisa/s.
The logger is activated by flipping a switch on the transmitter. Up to 42 logs can be recorded during one session (battery kept connected). The data remains on the card when the battery is disconnected, so that you can replace the battery before downloading data to the computer. Previous logs will be overwritten as soon as the first log is initiated after boot.
The messages to be logged can be selected in the telemetry config file, under the Logger process. Next to that, it is possible to call pprz_msg_send_xxx from anywhere in the code, using a reference to the sdlogger. 
Telemetry config …

[sd logger] Version 2.0 release, direct SPI logging, UART download

---

sw/airborne/subsystems/datalink/telemetry.c
sw/airborne/subsystems/datalink/telemetry_common.h
sw/tools/generators/gen_periodic.ml

So far when multiple modules/subsystem were calling `register_periodic_telemetry` for the same message/string, only the first one would actually register it's callback.
For cases like #1145 we would like to register multiple callbacks, so:
- Allow to add multiple callbacks: up to `TELEMETRY_NB_CBS` slots (4 right now).
- Also return slot index of callback (to make it easier to add an `unregister` function later) or -1 on failure

Register multiple periodic messages

---

conf/airframes/flixr/conf.xml
conf/airframes/flixr/flixr_lisa_mx.xml
conf/messages.xml
conf/telemetry/default_rotorcraft.xml
sw/airborne/math/pprz_orientation_conversion.h
sw/airborne/modules/ins/ahrs_chimu_uart.c
sw/airborne/modules/ins/ins_arduimu.c
sw/airborne/modules/ins/ins_arduimu_basic.c
sw/airborne/subsystems/ahrs.h
sw/airborne/subsystems/ahrs/ahrs_float_cmpl.c
sw/airborne/subsystems/ahrs/ahrs_float_cmpl.h
sw/airborne/subsystems/ahrs/ahrs_float_cmpl_wrapper.c
sw/airborne/subsystems/ahrs/ahrs_float_dcm_wrapper.c
sw/airborne/subsystems/ahrs/ahrs_float_invariant_wrapper.c
sw/airborne/subsystems/ahrs/ahrs_float_mlkf_wrapper.c
sw/airborne/subsystems/ahrs/ahrs_int_cmpl_euler_wrapper.c
sw/airborne/subsystems/ahrs/ahrs_int_cmpl_quat_wrapper.c
sw/airborne/test/ahrs/run_ahrs_on_synth_ivy.c
sw/logalizer/ahrs2fg.c

When running multiple AHRS algos in parallel, each filters can send the same message but with a different ID to distinguish the source.
See also #1145 
This adds a `comp_id` field to the following messages:
- AHRS_EULER
- AHRS_EULER_INT
- AHRS_QUAT_INT
- AHRS_RMAT_INT
- AHRS_GYRO_BIAS_INT
- GEO_MAG
Also register some more message in some of the filters and don't use the value from the state interface to send the attitude in body frame but rather compute it from the actual ahrs output (imu frame).
So it will still be correct if muliple AHRS are running and another one is enabled (sets the attitude in the state interface).

Add component/filter ID to AHRS messages

---

sw/ground_segment/tmtc/rotorcraft_server.ml

Try to set a course to a sensible value for rotorcrafts, by computing it from north and east velocity.
Needed e.g. for ACINFO.

[tmtc][rotorcraft] set course using east/north velocity

---

sw/logalizer/plotter.ml

first of all the image/label with the current value is not displayed anymore (at least on Ubuntu 14.04).
And probably more importantly, these constant updates of the menu result in high cpu-load and memory usage of hud-service,
Rendering the computer unusable if left running for a long time (until hud-service is killed and restarted).
Workaround for #1446 by simply disabling the update of these labels/menu entries

[logalizer] plotter: disable update of average and stdev in menu

---

sw/airborne/boards/bebop/actuators.c

The motors were spinning all in the same direction on bebop1.

[fix] bebop1 motor direction

---

conf/messages.xml
conf/settings/rotorcraft_basic.xml
sw/airborne/firmwares/rotorcraft/autopilot.c
sw/airborne/firmwares/rotorcraft/autopilot.h
sw/airborne/firmwares/rotorcraft/datalink.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_v.h
sw/ground_segment/cockpit/live.ml
sw/ground_segment/python/guided_mode_example.py
sw/ground_segment/tmtc/server_globals.ml
sw/lib/python/ivy_msg_interface.py
sw/lib/python/pprz_msg/message.py
sw/lib/python/settings_xml_parse.py

Meant for controlling the rotorcraft via external input (e.g. POSITION_TARGET_LOCAL_NED datalink message)
- currently position mode only
- could be extended with velocity, relative position, etc.
Could also be used for mavlink:
http://mavlink.org/messages/common#SET_POSITION_TARGET_LOCAL_NED

Rotorcraft guided mode

---

conf/airframes/untested/hex_naze32.xml
conf/boards/naze32_rev4.makefile
conf/boards/naze32_rev5.makefile
sw/airborne/boards/naze32_common.h

That means by default you can't use SERVOS 1 and 2 and only the pwm channels on servo connectors 3-6 are active.
Chosing RADIO_CONTROL_PPM_PIN as PA7 (RC_CH6) via
`<configure name="RADIO_CONTROL_PPM_PIN" value="PA7"/>`
will also enable servos 1 and 2.
Alternative to #1478

[boards] naze32: PPM input on PA0 by default

---

sw/airborne/modules/gps/gps_ubx_ucenter.c
sw/airborne/modules/gps/gps_ubx_ucenter.h

should fix #1459 
tested on UBX M8M module with default config at startup

[gps] fix ubx ucenter autobaud and autoconf

---

conf/airframes/mm/bebop.xml
sw/airborne/arch/linux/mcu_periph/i2c_arch.c
sw/airborne/arch/linux/mcu_periph/i2c_arch.h

Allow an external I2C bus connected through USB for the Bebop. Use the correct repeated-start for Transceive function for Linux targets as required by some I2C sensors.

Bebop i2c changes

---

conf/TUDELFT/tudelft_KM_control_panel.xml
conf/airframes/TUDELFT/tudelft_ladylisa_bluegiga_stereoboard.xml
sw/airborne/subsystems/ins/ins_int.c

- Updates to stereocam2state related conf files
- in ins_int.c 
-  at  vel_est_cb() the velocity is intergrated to position for the guidance module
-  at gps_cb() USE_GPS define is used around the update function. I figured out that, even though USE_GPS is false in the airframe file, GPS measurements are still used for calculating the state (which is weird right?). So this will fix that problem for now.

Stereocam updates and ins_int.c changes

---

sw/lib/python/ivy_msg_interface.py
sw/lib/python/pprz_msg/messages_xml_map.py

and don't treat sender_name (first string in ivy message) as msg_class

[python] ivy_msg_interface: find message class by name

---

conf/abi.xml
conf/messages.xml
sw/airborne/subsystems/abi_sender_ids.h
sw/airborne/subsystems/datalink/bluegiga.c
sw/airborne/subsystems/datalink/bluegiga.h
sw/airborne/subsystems/datalink/datalink.h
sw/tools/bluegiga_usb_dongle/main.c

Added abi message for rssi from bluegiga bluetooth module.
Simplified the bluetooth check and parse to pprz_check and parse.
Updated bluetooth the recent build of firmware (telemetry fully backwards compatible).
Update bluetooth ground code.

[datalink] update bluegiga protocol and add rssi abi message

---

conf/firmwares/subsystems/fixedwing/autopilot.makefile
conf/firmwares/subsystems/fixedwing/fdm_crrcsim.makefile
conf/firmwares/subsystems/fixedwing/fdm_jsbsim.makefile
conf/firmwares/subsystems/fixedwing/telemetry_bluegiga.makefile
conf/firmwares/subsystems/fixedwing/telemetry_superbitrf.makefile
conf/firmwares/subsystems/fixedwing/telemetry_transparent.makefile
conf/firmwares/subsystems/fixedwing/telemetry_transparent_usb.makefile
conf/firmwares/subsystems/fixedwing/telemetry_w5100.makefile
conf/firmwares/subsystems/fixedwing/telemetry_xbee_api.makefile
conf/firmwares/subsystems/rotorcraft/fdm_jsbsim.makefile
conf/firmwares/subsystems/rotorcraft/telemetry_bluegiga.makefile
conf/firmwares/subsystems/rotorcraft/telemetry_superbitrf.makefile
conf/firmwares/subsystems/rotorcraft/telemetry_transparent.makefile
conf/firmwares/subsystems/rotorcraft/telemetry_transparent_udp.makefile
conf/firmwares/subsystems/rotorcraft/telemetry_transparent_usb.makefile
conf/firmwares/subsystems/rotorcraft/telemetry_xbee_api.makefile
conf/firmwares/subsystems/shared/telemetry_bluegiga.makefile
conf/firmwares/subsystems/shared/telemetry_ivy.makefile
conf/firmwares/subsystems/shared/telemetry_superbitrf.makefile
conf/firmwares/subsystems/shared/telemetry_transparent.makefile
conf/firmwares/subsystems/shared/telemetry_transparent_udp.makefile
conf/firmwares/subsystems/shared/telemetry_transparent_usb.makefile
conf/firmwares/subsystems/shared/telemetry_w5100.makefile
conf/firmwares/subsystems/shared/telemetry_xbee_api.makefile
sw/airborne/firmwares/fixedwing/fixedwing_datalink.c
sw/airborne/firmwares/rotorcraft/rotorcraft_datalink.c
sw/airborne/subsystems/datalink/datalink.c
sw/airborne/subsystems/datalink/datalink.h

Trying to help the joining of fixedwing and rotorcraft. This way all shared datalink code and updates only have to be done once. Firmware specific code not yet shared can be kept separate in the original files.
Pull request also contains a start for drone to drone messaging but reading the messages is waiting for the dl macros in telemetry.

[refactor] add shared datalink for all firmware

---

conf/airframes/HOOPERFLY/hooperfly_racerpex_hexa_lisa_mx_20.xml
conf/airframes/HOOPERFLY/hooperfly_racerpex_octo_lisa_mx_20.xml
conf/airframes/HOOPERFLY/hooperfly_racerpex_quad_lisa_mx_20.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_hexa_lisa_mx_20.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2.xml

Updated all the HooperFly airframes to use `module` keyword vs. `subsystem`. Also added an airframe description for Elle0 v1.2.

Convert subsystem to module for HooperFly frames

---

conf/airframes/TUDELFT/tudelft_heli450.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_rate.c

The integrator was doing very little for rate control as it was scaled to a very small value and it accumulated very fast up to the maximum. With these changes it takes longer to reach the maximum

Rate integrator

---

conf/airframes/HOOPERFLY/hooperfly_racerpex_hexa_lisa_mx_20.xml
conf/airframes/HOOPERFLY/hooperfly_racerpex_octo_lisa_mx_20.xml
conf/airframes/HOOPERFLY/hooperfly_racerpex_quad_lisa_mx_20.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_lisa_mx_20.xml

- Removed ADC module blocks from the Elle0 airframe files (fixes issue with batter level not being displayed in the GCS)
- Changed the PWM servo max values from 1900 to 2000 for all airframe files
- Changed the low and critical battery level values to 10.1 volts and 9.6 volts, respectively, for all airframe files

Hooperfly airframe updates

---

sw/supervision/paparazzicenter.glade

especially remove CTRL-C to be copy AIRCRAFT
if the label is gtk-copy, it will automatically set the accelerator keys...
should fix #1544

[paparazzi center] remove accelerator keys

---

sw/supervision/paparazzicenter.glade

You could type in the console, but it is actually only used for output... modifying text in it makes no sense.
So make it non editable for the user...

[paparazzi center] make console non editable

---

conf/airframes/examples/easystar_ets.xml
conf/conf_example.xml
conf/firmwares/subsystems/fixedwing/fdm_crrcsim.makefile
conf/firmwares/subsystems/fixedwing/fdm_jsbsim.makefile
conf/firmwares/subsystems/rotorcraft/fdm_jsbsim.makefile
conf/modules/airspeed_adc.xml
conf/modules/digital_cam_uart.xml
sw/simulator/nps/nps_autopilot_fixedwing.c
sw/simulator/nps/nps_fdm.h
sw/simulator/nps/nps_fdm_crrcsim.c
sw/simulator/nps/nps_fdm_jsbsim.cpp
sw/simulator/nps/nps_sensor_airspeed.c
sw/simulator/nps/nps_sensor_airspeed.h
sw/simulator/nps/nps_sensors.c
sw/simulator/nps/nps_sensors.h

Get airspeed, pressure and temperature from FDM and add an airspeed sensor that directly pushes equivalent airspeed to the state interface.
Also fix some other NPS related things:
- disable airspeed_adc module for NPS
- fix NPS_BYPASS_NPS for fixedwings

simulate airspeed sensor in NPS

---

conf/Makefile.arm-linux-toolchain

On arm-linux: actually use g++ cross compiler instead of falling back to default CXX

[conf] enable compilation of C++ files on arm-linux

---

sw/airborne/arch/stm32/mcu_arch.c

and update clock setup accordingly

[ext] update to latest libopencm3

---

sw/airborne/modules/computer_vision/opticflow_module.c

Reversed order of calling functions to avoid errors. See commit message.

[computer vision] Fixed error with running opticflow_module_stop() on UAV

---

sw/airborne/arch/stm32/subsystems/radio_control/spektrum_arch.c

My RC was outputting slightly negative throttle values. This resulted in an overflow of the throttle curve. The radio values are expected to always be within pprz bounds, so there should be a bound on the radio values.

bounding of the spektrum input

---

conf/modules/ahrs_chimu_spi.xml
conf/modules/ahrs_chimu_uart.xml
conf/modules/bebop_front_camera.xml
conf/modules/cv_opticflow.xml
conf/modules/cv_qrcode.xml
conf/modules/gps_ublox.xml
conf/modules/ins_xsens.xml
conf/modules/ins_xsens700.xml
conf/modules/module.dtd
conf/modules/video_exif.xml
conf/modules/video_rtp_stream.xml
conf/modules/video_thread.xml
sw/tools/generators/gen_aircraft.ml

Change `<define name="foo" type="include"/>` to `<include name="foo"/>`.
And allow to use `<define name="foo" value="my string" type="string"/>`

module xml: split define and include, use type for string flags

---

sw/airborne/firmwares/fixedwing/guidance/energy_ctrl.c

This is a regression and seems to be wrong since 4bfab9d05000e91c6a6a5a8d45f55e5ea6269543

[energy ctrl] fix accel conversion for correct vdot

---

sw/supervision/paparazzicenter.glade
sw/supervision/paparazzicenter.ml

If there are unsaved changes, ask if you want to save them on quit of Paparazzi Center.
This solves the "problem" of #1567 if you work on a local conf not under revision, but otherwise, you can still have changes due to checkout, so the startup confirmation will show up.

[pprzcenter] save conf confirmation on quit

---

sw/airborne/peripherals/mpu60x0_spi.c

If the MPU starts up slowly this could stop if from being initialized.
Now it waits until it is detected before initialization.

[imu] Fix MPU start bug

---

sw/ground_segment/python/dashboard/radiowatchframe.py
sw/ground_segment/python/guided_mode_example.py
sw/ground_segment/python/ivytoredis/ivy_to_redis.py
sw/ground_segment/python/messages_app/messagesframe.py
sw/ground_segment/python/move_waypoint_example.py
sw/ground_segment/python/real_time_plot/messagepicker.py
sw/ground_segment/python/real_time_plot/plotpanel.py

serial/ivy_msg_interface are now in pprzlink module
this means anybody using ivy_msg_interface (or serial_msg_interface) needs to change
`from ivy_msg_interface import IvyMessagesInterface`
to
~~`from pprzlink.ivy_msg_interface import IvyMessagesInterface`~~
`from pprzlink.ivy import IvyMessagesInterface`

[pprzlink][python] update pprzlink imports

---

conf/airframes/TUDELFT/tudelft_course2016_bebop_avoider.xml
conf/airframes/TUDELFT/tudelft_heli450.xml
conf/airframes/examples/course_bebop_colorfilter.xml
conf/airframes/examples/quadrotor_lisa_mx.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_rate.c

Currently gains from rate control do not carry over to attitude stabilization, because there is a factor 2 in the rate control and prescaler values (factor 3 for rate) in the attitude control. I searched through the airframes, and there are not many that use rate control. I doubled all the gains and removed rate control for bebop, as rate control over datalink is very difficult due to lag.
The prescaler values should also be default 1 for stabilization quat_int, as they already are for float_quat. However, this will mean updating a large amount of airframes, which will require some scripting. I might have time for this later.

remove scaling from rate feedback

---

sw/airborne/subsystems/gps/gps_furuno.c
sw/airborne/subsystems/gps/gps_nmea.c
sw/airborne/subsystems/gps/gps_nmea.h

send GPS ABI message even if position is not available but a new valid sentence was received,
e.g. while no fix but get tow and satellite info
should be a better fix for #1618
same problem is probably present in some other gps drivers...

[gps] nmea: send ABI msg on every valid NMEA sentence

---

sw/airborne/modules/computer_vision/lib/vision/image.c

I've edited the image_draw_line function to take into account the fact that in yuv422 images pixels can only be edited in pairs in the x direction, so the increment in the x direction should be equal to 2. I hope not to be mistaken, but this way it is actually possible to draw line of the specified color.

Edited image.c for YUV422 images.

---

conf/modules/telemetry_transparent.xml
sw/lib/ocaml/gen_common.ml
sw/lib/ocaml/gen_common.mli
sw/tools/generators/gen_aircraft.ml

This should fix the target filtering on modules loading by taking into account the firmware and the list of targets as a real boolean expression (to handle properly the inverted selection)
see #1614

Fix target filtering

---

conf/system/udev/rules/50-paparazzi.rules

The string in the Lisa/M V2.1 DFU bootloader is: Lisa/M V2.1 (Upgrade)
The wildcard now accepts the V2.1 as part of the string. Previous
versions of Lisa/M DFU bootloader did not have the hardware version in
them. This is needed so that the Lisa/M DFU is accessible from the
userspace in the plugdev group.

The udev rules were not detecting Lisa/M V2.1 correctly.

---

conf/Makefile.chibios-libopencm3
conf/Makefile.linux
conf/Makefile.lpc21
conf/Makefile.nps
conf/Makefile.sim
conf/Makefile.stm32
conf/boards/naze32_rev4.makefile

In particular, activate LTO compilation to reduce code size on small board naze32.
It doesn't seem to be enough, but already helps.
see #1594

[build] add boards specific flags when needed

---

sw/ground_segment/cockpit/Makefile

workaround wrong reported version of lablgtk in Debian Sid and Ubuntu xenial.
ocamlfind reports version 2.16 while it's actually 2.18
see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822949 and https://bugs.launchpad.net/ubuntu/+source/lablgtk2/+bug/1577236

[cockpit] workaround lablgtk 2.18 Debian/Ubuntu bug

---

conf/airframes/AGGIEAIR/aggieair_rp3_lia.xml
conf/modules/nav_survey_poly_osam.xml
sw/airborne/modules/nav/nav_survey_poly_osam.c
sw/airborne/modules/nav/nav_survey_poly_osam.h

I.e. sometimes we dont want the half width turn at the end of the survey (because we want consistent spacing between images). 
Also the poly survey now can be run multiple times, you just have to reset the counter in GCS.

Make half turn in poly survey optional

---

conf/airframes/TUDELFT/tudelft_conf.xml
conf/airframes/TUDELFT/tudelft_outback.xml
conf/modules/opa_controller.xml
sw/airborne/boards/opa_ftd_1.0.h
sw/airborne/modules/boards/opa_controller_ap.c
sw/airborne/modules/boards/opa_controller_ap.h
sw/airborne/modules/boards/opa_controller_fbw.c
sw/airborne/modules/boards/opa_controller_fbw.h
sw/airborne/subsystems/intermcu.h
sw/airborne/subsystems/intermcu/intermcu_ap.c
sw/airborne/subsystems/intermcu/intermcu_fbw.c

Special controller for the OPA (Oversized paparazzi Autopilot), which enables the full functionally of the the board.
This includes:
- Power of AP from FBW
- Power of Motor from FBW
- Power of Charging of FBW battery from FBW
- Disabling power of Motor from AP settings trough FBW
- Power of Vision computer trough AP

[modules] Add OPA controller

---

conf/modules/ins_skeleton.xml
sw/airborne/modules/ins/ins_skeleton.c
sw/airborne/modules/ins/ins_skeleton.h

INS module skeleton.
This module is meant to be used with an additional module which implements any of the following
- ins_module_init()
- ins_module_propagate(struct Int32Vect3 *accel, float dt)
- ins_module_update_gps(struct GpsState *gps_s, float dt)
- ins_module_update_baro(float pressure)
- ins_module_reset_local_origin(void)
In each of those functions the updated estimate has to be written to the ins_module struct,
which is then used to update the state interface.
alternative proposal to #1572

[modules] add ins_skeleton

---

conf/airframes/examples/quadrotor_revo.xml
conf/boards/openpilot_revo_1.0.makefile
conf/conf_tests.xml
conf/firmwares/subsystems/shared/baro_board.makefile
conf/firmwares/subsystems/shared/imu_openpilot_revo.makefile
conf/flash_modes.xml
sw/airborne/arch/stm32/openpilot_revo.ld
sw/airborne/boards/openpilot_revo/baro_board.h
sw/airborne/boards/openpilot_revo_1.0.h
sw/airborne/subsystems/imu/imu_mpu6000_hmc5883.c

IMU, mag, baro and telemetry tested.
Positive x-axis of the IMU is indicated by the arrows on the board, the side with LEDS and F4 is up (negative z-axis).
Still missing support for the modem and the external flash...
To get the axes correct also extended the imu_mpu600_hmc5883 driver to allow different axes/channel assignments.

[boards] support for OpenPilot Revolution board

---

sw/airborne/modules/computer_vision/opticflow/size_divergence.c

The bigger subpixel_factor led to problems (overflows) in size_divergence. This code change fixes the most immediate problem. However, the divergence results are still worse than with the old code, e.g., at the time of the commit 9ae722e294e7787da81060cd12d54d8e5c23b78a The reason for that does not seem to lie in the size_divergence code.

Optical flow giving bad divergence results - bug fix part I

---

conf/airframes/HOOPERFLY/hooperfly_conf.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2_214.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2_215.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2_216.xml

Leverage the $AC_ID macro as a mechanism for isolating airframe specific data, in this case, calibration data.

Refactor elle0 v1.2 airframes to use includes for calibration data

---

conf/Makefile.stm32-upload

The added leave command tells the DFU target to leave the DFU mode after downloading or uploading a binary. Especially useful for devices that don't have a reset button.

Make the target device leave DFU mode after upload.

---

conf/flight_plans/flight_plan.dtd
conf/flight_plans/nav_modules.xml
sw/tools/generators/gen_flight_plan.ml

- `<call_once fun="x"/>` is an alias for `<call fun="x" loop="false"/>`
The idea is to make it easier and more clear how to call functions that do not return a bool and should only be called once.
Same as #1612 without the run alias

[flight plans] add call_once alias

---

conf/conf_tests.xml

I missed the new airframe in the conf_tests - this fixes the problem. Sorry about that.

Fixed aircraft IDs for new airframe

---

.travis.yml

So travis doesn't produce this warning anymore: 
> E: There are problems and -y was used without --force-yes
The command "sudo apt-get install -y paparazzi-dev paparazzi-jsbsim gcc-arm-none-eabi libipc-run-perl" failed and exited with 100 during .

Fixed travis to compile with unsigned packages

---

sw/airborne/modules/computer_vision/opencv_example.cpp

The opencv example didn't work properly for the bebop bottom camera. Reversing `width` and `height` in the `cv::Mat` constructor (rows before cols) fixes this problem.

[opencv_example] Fix for the non-square video feed

---

docker/Makefile
docker/dep/Dockerfile
docker/dev/Dockerfile
docker/dev/entrypoint.sh
docker/run.sh

- Update to Ubuntu xenial and switch to new gcc-arm-embedded PPA.
- Hhandle permissions for docker volumes by dynamically changing the id of user pprz to LOCAL_USER_ID.
This should finally make it possible use the shared volume with the paparazzi source in docker on machines where your user/group id is not 1000

[docker] use ubuntu 16.04 and deal with user/group ids != 1000

---

conf/airframes/TUDELFT/tudelft_bebop_indi.xml
conf/settings/control/stabilization_indi.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.h

the yaw of a typical quadrotor easily saturates. One of the problems that occur when asking for a large change in yaw angle, is that the quadrotor can build up so much angular velocity in the yaw axis, that it can not physically slow down before reaching the yaw setpoint due to saturating. This will result in overshoot. 
This can be helped by adding a yaw rate limit, which this PR does for the INDI controller.

added the possibility to add a yaw rate limit to stabilization indi

---

sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c

There was a spurious return (used for debugging), preventing optical flow from being calculated in the master. I removed it.

Removed spurious return from optic flow calculator

---

sw/airborne/boards/ardrone/board.c
sw/airborne/peripherals/video_device.h

Master is breaking ardrone build. I added the required include to the board file for the ardrone and updated the comment of the file location for the video_device file. Builds now.

[vision] added missing include for ardrone board file

---

sw/airborne/state.c

Conversion between int and float can be done even when ned_origin is not initialized

[state] allow some conversions of accel

---

sw/airborne/firmwares/rotorcraft/autopilot.c
sw/airborne/firmwares/rotorcraft/autopilot.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
sw/airborne/firmwares/rotorcraft/rotorcraft_datalink.c
sw/ground_segment/python/guided_mode_example.py

We expanded the message flag definition to facilitate updating the horizontal and vertical setpoints in different reference frames as well as separate definitions of whether the setpoints are position or velocity commands. Also added a heading rate setpoint. 
This is a draft pull request, I still need to test it (especially the new rate setpoint) before it can be approved. Feedback is welcome @rmeertens.
continues/replaces https://github.com/paparazzi/paparazzi/pull/1686

[guidance] Expansion of the guided protocol

---

conf/modules/cv_opencvdemo.xml
sw/airborne/modules/computer_vision/cv_opencvdemo.c
sw/airborne/modules/computer_vision/opencv_example.cpp
sw/airborne/modules/computer_vision/opencv_image_functions.cpp

The function color_opencv_to_yuv422 did not work correctly, the resulting image had a very green tint. This pull request also updates the cv_opencvdemo module to work with the new video thread.

[opencv_example] Fixed conversion from colored opencv image to yuv422 image buffer

---

conf/firmwares/subsystems/rotorcraft/gps_datalink.makefile
conf/firmwares/subsystems/rotorcraft/gps_optitrack.makefile

Until now when flying with gps `datalink` (which we use for optitrack), you always need to define in your aiframe `<define name="AHRS_HEADING_UPDATE_GPS_MIN_SPEED" value="0"/>` to get heading updates.
I cannot imagine that you would want something else than 0, so I put it as default in the makefile.

[gps] optitrack always send heading

---

sw/airborne/math/pprz_algebra_int.c

original rotation would overflow for some rotations. I extended the variable size to ensure it all fits. Simple fix.

[fix] increase quat size to avoid overflow

---

sw/airborne/modules/computer_vision/lib/vision/image.c
sw/airborne/modules/computer_vision/qrcode/qr_code.c

The draw line function was.... not drawing lines to the right spot. 
Fixed it by reverting to a previous version. 
Also: now I'm not assuming that a QR code has 4 sides. whoo

fixed drawing a line, now drawing around any qr code

---

conf/modules/module.dtd
sw/lib/ocaml/gen_common.ml

This is not a dependency mechanism. It is just equivalent to adding modules directly in an airframe file.
This should help to solve the issue in gps_modules branch in particular (#1625).

[modules] autoload modules from an other module

---

conf/boards/lisa_s_1.0.makefile
sw/airborne/boards/lisa_s_1.0.h

For Lisa/S, I am not using a superbit-rf but another PPM receiver.
The superbit-rf reset pin is used for ppm in.

superbit_rst pin as ppm_in

---

sw/tools/rtp_viewer/rtp_viewer.py

I made a mistake in the latest commit of the previous pull request, where the default video capture source file was not the correct file name. This commit corrects it.

[rtp_viewer] fixed default sdp file location

---

sw/airborne/boards/lisa_s_1.0.h

I use an RPM sensor on lisa/s on the RADIO_IRQ pin with this config.

Lisa/S: add support for rpm sensor on RADIO_IRQ pin

---

sw/airborne/modules/sensors/rpm_sensor.c
sw/airborne/modules/sensors/rpm_sensor.h

RPM sensor is now only useful for telemetry. I need it in another piece of code, so this additional function allows me to get the RPM.

[rpm sensor] add a get function

---

sw/airborne/subsystems/imu/imu_aspirin_2_spi.c

For this very specific case (Lisa/S with upside_down define), I got a compile error because `mag` was not defined.

[lisa/s] disable magneto fix compile error

---

sw/airborne/arch/sim/sim_gps.c
sw/airborne/math/pprz_geodetic_double.c
sw/airborne/math/pprz_geodetic_double.h
sw/airborne/math/pprz_geodetic_float.c
sw/airborne/math/pprz_geodetic_int.c
sw/airborne/math/pprz_geodetic_wgs84.h
sw/airborne/modules/ins/ins_xsens.c
sw/airborne/modules/ins/ins_xsens700.c
sw/airborne/modules/ins/xsens.c
sw/airborne/modules/ins/xsens700.c
sw/airborne/state.h
sw/airborne/subsystems/gps.c
sw/airborne/subsystems/gps.h
sw/airborne/subsystems/gps/gps_ubx.c
sw/airborne/subsystems/ins.c
sw/airborne/subsystems/ins/ins_alt_float.c
sw/airborne/subsystems/ins/ins_float_invariant.c
sw/airborne/subsystems/ins/ins_gps_passthrough_utm.c

Although there is no defined reference for the utm altitude, in paparazzi (most in fixedwing firmware) it is more often than not assumed that alt is hmsl. I updated the helper functions from gps->utm to return alt with hmsl. 
Additionally, I added additionally checks for the gps valid mask. Notably, if both UTM and LLA positions are not set utm is returned as (0,0,0, zone). Also, if gps.hmsl is not available we use the ellipsoid alt minus the geoid height at the original origin of the flight plan.

Return utm.alt as hmsl from gps helper function

---

conf/modules/ahrs_chimu_spi.xml
sw/tools/generators/gen_modules.ml

Exit with an error instead of only printing a warning if a module dependency is not satisfied.
See also #1744

[gen_modules] exit with error if dependency is not satisfied

---

conf/modules/pose_history.xml
sw/airborne/modules/pose_history/pose_history.c
sw/airborne/modules/pose_history/pose_history.h

In https://github.com/paparazzi/paparazzi/pull/1729 @knmcguire and @flixr had the idea of creating a pose history module... So here it is!
Currently it records at 512hz, and remembers its state for two seconds (1024 measurements). Searching in the buffer is not very efficient, but good enough for now to test the optical flow.

Pose history

---

conf/modules/mag_hmc58xx.xml
sw/airborne/modules/sensors/mag_hmc58xx.c

this allow to choose arbitrary orientation for external mounted hmc mag
and move data back to IMU frame before sending them over ABI.
related to #197
this is the only driver supporting this, but hmc mag are the most
commonly used, especially as external sensor

[mag] add a MAG_TO_IMU option to HMC58XX drivers

---

sw/airborne/subsystems/gps/gps_datalink.c
sw/ground_segment/misc/natnet2ivy.c

There was a small typo when converting gps_datalink to module which broke it, this fixes that. I also use this pr to fix the tow in the natnet message and increase resolution to ms.

fix typo in datalink, add ms to datalink tow

---

conf/modules/video_thread.xml
sw/airborne/modules/computer_vision/video_thread.c

The default 'nice level' for the video_threads is 10, but this needs to be lower in order for some critical vision algorithms to work properly and reliably (such as optical flow hover control #1698).
Other possible improvements to video_thread;
- Dynamically change VISION_THREAD_NICE_LEVEL (via GCS setting)
- Being able to have some vision functions run with less fps than others (e.g. use RunOnceEvery)
- Improved fps regulation (e.g. smoothed average)
- Provide the vision functions with access to current frame time and fps

[video_thread] Improvements to video_thread performance

---

sw/airborne/firmwares/fixedwing/main_ap.c
sw/airborne/firmwares/fixedwing/main_chibios.c
sw/airborne/firmwares/fixedwing/main_chibios.h
sw/airborne/firmwares/fixedwing/main_fbw.c
sw/airborne/firmwares/fixedwing/nav.c
sw/airborne/firmwares/fixedwing/nav.h
sw/airborne/inter_mcu.c
sw/airborne/inter_mcu.h
sw/airborne/modules/airborne_ant_track/airborne_ant_track.c
sw/airborne/modules/cam_control/cam.c
sw/airborne/modules/cam_control/cam.h
sw/airborne/modules/cam_control/cam_roll.c
sw/airborne/modules/cam_control/point.c
sw/airborne/modules/com/generic_com.c
sw/airborne/modules/digital_cam/dc_shoot_rc.c
sw/airborne/modules/digital_cam/servo_cam_ctrl.c
sw/airborne/modules/gas_engine/gas_engine_idle_trim.c
sw/airborne/modules/ins/ins_arduimu_basic.c
sw/airborne/modules/loggers/sdlog_chibios.c
sw/airborne/modules/loggers/sdlog_chibios.h
sw/airborne/modules/loggers/sdlog_chibios/usbStorage.c
sw/airborne/modules/loggers/sdlog_chibios/usbStorage.h
sw/airborne/modules/nav/nav_drop.c
sw/airborne/modules/nav/nav_drop.h
sw/airborne/modules/servo_switch/auto1_commands.c
sw/airborne/pprz_mutex.h
sw/airborne/pprz_rtos.h
sw/airborne/rc_settings.c

- add protection on ap and fbw state structures
- add RTOS abstraction macros
- update closing of ap/fbw threads with sdlog

[chibios] split FBW and AP threads

---

sw/airborne/boards/bebop/video.c

Related issue; #1762.
Choosing a square resolution seems to fix the issue. However, I'm not sure if 480 x 480 is the ideal resolution.
Temporary fix until #1750 is finished

[fix] Bebop bottom camera resolution

---

sw/tools/rtp_viewer/README.md
sw/tools/rtp_viewer/rtp_viewer.py

Useful for the viewing the bebop front camera stream, since it is rotated 90 degrees.
For now I disabled the possibility of sending a ROI message when rotated, since this would require remapping the region to the original rotation.

[rtp_viewer] added possibility to rotate viewer

---

sw/airborne/modules/computer_vision/opticflow_module.c

Remove the line 
`-  // TODO: why is there a mutex above and not below when changing opticflow_result?
`
And moved the mutex.

opticflow_module: moved mutex

---

conf/airframes/TUDELFT/tudelft_bebop_autonomous_race.xml
conf/modules/cv_detect_contour.xml
sw/airborne/modules/computer_vision/detect_contour.c
sw/airborne/modules/computer_vision/detect_contour.h
sw/airborne/modules/computer_vision/opencv_contour.cpp
sw/airborne/modules/computer_vision/opencv_contour.h

Revamped https://github.com/paparazzi/paparazzi/pull/1785
Now it works, code looks nice, no warnings and actually compiles.

Added detect contour

---

sw/ext/Makefile

Today I ran test_all_confs and saw that the autonomous_dronerace airframe failed. It ended up that this was because my opencv_bebop submodule had never been initialised and it is not built automatically with make. It is not that useful for new developers wanting to work with opencv or is it good for the CI tests tht will test airframes that use opencv.
Due to the way the opencv_bebop is made it builds quite slowly the first time it checksout but it also tries to build some files every time you build. What I do with this commit is have it that the first time you build paparazzi it will download and build opencv_bebop but only try to rebuild the project if the install folder is missing from the subfolder. This means that the library will only be rebuilt if the user runs 'clean_opencv_bebop' …

don't clean opencv_bebop with clean in main folder

---

conf/conf_tests.xml
conf/flight_plans/AGGIEAIR/BasicTuning_Launcher.xml
conf/flight_plans/flight_plan.dtd
sw/airborne/modules/nav/nav_geofence.h
sw/tools/generators/gen_flight_plan.ml

Based on #1664 - newly added an option to specify `geofence_max_agl` in the flight plan, on top of `geofence_max_alt`. Both values are checked and used, the lower one triggers the safety mode.
Also added a check for negative security height (which is a nonsense).

Updated geofencing

---

conf/boards/apogee_1.0_chibios.makefile
sw/airborne/arch/chibios/mcu_arch.c
sw/airborne/arch/chibios/mcu_arch.h
sw/airborne/firmwares/fixedwing/main_chibios.c
sw/airborne/subsystems/datalink/downlink.c

In case of crash of the autopilot, the mcu is restarted and the FBW thread is restarted (low level peripherals as well) but not the AP thread, assuming it is the source of the problem.
It allows a safety pilot to take back the control of the plane in manual mode.
Telemetry is also restarted, but the configuration of xbee modules (when relevant) is not done (already done, and skip the active for faster reboot).

[chibios] recover from hard fault

---

sw/airborne/modules/computer_vision/lib/vision/fast_rosten.c
sw/airborne/modules/computer_vision/lib/vision/fast_rosten.h
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.h

We were initialising corners each time we ran the opticflow fast9 code. I now initialise it only once. 
@kirkscheper and others interested: could you please look over this pull request carefully?

[Optic flow] only initialising fast9 corners once

---

conf/airframes/TUDELFT/tudelft_bebop_opticflow.xml
conf/modules/cv_opticflow.xml
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.h
sw/airborne/modules/computer_vision/opticflow_module.c

Hi all,
I noticed that the latest changes of adding a noise measurement to the optical flow module (for the intention of use of the hff filter) were not exactly producing the necessary results. This pull request is to at least make it flyable again in the current master, after I heard several complaints from our lab.
The most important issue was this: The more corners the algorithm tracked, the higher the noise measurement (est velocity error = tracked corners/ max_corners) becomes. However this is not wanted for the ins_hff, since there a higher estimated velocity error results in less trust in that measurementof the Kalman filter. I made a new equation, which actually gives a lower noise measurement with more corners. 
In the future there needs to be a better, with optitrack groundtruth …

Pull request edgeflow noisemeasurement fix

---

sw/tools/parrot/bebop.py

To allow bebop firmware version 3.2.0 and higher, but not just 3.2.0.

correction for bebop firmware version check during uploading

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/navigation.c
sw/airborne/firmwares/rotorcraft/navigation.h

I think having dedicated variables for the commands in nav manual mode makes more sense than abusing the nav angle setpoints for this purpose. 
This can also resolve bugs when using this mode: nav_heading is for instance also set (as a BFP angle) by guidance_h_nav_enter()

set nav cmds instead of angles in nav manual mode

---

sw/logalizer/logplotter.ml

The KML output was parsing the GPS messages as radians, but it was degrees instead. This means the values were converted to degrees once more afterwards.

[ground_segment] Fix log plotter KML output

---

sw/airborne/modules/gps/gps_ubx_i2c.c

Was getting a warning about using memcpy with volatile buffer since recent changes. Saw this fix used in other i2c modules. Tested and working on ublox i2c with no warnings (the warning about casting volatile is silenced in the makefiles).

[ubx_i2c] silence warnings by casting i2c buffer

---

conf/modules/gps_ubx_i2c.xml

Interim fix until ublox can be refactored #1843 
Just do something like:
```
<module name="gps" type="ubx_i2c">
<configure name="GPS_UBX_I2C_DEV" value="i2c1"/>
</module>
```

[ublox] autoload gps_ublox module

---

sw/airborne/arch/stm32/usb_ser_hw.c

It should not affect other platforms that do have the AF9 pin connected,
this should just end up ignoring the state of the AF9 pin.

Disable USB VBUS checking.

---

sw/airborne/boards/bebop.h

Proposed to allow everybody to attach FTDI cables to their bebops. This can also be solved in the airframe file, but then that one gets bigger :s

added ttyUSB0 to bebop board

---

conf/settings/rotorcraft_basic.xml
conf/settings/rotorcraft_basic_multi.xml
sw/airborne/firmwares/rotorcraft/autopilot.c
sw/airborne/firmwares/rotorcraft/autopilot.h
sw/airborne/firmwares/rotorcraft/main.c
sw/ground_segment/joystick/gb2ivy.py

Allow to change some modes from settings even without RC for rotorcraft firmware.
This solution have been discussed in #1819

Ap mode setting

---

sw/tools/generators/gen_ubx.ml

After using some of the generated code in an 8-bit micro-controller [which gave total garbage as result], a small issue was found in the UBX_GPS paring. This **probably** does not affect 32bit microcontrollers in most cases, but here is a fix just in case (if anyone else would run it on 8bit).
Any reason behind this? Since it is at 3 places it almost looks like done on purpose.

[gps_ubx] cast 1234 to correct type instead of 134

---

sw/airborne/modules/computer_vision/blob/blob_finder.h

The unsigned range of integer values that can be stored in 16 bits is 0 through 65,535. This is not sufficient enough for blob detection with e.g. a bebop front camera.

[blob_finder] upgraded pixel_cnt to 32 bit integer

---

sw/airborne/filters/low_pass_filter.h

This calculation is only done once, so approximating the tangent is not
really necessary.

Use tangent in filter init

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_v.h

This refactors the speed/position setting in the vertical loop in guided mode as well as added a thrust setting option which should facilitate autonomous takeoff in guided mode care of @dewagter .
I am also sneaking in a fix to the vertical adaptive loop which should address #1857 , basically if the user defines a nominal throttle setting as well as adaptive throttle, use the user definition as the initial guess for the adaptive estimator. Tested and verified improvement.

[guided mode] expand guided mode in vertical guidance

---

sw/tools/generators/gen_abi.ml

AbiBindMsgX should be called only once per abi_event struct.
Regardless, this tries to make it a bit more robust if you re-use the same abi_event for consecutive AbiBindMsgX calls:
If AbiBindMsgX is called multiple times _consecutively_, the event/callback is now only added if it is different from the last one added...
This should at least fix the endless loop since the event->next can't point to itself anymore...
Should fix #1924 in a rudimentary way... but would still be possible to bind multiple times using the same abi_event if another bind for the same message happens in between.
Bottom line: make sure that your code doesn't call AbiBindMsg with the same abi_event struct multiple times!

[abi] fix endless loop if AbiBindMsgX is called twice for same event

---

conf/airframes/AGGIEAIR/aggieair_ark_quad_lisa_mx.xml
conf/airframes/AGGIEAIR/aggieair_conf.xml
conf/modules/lidar_lite.xml
sw/airborne/modules/lidar/lidar_lite.c
sw/airborne/modules/lidar/lidar_lite.h
sw/airborne/subsystems/abi_sender_ids.h

Lidar module version 1 (silver label)
https://github.com/pulsedlight3d

Lidar-Lite v1 module

---

sw/ground_segment/python/gvf/gvfApp.py
sw/ground_segment/python/gvf/gvfframe.py

I forgot to change this in the code of the previous pull request.
Now when one launches the python App for the GVF it is possible to give the ac_id of the aircraft to be tracked. Before it was hardcoded to '3'.
The wiki has been improved a bit too.

GVF python app now accepts ac_id as argument

---

sw/lib/ocaml/fp_proc.ml

- also parse return in rotorcraft, not just fixedwing

[generator] flight_plan: rotorcraft does not parse return statement

---

Makefile.ac
sw/airborne/Makefile
sw/tools/find_vpaths.py
sw/tools/generators/gen_aircraft.ml
sw/tools/qt_project.py

Replaces #1533. Description over there is still accurate. Two additions:
1. The user needs to manually set PAPARAZZI_HOME, PAPARAZZI_SRC and TARGET in the build environment after opening .creator file. 
2. The user needs to manually set the build and clean steps. Disable the check at "all" and put in "Make Arguments":   -C /home/houjebek/paparazzi -f Makefile.ac AIRCRAFT=<name> <target>.compile. For example:  -C /home/houjebek/paparazzi -f Makefile.ac AIRCRAFT=Iris ap.compile
This needs to happen only once, after which QT will create a .creator.user file

[generator] Qt project generator with VPath fix

---

sw/airborne/modules/mission/mission_common.c
sw/airborne/modules/mission/mission_common.h

It would be nice to associate a specific id to each mission that is sent to the mission module.
Currently all we get back is an array of the type of missions in the queue. 
By associating an ID number there is no confusion as to what missions are in the queue.

added mission index to mission module

---

sw/airborne/firmwares/rotorcraft/main_fbw.c

I had a few close calls with the kill switch not working (with my Iris+ with Pixhawk and the 3dr frysky remote ) when it is in fbw mode, so...
Tested and works with the Iris+

Kill switch now also works for fbw mode

---

conf/airframes/TUDELFT/tudelft_iris_indi.xml
sw/airborne/firmwares/rotorcraft/main_fbw.c
sw/airborne/firmwares/rotorcraft/main_fbw.h

FBW mode (fly by wire) is a feature implemented on the Pixhawk, which (e.g. in case the AP crashes) enables the pilot to always override with RC control. This mode makes sense in case of e.g. fixed wing operation, which often don't necessarily require stabilization to be human-controllable. However, for a quadrotor such as the Iris+ it's useless, unless an IMU is added to the FBW processor such as in the Outback board. (and although the Pixhawk has two IMU's, both are connected to the AP)
The Pixhawk has an auxiliary processor (its got an STM32F1 FBW processor and an STM32F4 AP processor) to take care of the servo commands and RC receiver, and a main processor which runs the AP and stuff. The RC commands are passed on to the AP by the FBW. And before that happens, the FBW interprets the …

Added define to disable rc-direct fbw mode manual

---

conf/airframes/TUDELFT/tudelft_conf.xml
conf/airframes/TUDELFT/tudelft_iris_indi.xml
sw/airborne/firmwares/rotorcraft/autopilot.c

In the FrSky remote that comes with the 3dr Irir+, the mode switch is mixed with the RTL switch (return to launch). The RTL switch negates the value of the mode switch.
This PR enables pprz to distill the mode unregardless of the STL switch position.
If anyone knows a better place for the RADIO_MODE_3x2 define, that would be great. Would be nice to have that in the rc xml instead of the airframe xml?

Added 2x3 way mode switch

---

sw/tools/generators/gen_airframe.ml

It used to be int16_t, but that easily overflows, for example in https://github.com/paparazzi/paparazzi/blob/master/conf/airframes/examples/quadshot_asp21_spektrum.xml#L44
servo_value and command_value are already int32_t, so I don't see a reason
to stick to int16_t

Changed the behaviour of var in command laws

---

sw/airborne/peripherals/mpu9250.c
sw/airborne/peripherals/mpu9250_regs.h
sw/airborne/peripherals/mpu9250_spi.c

According to the datasheet, the max startup time is 100 ms. If configuration starts too early, it might not be correct.

[imu] add delay to start configuring mpu9250

---

sw/airborne/arch/stm32/mcu_periph/i2c_arch.c

On some boards we need to be able to specify a different AF for some of the I2C pins (if the "non-default" pins are used).

[stm32][i2c] allow to define the GPIO alternate function number

---

sw/airborne/firmwares/motor_bench/main_motor_bench.c
sw/airborne/firmwares/tutorial/main_demo5.c
sw/airborne/modules/telemetry/telemetry_intermcu_fbw.c
sw/airborne/subsystems/datalink/datalink.h

This cropped up some time ago when someone wanted to send a large array...
I don't see any reason to limit the maximum message size to 128 byte on the airborne side, since the protocol can handle up to 256 bytes....

[datalink] maximum MSG_SIZE is 256

---

sw/airborne/firmwares/rotorcraft/main.c

Stopgap measure to fix #1961
This is actually only needed if USE_INS_NAV_INIT is used (the default).

[rotorcraft] make sure global waypoints are localized

---

sw/tools/generators/gen_flight_plan.ml

This makes the 'until' attribute of `heading`, `attitude` and `manual` consistent with the rest:
So until will always behave like:
- do something
- check if again
E.g. `<attitude ... until="some_condition"/>` will now create
```
NavAttitude(...);
if (some_condition) NextStageAndBreak();
break;
```
Fixes #1903

[flight plan] make 'until' attribute consistent

---

conf/airframes/FLIXR/flixr_conf.xml
conf/airframes/untested/quad_revo_nano.xml
conf/boards/openpilot_revo_nano.makefile
conf/firmwares/subsystems/shared/baro_board.makefile
conf/firmwares/test_progs.makefile
conf/modules/imu_openpilot_revo_nano.xml
sw/airborne/arch/stm32/mcu_arch.c
sw/airborne/arch/stm32/openpilot_revo_nano.ld
sw/airborne/boards/openpilot_revo_nano.h

- While the STM32F411 can run at up to 100MHz, this is not supported out-of-the-box with libopencm3 yet.
So we use the 84MHz clock setup from the STM32F401.
- ADC pins not set up yet

[boards] add support for openpilot revo nano board

---

conf/conf_example.xml
sw/airborne/firmwares/rotorcraft/main.c

Use the main periodc freq timer for modules if the freqs are the same
This is e.g. useful to log the important values every time the control loop runs.
should fix #1923

[rotorcraft] re-use main timer if PERIODIC_FREQUENCY == MODULE_FREQUENCY

---

conf/abi.xml
sw/airborne/modules/computer_vision/opticflow_module.c
sw/airborne/modules/ctrl/optical_flow_landing.c

To fix issue #1973, I changed the abi.xml file to treat quality as a float instead of a uint8_t instead.
This currently seems the best option. 
Alternatively I could address the FIXME in the AbiSendMsgOPTICAL in opticflow_module.c:
"// FIXME, scale to some quality measure 0-255"
However, if we change the float noise_measurement in the struct opticflow_result_t to uint8_t noise_measurement to optimize for speed, while multiplying the relevant variables by 255, other code, i.e. the filtering in the edgeflow algorithm would break as float noise_measurement is used in calculations.
**NB** I also updated the type declaration in optical_flow_landing.c to prevent compile errors.

fix loss of information due to quality variable type declaration in OF ABI

---

conf/boards/px4io_2.4.makefile
conf/radios/FrSky3dr.xml

Two minor fixes.
The kill switch now uses the normal pprz conventions. Apparantely, that was also already the standard for the Iris, I just misinterpreted the label (On = Kill switch is enabled, meaning the drone is killed)

Pixhawk config fixes

---

sw/airborne/modules/nav/nav_bungee_takeoff.c

This fix is related to the following discussion on the ML:
http://lists.paparazziuav.org/Bungee-Takeoff-failure-td18223.html
It should make the bungee takeoff independent of the initial position of the bungee waypoint set by the user.

[nav] use current alt in bungee ref point

---

conf/Makefile.disco
conf/airframes/ENAC/fixed-wing/disco.xml
conf/boards/disco.makefile
conf/firmwares/subsystems/fixedwing/autopilot.makefile
conf/firmwares/subsystems/shared/baro_board.makefile
conf/modules/actuators_disco.xml
conf/modules/imu_disco.xml
sw/airborne/arch/linux/mcu_periph/pwm_sysfs.c
sw/airborne/arch/linux/mcu_periph/pwm_sysfs.h
sw/airborne/arch/linux/mcu_periph/uart_arch.c
sw/airborne/arch/linux/mcu_periph/uart_arch.h
sw/airborne/arch/linux/serial_port.c
sw/airborne/arch/linux/serial_port.h
sw/airborne/boards/disco.h
sw/airborne/boards/disco/actuators.c
sw/airborne/boards/disco/actuators.h
sw/airborne/boards/disco/baro_board.h
sw/airborne/boards/disco/board.c
sw/airborne/subsystems/imu/imu_disco.c
sw/airborne/subsystems/imu/imu_disco.h
sw/airborne/subsystems/radio_control/sbus_common.c
sw/tools/parrot/bebop.py

- mostly based on Bebop2
- add PWM output and SBUS input on Linux (based on ArduPilot work)
- some changes to the Linux serial port lib to handle arbitrary baudrate
(this code could be improved and factorized in the future)
- all sensors are working, the video system is not tested

[board] add support for Parrot Disco plane

---

conf/modules/stabilization_attitude_fw.xml
conf/modules/stabilization_float_euler.xml
conf/modules/stabilization_float_quat.xml
conf/modules/stabilization_heli_indi.xml
conf/modules/stabilization_indi.xml
conf/modules/stabilization_indi_simple.xml
conf/modules/stabilization_int_euler.xml
conf/modules/stabilization_int_quat.xml
conf/modules/stabilization_passthrough.xml
conf/modules/stabilization_rate.xml
conf/modules/stabilization_rate_indi.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_rate_indi.c
sw/airborne/modules/obstacle_avoidance/guidance_OA.h

With this commit, you can only use indi rate, when you are using
stabilization indi or indi_simple.
This should solve the build problems.

Fix for buidling indi_rate

---

sw/tools/qt_project.py
sw/tools/qtc.creator.user_template

Will automatically set the correct build and clean target in qtcreator when building an aircraft in pprz center. Will also set the default code style (mainly tabsize = 2).
May not be perfect (depends on the user settings of qtcreator), and requires a restart of qtcreator before the settings are applied, but still saves a lot of manually settings of settings when often switching.

Automatically switch build settings qtcreator

---

conf/modules/px4_flash.xml

If anyone knows a better solution...?
Basically I need to undefine the PX4IO stuff in case of a pixracer.

Fix compile error when not using intermcu with px4flash module

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c

Also prevent unused parameter warning for the thrust callback

[indi] support rate mode

---

conf/modules/imu_vectornav.xml
sw/airborne/modules/imu/imu_vectornav.c
sw/airborne/modules/imu/imu_vectornav.h
sw/tools/vectornav_configurator/Makefile
sw/tools/vectornav_configurator/VectorNavSetup_console.cpp

Allows using Vectornav as IMU - useful if you want to test AHRS algorithms with calibrated gyro/accel data provided by vectornav.

[imu] Vectornav as IMU (gyro and accel data only)

---

sw/airborne/firmwares/rotorcraft/main_fbw.c

I was hunting for another bug,  but then I came across this:
Currently in the AP when arming through the kill switch, the kill switch must be turned on before switching  it off will arm the engines. (so if the rc was left on with kill off and throttle up when the AP is powered up, it will not attack you)
In the FBW side this is not the case. Not completely sure if we want it, but it would be more consistent I guess.

Must turn on kill switch once before kill switch can be turned off 

---

conf/joystick/frsky_tarranis_X9D_plus.xml

Added FrSky Tarranis X9D plus joystick xml file

[JOYSTICK] Added FrSky Tarranis X9D plus joystick xml

---

sw/airborne/modules/guidance/gvf/gvf.c

Hello,
now if the tracked ellipse in the guidance vector field is a circle, then the mode is changed to HORIZONTAL_MODE_CIRCLE. By doing this, the GCS will draw the circumference on the screen once a CIRCLE msg is received by the server at ground.

Drawing circles in the GCS if the user is employing the Guidance Vector Field

---

sw/airborne/modules/px4_flash/px4_flash.c
sw/airborne/subsystems/intermcu/intermcu_fbw.c
sw/tools/px4/set_target.py

There were some timing issues that disturbed communication when flashing the fbw side of px4.

Fix px4 fbw flash problem, related to #2040

---

sw/airborne/firmwares/rotorcraft/autopilot_firmware.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h

heading setpoint in float for convenience and robustness
I also changed the rotorcraft_fp and hover_loop messages to send the float value (see pprzlink pr)

guidance_h heading setpoint in float

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c

The guidance_indi was doing an unnecessary hard reset. This commit makes it take the stabilization thrust and the current euler angles as current state variables.

better initialization guidance_indi

---

conf/Makefile.chibios
conf/Makefile.lpc21
conf/Makefile.stm32-upload
conf/boards/cc3d.makefile
conf/boards/cjmcu.makefile
conf/boards/krooz_sd.makefile
conf/boards/lia_1.1.makefile
conf/boards/lisa_m_1.0.makefile
conf/boards/lisa_m_common.makefile
sw/airborne/arch/stm32/cjmcu.makefile

This is not tested as I do not have a setup to test this at the moment. @agressiva pointed out that this is an issue. Maybe he can confirm that this patch solves his issue.

OpenOCD moved the location of scripts. This patch fixes the defaults.

---

sw/airborne/arch/linux/mcu_periph/sys_time_arch.c
sw/airborne/arch/linux/mcu_periph/sys_time_arch.h

Instead of taking the periodically (often too slow) updated system ticks, the function get_sys_time_usec now obtains the time directly from the clock. This at least improves the resolution.

linux time usec from clock

---

sw/airborne/modules/computer_vision/lib/vision/fast_rosten.c
sw/airborne/modules/computer_vision/lib/vision/fast_rosten.h
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c

- Bugfix : If the reallocation of the `ret_corners` array caused it to be moved in memory, the calling function would lose track of the new corners because the pointer was only passed by value into the `fast9_detect()`. Now it is passed by reference to avoid this.
- Minor change : Local variable `corner_cnt` of `fast9_detect()` changed to `uint16_t` instead of `uint32_t`.
- _RoI_ feature not used in optic flow calculations for now, but will be when feature management is implemented.

Added a Region of Interest feature to the fast9 corner detector and fixed a reallocation bug

---

conf/airframes/TUDELFT/tudelft_bebop_indi_actuators.xml
conf/modules/stabilization_indi.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/wls/qr_solve.c
sw/airborne/firmwares/rotorcraft/stabilization/wls/qr_solve.h
sw/airborne/firmwares/rotorcraft/stabilization/wls/r8lib_min.c
sw/airborne/firmwares/rotorcraft/stabilization/wls/r8lib_min.h
sw/airborne/firmwares/rotorcraft/stabilization/wls/wls_alloc.c
sw/airborne/firmwares/rotorcraft/stabilization/wls/wls_alloc.h
sw/airborne/test/Makefile
sw/airborne/test/test_alloc.c

This is a pull request for a control allocation scheme, made by Daan Höppener, a student of mine. It allows you to specify priorities for different control objectives through a weighting in the cost function. This is why it has weighted least squares (WLS) in the name. Prioritizing parts of the control objective (pitch and roll over yaw for instance) is important for stable flight when there are saturations. Normally, the optimal control input can be found with the pseudo-inverse. However, when there are saturations, WLS-control allocation will satisfy the important parts of the control objective at the cost of the unimportant parts.
The optimal solution for this cost function is found using the active set method, which requires solving multiple least squares problems. For this we are …

WLS control allocation

---

conf/modules/cv_blob_locator.xml
conf/modules/cv_colorfilter.xml
conf/modules/cv_detect_contour.xml
conf/modules/cv_detect_window.xml
conf/modules/cv_opencvdemo.xml
conf/modules/cv_opticflow.xml
conf/modules/cv_qrcode.xml
conf/modules/video_capture.xml
conf/modules/video_usb_logger.xml
sw/airborne/modules/computer_vision/colorfilter.c
sw/airborne/modules/computer_vision/cv.c
sw/airborne/modules/computer_vision/cv.h
sw/airborne/modules/computer_vision/cv_blob_locator.c
sw/airborne/modules/computer_vision/cv_opencvdemo.c
sw/airborne/modules/computer_vision/detect_contour.c
sw/airborne/modules/computer_vision/detect_window.c
sw/airborne/modules/computer_vision/lib/vision/fast_rosten.c
sw/airborne/modules/computer_vision/lib/vision/image.h
sw/airborne/modules/computer_vision/lib/vision/lucas_kanade.c
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.h
sw/airborne/modules/computer_vision/opticflow_module.c
sw/airborne/modules/computer_vision/qrcode/qr_code.c
sw/airborne/modules/computer_vision/video_capture.c
sw/airborne/modules/computer_vision/video_usb_logger.c
sw/airborne/modules/computer_vision/viewvideo.c

This pull request tries to make the Lucas-Kanade optical flow algorithm more robust and extentable by keeping track of the same features over time instead of re-detecting every frame. Re-detection will now happen when tracked corners reach a low threshold, and only in the region(s) that have a low amount of corners.
It also fixes the already existing method which detected corners on the new frame and then projected them to the previous one to track them again.
The second commit introduces an FPS parameter to all computer vision modules such that the video listeners that they attach to the camera with the `cv_add_to_device` function can operate at a lower frequency than the camera frame rate. This can be useful in cases like the optical flow where a high frame rate could accumulate error. …

Optic flow changes

---

conf/telemetry/AGGIEAIR/aggieair_rotorcraft.xml
sw/airborne/modules/adcs/battery_monitor.c
sw/airborne/modules/adcs/battery_monitor.h

the synchronous API was a legacy code from older ChibiOS implementation and hence it didn't work in master

Refactor battery monitor to use asynchronous i2c API

---

conf/modules/dw1000_arduino.xml
sw/airborne/math/pprz_algebra_float.h
sw/airborne/modules/decawave/dw1000_arduino.c
sw/airborne/modules/decawave/dw1000_arduino.h
sw/airborne/modules/decawave/trilateration.c
sw/airborne/modules/decawave/trilateration.h
sw/airborne/subsystems/abi_sender_ids.h

Implement trilateration algorithm for positionning using the
UltraWideBand modules DW1000 from Decawave.
The interface with the modules is done with an arduino using the low
level library https://github.com/thotro/arduino-dw1000 with some
modifications.
The data extraction and trilateration are working, calibration and real
flight have not been done at the moment.

[module] add support for Decawave DW1000 modules

---

Makefile
sw/airborne/subsystems/datalink/datalink.c
sw/airborne/subsystems/datalink/datalink.h
sw/ground_segment/python/udp_link/udp_link.py
sw/simulator/nps/nps_main_hitl.c

To activate, build project with correct option:
`PPRZLINK_LIB_VERSION=2.0 make`
(note that `make clean` is usualy required before that)
At the moment, only a few messages in datalink.c are using explicitly the new format. More examples will come later, in particular regarding inter UAV communications.

[pprzlink] allow to compile paparazzi with PPRZLINK v2

---

conf/Makefile.swing
conf/airframes/examples/swing.xml
conf/boards/swing.makefile
conf/firmwares/subsystems/shared/baro_board.makefile
conf/modules/actuators_swing.xml
conf/modules/imu_swing.xml
sw/airborne/boards/swing.h
sw/airborne/boards/swing/actuators.c
sw/airborne/boards/swing/actuators.h
sw/airborne/boards/swing/baro_board.h
sw/airborne/boards/swing/board.c
sw/airborne/subsystems/imu/imu_swing.c
sw/airborne/subsystems/imu/imu_swing.h
sw/tools/parrot/ardrone2.py
sw/tools/parrot/bebop.py
sw/tools/parrot/parrot_utils.py
sw/tools/parrot/swing.py

- dedicated swing without mag
- strip code before upload
- read battery and baro from sysfs
- read power button by hand and restart
- needs to be plugged to enable telnet, can be disconnected after upload
+ factorize Parrot tools (based on Freek work)
At the moment, it is using a firmware provided by Parrot, we need to see if it works with the default official firmware.

Swing integration

---

conf/airframes/HOOPERFLY/hooperfly_enac_hexa_elle0_v1_2.xml
conf/airframes/HOOPERFLY/hooperfly_racerpex_quad_elle0_v1_2.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2_212.xml
conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2_213.xml
conf/flight_plans/HOOPERFLY/hooperfly_rotorcraft_nocturnal.xml
conf/simulator/jsbsim/aircraft/HOOPERFLY/hooperfly_enac_hexa.xml

- TeensyFly frame config updates
- Assign Elle0 led #3 to GPS lock
- Increase AHRS alignment window
- ENAC hexa frame 
- Seed a frame configuration
- Create a simulation configuration (motor rotation directions on the ENAC hexa frame are the reverse of a standard HooperFly hexa)
- RacerPEX Quad Elle0 configuration
- Created a Quad version of the ENAC frame for system testing and remote support

HooperFly & ENAC frame updates

---

sw/ground_segment/python/gvf/gvfFormation.py

The script now uses the correct library from /var/python (now it can work with pprlink v2.0 for example).
It seems that the 'array msgs' do not need to be split anymore (otherwise, with .split it crashes).

Updating gvfFormation.py

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c

The function quat_from_rpy_cmd_i does not seem to act as desired.
The quat_int controller uses simple conversion from eulers, which works
intuitively on a test case, so this one is preferred.

Fix INDI rpy setpoint function

---

sw/lib/ocaml/META.pprz.template
sw/lib/ocaml/Makefile
sw/lib/ocaml/http.ml

the SRTM download page now redirects to https
so enable support for TLS
needs the Debian/Ubuntu package libocamlnet-ssl-ocaml-dev

fix SRTM download

---

conf/firmwares/rotorcraft.makefile
conf/firmwares/subsystems/fixedwing/autopilot.makefile
conf/modules/optical_flow_landing.xml
sw/airborne/math/pprz_stat.c
sw/airborne/math/pprz_stat.h
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/ctrl/optical_flow_landing.c
sw/airborne/modules/ctrl/optical_flow_landing.h

This cleans up the optical flow module a bit and adds more options to be set from the airframe file. Also moves the computation of the covariance and mean to the statistics file in the math library. I also cleaned up a warning in the optical flow calculator with the shadow variable name 'state'. @guidoAI can you take a look at this?
@gautierhattenberger I made a stat.c file and added it to the rotorcraft makefile. Is this alright? I thought it is better if it compiled than in the header...

upgrades to optical flow landing module

---

conf/modules/gps.xml
sw/airborne/modules/multi/traffic_info.c
sw/airborne/subsystems/gps.c

This is used by the traffic info module to have position of surrounding aircraft at higher rate and lower latency.
Based on PPRZLINK v2.

Air to air gps

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c

- The attitude visualizer message was missing from indi_simple
- With INDI it was not possible to take off without RC in NAV mode (also not in sim). This was because the in_flight heuristic depends on the thrust variable, which is not really used with INDI.
Things that depend on the thrust variable:
- Current estimation
- in_flight heuristic -> which I again use to determine if the controller should run or not
This commit at least let you take off...

Attitude viz message and no_rc takeoff for indi

---

conf/airframes/AGGIEAIR/aggieair_iris_indi.xml
conf/airframes/examples/bebop.xml
conf/modules/lidar_lite.xml
conf/modules/px4flow_i2c.xml
conf/modules/sonar_bebop.xml
sw/airborne/boards/ardrone/baro_board.c
sw/airborne/boards/baro_board_ms5611_i2c.c
sw/airborne/boards/krooz/imu_krooz.c
sw/airborne/boards/krooz/imu_krooz_memsic.c
sw/airborne/boards/navgo/imu_navgo.c
sw/airborne/filters/median_filter.h
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/lidar/lidar_lite.c
sw/airborne/modules/lidar/lidar_sf11.c
sw/airborne/modules/optical_flow/px4flow_i2c.c
sw/airborne/modules/sonar/sonar_bebop.c
sw/airborne/modules/stereocam/stereocam2state/stereocam2state.c

This looks for large changes in sonar readings and delays sending the new measurements till the rate of change of the new measurement compared to the last sent measurement drops below a certain fixed threshold. This was found to be necessary to prevent large outliers from being propagated through the ins (the sonar is typically trusted quite heavily).
This outlier detector will also delay the propagation of true vertical height transitions for eg when flying over a table, the gradient threshold has been chosen to remove temporary outliers and not delay true transitions for very long.

added outlier detector to bebop sonar

---

Makefile.ac

Properly seperate cxx and cflags again

---

conf/Makefile.nps
conf/modules/fdm_gazebo.xml
sw/airborne/arch/sim/mcu_arch.c
sw/airborne/arch/sim/mcu_periph/i2c_arch.c
sw/simulator/nps/nps_autopilot_fixedwing.c
sw/simulator/nps/nps_autopilot_rotorcraft.c
sw/simulator/nps/nps_fdm_gazebo.cpp
sw/simulator/nps/nps_flightgear.c
sw/simulator/nps/nps_flightgear.h
sw/simulator/nps/nps_main_common.c
sw/simulator/nps/nps_radio_control_spektrum.c

Added some additional warnings to the simulator to better resemble the flight code and addressed the new warnings.
Added the capability to turn off the GPS, useful for testing indoor environments.
Added some additional debugging capabilities.
I came across a strange warning that I didn't see before:
cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
I can't find where the cflags are being added to the CXXFLAGS but this warning is also in the current master. Any ideas?

[sim] updates to gazebo so simulate pressure and acceleration

---

conf/abi.xml
conf/airframes/TUDELFT/tudelft_ardrone2_opticflow.xml
conf/airframes/TUDELFT/tudelft_ardrone2_opticflow_indi.xml
conf/airframes/TUDELFT/tudelft_bebop2_opticflow.xml
conf/airframes/TUDELFT/tudelft_bebop_opticflow.xml
conf/conf_example.xml
conf/modules/ins_hff_extended.xml
sw/airborne/subsystems/ins/hf_float.c
sw/airborne/subsystems/ins/hf_float.h
sw/airborne/subsystems/ins/ins_int.c

This adds a bias estimate to the hff filter and allows the filter to run with only velocity inputs as well as position estimates. This also adds the possibility to have a local position estimate added to the ins. 
This has been tested with a bebop 2 and a pocket drone. It is important to define the noise characteristics to suit the drone being used but once done the performance is quite good.

[ins] updated hff to accept velocity as only input and add bias

---

conf/simulator/gazebo/models/ardrone/ardrone.sdf
conf/simulator/nps/nps_sensors_params_ardrone2.h

This should fix the accelerometer bounds issue #2090.
Also adds missing drag to the ardrone model, which is now correctly measured by the accelerometer.
Verify by setting the telemetry to sensors_scaled and plotting the scaled accelerometer values:
Before:
After:

Fix #2090 

---

conf/airframes/TUDELFT/tudelft_xvert.xml
conf/airframes/airframe.dtd

A dedicated XML tag will allow tools to fetch the description. Fetching comments is much harder. This will also help keep airframe files up to date and describe capabilities.

[DTD] add descriptions to airframes instead of commented xml

---

sw/simulator/nps/nps_fdm_gazebo.cpp

This PR fixes a bug in the accelerations measured by gazebo.
Gazebo's GetWorldLinearAccel() did not seem to take the ardrone's velocity_decay (drag) into account, instead it measured the drone's acceleration *without drag* which resulted in incorrect measurements
in-flight (the drone's acceleration in world frame did not go to zero when the drone reached its steady-state velocity).
Fixed by manually deriving the drone's world velocity over time, as in [Gazebo's own IMU implementation](https://bitbucket.org/osrf/gazebo/src/e26144434b932b4b6a760ddaa19cfcf9f1734748/gazebo/sensors/ImuSensor.cc?at=default&fileviewer=file-view-default#ImuSensor.cc-370).
Created an issue for Gazebo [here](https://bitbucket.org/osrf/gazebo/issues/2363/linear-velocity_decay-not-included-in-link).

Fix incorrect in-flight acceleration measurements in Gazebo

---

sw/airborne/firmwares/fixedwing/guidance/energy_ctrl.c
sw/airborne/modules/mission/mission_fw_nav.c
sw/airborne/modules/mission/mission_rotorcraft_nav.c

Fixes #2136 as recommended by @kirkscheper

Make dt_* global variables static in mission and energy_ctrl.

---

conf/airframes/KS/kirk_conf.xml
conf/airframes/KS/ks_bebop2_stereo.xml
conf/airframes/TUDELFT/tudelft_conf.xml
conf/airframes/TUDELFT/tudelft_ladybird_lisa_mxs.xml
conf/modules/video_thread.xml
conf/simulator/gazebo/models/simple_quad/model.config
conf/simulator/gazebo/models/simple_quad/simple_quad.sdf
conf/simulator/gazebo/models/simple_x_quad/model.config
conf/simulator/gazebo/models/simple_x_quad/simple_x_quad.sdf
conf/simulator/gazebo/world/empty.world
sw/airborne/arch/sim/subsystems/settings_arch.c
sw/airborne/subsystems/actuators/motor_mixing_types.h
sw/airborne/subsystems/gps/gps_sim_nps.c
sw/simulator/nps/nps_autopilot_fixedwing.c
sw/simulator/nps/nps_autopilot_rotorcraft.c
sw/simulator/nps/nps_fdm_gazebo.cpp
sw/simulator/nps/nps_sensor_gps.c

This enables gazebo to grab the quadrotor configuration from the airframe file and load up the correct model. This also ensures that the same yaw configuration is used for the simulator as is defined in the motor_mixing to reduce possible user error. Now the only thing is that the order of the actuator names still has to be correct.
Secretly, this also refractors how GPS is ignored in nps. As well as replaces course with heading when GPS_DATALINK is used so that nps correctly copies reality when using natnet/optitrack.
@knmcguire and @tomvand can you take a look here and let me know if there are any issues.

[nps] load aircraft into gazebo at run time + actuator handling

---

sw/airborne/subsystems/ins/hf_float.c

The defines for Q, Qdotdot, etc. can potentially create conflicts with internal variables in other modules. Now they have the HFF_ prefix.

Changed define variable names to avoid conflicts with other code

---

conf/airframes/TUDELFT/tudelft_conf.xml
conf/userconf/OPENUAS/openuas_conf.xml
start.py
sw/lib/python/paparazzi.py
sw/lib/python/paparazzi_health.py
sw/supervision/paparazzicenter.glade
sw/supervision/pc_aircraft.ml

**change:**
- tag which airframes were tested in which commit
**personal use:**
- commit-count since last flight
- instant-revert to flying code
- history of tests
**users:**
- provide information on what was tested in a release
**project:**
- airframe age computations & cleanup
- release candidate selection

Store the git SHA of test-flown aircraft

---

sw/tools/parrot/bebop/wifi_tools/README.md
sw/tools/parrot/bebop/wifi_tools/README.txt
sw/tools/parrot/bebop/wifi_tools/connect2ssid.sh
sw/tools/parrot/bebop/wifi_tools/pprz.conf
sw/tools/parrot/bebop/wifi_tools/pprz_swarmhub.conf
sw/tools/parrot/bebop/wifi_tools/recoverDrone.sh
sw/tools/parrot/bebop/wifi_tools/remove4press.sh
sw/tools/parrot/bebop/wifi_tools/scripts/button_switch
sw/tools/parrot/bebop/wifi_tools/scripts/config_network.script
sw/tools/parrot/bebop/wifi_tools/scripts/connect2hub
sw/tools/parrot/bebop/wifi_tools/scripts/pprz.conf

Added a set of scripts (in sw/tools/parrot/bebop) to allow Bebop 2 drones to connect to a router instead of acting as access points.

Pullrequest bebop2 tools wifi tools

---

sw/airborne/subsystems/ins/hf_float.c

Moved the include for telemetry.h to the top, before all defines, otherwise it may cause errors where define names conflict with variable names in other compiled modules.

hf_float.c moved telemetry.h include to top

---

sw/tools/key_generator/.gitignore
sw/tools/key_generator/Cargo.toml
sw/tools/key_generator/src/main.rs

Generates two header files, `keys_uav.h` and `keys_gcs.h` and puts them into the destination directory. Should be called externally from a makefile.
Makefile command: 
```
$(AIRFRAME_H) : $(CONF)/$(AIRFRAME_XML) $(CONF_XML) $(AIRCRAFT_MD5)
...
$(Q)cargo run --manifest-path $(PAPARAZZI_HOME)/sw/tools/key_generator/Cargo.toml --release $(AC_GENERATED)
```
Requires Rust and Cargo (get it from https://www.rustup.rs/ )

Added key generator for asymmetric keys

---

conf/airframes/examples/ardrone2_gazebo_cyberzoo.xml
conf/airframes/tudelft/bebop_orangeavoid_course2017.xml
conf/flight_plans/tudelft/course2017_avoid_orange_cyberzoo.xml
conf/modules/orange_avoider.xml
conf/simulator/gazebo/models/cyberzoo/cyberzoo.sdf
conf/simulator/gazebo/models/cyberzoo/model.config
conf/simulator/gazebo/models/orange_pole/model.config
conf/simulator/gazebo/models/orange_pole/orange_pole.sdf
conf/simulator/gazebo/world/ardrone_cyberzoo.world
conf/userconf/tudelft/conf.xml
conf/userconf/tudelft/course2017_conf.xml
conf/userconf/tudelft/course2017_control_panel.xml
sw/airborne/modules/computer_vision/lib/vision/image.c
sw/airborne/modules/orange_avoider/orange_avoider.c

This code is being used in the TUDelft MAVLab course

Gazebo in tudelft conf, with orange avoid example

---

sw/ground_segment/python/gvf/gvfFormation.py

While I am writing a new script (taking this one as a starting point) for another module I am realizing about small bugs that can be annoying. 
In this case, if we exit the main loop, then we always close the ivy interface, so the script can happily finish and exit to the shell.

Python script exits in a clean way

---

conf/abi.xml
sw/airborne/modules/computer_vision/opticflow_module.c
sw/airborne/modules/dragspeed/dragspeed.c
sw/airborne/modules/guidance_opticflow/guidance_opticflow_hover.c
sw/airborne/modules/optical_flow/px4flow.c
sw/airborne/modules/optical_flow/px4flow_i2c.c
sw/airborne/modules/stereocam/stereocam.c
sw/airborne/subsystems/abi_sender_ids.h
sw/airborne/subsystems/ins/hf_float.c
sw/airborne/subsystems/ins/ins_int.c
sw/airborne/subsystems/ins/vf_extended_float.c
sw/airborne/subsystems/ins/vf_float.c

This makes it optional to define if you want to update the horizontal and/or vertical parameters of the velocity and position estimates from the abi message. This should address the issue #2144 .

add flags to velocity and position estimate abi messages

---

conf/airframes/examples/microjet.xml
sw/ground_segment/cockpit/live.ml
sw/ground_segment/cockpit/live.mli
sw/ground_segment/cockpit/strip.ml
sw/ground_segment/cockpit/strip.mli

See issue #1555 .
Waiting for @OpenUAS to test.

Make GCS radio link indicator configurable 

---

Makefile

see discussion in #2167
It is recommended to run `make clean && make` for a proper upgrade to the new version of the library

[pprzlink] set version 2 as default

---

conf/airframes/ENAC/conf_enac.xml
conf/airframes/ENAC/cyfoam.xml
conf/modules/ctrl_effectiveness_scheduling.xml
conf/modules/tlsf.xml
conf/simulator/jsbsim/aircraft/Systems/aerodynamics_cyfoam.xml
conf/simulator/jsbsim/aircraft/cyclone.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.h
sw/airborne/modules/ctrl/ctrl_effectiveness_scheduling.c
sw/airborne/modules/ctrl/ctrl_effectiveness_scheduling.h

- Added Cyfoam airframe file
- Added control effectiveness scheduling function
- More advanced scheduling function should be added in the future
- Added simple JSBsim files for Cyclone for a crude simulation

Cyfoam, ctrl effectiveness scheduling, JSBsim

---

sw/ground_segment/python/gvf/README
sw/ground_segment/python/gvf/gvfframe.py

The app for monitoring the GVF in python now works again.
No idea why this script was working a year ago. Maybe because 'msg.get_field' was not a list before (and now it is).

split cannot be used with lists

---

sw/ground_segment/tmtc/pprzlink_proxy.py

PPRZLINK Proxy is a tool to allow multiple aircraft simulations
with air-to-air communication using the PPRZLINK v2 protocol
using UDP.
As aircarft can't be identified by their IP addresses (most of the
time, all simulators are running on the same computer), each agent (GCS,
aircraft) are using different ports and the mapping between ports and IDs
is done by this tool.

[tmtc] add pprzlink_proxy tool

---

sw/airborne/boards/lisa_l/baro_board.c
sw/airborne/filters/median_filter.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
sw/airborne/peripherals/adxl345_spi.c
sw/airborne/peripherals/mpu60x0_i2c.c
sw/airborne/peripherals/mpu60x0_spi.c
sw/airborne/subsystems/navigation/common_flight_plan.h
sw/tools/generators/gen_flight_plan.ml

Some warnings related to the use of the Label() macro are still there.
It seems that the only way would be generate the labels instead of calling the macros. Any better idea ?
See issue #2207

[build] fix some of the implicit-fallthrough warnings from GCC7

---

conf/airframes/examples/ardrone2_gazebo.xml
conf/airframes/examples/ardrone2_opticflow_hover.xml
conf/airframes/tudelft/ardrone2_opticflow.xml
conf/airframes/tudelft/ardrone2_opticflow_indi.xml

The ARDrone in paparazzi Master was flying at 2-5 FPS, which is insufficient for proper optical flow.
Upon investigating it turns out that this is the case since https://github.com/paparazzi/paparazzi/pull/2079
where the feature management was introduced, later fixed in https://github.com/paparazzi/paparazzi/pull/2087. However the feature management is turned off by default.
Furthermore the pyramid was set two 2 layers standard.
Testing on an ARDrone and Bebop alongsides showed that the Bebop had no issue with the code and was still flying arround 90 FPS(camera maximum) while the ARDrone dropped from 30-60 FPS(camera max) to 2-5 FPS. 
In this pullrequest I set the pyramid back to 0, which improved FPS to about 10-15 FPS. I also tried to turn on feature management, which had the same …

ARDrone vision fix

---

conf/airframes/tudelft/bebop_orangeavoid_course2017.xml
conf/userconf/tudelft/course2017_conf.xml

Fixed the MT9F002 defines in the bebop airframe in preparation for the 2018 MAVLab course. Set video streaming back to broadcast to simplify streaming. Test-flown and tagged accordingly in the conf file.

Fix bebop_orangeavoid_course2017 defines

---

sw/airborne/math/pprz_stat.c
sw/airborne/modules/computer_vision/opticflow/size_divergence.c

Referencing back to https://github.com/paparazzi/paparazzi/issues/2097#issuecomment-320302913 again, there is still a divide by 0 possible and actually happening.
If for all samples in  
for (uint16_t sample = 0; sample < n_samples; sample++)
distance_1 is 0, then the newly introduced used_samples remains 0, leading to a division by 0 in the mean_f function in:
https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/modules/computer_vision/opticflow/size_divergence.c#L118
This value then messes up filters where the size_divergence is used, for example OF_Landing and forthcoming OF_Hover.
The suggested fix sets the mean_divergence to 0. Though I am NOT sure if this is the correct behavior to fix it.

added a divide by 0 failsafe

---

sw/airborne/firmwares/rotorcraft/main_ap.c

I looked at #2203 , and I think this should give the right warning. I could not exactly find where PERIODIC_FREQUENCY is defined, looks like it is generated but I am not sure from where.

give a warning when periodic freq is infeasible

---

.gitmodules
conf/modules/cv_opencvdemo.xml
sw/airborne/modules/computer_vision/opencv_example.cpp

Adds an nps target to the cv_opencvdemo module.
Also re-enabled the canny edge detector example, as the result
is easier to see than the blurring example.
Added the LDFLAGS produced by the current version of opencv_bebop.

Add nps target to cv_opencvdemo module

---

sw/airborne/subsystems/navigation/common_flight_plan.h
sw/include/std.h
sw/tools/generators/gen_flight_plan.ml

This should fix most remaining warnings from flight plans.
Also provide a convenience macro depending of the compiler version.
see #2207

[build] handle fallthru warning in flight plans due to NextStage

---

sw/tools/parrot/bebop/wifi_tools/scripts/connect2hub

it seems that 2 seconds is a bit to short in some cases when the router takes longer to reply. 5 seconds gives much better results.

[parrot] wait longer when connecting bebop to wifi router

---

conf/airframes/ENAC/cyfoam.xml
sw/airborne/subsystems/radio_control.h

It seems to me the inputs to this macro cause problems and are not very useful, as you can also just put 'commands' in the command_laws. Only fbw uses 'trimmed_commands' instead of 'commands', but this can be dealt with by putting 'trimmed_commands' in the command laws instead of 'commands'.
This does require editing all airframes...

suggestion to make command laws more flexible

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.h

Should fix the #599. Most of it was already done but this removes the dependency of the stabilization on the guidance.

[rotorcraft] fix dependancy of stabilization on guidance

---

sw/airborne/arch/linux/mcu_periph/i2c_arch.c
sw/airborne/arch/linux/mcu_periph/sys_time_arch.c
sw/airborne/arch/linux/mcu_periph/uart_arch.c
sw/airborne/arch/linux/mcu_periph/udp_arch.c
sw/airborne/boards/ardrone/navdata.c
sw/airborne/boards/swing/baro_board.c
sw/airborne/boards/swing/board.c
sw/airborne/mcu_periph/i2c.c
sw/airborne/modules/computer_vision/cv.c
sw/airborne/modules/computer_vision/video_thread.c
sw/airborne/modules/sonar/sonar_bebop.c

This adds a thread to read/write i2c transactions so that they don't block the main thread. This should address #1500. I currently have a hard sleep in the i2c thread of 5us, let me know if this is appropriate. Of course the transactions will not come in too fast but you also don't want too much latency.

add i2c transaction cue to the linux arch

---

conf/Makefile.nps
conf/Makefile.sim
sw/airborne/arch/chibios/mcu_periph/i2c_arch.h
sw/airborne/arch/linux/mcu_periph/i2c_arch.c
sw/airborne/arch/linux/mcu_periph/i2c_arch.h
sw/airborne/arch/linux/mcu_periph/sys_time_arch.c
sw/airborne/arch/linux/mcu_periph/uart_arch.c
sw/airborne/arch/linux/mcu_periph/udp_arch.c
sw/airborne/arch/sim/mcu_periph/i2c_arch.h
sw/airborne/arch/stm32/mcu_periph/i2c_arch.h
sw/airborne/boards/ardrone/navdata.c
sw/airborne/boards/bebop/actuators.c
sw/airborne/boards/bebop/mt9f002.c
sw/airborne/boards/bebop/mt9v117.c
sw/airborne/boards/swing/baro_board.c
sw/airborne/boards/swing/board.c
sw/airborne/mcu_periph/i2c.c
sw/airborne/mcu_periph/i2c.h
sw/airborne/modules/computer_vision/video_thread.c
sw/airborne/modules/sonar/sonar_bebop.c

The cameras for the bebop need blocking to write the configuration. Additionally, actuators have a multi-write protocol so also need blocking write.
This also moves the GNU_SOURCE def to the makefile and places ifdef protection for pthread_setname on mac.

add blocking option to i2c, remove unnecesary GNU_SOURCE and protect  pthread_setname from mac

---

sw/airborne/arch/linux/mcu_periph/sys_time_arch.c
sw/airborne/arch/linux/mcu_periph/uart_arch.c
sw/airborne/arch/linux/mcu_periph/udp_arch.c

Bracket pthread_setname_np calls used by the simulation with __APPLE__ to avoid conflicts. Tested on Mac OS X system.

Fix pthread_setname_np conflicts for Mac OS X with respect to simulation.

---

sw/ground_segment/cockpit/Makefile

The bug from #1647 still exists on newer versions if lablgtk so I expanded the patch to look for all versions 2.18.*. This is needed to have versions above 16.04 to work.

[Makefile] extend workaround lablgtk fix to all 2.18 versions

---

sw/airborne/state.c

- return before setting flag if conversion is not done
if bit is set for a given representation while conversion was not  possible, this may impact future conversions in other representation  as well, depending of the priority order (note that proper errno is still not set at the moment)
-  add more conversions for LLA format, especially handle NED and UTM initialization

State return fix

---

sw/airborne/arch/linux/mcu_periph/i2c_arch.c
sw/airborne/arch/linux/mcu_periph/sys_time_arch.c
sw/airborne/arch/linux/mcu_periph/uart_arch.c
sw/airborne/arch/linux/mcu_periph/udp_arch.c
sw/airborne/modules/computer_vision/cv.c
sw/airborne/modules/computer_vision/lib/v4l/v4l2.c
sw/airborne/modules/computer_vision/video_thread.c

Unfortunately, the pthread_setname_np accepts a maximum of 15 characters.
Additionally, I added the thread naming for some additional threads.

[Linux] Update thread naming

---

conf/modules/pipe.xml
sw/airborne/arch/linux/mcu_periph/pipe_arch.c
sw/airborne/arch/linux/mcu_periph/pipe_arch.h
sw/airborne/arch/sim/mcu_periph/pipe_arch.c
sw/airborne/arch/sim/mcu_periph/pipe_arch.h
sw/airborne/mcu.c
sw/airborne/mcu_periph/pipe.c
sw/airborne/mcu_periph/pipe.h

This allows for high speed, lossless fifo communication between two programs running on a linux platform using a two half duplex named pipes.

[mcu_periph] add full duplex named pipe

---

conf/airframes/tudelft/yapa_xsens.xml
sw/airborne/firmwares/fixedwing/main_ap.c

- interrupts not enabled during xbee setup (which is called from modules_init)
- thereby only the first byte is sent (in LPC: the tx-complete interrupt loads the next byte)
- and configuration fails
- moving modules_init() after the interrupts solves this
- it is unclear how much this will break elsewhere.

[xbee_api] fixedwing LPC21 xbee_api broken

---

sw/ground_segment/tmtc/link.ml

Configure the xbee channel at modem initialization.
Use option -ch to change xbee channel.
Default is 0x0C.

[datalink] Set Xbee channel

---

sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c

Small change: if the rotation rate is too high, instead of derotating the flow, the flow is set to 0. First this was only done for the roll angle. Now it will also be done for the pitch angle.

Derotation threshold now also for pitch

---

sw/tools/generators/gen_flight_plan.ml

with this, flight plan variables can be used by raw code written in the
flight plan header section

[flight_plan] move declaration of automatic var before header section

---

conf/modules/digital_cam.xml
sw/airborne/modules/digital_cam/dc.c

this is useful to trigger or just send information to an embedded companion CPU in addition to the GCS

[module] add option to digital cam to send second DC_SHOT message

---

conf/airframes/examples/bebop2_opticflow.xml
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/computer_vision/opticflow_module.c

In the current master version, vertical velocity is also determined by the optical flow module, with the help of divergence. However, the current code is not robust - leading to faulty large altitude estimates and very large velocities. This leads to large control inputs, which result in worse vision, which result in even worse estimates... you get the drift.
So, in this pull request, I just changed some things in the bebop2_opticflow.xml (it was set not to update sonar on AGL, etc.) and the opticflow_module.c files to make the hover mode work again out of the box (this was broken due to the addition of the vertical velocity). 
In the future, this pull request should be followed up by a more fundamental solution that takes the reliability of the divergence into account for estimating the …

Solving problems flying with optical flow

---

conf/airframes/OPENUAS/openuas_parrot_disco.xml
conf/boards/disco.makefile
conf/flight_plans/OPENUAS/openuas_versatile.xml
conf/modules/airspeed_ms45xx_i2c.xml
conf/radios/OPENUAS/openuas_sbus_out.xml
conf/telemetry/OPENUAS/openuas_fixedwing_imu.xml
conf/userconf/OPENUAS/openuas_conf.xml
conf/userconf/OPENUAS/openuas_control_panel.xml
sw/airborne/arch/sim/max1167_hw.c
sw/airborne/boards/bebop/actuators.c
sw/airborne/boards/bebop/mt9v117.c
sw/airborne/boards/disco.h
sw/airborne/boards/disco/actuators.c
sw/airborne/boards/disco/actuators.h
sw/airborne/boards/disco/baro_board.h
sw/airborne/boards/disco/board.c
sw/airborne/modules/loggers/file_logger.c
sw/airborne/modules/sensors/airspeed_ms45xx_i2c.c
sw/airborne/modules/sensors/airspeed_ms45xx_i2c.h
sw/tools/generators/gen_flight_plan.ml
sw/tools/parrot/disco.py

Outcome: Full PPRZ support for Parrot Disco. Test Disco with firmware v1.7.1
Stage 1 is a well flying Disco with lots of options
Full Auto2 flights of minimum 1 hour total airtime with firmware 1.7.1
Stage 2 will contain more nice to haves like First inital frontcam workings
Stage 3 will be the final stage with HW X264 encoding and hardware accelerated video stabilization
For this a separate PR will be made.

Parrot Disco stage 1 of fixes added

---

conf/airframes/tudelft/bebop2_undistort_front.xml
conf/airframes/tudelft/guido_conf.xml
conf/modules/cv_undistort_image.xml
sw/airborne/modules/computer_vision/lib/vision/undistortion.c
sw/airborne/modules/computer_vision/lib/vision/undistortion.h
sw/airborne/modules/computer_vision/undistort_image.c
sw/airborne/modules/computer_vision/undistort_image.h

I have added undistortion functions to the vision library. These can be used to convert image coordinates from distorted fisheye lenses to undistorted coordinates and back, taking into account the camera calibration matrix and the distortion of the specific lens. The distortion function is the one from Dhane, P., Kutty, K., & Bangadkar, S. (2012). A generic non-linear method for fisheye correction. International Journal of Computer Applications, 51(10). (invertible fisheye model), as it is an invertible model. 
I also made a module, undistort_image, that uses the functions to undistort a whole image. This is quite a slow process, so it is not really advisable to use this in a vision pipeline leading to control. However, it can be used to find the right undistortion parameter k, and shows …

Image undistortion for fisheye lenses

---

conf/Makefile.sim
conf/modules/mission_fw.xml
conf/modules/mission_rotorcraft.xml
conf/modules/nav_flower.xml
sw/airborne/modules/mission/mission_common.c
sw/airborne/modules/mission/mission_common.h
sw/airborne/modules/mission/mission_fw_nav.c
sw/airborne/modules/mission/mission_rotorcraft_nav.c
sw/airborne/modules/nav/nav_flower.c
sw/airborne/modules/nav/nav_flower.h

Specific navigation functions or even payload actions can be registered in the mission module in order to be called from the mission controller like the built-in navigation patterns.
Each custom element (callback function) is registered/called with an unique string identifier of 5 char max. A maximum of 12 parameters can be passed to the callback function.
An example is provided with the nav_flower navigation function.

[mission] add support for custom mission patterns or actions

---

conf/airframes/examples/bebop2_opticflow.xml
conf/airframes/tudelft/bebop2_opticflow.xml
conf/airframes/tudelft/bebop2_optitrack_visionfront.xml
conf/airframes/tudelft/bebop_opticflow.xml
conf/modules/cv_opticflow.xml
sw/airborne/boards/bebop/mt9f002.c
sw/airborne/boards/bebop/mt9f002.h
sw/airborne/boards/bebop/mt9v117.c
sw/airborne/boards/bebop/mt9v117.h
sw/airborne/modules/computer_vision/lib/vision/image.c
sw/airborne/modules/computer_vision/lib/vision/image.h
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/peripherals/video_device.h

Derotation is also needed when using flow from the frontal camera. However, a simple correction factor applied to the median flow will not work for broad field-of-view lenses such as the Bebop 2 lens. The best way then, is to undistort and derotate individual vectors. This is what I implemented in this pull request. The parameters for the undistortion are stored in the camera-specific file and can hence be set in the airframe file.

Derotate flow front camera

---

.gitmodules
conf/Makefile.chibios
conf/Makefile.stm32
conf/abi.xml
conf/airframes/ENAC/fixed-wing/zagi_mekf_wind.xml
conf/chibios/chibios_extra_rules.mk
conf/firmwares/test_progs.makefile
conf/modules/airspeed_ms45xx_i2c.xml
conf/modules/ins_mekf_wind.xml
conf/telemetry/fixedwing_flight_recorder.xml
sw/airborne/autopilot.c
sw/airborne/firmwares/fixedwing/main_chibios.c
sw/airborne/math/pprz_isa.h
sw/airborne/modules/air_data/air_data.c
sw/airborne/modules/ins/ins_mekf_wind.cpp
sw/airborne/modules/ins/ins_mekf_wind.h
sw/airborne/modules/ins/ins_mekf_wind_wrapper.c
sw/airborne/modules/ins/ins_mekf_wind_wrapper.h
sw/airborne/modules/sensors/airspeed_adc.c
sw/airborne/modules/sensors/airspeed_ms45xx_i2c.c
sw/airborne/modules/sensors/airspeed_ms45xx_i2c.h
sw/airborne/modules/sensors/aoa_adc.c
sw/airborne/modules/sensors/aoa_pwm.c
sw/airborne/pprz_syscalls.c
sw/airborne/subsystems/abi_sender_ids.h
sw/airborne/test/test_eigen.cpp
sw/simulator/nps/nps_autopilot_fixedwing.c

This new module is a full INS including wind estimation based on IMU/GPS/baro + airspeed/AoA/Sideslip measurements with MEKF filter.
The integration is using the C++ Matrix library Eigen included as a submodule.
Some minor changes:
- airspeed and incidence sensors using ABI
- improve some drivers and system configuration
- example airframe, tested in flight
Reference:
Martin Brossard, Jean-Philippe Condomines, Silvère Bonnabel. Tightly coupled navigation and wind estimation for mini UAVs. AIAA GNC 2018, AIAA Guidance, Navigation, and Control Conference, Jan 2018, Kissimee, United States.
https://hal-enac.archives-ouvertes.fr/hal-01814261

Mekf Wind INS

---

conf/modules/radio_control_spektrum.xml
sw/airborne/subsystems/radio_control/spektrum.c

This was the previous behavior before rewritting the spektrum driver.
DSMX mode should only be used for compatible receivers and transmitters,
otherwise the system type will be be detected properly and frames will
be discarded.
This should solve #2270

[radio] use DSM2 as default binding protocol

---

conf/ubx.xml
sw/airborne/modules/gps/gps_ubx_ucenter.c
sw/airborne/modules/gps/gps_ubx_ucenter.h

Since the Ublox 7 series, several constellations are supported.
Since the Ublox 8 series, constellations can be enabled at the same time.
It now becomes important to know which version is in your plane and which constellation is activated.
A dedicated message will be sent on startup.

[ublox] Hw-Sw version info and Config Info on startup

---

.travis.yml
conf/modules/fdm_gazebo.xml
docker/ci/Dockerfile
sw/simulator/nps/nps_fdm_gazebo.cpp

Gazebo 7 is not supported on Ubuntu 18.04 (Bionic), this PR updates the function calls in the nps fdm to be compatible with Gazebo 8 and Gazebo 9. With this, gazebo is no longer compatible with installations on systems earlier than Ubuntu 16.04 (Xenial).

Update gazebo from v7 to v8/v9 compatibility

---

.gitignore
conf/abi.xml
conf/modules/relative_localization_filter.xml
sw/airborne/math/pprz_algebra.h
sw/airborne/math/pprz_algebra_float.c
sw/airborne/math/pprz_algebra_float.h
sw/airborne/modules/decawave/decawave_anchorless_communication.c
sw/airborne/modules/relative_localization_filter/discrete_ekf.c
sw/airborne/modules/relative_localization_filter/discrete_ekf.h
sw/airborne/modules/relative_localization_filter/discrete_ekf_no_north.c
sw/airborne/modules/relative_localization_filter/discrete_ekf_no_north.h
sw/airborne/modules/relative_localization_filter/relative_localization_filter.c
sw/airborne/modules/relative_localization_filter/relative_localization_filter.h

Added a relative localization filter that does not require the drones to have knowledge of a common heading (such as North). This allows to be independent of errors coming from the magnetometer or the building bias that may be caused by a gyroscope. The filter is as implemented and used in van der Helm et al. "On-board Range-based Relative Localization for Micro Aerial Vehicles in indoor Leader-Follower Flight". https://arxiv.org/abs/1805.07171.

Pullrequest relative localization no north filter

---

conf/airframes/tudelft/bebop2_undistort_front.xml
conf/modules/cv_undistort_image.xml
sw/airborne/modules/computer_vision/undistort_image.c
sw/airborne/modules/computer_vision/undistort_image.h
sw/airborne/peripherals/video_device.h

This reuses the camera intrinsics from the video device hence removing some double settings.

update undistort to use video camera intrinsics

---

conf/userconf/OPENUAS/openuas_conf.xml
conf/userconf/tudelft/conf.xml

they can be added back once the issues are properly handled
- some errors with opencv compilation not producing the correct lib
- some error in the xml
At least try to have a CI build that doesn't fail. The actual problems are not that clear, and it may come from the CI configuration as well. Until this is properly identified, there is no point keeping them in the nightly build.

[conf] remove conf failing the CI tests

---

sw/ground_segment/cockpit/Makefile

Cherry picked backport patch for 5.12 to compile on Ubuntu 18.04

extend workaround lablgtk fix to all 2.18 versions (#2264)

---

sw/airborne/math/pprz_algebra_float.c
sw/airborne/math/pprz_algebra_float.h
sw/airborne/math/pprz_algebra_int.c
sw/airborne/math/pprz_algebra_int.h

Improve doc and choose a more reasonable output resolution of the integer version.
The only possible issue might be in the hybrid guidance:
- quat setpoint should now have the proper value, but since the "wrong" value was currently compensated later in the code it shouldn't change anything
- euler setpoint should be correct now, but it is unclear if it was even used with hybrid guidance (it shouldn't)
- hybrid guidance from master is currently not much used apparently and might need some extra cleaning and better integration anyway, better have this part correct now at least
I suggest to merge this now for next release even if hybrid guidance can't be fully checked before that.
fix #2331

[math] fix quat_of_axis functions

---

sw/airborne/subsystems/radio_control/sbus_common.c
sw/airborne/subsystems/radio_control/sbus_common.h

Fix bug when SBUS packets contain the `SBUS_START_BYTE` and can not synchronise at boot.

[rc] Fix SBUS initialization synchronising with timeout

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_transformations.c

[rotorcraft] stabilization quat_from_earth_cmd_f() :  fix b_x and b calculation
- b_x is rotation matrix first row in NED
- dot(b,n) = 0

Fix bugs of quat_from_earth_cmd_f()

---

start.py
sw/airborne/modules/loggers/logger_uart_parse.py
sw/ground_segment/python/fc_rotor/fc_rotor.py
sw/ground_segment/python/joystick/ivydanger.py
sw/ground_segment/python/udp_link/datalink_to_w5100.py
sw/ground_segment/python/udp_link/proxy_udp_multicast_to_link.py
sw/ground_segment/tmtc/pprzlink_proxy.py
sw/logalizer/sdlogger_get_setting_id.py
sw/misc/attitude_reference/pat/utils.py
sw/simulator/mesonh/mesonh.py
sw/tools/airframe_editor/airframe_editor.py
sw/tools/airframe_editor/gui_dialogs.py
sw/tools/iridium/iridium_link.py
sw/tools/parrot/parrot_utils.py
sw/tools/px4/set_target.py
sw/tools/stm32loader/stm32loader.py
tests/test_python3_compatibility.py

Many python scripts in paparazzi are not designed to run on python3 yet have shebang lines with simply python. If a user computer has python3 as default this will cause many scripts (including parrot_utils.py) to not work. This PR makes all scripts default to python2.
I also added a simple script to try to identify which scripts might not be python3 compatible for when we will try to upgrade the scripts.
I also tried to update some print functions to python3 using the suggestions from 2to3.
Please advise if any of these files are known to actually be fully functional under both versions and I will revert those files before merging.

[python] added explicit pyhton2 binding where ambiguous

---

conf/airframes/ENAC/rover_ostrich.xml
conf/autopilot/rover_holonomic.xml
conf/modules/actuators_ostrich.xml
conf/modules/guidance_rover_holonomic.xml
sw/airborne/autopilot.c
sw/airborne/autopilot.h
sw/airborne/firmwares/fixedwing/autopilot_firmware.c
sw/airborne/firmwares/fixedwing/autopilot_static.c
sw/airborne/firmwares/fixedwing/autopilot_utils.h
sw/airborne/firmwares/rotorcraft/autopilot_firmware.c
sw/airborne/firmwares/rotorcraft/autopilot_static.c
sw/airborne/firmwares/rover/autopilot_firmware.c
sw/airborne/firmwares/rover/guidance/rover_guidance_holonomic.c
sw/airborne/firmwares/rover/guidance/rover_guidance_holonomic.h
sw/airborne/math/pprz_geodetic.h
sw/airborne/modules/actuators/actuators_ostrich.c
sw/airborne/modules/actuators/actuators_ostrich.h
sw/airborne/subsystems/actuators/actuators_ostrich.h

Add basic support for holonomic rovers.
In addition, a `throttle` field have been added to the general autopilot structure that is used to report the global throttle level to the GCS strip. This way, the relevant message in each firmware doesn't need to know explicitly the name of the command (sometimes `COMMAND_THRUST` or `COMMAND_THROTTLE` or more complex in case of holonomic rover)

Rover holonomic

---

sw/airborne/arch/linux/mcu_periph/uart_arch.c
sw/airborne/arch/linux/serial_port.c

Whenever the UART does give an event you need to read all the bytes and not only a single byte. Next to that opening the uart without having a buffer removes delays.

[linux] Fix uart/serial waiting

---

sw/airborne/boards/px4fmu/chibios/v4.0/px4fmu.h

Correct the fault in the px4fmu_v4.0 default ADC and enable current sensing.

[boards] Fix PX4FMu ADC defaults

---

conf/modules/baro_bmp3.xml
sw/airborne/modules/sensors/baro_bmp3.c
sw/airborne/modules/sensors/baro_bmp3.h
sw/airborne/peripherals/bmp3_i2c.c
sw/airborne/peripherals/bmp3_i2c.h
sw/airborne/peripherals/bmp3_regs.h
sw/airborne/subsystems/abi_sender_ids.h

- peripheral and test module
- only I2C interface for now
- configured with recommended settings for drone applications
- tested with BMP388

[driver] add BMP3 (Bosh-Sensortech) baro driver

---

sw/airborne/modules/computer_vision/lib/vision/act_fast.c
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.h

ACT corner used to increment the number of agents looking for corners in case of little texture. It had a maximum of 1000 agents, while the fast 9 corner structure array was only 512 long. So, after long periods of little texture, the ACT corner file would write outside the memory, causing troubles with video capturing. Easy to find bug, which has now been removed.

Fixed ACT corner bug

---

conf/modules/filter_1euro_imu.xml
sw/airborne/filters/1e_filter.h
sw/airborne/modules/imu/filter_1euro_imu.c
sw/airborne/modules/imu/filter_1euro_imu.h
sw/airborne/subsystems/abi_sender_ids.h

One Euro filter is a very simple adaptive low pass filter that can efficiently remove the noise from the gyros and accelerometers without adding to much lag.
As it is a separated module connected to the ABI bus, it can be used with any IMU and AHRS/INS combination by selecting the correct data source for the estimation filters.
The plot below shows the recording of the roll gyro, with the blue line the original noisy signal while the red line is the filtered value. The noise level is much lower but their is almost no lag during fast rotations.
The FFT of the above signal shows the noise from the motors between 150 and 200 Hz that is almost completely removed.
This filter is very cheap in terms of computation and also very easy to tune with only two parameters.
See …

[filter] IMU prefiltering using the One Euro filter

---

sw/airborne/arch/chibios/mcu_periph/i2c_arch.c
sw/airborne/arch/chibios/mcu_periph/spi_arch.c
sw/airborne/arch/chibios/mcu_periph/uart_arch.c

Minimum recommended size is 256. Default is bigger to have some margins but can be set smaller or bigger if needed.

[periph] configurable stack size for UART, I2C and SPI

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c

When calling the set_z or set_vz functions in guided mode, the reference
should not be called as it would make them ineffective when the control
rate is high
close #2410

[rotorcraft] don't reset vertical ref in guided mode

---

sw/lib/python/pprz_connect.py

This is providing the init sequence as done by the GCS to get and maintain the list of aircraft known by the server and their configurations.
This is a small tool I made for student projects, but I think it might be useful for others as well.

[python] add small tool to get A/C conf from server

---

sw/ground_segment/python/natnet3.x/natnet2ivy.py

previously, only the last computed speed was returned in the end, regardless of the filter option (number of points to use), thanks to two errors in a row that kind of cancel themselves.
this is also a nice example of why Python can really sucks, it has obviously nothing to do with the initial author of this code... :/

[python] fix natnet3 speed filter

---

conf/modules/light_scheduler.xml
sw/airborne/arch/chibios/modules/light/light_ws2812_arch.c
sw/airborne/arch/chibios/modules/light/light_ws2812_arch.h
sw/airborne/boards/apogee/chibios/v1.0/board.h
sw/airborne/boards/apogee/chibios/v1.0/mcuconf.h
sw/airborne/modules/light/light_scheduler.c
sw/airborne/modules/light/light_scheduler.h

WS2812 are RGB LEDs that can be controlled in series with a single wire. A demo module makes a group of LEDs continuously changing color.
Using the ChibiOS DMA driver.

[module] WS2812 led module

---

conf/modules/ahrs_float_dcm.xml
sw/airborne/subsystems/ahrs/ahrs_float_dcm.c

the same filter is already applied in the int_quat ahrs and can prevent
incorrect measurement rejection when strong structural vibrations
increase the IMU noise

[ahrs] add filter on accel heuristic of DCM AHRS

---

conf/flight_plans/rotorcraft_basic.xml
sw/lib/ocaml/expr_lexer.mll

You can write `foo @DEREF bar` in place of `foo->bar`.
Maybe too verbose ? Would `@DR` be better ?

[ocaml] add pointeur dereferencing keyword to avoid conflict with XML invalid characters. Follow #2434.

---

conf/modules/airspeed_sdp3x.xml
sw/airborne/modules/sensors/airspeed_sdp3x.c
sw/airborne/modules/sensors/airspeed_sdp3x.h
sw/airborne/subsystems/abi_sender_ids.h

SDP3X airspeed sensors seem to be very fast to respond and this makes it difficult to use for maintaining constant airspeed for example... So a bit of optional filtering helps.

Filtering option added to SDP3X airspeed sensor

---

sw/ground_segment/cockpit/Makefile

ChibiOS seems to have force pushed to their repo at some point, so I had to find the equivalent new hash:
* Old hash: [3a6e100efce969b984958f78c13f1c770e5fb730](https://github.com/ChibiOS/ChibiOS/commits/3a6e100efce969b984958f78c13f1c770e5fb730)
* New hash [866b8f765c3d18bc11f1d9224b4ab979e25d63c4](https://github.com/ChibiOS/ChibiOS/commits/866b8f765c3d18bc11f1d9224b4ab979e25d63c4)
I also cherry picked the commit addressing the lablgtk version issue.

Update v5.10 to work on current Ubuntu

---

sw/airborne/arch/stm32/usb_ser_hw.c

Fixes USB serial port not working on the Eachine Trashcan CrazybeeF4FR board. The GPIOA peripheral clock enable from the [STM32F4 example](https://github.com/libopencm3/libopencm3-examples/blob/f9713ff86508a522a2c02bde947b57a871bc34bc/examples/stm32/f4/stm32f4-discovery/usb_cdcacm/cdcacm.c#L231) was missing.

FIX usb_transparent STM32F4 GPIOA clock not enabled

---

sw/airborne/firmwares/fixedwing/autopilot_generated.c
sw/airborne/firmwares/fixedwing/autopilot_static.c
sw/airborne/modules/nav/nav_bungee_takeoff.c

Two issues:
- launch variable was not set to true which prevents the control to set throttle command
- the autopilot_set_kill_throttle had not effects on fixedwing (in fact always setting to true). We probably missed this because this function is mostly called to kill but not to resurrect motor...
Second point is a major bug I think...

[fix] bungee_takeoff was not turning motor on

---

conf/airframes/ENAC/conf_enac.xml
conf/airframes/ENAC/fixed-wing/tawaki.xml
sw/airborne/arch/chibios/mcu_arch.c
sw/airborne/arch/chibios/mcu_arch.h
sw/airborne/boards/apogee/chibios/v1.0/board.c
sw/airborne/boards/chimera/chibios/v1.0/board.c
sw/airborne/boards/tawaki/chibios/v1.0/board.c
sw/airborne/boards/tawaki/chibios/v1.0/mcuconf.h
sw/airborne/modules/loggers/sdlog_chibios.c
sw/airborne/modules/loggers/sdlog_chibios/sdLog.h
sw/airborne/modules/loggers/sdlog_chibios/usbStorage.c

This features are needed for some board to close properly the log files.
This is now board specific, Tawaki, Apogee and Chimera are the only one
concerned so far.
- increase ADC predivider to relax DMA throughtput pressure on memory
- don't flush individually every open file, but close filsesystem to speed filesystem closing when power drop is detected
- relaxing all unnecessary PINs to input floating to save energy is stil

[chibios] make log file closing faster and safer

---

conf/modules/cv_target_localization.xml
conf/modules/jevois.xml
sw/airborne/modules/computer_vision/cv_target_localization.c
sw/airborne/modules/computer_vision/cv_target_localization.h
sw/airborne/modules/sensors/cameras/jevois.c
sw/airborne/modules/sensors/cameras/jevois.h

The Jevois driver has the option to send some state information such as altitude, position and orientation.
The extraction of ID number is skipping the potential letters at the beginning of the ID string, as well as trailing characters if any.
This is allows to use the default Aruco demo for instance since the ID reported begins with 'U'.

[jevois] move some functionnality to jevois cam driver

---

sw/airborne/firmwares/rotorcraft/stabilization/wls/wls_alloc.c
sw/airborne/test/test_alloc.c

I wrote a test for the WLS control allocation and found a mistake with the initialization of one of the arrays. The fix gives the correct result in the test, but is not flight tested.
Something else, but related:
I also realized that the use of Variable Length Arrays (VLA) leads to a lot more assembly code than fixed size arrays, and in this case it is not really needed if you call the algorithm with arguments of the same size. (Usage example: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/firmwares/rotorcraft/stabilization/wls/wls_alloc.c#L109)
I think that only if you would have two constrained least squares problems of different size to solve it could make sense to do it like this. Should we restrict it to 'single use' in order to make it faster?

Wls update

---

conf/modules/gvf_module.xml

Quick fix. I missed catching this mistake in the corresponding PR days ago.
Now the gvf_module compiles again in master.

Fix for the gvf module

---

sw/airborne/arch/sim/sim_ap.c
sw/airborne/modules/datalink/bluegiga_dl.c
sw/airborne/modules/datalink/extra_pprz_dl.c
sw/airborne/modules/datalink/gec_dl.c
sw/airborne/modules/datalink/pprz_dl.c
sw/airborne/modules/datalink/xbee_dl.c
sw/airborne/subsystems/datalink/datalink.h
sw/airborne/subsystems/datalink/superbitrf.c
sw/airborne/subsystems/datalink/w5100.h

When using the `extra_dl` port for communication with an on-board computer board, the `datalink_time` variable which is used for datalink lost detection is set to zero for all new messages. This is including the onboard messages that are never lost.
This fix disable by default the `datalink_time` update for `extra_dl` and make it configurable for all over possible datalink transports.

[fix] datalink_time is currently set to zero even for non-telemetry link

---

conf/modules/gvf_module.xml
conf/modules/nav_basic_fw.xml
sw/airborne/firmwares/fixedwing/nav.c
sw/airborne/firmwares/fixedwing/nav.h
sw/airborne/modules/guidance/gvf/nav/nav_survey_polygon_gvf.c
sw/airborne/modules/guidance/gvf/nav/nav_survey_polygon_gvf.h
sw/airborne/modules/nav/nav_survey_poly_osam.c
sw/airborne/modules/nav/nav_survey_poly_rotorcraft.c
sw/airborne/modules/nav/nav_survey_poly_rotorcraft.h
sw/airborne/subsystems/navigation/nav_survey_rectangle.c
sw/airborne/subsystems/navigation/nav_survey_rectangle.h

This is to prevent multiple declarations. It should also keep the variable sweep capabilities but with a different setting for each nav module.
this was introduced by #2488 and related PR.

[fix] split the sweep variable and let each module use its own

---

conf/modules/gain_scheduling.xml
sw/airborne/modules/ctrl/gain_scheduling.c

This should fix the compile warning for the new FFD. gain which was added in #2380. Similar problem was #2393 
Also added the ability to change the first gain set with settings, since it is overwritten with the periodic loop.

[ctrl] Fix gain scheduling warning with FFD gain

---

conf/modules/sonar_vl53l1x.xml
sw/airborne/modules/sonar/sonar_vl53l1x.c
sw/airborne/modules/sonar/sonar_vl53l1x.h
sw/airborne/peripherals/vl53l1_platform.c
sw/airborne/peripherals/vl53l1_platform.h
sw/airborne/peripherals/vl53l1_types.h
sw/airborne/peripherals/vl53l1x_api.c
sw/airborne/peripherals/vl53l1x_api.h
sw/airborne/peripherals/vl53l1x_nonblocking.c
sw/airborne/peripherals/vl53l1x_nonblocking.h
sw/airborne/subsystems/abi_sender_ids.h

This PR adds support for the VL53L1X laser ranger as found on the bitcraze flowdeck, and a module to use it as an AGL sensor.
Code has been tested using softi2c (#2514) on the eachine trashcan. Code compiles with the ardrone2 example airframe for ap and nps targets.

VL53L1X laser ranger driver and sonar module

---

conf/modules/fdm_jsbsim.xml
sw/simulator/nps/nps_fdm_jsbsim.cpp

The development of jsbsim is now switch to git with an new active team.
The stable release v1.0.0rc1 has several fix and improvements, but
requires some modification from us to properly handle the type of file
path passed as arguments to load models.
Also, the default path when pkg-config is not found was /opt, which was
used in very early versions of NPS. The default is now /usr so that it
is compatible with a standard install of the new lib version.
In addition the new version will be packaged for ubuntu 20.04 focal

[jsbsim] support of more recent jsbsim versions

---

conf/airframes/ENAC/quadrotor/crazyflie_2.1.xml
conf/modules/cf_deck_multi_ranger.xml
conf/modules/range_forcefield.xml
conf/modules/sonar_vl53l1x.xml
sw/airborne/modules/datalink/bitcraze/syslink_dl.c
sw/airborne/modules/range_finder/cf_deck_multi_ranger.c
sw/airborne/modules/range_finder/cf_deck_multi_ranger.h
sw/airborne/modules/sonar/sonar_vl53l1x.c
sw/airborne/modules/sonar/sonar_vl53l1x.h
sw/airborne/peripherals/bmi088.h
sw/airborne/peripherals/pca95x4.c
sw/airborne/peripherals/pca95x4.h
sw/airborne/peripherals/vl53l1_platform.h
sw/airborne/peripherals/vl53l1x_api.c
sw/airborne/peripherals/vl53l1x_api.h
sw/airborne/peripherals/vl53l1x_nonblocking.c
sw/airborne/peripherals/vl53l1x_nonblocking.h

This PR is integrating the multi-ranger deck from bitcraze https://www.bitcraze.io/products/multi-ranger-deck/
And also:
- factorizing the boot and read sequence of the vl53l1 range sensor
- use the event loop instead of only the periodic loop (shorten the time to read data from sensor)
- update the sonar module accordingly
- fix a bug in syslink datalink module
This code have been tested on a crazyflie 2.1, with the forcefield module to autonomously avoid hitting the walls.

Multi ranger deck integration

---

sw/airborne/modules/range_finder/cf_deck_multi_ranger.c
sw/airborne/subsystems/abi_sender_ids.h

sorry, I missed this one when cleaning the request

[fix] give a proper ID for multiranger ABI message

---

conf/airframes/tudelft/disco_modified.xml
conf/userconf/tudelft/conf.xml

New airframe for a modified Parrot disco drone, used for the flat spin landing experiment. The inner hardware of the drone uses different components (documented in the file), notably a Pixracer 1 with the gyro set to measure rotations of up to 2000 deg/s, needed for the experiment. 
I have not been the only one working on the file and while it has been flown by me, I might need some help/suggestions on how to clean up the file, to get it up to spec for master.

Modified disco airframe used in flat spin landing experiment

---

sw/tools/calibration/calibrate.py
sw/tools/calibration/calibration_utils.py

The calibration script was interpreting the noise_threshold input as a string when running the script with python3. I also got problems with the deprecated pyplot.hold, which could be omitted without problems.
I'm not sure what version of python we are aiming for? As far as I know python2 is no longer maintained so I suppose python3?

adapt calibration script to python updates

---

sw/airborne/firmwares/rotorcraft/navigation.c
sw/airborne/modules/nav/nav_smooth.c

- add fabs and explicit type conversion respectively to fix calculation errors
Fixes issue #2531

Navigation: fix calculations of ground speeds and navigation progress

---

sw/lib/python/paparazzi.py

Instead of 'import commands' use 'import subprocess' as this is compatible with Python3.

Subprocess Module instead of Commands Module

---

conf/modules/gvf_module.xml
sw/airborne/modules/guidance/gvf/gvf.c
sw/airborne/modules/guidance/gvf/nav/nav_survey_polygon_gvf.c
sw/airborne/modules/guidance/gvf/nav/nav_survey_polygon_gvf.h

Finally I had some time to test the "dynamic sweep" in poly survey with GVF. It turns out that the code from that PR does not even compile when you set to true the corresponding define. The code does not make much sense anyway, so it is better to delete it.
Once I have a chance, I will also check whether the dynamic sweep works correctly with the original poly survey.
The bright side is in the second commit. I have found a bug in the GVF for tracking lines defined with two points. It did not work correctly for the corner case of "perfect horizontal lines" (90 or 270 degrees). Testing the poly survey triggered the bug. Now the fix is even more elegant, and I tested it thoruhgfully in simulation.

Erase dynamic sweep gvf

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_float.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_int.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_float.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_float.h
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_int.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_quat_int.h

Upon some mode switches, the reference attitude is reset to the current attitude. A quaternion is made from the current attitude in euler angles, but for this a 'pitch-corrected' heading is used (a heading that points in the same direction if you pass 90 deg pitch. This is a problem, because if interpreted as a normal ZYX euler angle set the reference attitude is incorrectly set. The result is a 180 yaw movement when switching between FWD and ATT with pitch < -90 deg. The real unedited ZYX euler angles should be used instead.
Actually, looking at it again, should the ref psi be reset at all? Ref phi and theta are also not reset...

fixed ref reset on mode switch heading issue

---

conf/Makefile.chibios
conf/modules/ins_ekf2.xml

I get errors if I try to compile cpp code (EKF2) with chibios. Using cpp 11 solves it.

Compile chibiOS with cpp 11

---

conf/modules/extra_dl.xml
conf/modules/mavlink.xml
sw/tools/generators/gen_aircraft.ml
sw/tools/generators/gen_modules.ml
sw/tools/generators/gen_periodic.ml

With the introduction of #2545, the modules and periodic telemetry prescalers was not set properly. The problem is that the correct value is only available after generating the makefile and calling "make" again (old process), but it is not possible anymore have the information from the start, and only the default freq was used (as reported in #2537).
So, instead of a static prescaling computed by the generators, the prescaler values are now computed at compile / run time.
In terms of frequency, it should be similar to the old code as long as there is no periodic functions trying to go faster than the base frequency. It was previously reported by the generator, it won't be the case anymore. A future improvement would be to have checks at compile time eventually.
The only change I'm …

Fix modules and telemetry freq

---

conf/modules/logger_control_effectiveness.xml
sw/airborne/modules/loggers/logger_control_effectiveness.c
sw/airborne/modules/loggers/logger_control_effectiveness.h
sw/tools/control_effectiveness/config/quadrotor.json
sw/tools/control_effectiveness/config/quadrotor_simple_indi.json
sw/tools/control_effectiveness/control_effectiveness_estimation.py
sw/tools/control_effectiveness/control_effectiveness_utils.py

This is an attempt to make a generic tool to log and process data used to estimate control effectiveness.
The module part can record all commands and imu data by default, plus a number of other sensor if required (position, speed, airspeed,...).
The ground tool is able to read the data and apply a series of filters before calling the optimization to find fitting parameters. A mixing matrix can also be applied to find cross talk like for full indi). Not all sensor models are implemented yet. The process is configured with a json file.
This is not really tested, only in the case of simple indi. And I'm not completely sure of the mixing part, so @EwoudSmeur , I would appreciate your opinion on this !
Hopefully some day we won't edit the code by hand for every aircraft to tune for indi ;)

[effectiveness] module and tool to log and process control effectiveness

---

sw/airborne/subsystems/gps/gps_ubx.c

Testflying to test the new uBlox M9N   FW 4.03 set to High rate ~12Hz with 4 constellations TOGETHER :) gave this issue. Investigate and culprit is (see ublox M9 datasheet) gspeed message is now in mm/s not in cm/s for the new PVT mesages, old are VEL are in cm/s.
Anyhow a small change fixed it 
Flight before fix:
Flight after fix:
BTW: In same run set the HMSL_BIT value immediately after when there is a HSML..

Fix for gspeed spiking issue #2566

---

sw/ground_segment/tmtc/server.ml
sw/lib/ocaml/env.mli
sw/logalizer/play_core.ml

[log] add the latest generated settings if available to log file
This way, the exact order of the settings used during the flight might
be available.
The only false case would be to start a server, rebuild and aircraft
with different parameters or target, then flash and start the plane. In
this case, there is no guarantee that the information is correct.
However, this is the best we can do, since we can't know when starting
the server with which target the aircraft will be used.
close #2563
Also fix the log replay

Fix settings in log

---

sw/airborne/math/pprz_algebra_float.c
sw/airborne/math/pprz_algebra_int.c

If the state quaternion is slightly off around +-90 degrees pitch, the result
might be a NaN if the asin is computed. I added bounds to make sure this
can never happen. The argument should not be outside [-1,1] anyway.

Protect quat to euler conversion for NaN

---

sw/ground_segment/joystick/input2ivy.ml
sw/ground_segment/joystick/ml_sdl_stick.c
sw/ground_segment/joystick/sdl_stick.c
sw/ground_segment/joystick/sdl_stick.h

Initial position of axis are unknown until an event occurs on this axis.
This PR adds the option "-c" on input2ivy to wait for an event to occurs on each axis before the program start its normal behavior (sending ivy messages).
This ensures that no false values are sent.

[Joystick] Add option to wait for an event on all axis to start.

---

conf/flight_plans/flight_plan.dtd
sw/tools/generators/gen_flight_plan.ml

Add `nav_type` and `nav_params` attributes to the basic flight pattern instructions of the flight plan to select alternate guidance and nav functions for them.
To use it, it is just needed to provide macros or functions with the form `MyNavXxxxx` for all nav instructions like `NavCircleWaypoint` or `NavGotoWaypoint`. Then call the FP instructions like this:
` <circle wp="WP1" radius="80" nav_type="MyNav"/>`
In this example, `MyNavCircleWaypoint` will be called instead of the default `NavCircleWaypoint`.

[nav] selectable navigation functions from flight plan

---

conf/Makefile.arm-embedded-toolchain
conf/Makefile.arm-linux-toolchain
conf/Makefile.chibios

In Ubuntu 18.04 or lower, ARM stuff come from the gcc-arm-embedded PPA, and GDB is invoked by `arm-none-eabi-gdb`.
In Ubuntu 20.04, ARM stuff come from official ubuntu packages with packages `gcc-arm-none-eabi` and `gdb-multiarch`. GDB is now invoked with `gdb-multiarch`.

[GDB] New gdb name for ARM.

---

.travis.yml

replaced deprecated --force-yes command

---

conf/userconf/tudelft/course2019_conf.xml
sw/airborne/modules/orange_avoider/orange_avoider.c

Import PR from https://github.com/tudelft/paparazzi/pull/64
@matteobarbera

MAVLab course update: typos, comments (tudelft pr#64)

---

sw/lib/ocaml/aircraft.ml

the appear with a ~ in the settings list which should be removed before testing for modules

[fix] parse correctly settings with names

---

sw/airborne/firmwares/fixedwing/nav.h

Added extern statement for oval_status in firmwares/fixedwing/nav.h so that this variable can be used in flight plans. If you try to compile with conf/flight_plans/cube.xml, you can see the undefined error for this variable.

Added extern statement for oval_status in firmwares/fixedwing/nav.h

---

conf/conf_tests.xml

seems to make Semaphore CI happy and ardrone2 is not produced anymore

[conf] replace ardrone2_opticflow with bebop2 version in test conf

---

sw/ground_segment/tmtc/server.ml
sw/lib/python/pprz_connect.py

During a replay session, when requested with CONFIG_REQ, the server is not consistent over the "ac_id" field.
I propose to fix it to what I think is the most logical.
When the replay starts, the server send the message `ground NEW_AIRCRAFT replay1`.
When requested by the `AIRCRAFTS_REQ` message, the server also reply with `replay1`.
In all later messages, the server use `replay1` as ac_id as well.
The only exception is that, when requested with the `CONFIG_REQ` message, the server replay with `1` as ac_id.
I think it should reply with `replay1`.
The only code I found to be affected by this change is in pprz_connect, which assume the id is an integer. Removing the cast to integer fix it, and makes a previously erroneous docstring true.
This could break external code, however, considering …

[Server] modify ac_id field of CONFIG message for replay sessions

---

conf/airframes/matek_f405_wing/Easyglider_matek_f405_autoload.xml
conf/airframes/matek_f405_wing/Easyglider_matek_f405_wing.xml
conf/flight_plans/lagonisi_beach_survey.xml

I edited the lagonisi_beach_survey.xml flight plan because it contained on call to flaps function which should be call_once
AND
the "Easyglider_matek_f405_wing.xml" airframe file because it contained one of my private modules named "fixed_wing_cam_v1"

FIXED two typos in two files

---

sw/Makefile.ocaml

For unknown reason, log plotter is crashing with ubuntu 20.04, but seems
to work when the ocaml tools are compiled with debug flag. This should
not slow down execution but produce bigger code.
A proper fix or replacement should still be found to this issue.
see #2621

[fix] log plotter not crashing with ubuntu 20.4 in debug mode

---

conf/modules/logger_sd_spi_direct.xml
sw/airborne/modules/loggers/sdlogger_spi_direct.c
sw/lib/python/settings_xml_parse.py
sw/logalizer/sdlogger_download.c

Fixes/updates for the SPI SD logger:
- Allow arbitrary devices for download. *I have only tested this with usb serial!*
- Update sdlogger_download to pprzlink v2. Hardcoded as before, so pprzlink v1 is no longer supported...
- Reduce download chunk size to 64 bytes max. I had missing packets (not sure if buffers on the drone or on my pc are overflowing), fixed by limiting the max number of bytes sent at once.
- ~~Remove warning from settings_xml_parse.py because it was interfering with the download program. Not sure if this is used anywhere else...~~
- Updated documentation.
The fixes are slightly hacky in places because I did not have a lot of time to work on this. Let me know if something needs to be fixed/cleaned-up.
Tested on stm32f4 (trashcan/crazybeef4fr) with the bitcraze usd-deck …

SPI SD Logger updates

---

sw/airborne/modules/e_identification_fr/e_identification_fr.c

This concerns the drone tracker required by french law.
The tracker ID is now stored on the tracker itself, instead of the autopilot, to comply better with the law.

[tracker] Identifier is now stored in the tracker, not the autopilot.

---

sw/airborne/firmwares/fixedwing/nav.c

this cause the `nav_home` to fail in vertical control

[nav] in_flight detection is not implemented in fixedwing firmware

---

conf/modules/logger_sd_spi_direct.xml
sw/airborne/modules/loggers/sdlogger_spi_direct.c

With this pull request, the spi_sd_logger can download log files over a different serial link than the default downlink device. To do so, the module will also listen to SETTING messages on this download port.

SPI SD Logger: download over other serial link

---

sw/ext/Makefile

Add explicit python*2* instead of python to mavlink build target in sw/ext/Makefile after bug report from @matteobarbera 
@matteobarbera : can you test this PR to see if it fixes the problem?

Add explicit python*2* to sw/ext/Makefile mavlink target

---

Makefile
sw/airborne/arch/chibios/mcu_periph/rng_arch.c
sw/airborne/modules/datalink/gec_dl.c
sw/airborne/modules/datalink/gec_dl.h

It compiles, but I'm not 100% sure of the modifications since it is not working, unless it is only a configuration error.

[gec] fix compilation of secure telemetry module gec_dl

---

sw/airborne/boards/tawaki/chibios/common/tawaki.h

UART6 default to TX:TRUE, RX:FALSE.

[Tawaki] Define pin for UART[68]_TX.

---

sw/airborne/arch/chibios/mcu_periph/uart_arch.c

UARTx_CRx can be defined to replace default values. This allows to use complex UART features without making the driver too complex.

[chibios] enable overriding UART registers.

---

conf/abi.xml
conf/modules/optical_flow_mateksys_3901_l0x.xml
sw/airborne/modules/optical_flow/mateksys_3901_l0x.c
sw/airborne/modules/optical_flow/mateksys_3901_l0x.h
sw/airborne/modules/optical_flow/px4flow.c
sw/airborne/modules/optical_flow/px4flow.h
sw/airborne/modules/optical_flow/px4flow_i2c.c
sw/airborne/subsystems/abi_sender_ids.h

follow up from https://github.com/paparazzi/paparazzi/pull/2639
Submodule of ppzlink updated to latest version

[computer vision] Driver addition for mateksys_PMW3901_l0x

---

sw/supervision/python/parser.py

method time.clock() is deprecated in python 3.8.
It was not needed, so removing it.

[python supervision] Remove deprecated function.

---

sw/ground_segment/tmtc/server.ml

I wanted to be able to name the output files of the server, so I added a cmd line argument to server.ml for this purpose. The timestamp previously used is still used if no name is provided. If a name is provided, the timestamp will be added to the string...
For example, the command...
./server -log_name ardrone2
... Will produce the files...
ardrone2__DATE__TIME.data and ardrone2__DATE__TIME.log
I am not very experienced with ocaml, so please feel free to suggest another way to do this.
Best,
Jack

Added log name argument to server.ml

---

sw/airborne/firmwares/rotorcraft/autopilot_arming_yaw.h

Sometimes, a drone can be accidentally killed in flight. Re-arming often takes
too long and the drone it crashes. This would be avoided if after kill, the
drone can rapidly re-arm by unkilling.
Maybe someone should shed his/her light on the robustness of this implementation. Personally, I don't like that autopilot_arming_set() could be called from anywhere to mess up the state machine due to different causes. Can this function be removed entirely?

Allow rapid re-arming after kill

---

Makefile
conf/Makefile.arm-embedded-toolchain
conf/Makefile.lpc21

when compiling ground_segment target, it should not depend on misc tools
that are themselves compiling the ext libraries, including libopencm3.
this way, the command 'make ground_segment' should be enough to run a
simulation without installing a cross compiler

[build] split subdirs rules

---

conf/flight_plans/flight_plan.dtd
sw/tools/generators/gen_flight_plan.ml

This adds an optional attribute wp_frame to the root node flight_plan, that default to "utm".
If this attribute is set to "LTP", waypoints frame is then the LTP frame (ENU).

[Flight plan] Add support for LTP waypoints.

---

conf/airframes/examples/MentorEnergy.xml
conf/airframes/examples/Twinstar_energyadaptive.xml
conf/airframes/examples/ardrone2.xml
conf/airframes/examples/bebop2_ukf_magnetometer_calibration.xml
conf/airframes/examples/bixler_lisa_m_2.xml
conf/airframes/examples/bumblebee_quad.xml
conf/airframes/examples/krooz_sd_quad_mkk.xml
conf/airframes/examples/ladybird_lisa_s.xml
conf/airframes/examples/ladybird_lisa_s_bluegiga.xml
conf/airframes/examples/lisa_l_chimu.xml
conf/airframes/examples/microjet_imu_xsens.xml
conf/airframes/examples/microjet_lisa_m.xml
conf/airframes/examples/microjet_lisa_m_xsens.xml
conf/airframes/examples/microjet_twog_aspirin.xml
conf/airframes/examples/quadrotor_elle0.xml
conf/airframes/examples/quadrotor_hbmini.xml
conf/airframes/examples/quadrotor_lisa_m_2_pwm_spektrum.xml
conf/airframes/examples/quadrotor_lisa_mx.xml
conf/airframes/examples/quadrotor_lisa_s.xml
conf/airframes/examples/quadrotor_navgo.xml
conf/airframes/examples/quadrotor_navstik.xml
conf/airframes/examples/quadshot_178_pylons.xml
conf/airframes/examples/quadshot_asp21_FutabaPPMonUart1.xml
conf/airframes/examples/quadshot_asp21_spektrum.xml
conf/airframes/examples/separate_fbw_ap.xml
conf/airframes/examples/twinjet.xml
conf/airframes/examples/twog_analogimu.xml
conf/airframes/examples/yapaChimuSpi.xml

`modules` is deprecated, so lets try to remove it from the examples.

[examples] migrate modules from deprecated "modules" node to "firmware".

---

sw/tools/generators/gen_makefile.ml

it does matter for LDFLAGS in particular
close #2673

[build] output flags in orginal order

---

conf/airframes/tudelft/bebop_course_orangeavoid.xml
conf/airframes/tudelft/bebop_mav_course_exercise.xml
conf/flight_plans/tudelft/course_orangeavoid_cyberzoo.xml
conf/flight_plans/tudelft/course_orangeavoid_cyberzoo_guided.xml
conf/joystick/ps4_gamepad.xml
conf/joystick/ps4_gamepad_yawontriggers.xml
conf/joystick/sm600.xml
conf/modules/mav_course_exercise.xml
doc/sphinx/source/tutorials/intermediate/create_joystick.rst
sw/airborne/modules/mav_course_exercise/mav_exercise.c
sw/airborne/modules/mav_course_exercise/mav_exercise.h

- Files for PDF exercise (https://github.com/tudelft/paparazzi/pull/67)
- Explicit call to python2 for systems that default to python3
- Description and comments fixes
- [flight_plan] remove warning about dummy WP
- Added configs for ps4 gamepads, fixed typos (https://github.com/tudelft/paparazzi/pull/68)
- Update: for flight testing in the CyberZoo
- Fix color gain in mav_course_exercise.xml airframe (https://github.com/tudelft/paparazzi/pull/72)
- [flight_plan] Re-measured the autoland border. It is not safe to exit the red square so it auto-lands to prevent damage. (https://github.com/tudelft/paparazzi/pull/73)
- [Camera] Vision runs faster is unnecessary frames are not grabbed. (https://github.com/tudelft/paparazzi/pull/74)

Update from the TUDelft Course 2021

---

conf/tools/http_server.xml

SimpleHTTPServer changed to http.server in python3.

[server] Update for python3.

---

conf/flight_plans/ENAC/crazyflie_multi_ranger_test.xml
conf/flight_plans/ENAC/fish_outdoor.xml
conf/flight_plans/ENAC/fish_voliere.xml
conf/flight_plans/OPENUAS/openuas_versatile_unified.xml
conf/flight_plans/competitions/IMAV2018_carto.xml
conf/flight_plans/competitions/IMAV2019_carto.xml
conf/flight_plans/competitions/IMAV2019_drop.xml
conf/flight_plans/dynamic_sectors.xml
conf/flight_plans/flight_plan.dtd
conf/flight_plans/rotorcraft_joystick_enac.xml
conf/flight_plans/rover_optitrack_PIR.xml
conf/flight_plans/tudelft/delft_bebop.xml
sw/lib/ocaml/mapFP.ml
sw/tools/generators/gen_flight_plan.ml

As suggested in #2677, I propose here to remove static sectors. All sector will be dynamic ones.

Remove static sectors

---

conf/airframes/tudelft/neddrone4.xml
conf/airframes/tudelft/neddrone5.xml
sw/airborne/firmwares/rotorcraft/main_ap.c

This adds an option to disable GPS loss whenever there is a valid datalink connection.

[rotorcraft] Add GPS loss bypass with datalink timeout

---

sw/tools/generators/gen_flight_plan.ml

by computing the ref0 earlier is it also required to get the ground alt earlier, otherwise the generated alt in enu frame is wrong
This was introduced by #2676 and should be back-ported to v5.18 as well

[generator] move the extraction of ground alt before ref0

---

sw/tools/generators/gen_radio.ml

Fix divide by zero when neutral is set to max value. @gautierhattenberger can you double-check this to be sure ?
Throw error on incorrect use of min/max when the reverse attribute is used.
Issue warning to ask to switch to new way of reversing a channel.
this throw an error and stop compilation:
`<channel function="THROTTLE" min="1932" neutral="1932" max="1107" average="0" reverse="1"/>`
this issue a warning:
`<channel function="THROTTLE" min="1932" neutral="1932" max="1107" average="0"/>`

[Generator] Throw error or warning for radio conf.

---

sw/lib/ocaml/radio.ml
sw/tools/generators/gen_radio.ml

the reverse flag is directly applied by the parser, so correct values are use for all macros

[fix] take the reverse into account in macro as well

---

conf/airframes/tudelft/neddrone4.xml
conf/airframes/tudelft/neddrone5.xml
conf/modules/guidance_indi_hybrid.xml
conf/userconf/tudelft/conf.xml
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.h

This should fix the problem with the missing define. However, I cannot build the tudelft/cyfoam airframe file now, because of some issue with the setting "take_heading_control" that I don't understand:
/tmp/ccnS2wuO.ltrans5.ltrans.o: In function `send_dl_value.lto_priv.621':
/home/ewoud/paparazzi/sw/airborne/autopilot.c:73: undefined reference to `take_heading_control'
/tmp/ccnS2wuO.ltrans13.ltrans.o: In function `guidance_indi_run.constprop.317':
/home/ewoud/paparazzi/sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c:418: undefined reference to `take_heading_control'
/tmp/ccnS2wuO.ltrans20.ltrans.o: In function `dl_parse_msg.constprop.127':
/home/ewoud/paparazzi/sw/airborne/subsystems/datalink/datalink.c:95: undefined reference to `take_heading_control' …

remove lift eff scaling

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c

Fixes two syntax definition errors in indi_guidance_hybrid code

[guidance_indi_hybryd] Fixed wrong syntax in define definitions

---

conf/Makefile.arm-linux-toolchain

This was blocking for some reason with the Parrot toolchain

[fix] add which command to test if GDB exists for arm linux

---

conf/airframes/ENAC/quadrotor/kakute_f7.xml
conf/boards/holybro_kakute_f7.makefile
conf/flash_modes.xml
sw/airborne/boards/holybro/kakute_f7/board.c
sw/airborne/boards/holybro/kakute_f7/board.h
sw/airborne/boards/holybro/kakute_f7/board.mk
sw/airborne/boards/holybro/kakute_f7/holybro_kakute_f7.cfg
sw/airborne/boards/holybro/kakute_f7/holybro_kakute_f7.h
sw/airborne/boards/holybro/kakute_f7/mcuconf.h

minimal support for the Holybro Kakute F7 v1.5 board
tested on desk: IMU, PWM output, telemetry
based on ChibiOS
SDCard not configured since using SPI and not SDIO interface

[board] support Holybro Kakute F7

---

sw/airborne/subsystems/ahrs/ahrs_float_cmpl.c

The bias gain is a factor 1000 smaller than the update gain, it would be better to not have it hardcoded to a value but linked in the script

Linked update and bias gain

---

conf/telemetry/highspeed_rotorcraft.xml
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c

The guidance_indi_enter function was not really implemented well. This commit resets the filters and sets the thrust level to the last value of stabilization_cmd[COMMAND_THRUST].

Enter guidance indi hybrid

---

sw/ground_segment/tmtc/server.ml
sw/logalizer/play_core.ml

In a replay session, settings file is not generated.
This PR generates it.
The settings updates well in the GCS.
Obviously, changing a setting won't affect it...
It seems I have reverted some 10 years old changes. Is it still relevant or not ?
https://github.com/paparazzi/paparazzi/commit/f0dcd7eceb52bb0defe5746799e9bdbd62fb9475

Replay settings

---

sw/airborne/arch/chibios/mcu_periph/adc_arch.c

- with ChibiOS 20.3 the half buffer starting position is computed by
hand and was wrong in this case: it should be the product of the half
buffer size by the number of channels
- some other minor fixes:
- using && instead of & in boolean comparison
- use an intermediate const variable for the number of channels to
suppress a warning (comparison always true due to limited data range)
when the number of channels is zero (no ADC in use)

[fix] correct ADC buffer offset for ChibiOS

---

conf/simulator/nps/nps_sensors_params_default.h

We were using the default for the Nederdrone, but apparently saturating the mag sensor in simulation causing heading issues. I think it is not really helpful to have this saturation limit here (one would need to make a new nps_sensors h file for every sensor setup) while most of the time we're not interested in simulating this limit anyway. Would it make sense to just set it to a large value in the default?

FIX simulation mag saturation

---

sw/logalizer/play_core.ml

Use "generated_settings" node instead of "settings" for replay settings.
Generate an empty node if not found.
According to #2569, "settings" node is "wrong", so its better if its not generated for replay.
Can you try it @OpenUAS to be sure it still works for you?

[replay] Use generated settings.

---

conf/airframes/OPENUAS/openuas_wltech_xk_a160.xml
conf/modules/imu_mpu6000.xml
conf/radios/OPENUAS/openuas_rxsr_cppm_8ch.xml
conf/userconf/OPENUAS/openuas_all_ac.xml
sw/airborne/subsystems/imu/imu_mpu6000.c

On certain Flight-controller, either bad batch of MPU6000, overheat, Non clean power and whatnot max value spikes can occur. This completely messes up the IMU attitude state. those boards are unique, to expensive or not feasible to replace chip.To still be able to fly these flight-controllers an 3value median filter is added to the RAW output. Default MPU module behaviour is still the same but by adding` <define name="IMU_MPU_USE_MEDIAN_FILTER" value="TRUE"/>` to the mpu6000 module in airframe the issue is resolved with this fix, see screenshot of before and after... BTW mind the Scale, no it is not more noise... ;-)
An airframe was added to PR be able to validate and testfly the fix.

Fix MPU6000 spikes in certain chipbatches

---

sw/lib/python/settings.py

Convert ac_id to str to avoid failed comparison between int and str.

[libs] Fix python settings lib.

---

docker/dev/entrypoint.sh

daba128 changed the Dockerfile to install gosu from the official Ubuntu repositories but did not change the path in entrypoint.sh
gosu ist now located at /usr/sbin/gosu and no longer at /usr/local/bin/gosu

[docker] Fix path to gosu in entrypoint.sh

---

sw/ground_segment/cockpit/live.ml
sw/ground_segment/cockpit/live.mli
sw/ground_segment/cockpit/pages.ml
sw/ground_segment/tmtc/aircraft_server.ml
sw/ground_segment/tmtc/aircraft_server.mli
sw/ground_segment/tmtc/server.ml

Improve TELEMETRY_STATUS when multiple (redundant) links are used.
Previously, there was no way to tell if one of the links was down.
Now, it should behave as expected:
- if one of the link is down, it goes red in the Link tab. It goes orange in the strip (with correct number of links up).
- if link combiner is down, all links are shown as down (link may still be up, but no message are received), and the indicator in the strip goes red.
- if all links are lost, they all goes red, and the indicator in the strip goes red.

Better link status

---

sw/ground_segment/python/redundant_link/link_combiner.py

There was a typo in this function name.

[LinkCombiner] rename function.

---

conf/modules/mag_rm3100.xml

Added `<dep>` node for i2c dependency for the RM3100 magnetometer (issue #2781)

RM3100 i2c dependency

---

sw/airborne/subsystems/ahrs/ahrs_float_dcm.c
sw/airborne/subsystems/ahrs/ahrs_float_dcm.h

We are preparing a rover firmware, and we have found it convenient to set this number to a lower value when we use the AHRS_float_dcm.
We leave as default the original hardcoded one.

Setteable MIN_COUSE_SPEED in ahrs_float_dcm

---

conf/modules/ahrs_common.xml
conf/modules/firmwares/rotorcraft.xml
conf/modules/guidance_rotorcraft.xml
conf/modules/nav_basic_rotorcraft.xml
conf/modules/stabilization_rotorcraft.xml
conf/modules/targets/fbw.xml
sw/lib/ocaml/aircraft.ml

After the first one, all functionalities are checked, but corresponding
modules are not ordered with the other one.
This second sorting algorithm (simpler) is just checking that final
selection of modules is correctly ordered and check for possible cyclic
dependencies not yet found.
ahrs_common dep node is fixed to avoid such a situation.

[ocaml] apply a second topological sort to modules

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_module.h

I came across this comment, which I thought was incorrect, looking at autopilot_static.c

fix guidance module comment

---

conf/airframes/ENAC/quadrotor/niquad_wind.xml
conf/modules/wind_estimation_quadrotor.xml
conf/simulator/jsbsim/aircraft/simple_quad_wind.xml
conf/simulator/nps/nps_sensors_params_noisy.h
conf/telemetry/default_rotorcraft.xml
sw/airborne/filters/linear_kalman_filter.c
sw/airborne/filters/linear_kalman_filter.h
sw/airborne/math/pprz_algebra_float.h
sw/airborne/modules/air_data/air_data.c
sw/airborne/modules/air_data/air_data.h
sw/airborne/modules/core/abi_sender_ids.h
sw/airborne/modules/meteo/wind_estimation_quadrotor.c
sw/airborne/modules/meteo/wind_estimation_quadrotor.h
sw/simulator/nps/nps_fdm_jsbsim.cpp

- add a generic linear kalman filter lib
- add a quad model with linear drag and simplified for recent jsbsim
- add example frame and noisy NPS sensor config
see "Estimating wind using a quadrotor" in IMAV2021 proceedings

[module] wind estimation from quadrotor motion

---

sw/airborne/test/Makefile
sw/airborne/test/test_geo_conversions.c

We had some issues trying to accurately land with respect to a ground-based GPS, and figured there must be something wrong with some of the / a conversion(s) somewhere. I tried this first one and it seems off by a factor of roughly 2.5. Not sure if I'm doing something wrong here. I'm planning on making a few more tests in the coming days.

check geo conversions

---

sw/airborne/modules/ins/ins_float_invariant.c

The projection of the magnetometer was not correct. The invariant INS require to have the mag correctly projected in 3D and not only in the horizontal plane.
The PR #2779 is also doing the wrong projection when sending Abi MAG message. It would be better to merge the different ways to produce virtual MAG data from GPS course, or maybe create a dedicated message REMOTE_MAG to send the correct measurement from the ground independently from the REMOTE_GPS message.

[fix] correct pseudo_mag projection

---

sw/airborne/arch/chibios/mcu_periph/i2c_arch.c
sw/airborne/arch/chibios/mcu_periph/spi_arch.c
sw/airborne/test/chibios_test_led.c
sw/airborne/test/chibios_test_shell.c
sw/airborne/test/chibios_test_telemetry.c

hard coded values were too small, especially for i24, leading to stack overflow
also increase stack size for test programs

[fix] use macro stack size for i2c4 and spi4

---

sw/lib/ocaml/telemetry.ml

The phase attribute should now be a float, but some Ocaml code still expected int.

[Telemetry] Fix phase type.

---

sw/airborne/autopilot.c

The only impact was that new mode was not sent over telemetry on change for fixedwing firmware

[fix] correct return value of set_mode function

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c

When using INDI, the control allocation is done in the controller, and commands for each motor are directly calculated. However, that leaves it up to the user to put protections in the airframe command laws to not spin the motors before the motors are armed. 
This commit puts a protection already in the controller. This should work for most actuators, though I'm not sure about motors that can spin in either direction?

Motors on indi

---

conf/airframes/tudelft/bebop_opticflow_indoor.xml
sw/airborne/modules/computer_vision/lib/vision/image.c

@pcampolucci and I have been looking at the `cv_opticflow` module to try and improve the FPS performance. We identified a bottleneck in [`pyramid_next_level`](https://github.com/paparazzi/paparazzi/blob/742600628e684d070e4ecbe57de1dc1a66394908/sw/airborne/modules/computer_vision/lib/vision/image.c#L406), where we optimized the convolution by using a 3x3 kernel instead of 5x5, separated into two 1D kernels to improve performance. If both cameras are set to pyramid level 2 this leads to a small improvement in performance.
Currently, in master, we observed the FPS of the front camera frequently drop to ~2 FPS. This was somewhat resolved by limiting the target FPS of the `MT9F002` and `MT9V117`. The default value is the max available, which slows down the autopilot and should perhaps be …

Opticflow pyramid build FPS improvements

---

sw/simulator/nps/nps_ivy.c
sw/simulator/nps/nps_main_common.c

It prevents NPS to crash with Ivy messages, especially when simulating several drones.
Also checking the argc attribute and avoiding an unnecessary memcpy.

[fix] protect ivy operations with mutex in nps

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c

mu (learning rate) in INDI adaptive was not used in stabilization_indi.c. xml values are now used in lms estimation.

Fix indi adaptive mu

---

conf/boards/holybro_kakute_f7.makefile
conf/chibios/chibios_rules.mk

This fixes the semaphore build and makes disables `single-precision-constant` fully on chibios. This is consistent with bare stm32

[chibios] Make constants consistent with different architectures

---

sw/supervision/python/Makefile

targets `clean` are called recursively by paparazzi main Makefile.
Rename target to not accidentally remove supervision python ui files.

[supervision] Fix Makefile.

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c

In particular, don't run `wls_alloc` if not needed, it has a good chance to fail while on ground anyway.
The CPU usage is rising when this optimization is called for nothing, which can be avoided.

[indi] only calculate command if in flight

---

sw/airborne/arch/chibios/mcu_periph/hal_stm32_dma.c
sw/airborne/arch/chibios/modules/actuators/esc_dshot.c

IRQ priorities have been modified in latest ChibiOS (after merging #2859). It is now always adjusting to the max kernel
priority and checking in debug mode.
close #2891

[fix] change IRQ priority for DMA

---

conf/modules/mag_rm3100.xml

This is a pull request addressing issue #2788. The module frequency is turned into a variable to allow the user to change it as they see fit to make use of the high polling frequency the RM3100 mag sensor is capable of.
With this change, the variable `MODULE_RM3100_RATE` can be defined in the airframe to change the default module frequency of 60 Hz.
```xml
<module name="mag" type="rm3100">
<configure name="MODULE_RM3100_RATE" value="150"/>
</module>
```
I tested the PR by defining `MODULE_RM3100_RATE` and setting it to 60, 150, 300 to check that the frequency change works as intended.

[mag] Make RM3100 module frequency variable

---

sw/ground_segment/joystick/Makefile

Fix joystick for Ubuntu 22.04, but probably break it for MacOS users.
If someone know a better way to fix this...

Fix joystick for Ubuntu 22.04

---

conf/modules/gps_ublox.xml
sw/airborne/modules/gps/gps_ubx.c
sw/airborne/modules/gps/gps_ubx.h

With this feature, we can force our Ublox GPS to make a cold reset when the AP is turned on. Thus we can simulate a cold start.
By adding the _reset_ field to the _gps_ubx_ structure I have also fixed the _gps_ubx_Reset_ function defined in _gps_ubx.h_.

Ublox GPS - Manual hot, warm and cold reset functionality

---

sw/airborne/modules/ins/ins_ekf2.cpp

NAV_INIT is supported since #2829, I think it should be enabled by default like other INS. I have tested it with GPS outdoor and it was fine;

[ins] enable nav init for EKF2 by default

---

conf/airframes/ENAC/rover_ostrich.xml
conf/flight_plans/ENAC/demo_aruco_drop_indoor.xml
conf/flight_plans/flight_plan.dtd
conf/flight_plans/rotorcraft_guided_demo.xml
conf/modules/tag_tracking.xml
sw/airborne/firmwares/rotorcraft/autopilot_guided.c
sw/airborne/firmwares/rotorcraft/autopilot_guided.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_v.h
sw/airborne/firmwares/rotorcraft/navigation.h
sw/airborne/modules/computer_vision/tag_tracking.c
sw/airborne/modules/computer_vision/tag_tracking.h
sw/airborne/modules/orange_avoider/orange_avoider_guided.c
sw/airborne/modules/wedgebug/wedgebug.c
sw/include/std.h
sw/tools/generators/gen_flight_plan.ml

- add a guided mode instruction in flight plan
- a speed control to the tag tracking module
- change guidance API to a more generic name (not related to GUIDED mode)
- add a demo flight plan
replace #2913

Tag tracking speed integration

---

conf/simulator/nps/nps_sensors_params_common.h
conf/simulator/nps/nps_sensors_params_default.h
conf/simulator/nps/nps_sensors_params_noisy.h
sw/airborne/modules/imu/imu_nps.c

nps IMU was wrong when `IMU_ACCEL_._SIGN` was defined.
Also, a large part of `nps_sensors_params_default.h` and `nps_sensors_params_noisy.h` has been factorised in ``nps_sensors_params_common.h`.

[nps] Fix IMU and MAG signs.

---

sw/airborne/modules/gps/gps_ubx.c

the flag headVehValid only concerns the headVeh (vehicle heading, computed from dual antenna configuration), not the headMot, which is the heading of motion, aka the ground course, always "valid"

[gps] fix parsing of PVT heading

---

docker/dep/Dockerfile

gcc-arm-none has been accidentally removed in a previous PR.
python3-future is necessary for #2920.

[docker] Add gcc-arm back and add python3-future.

---

.gitmodules
Makefile
sw/ext/Makefile

Replace `python2` by `python` as python2 is deprecated, and it make paparazzi build fail on Ubuntu 22.04.
Also take this opportunity to update mavlink, and link to the original repository as the changes in the paparazzi fork are included upstream.
This PR needs testing, can someone using mavlink test it ?

fix and update mavlink

---

sw/airborne/boards/lisa_mx/chibios/v2.1/board.h

Since the lisa MX 2.1 is missing the `board.cfg` I added it manually for now. Maybe it would be nice to add this if someone still has it.

[boards] Fix LisaMX v2.1 chibios I2C definitions

---

sw/airborne/modules/gps/gps_datalink.c
sw/ground_segment/python/natnet3.x/natnet2ivy.py

In earlier versions of PPRZ, the natnet2ivy had conversions hardcoded that align the axis system with the Earth ENU at the TU Delft Cyberzoo. Newer versions remove this to remain general, but created a new axis system that is not very intuitive (x to the viewer) or very understandable from the code.
This PR provides 2 new axes systems, with the goal of minimizing setup effort in Optitrack Motive, while providing intuitive axes that are easy to write flight plans for and easy to understand on the GCS. They are described more in depth in natnet2ivy.py
Cyberzoo axes: y/North away from the viewer, x/East to the right, z/Up upwards
Geographic axes: y/North to the actual north, x/East to the actual East, z/Up upwards (an argument needs to be provided to specify the angle offset between the two …

More intuitive axes systems for indoor test areas with Optitrack positioning systems

---

paparazzi

I propose to make the python paparazzi center the default one.
The old one can still be use by launching `./paparazzi -legacy`.

[supervision] Make python supervision the default one.

---

conf/.gitignore
conf/pprz_center_settings.ini

`conf/pprz_center_settings.ini` should not be tracked.
This PR removes it, and adds it to a `.gitignore`.

Clean unwanted file.

---

sw/airborne/arch/stm32/mcu_periph/can_arch.c
sw/airborne/arch/stm32/mcu_periph/pwm_input_arch.c
sw/airborne/arch/stm32/modules/actuators/actuators_dualpwm_arch.c
sw/airborne/arch/stm32/modules/actuators/actuators_pwm_arch.c
sw/airborne/arch/stm32/modules/actuators/actuators_shared_arch.c

The can port seems to have been removed from the arguments of this function in this commit:
https://github.com/libopencm3/libopencm3/commit/9ef5860863982a0db46e794bab3d8cc21b9d58a3

[Libopencm3] Fix #2969.

---

doc/sphinx/source/conf.py

Fix sphinx sys path to make it build in readthedocs.

[doc] deduce parser path from conf.py absolute path.

---

conf/Makefile.nps

Are you OK to increase the required compiler standard for C++ simulations?
Solves https://github.com/paparazzi/paparazzi/issues/2988
Tested to still work in Ubuntu 18, 20 and 22.

[c++17] Increase the C++ standard to 2017

---

conf/modules/ins_ext_pose.xml
sw/airborne/modules/ins/ins_ext_pose.c
sw/airborne/modules/ins/ins_ext_pose.h
sw/airborne/modules/loggers/logger_file.c

Some projects (e.g. system identification) require precise attitude from external sources. This filter merges IMU with external attitude from the EXTERNAL_POSE message.

[INS_EXT_POSE] Kalman Filter based on external attitude measurements

---

conf/modules/telemetry_transparent.xml
conf/modules/telemetry_transparent_usb.xml
conf/modules/usb_serial_stm32_example1.xml
conf/system/udev/rules/50-paparazzi.rules
sw/airborne/arch/chibios/halconf.h
sw/airborne/arch/chibios/mcu_arch.h
sw/airborne/arch/chibios/usb_ser_hw.c
sw/airborne/boards/lia/chibios/v1.1/mcuconf.h
sw/airborne/boards/lisa_mx/chibios/v2.1/mcuconf.h
sw/airborne/boards/lisa_mxs/chibios/v1.0/mcuconf.h
sw/airborne/mcu.c
sw/airborne/mcu_periph/usb_serial.h
sw/airborne/modules/datalink/extra_pprz_dl.h
sw/airborne/modules/datalink/gec_dl.h
sw/airborne/modules/datalink/mavlink.h
sw/airborne/modules/datalink/pprz_dl.h
sw/airborne/modules/loggers/sdlog_chibios/usbStorage.c
sw/airborne/modules/loggers/sdlog_chibios/usb_msd.c

Add a second USB serial.
The use case is during development, to use one of the serial as a telemetry port, and the other as a debug port (e.g. a shell, or just some prints).
The interfaces are named `Paparazzi UAV telemetry Port` and `Paparazzi UAV debug Port` (although you can use them as you want), and the udev rules file symlink theses to `/dev/pprz_tlm` and `/dev/pprz_dbg`.

Usb add serial

---

sw/supervision/python/session_widget.py

Arguments like "-ac a b" was previously parsed as "-ac b".
To be included in v6.2

[supervision] Fix session save programs.

---

conf/modules/ins_nps.xml
conf/modules/system_core.xml
conf/modules/targets/ap.xml
conf/modules/targets/nps.xml
sw/lib/ocaml/aircraft.ml

the issue was that suggested modules can depend on modules that should be found from the suggested list
also enforce that an autopilot should have at least an ins or a ahrs

[fix] fix dep solver to recursively check suggested module

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.h

Horizontal and vertical can have setpoint of different types (pos, speed or accel) independently, which is wrong in many cases.
It has been introduced recently with nav and guidance reorg (#2964 ).

[fix] apply correctly horizontal and vertical setpoints

---

conf/Makefile.chibios
sw/airborne/mcu_periph/usb_serial.h
sw/airborne/modules/loggers/sdlog_chibios.c
sw/airborne/modules/loggers/sdlog_chibios/sdLog.c
sw/tools/px4/px_uploader.py
sw/tools/px4/set_target.py

Small fixes for chibios.
- No GDB symbols by default, which saves a lot of space
- By default wait for autopilot on PX4 uploader
- Fix SD logger mistakes, there is still a bug when the autopilot is powered with USB. It tries to close all the logs and hangs on https://github.com/paparazzi/paparazzi/blob/a02ec170cf9f489fbc31d527b0504a862f988d68/sw/airborne/modules/loggers/sdlog_chibios/sdLog.c#L334. I couldn't figure out why, maybe someone else can @gautierhattenberger ?
- Disable the USB debug endpoint when not in use

[chibios] Small fixes

---

conf/airframes/examples/cube_orange.xml
sw/airborne/modules/actuators/actuators_uavcan.c
sw/airborne/modules/actuators/actuators_uavcan1cmd.h
sw/airborne/modules/actuators/actuators_uavcan2cmd.h

Tested and working. Currently only UNITLESS commands are supported and the commands go from MIN_PPRZ to MAX_PPRZ.

[uavcan] Add support for the EQUIPMENT_ACTUATOR_ARRAYCOMMAND message

---

conf/modules/digital_cam.xml
conf/modules/digital_cam_i2c.xml
conf/modules/digital_cam_servo.xml
conf/modules/digital_cam_shoot_rc.xml
conf/modules/digital_cam_uart.xml
conf/modules/digital_cam_video.xml
conf/modules/nav_survey_hybrid.xml
sw/airborne/modules/nav/nav_survey_hybrid.c
sw/airborne/modules/nav/nav_survey_hybrid.h

Survey based on the OSAM algo for rotorcraft. Instead of going from one  sweep line to the next with a line, a circle aligns the aircraft with the next line.
Circles radius at the start of lines can be either automatic (sweep distance), fixed or direct line (equivalent to original rotorcraft).
The code itself is reorganized to use a global structure instead of many variables. Only tested in simulation for now. If working correctly, it can be used for hybrids, rotorcraft and even fixedwing using the rotorcraft firmware.

Survey hybrid

---

sw/airborne/state.c

It was making a mess with float/int format and even `pos_status`. Only visible with certain combinations of get/set speed/pos.
It is still a miracle that it "worked" for so long...

[state] fix speed convert functions

---

conf/userconf/tudelft/course_conf.xml
sw/tools/rtp_viewer/play_video_bottom_ffmpeg.sh
sw/tools/rtp_viewer/play_video_front_ffmpeg.sh
sw/tools/rtp_viewer/rtp_viewer.py

I could not see the video streams of the Bebop 2 with VLC player. Also the Python rtp viewer was not working.
The issue I had is also mentioned here for openCV: https://github.com/opencv/opencv/issues/10328
So:
- I added two shell scripts to view the streams with ffmpeg player.
- I changed the python script to solve the above problem.
For me the Python script still throws an error with the changes, since a file in var/lib/python/pprzlink does not direct to the right messages.xml file. To make it work, I add 'sw/ext/pprzlink' to the directory name there, but it is autogenerated and on paparazzi's ignore list. Don't know how to fix that, so suggestions are welcome there.

Changes to fix video streams not working in Ubuntu 22.04

---

sw/ground_segment/cockpit/gcs.ml
sw/ground_segment/cockpit/lib/mapCanvas.ml
sw/ground_segment/tmtc/150m.ml
sw/ground_segment/tmtc/server.ml
sw/lib/ocaml/env.ml
sw/lib/ocaml/env.mli
sw/lib/ocaml/srtm.ml
sw/simulator/sim.ml
sw/tools/generators/gen_flight_plan.ml

With this, ocaml ground tools don't have to include the default paths themselves and the srtm data coming from the new or the legacy GCS can be used by these tools (server, gen_flight_plan, ...).

[ocaml] add old and new GCS srtm path to default directory list

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/math/pprz_algebra_float.c
sw/airborne/math/pprz_algebra_float.h
sw/simulator/nps/nps_sensors_utils.c

Fixing some warnings on arm64 compilation.
The stringop-overflow comes from `stabilization_indi.c` at line 831 (```float_mat_inv_4d(g1g2inv[0], g1g2_trans_mult[0]);```). This converts a 2d array into a 1d array and leads to warnings not finding the correct memory sizes. I could not pragma push this warning so that is why I had to disable them fully. I'm not 100% happy about the solution but I don't know a better one, so if someone has suggestions?

[nps] Fix NPS compile warnings

---

conf/telemetry/default_rotorcraft.xml
sw/airborne/arch/chibios/modules/actuators/actuators_dshot_arch.c
sw/airborne/arch/chibios/modules/actuators/esc_dshot.c
sw/airborne/boards/tawaki/chibios/common/mcuconf.h
sw/airborne/boards/tawaki/chibios/common/tawaki.h
sw/airborne/modules/actuators/actuators_dshot.h
sw/airborne/modules/core/abi_sender_ids.h

- Each dshot driver supports it's own telemetry uart
- Pprz message ESC can be sent over telemetry or flight recorder
- Configuration is done by giving the uart number
Example for Tawaki on default dshot connector:
`<define name="DSHOT_TIM4_TELEMETRY_NUM" value="DSHOT_TLM_RX"/>`

[dshot] fix dshot telemetry and provide pprz message support

---

conf/modules/stabilization_indi.xml
sw/airborne/modules/imu/imu_mpu9250_i2c.c
sw/airborne/modules/imu/imu_mpu9250_spi.c

With the pixracer board at 500Hz periodic frequency, the IMU was set to 100Hz.
Also, setting the rate gain in INDI to zero leads to dividing by zero, because of the way the gains are scaled, so this should be prevented.

Imu sample rate

---

sw/airborne/arch/chibios/mcu_periph/adc_arch.c

This fixes the sample rate setting on H7 processors, which was previously not set correctly. This resulted in really bad readings on the ADC with a lot of crosstalk.
For all H7 users, please recalibrate your `VoltageOfAdc` and `CurrentOfAdc`!

[chibios] Fix ADC reading sample rate error on H7

---

sw/airborne/modules/digital_cam/dc.c

There was a pointer error for the ac_id field.
It's curious the compiler didn't catched it.

Fix payload command

---

sw/airborne/arch/chibios/mcu_periph/sys_time_arch.c
sw/airborne/arch/chibios/mcu_periph/sys_time_arch.h
sw/airborne/arch/linux/mcu_periph/sys_time_arch.c
sw/airborne/arch/linux/mcu_periph/sys_time_arch.h
sw/airborne/arch/sim/mcu_periph/sys_time_arch.h
sw/airborne/arch/stm32/mcu_periph/sys_time_arch.h
sw/airborne/modules/loggers/pprzlog_tp.c

During very long flights, the time in the log would overflow and start back at zero. This complicates the parsing of log files.
It was caused because the function supplying the time in usec was overflowing after 70 minutes. By adding a function which is scaled by a factor 1/100 this should be solved.

fix log time overflow

---

sw/tools/install.py

- `gcs` docs  not showing
- `gazebo` version different on 22.04
- `opencv-bebop` not compiling properly on ubuntu22.04 -> disable so people can see

[install] small install update

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_hybrid.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_pid.c

Upon entering while in forward flight, the reference angles need to be reset based on the ZXY rotation order for tailsitters.

Fix guidance hybrid indi enter

---

sw/airborne/modules/imu/imu_cube.c

500DPS is a bit low, changing it to 2000DPS by default

[imu] Change cube orange+ IMU2 range

---

conf/modules/fdm_pybullet.xml

Currently, the pybullet simulation module only works with a hardcoded version of python 3.8. This modification allows you to work with the version installed on your machine.

Solve problem with python version for pybullet

---

sw/tools/generators/gen_flight_plan.ml

When the altitude of the geofence is not changed, this is not a warning but Info. When the WPs are too low it remains a warning.

[warnings] solve warnings

---

conf/airframes/ENAC/cyfoam.xml
conf/airframes/ENAC/fixed-wing/zagi_mekf_wind.xml
conf/airframes/OPENUAS/openuas_df_mini_spirit.xml
conf/airframes/OPENUAS/openuas_eflite_t28.xml
conf/airframes/OPENUAS/openuas_multiplex_minimag.xml
conf/airframes/OPENUAS/openuas_multiplex_twinstar_nd.xml
conf/airframes/OPENUAS/openuas_own_flexo.xml
conf/airframes/OPENUAS/openuas_own_sumo_ii.xml
conf/airframes/OPENUAS/openuas_parrot_disco.xml
conf/airframes/tudelft/cyfoam.xml
conf/airframes/tudelft/disco_rotorcraft_indi.xml
conf/modules/air_data.xml
conf/modules/airspeed_ms45xx_i2c.xml
sw/airborne/boards/disco.h
sw/airborne/modules/sensors/airspeed_ms45xx_i2c.c
sw/airborne/modules/sensors/airspeed_ms45xx_i2c.h

do not use air density ```rho``` to calibrate airspeed sensor but force user to use ```pressure_scale```
- otherwise, air_data and state are different

[fix] Airspeed data different from airspeed state

---

sw/airborne/peripherals/invensense2.c
sw/airborne/peripherals/invensense2.h

This corrects for the internal PLL errors in the invensense V2 chips. 
For the Invensense V3 there is no such register anymore. For those and other chips it might be good to average out x amount of measurement timings and calculate a timebase correction factor. Based on measurements with a generated frequency the PLL can deviate easily more than 1%

[periph] Invensense2 add timebase correction for PLL

---

sw/airborne/firmwares/rotorcraft/autopilot_firmware.c
sw/airborne/firmwares/rotorcraft/autopilot_firmware.h

A quadplane that flies very stably in forward flight with hover motors off will set the ```inflight``` to false, effectively killing the drone.
New conditions are needed to detect the end of ```inflight``` for quadplanes.
Proposed: only let the flightplan kill in the flare block by setting ```motors_on``` to ```false```

Do not kill a quadplane inflight

---

sw/airborne/modules/gps/gps.c
sw/airborne/modules/gps/gps.h
sw/airborne/modules/gps/gps_ubx.c

We already have a timeout when messages are not received anymore. This adds a possible timeout when GPS fix is lost (but we still have messages). It can prevent to switch to failsafe at the first gps lost message.
Disabled by default to keep the same behavior than before, but tested during real flights.

[gps] add a timeout on gps fix lost

---

sw/airborne/firmwares/rotorcraft/autopilot_firmware.c
sw/airborne/firmwares/rotorcraft/autopilot_firmware.h
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/modules/sensors/airspeed_ms45xx_i2c.c

[stabilization_indi] 2nd order rate filters and disabling pseudoinverse

---

sw/airborne/modules/sensors/mag_ist8310.c
sw/airborne/modules/sensors/mag_lis3mdl.c

- fix typo in ist8310 driver
- add rotation option to lis3mdl driver (for old style calibration)

[mag] type and rotations

---

sw/airborne/firmwares/rotorcraft/stabilization.c
sw/airborne/firmwares/rotorcraft/stabilization.h
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c

Test flying fix:
- rates and attitude sp use the same memory
- so they could be used at the same time

[fix] rates and attitude sp use the same memory

---

sw/include/std.h

We have a lot of ```Bound``` in the code, but this macro doesn't handle NaN values. In fact in many cases NaN values are not considered, even though they can be disastrous if they stick in integrators. It might not technically make sense to assign the max or min to a NaN value, but at least the output of the Bound should be within the given range, and not NaN in my opinion.
With this subtle change NaN will become max in the Bound function.

Bound function also bounds nan

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/math/wls/wls_alloc.c
sw/airborne/math/wls/wls_alloc.h
sw/airborne/test/test_alloc.c

Upon testing more implementations, we found some conditions that can trigger NaN in the output of the WLS. This is solved with this PR.
(requires https://github.com/paparazzi/paparazzi/pull/3115 to be merged first)

WLS update NaN

---

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.h

quadplane stabilization (WLS-only)

---

conf/airframes/examples/bebop2_opticflow.xml
conf/modules/cv_opticflow.xml
sw/airborne/modules/computer_vision/lib/vision/act_fast.c
sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c
sw/airborne/modules/computer_vision/opticflow_module.c
sw/airborne/modules/sensors/baro_MS5534A.c

Optical-Flow: 
- configures not configuring (old bug)
- possible FAST9 segfault (old bug)
- several parameters not active anymore in OF (recent bug)

[fix] FAST9 camera id check

---

conf/airframes/tudelft/rot_wing_25kg.xml
conf/modules/imu_common.xml
sw/airborne/modules/imu/imu.c

This adds the ability to log multiple IMU's at the highest speeds possible (32kHz, 8kHz, 1kHz etc.). It will log the accelerometer and gyroscope at the sampling frequencies onto the flightlogger SD card. The timestamps are not 100% correct, but if you average out the timestamp over time you will get the correct frequencies in the log.

[imu] Add fast logging

---

sw/airborne/peripherals/invensense2.c

The table for the Invensense V2 accelerometer was shifter by one, since it has two options to set 265Hz.

[imu] Fix Invensense V2 accelerometer DLPF config

---

conf/modules/nav_hybrid.xml
sw/airborne/modules/nav/nav_rotorcraft_hybrid.c
sw/airborne/modules/nav/nav_rotorcraft_hybrid.h

@dewagter @EwoudSmeur @fvantienen This is a proposal to use different speeds for `goto` and `route` to prevent unnecessary transition to forward flight when just going to a waypoint. In most flight plan, the goto is used for small displacement, while using a route is more suitable for longer trajectories where forward flight is useful.
The `force_forward` is still possible.

[nav] use a low speed for goto with hybrid

---

conf/airframes/examples/cube_orange.xml
conf/airframes/tudelft/bebop2_indi_convergence.xml
conf/airframes/tudelft/cyfoam.xml
conf/airframes/tudelft/disco_rotorcraft_indi.xml
conf/airframes/tudelft/nederdrone4.xml
conf/airframes/tudelft/nederdrone6.xml
conf/airframes/tudelft/nederdrone7.xml
conf/airframes/tudelft/nederdrone8.xml
conf/airframes/tudelft/rot_wing_25kg.xml
conf/modules/guidance_indi_hybrid.xml
conf/modules/guidance_indi_hybrid_quadplane.xml
conf/modules/guidance_indi_hybrid_tailsitter.xml
conf/modules/nav_hybrid.xml
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_quadplane.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_quadplane.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_tailsitter.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_tailsitter.h

As discussed in #3122, it was desired to reduce the number of ```#ifdef``` blocks. Here I propose to split the unique code for ```tailsitter``` and ```quadplane``` in separate modules that automatically include and configure ```hybrid```

hybrid quadplanes and tailsitters explicit

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid_quadplane.c

Another attempt to solve #3081 (which in the meantime caused 3 incidents).
The default behavior is that the flight-plan logic puts the quadplane in holding point after the flight or the pilot kills the drone via the transmitter. Any other time, the in-flight should not automatically turn off.

Do not kill quadplanes in-flight.

---

sw/airborne/modules/ins/ins_ekf2.cpp

It fixes the display of IMU status in the GCS when the OPTITRACK mode of EKF2 is used.

[ins] fix ekf2 status flag when using external vision positionning

---

conf/airframes/tudelft/bebop_indi.xml
conf/airframes/tudelft/cyfoam.xml
conf/userconf/tudelft/conf.xml
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.h

It is much more understandable and convenient if the first order actuator dynamics in INDI are specified in continuous time, through the corner frequency of the first order model. Then it is also possible to change the periodic frequency without having to change the actuator filter parameters.
I tried some find-replace in all the airframe files, but it got complex because of the different periodic frequencies. I decided to just add an error if the old name is used.

INDI actuator dynamics in continuous time

---

sw/airborne/arch/chibios/modules/actuators/actuators_pwm_arch.c
sw/airborne/boards/apogee/chibios/v1.0/board.cfg
sw/airborne/boards/apogee/chibios/v1.0/board.h
sw/airborne/boards/chimera/chibios/v1.0/chimera.h
sw/airborne/boards/crazyflie/chibios/v2.1/crazyflie.h
sw/airborne/boards/cube/orange/board.cfg
sw/airborne/boards/cube/orange/board.h
sw/airborne/boards/holybro/kakute_f7/holybro_kakute_f7.h
sw/airborne/boards/lia/chibios/v1.1/board.h
sw/airborne/boards/lisa_mx/chibios/v2.1/board.h
sw/airborne/boards/lisa_mxs/chibios/v1.0/board.h
sw/airborne/boards/mateksys/F765-WING/matekF765-WING.h
sw/airborne/boards/mateksys/FC-H743-SLIM/board.cfg
sw/airborne/boards/mateksys/FC-H743-SLIM/board.h
sw/airborne/boards/nucleo/144_f767zi/nucleo144_f767zi.h
sw/airborne/boards/px4fmu/chibios/v2.4/board.h
sw/airborne/boards/px4fmu/chibios/v4.0/px4fmu.h
sw/airborne/boards/px4fmu/chibios/v5.0/board.cfg
sw/airborne/boards/px4fmu/chibios/v5.0/board.h
sw/airborne/boards/tawaki/chibios/common/tawaki.h

ChibiOS PWM driver is required for DShot driver, but activating it should not result in an activation of the PWM driver by paparazzi. Otherwise, the last driver to be called at init will set the parameters and eventually overwrite the correct values.
Not tested yet.

[pwm] use different names to activate PWM drivers in chibios and pprz

---

conf/modules/imu_heater.xml
sw/airborne/modules/checks/preflight_checks.c
sw/airborne/modules/imu/imu_heater.c
sw/airborne/modules/loggers/sdlog_chibios.c

This fixes an overflow issues when the total message of the preflight checks becomes larger than 256. Also adds a preflight check for the IMU heater

[checks] Add IMU heater preflight check and fix minor bugs

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c

- ```thrust_dyn``` only exists when not using ```GUIDANCE_INDI_SPECIFIC_FORCE_GAIN```
- ```act_dyn_discrete``` is set at the beginning from the new ```ACT_FREQ``` define, but should be computed during initialization from ```ACT_DYN``` if that old define is still present.

Fix continuous actuator

---

conf/airframes/tudelft/rot_wing_v3b.xml
conf/modules/mavlink.xml
sw/airborne/modules/datalink/mavlink.c

Not sure how to solve this: to control camera's MAVLink is used but the AP should then not identify as PPRZ

Control camera's over MAVLink

---

sw/airborne/modules/ctrl/eff_scheduling_rot_wing.c
sw/tools/generators/gen_airframe.ml

```actuators[ ]``` is a list of servos with indexes ```SERVO_NAME_IDX```.
The defines generated with the number shown in ```<servo no="xxx"/>``` are only intended for the specific actuator driver. They should thus never be referenced in any code. This PR hides those defines, (which exposes bugs, that will now not be possible anymore)

Hide actuator driver number from code

---

conf/airframes/tudelft/rot_wing_v3d.xml
sw/airborne/firmwares/rotorcraft/autopilot_firmware.c
sw/airborne/firmwares/rotorcraft/autopilot_utils.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_flip.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_none.c

Appears feasible to remove ```COMMAND_ROLL``` ```PITCH``` and ```YAW``` when not used.

Remove command_pitch and command_roll and command_yaw

---

conf/airframes/AGGIEAIR/aggieair_iris_indi.xml
conf/airframes/FLIXR/flixr_lisa_mx.xml
conf/conf_tests_coverity.xml
sw/airborne/modules/guidance/gvf_parametric/gvf_parametric_low_level_control.c
sw/lib/ocaml/ocaml_tools.ml

- fix all compile warnings
- I use ```gzip -f ``` because fast computers can end up having the same filename for conf zips when compiling small firmwares
- except #3226

Fix all compile warnings confs (on 20.04)

---

conf/flight_plans/flight_plan.dtd
sw/airborne/firmwares/fixedwing/nav.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/navigation.c
sw/airborne/firmwares/rotorcraft/navigation.h
sw/airborne/firmwares/rover/guidance/rover_guidance.c
sw/airborne/firmwares/rover/navigation.h
sw/airborne/modules/nav/nav_heli_spinup.c
sw/tools/generators/gen_flight_plan.ml

This mode is not really used and not even recommended. It is also not implemented in all firmwares. If a direct call to stabilization command is needed, it should be done with a specific function but not from a built-in instruction from the flight plan.
It was discussed in #3208, but not applied because of `nav_heli_spinup`. A new h_mode 'NONE' allows to disable guidance and stabilization while in NAV mode, which allows to set directly the commands.

[nav] remove nav_manual mode

---

sw/airborne/modules/gps/gps_datalink.c
sw/ground_segment/python/natnet3.x/natnet2ivy.py

@tmldeponti recently found that the pitch and roll components of the `natnet2ivy.py` are sometimes wrong. Further investigation showed that this happens due to a wrong rotation order that shows up when _not_ using options `--x_side right` and `--ac_nose far`, and when the craft is yawed away from pointing to the "north". Also, the yaw angle component seemed unaffected, which is why this bug hasn't shown up before (optitrack pitch/roll components are not typically used by estimators AFAIK?).
The diff looks huge, but actually the only functional change is post-multiplying `q_nose_correction` instead of pre-multiplying here:
https://github.com/paparazzi/paparazzi/blob/41998a12b3dd9de7dc061b532eece9addb1bef6b/sw/ground_segment/python/natnet3.x/natnet2ivy.py#L310-L312
To really make sure this …

Fix natnet2ivy rotation order

---

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c

There were jumps in omega (reference heading rate), because in one line the current roll angle is used, and in this other piece of code the commanded angles are used. This lead to jumps in the feed forward rate command.
With everything in current Euler angles this should be solved.

fix omega discontinuous

---

conf/modules/ins_ext_pose.xml
conf/telemetry/highspeed_rotorcraft.xml
sw/airborne/modules/ins/ins_ekf2.cpp
sw/airborne/modules/ins/ins_ext_pose.c
sw/airborne/modules/ins/ins_ext_pose.h

I have recently pull requested a new message to log the input from external vision systems so that it can be used to verify the output of INS filters (see https://github.com/paparazzi/pprzlink/pull/185#issue-2107403504).  As suggested by @fvantienen this can be useful for debugging the behaviour of these filters. 
Indeed this message helped finding the bug mentioned by @tblaha  (see https://github.com/paparazzi/paparazzi/pull/3231#issue-2101969742).
In this pull request I have added code to stream the new EXT_POSE_2 message to both the EXT_POSE as well as EKF2 INSs. The quaternions in this message will be streamed correctly once the pull request from @tblaha is accepted. 
Moreover, I have been working with the INS EXT_POSE from @robinferede and @dewagter and I have made some changes which …

Slight Changes to INS EXT POSE and INS EKF2

---

conf/airframes/tudelft/rot_wing_v3b.xml
conf/airframes/tudelft/rot_wing_v3d.xml
conf/airframes/tudelft/rot_wing_v3e.xml
conf/airframes/tudelft/rot_wing_v3f.xml
conf/airframes/tudelft/rot_wing_v3g.xml
conf/airframes/tudelft/rot_wing_v3h.xml
conf/flight_plans/tudelft/rotating_wing_EHVB.xml
conf/modules/stabilization_indi.xml
conf/simulator/jsbsim/aircraft/rotwing3.xml
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.h
sw/airborne/modules/ctrl/eff_scheduling_rot_wing.c
sw/airborne/modules/ctrl/eff_scheduling_rot_wing.h

I restructured the INDI controller, keeping the workings exactly the same. The benefit of the new structure is that we replace the increments by a disturbance estimate, such that in the control allocation we allocate the complete control objective (specific angular accelerations and thrust), not increments. This allows us to limit the specific angular accelerations (read: moments) that we allow the drone to allocate.
As an example, the rotating wing drone has a tail, which will automatically reduce the sideslip. We don't want the drone to stick to a specific heading, and in doing that 'fight' with the tail. With this update, we can limit the estimated disturbance such that we only control yaw to a limited extent.
What is also included is a feed forward on the yaw rate from RC if the yaw …

Restructure INDI to limit estimated disturbances

---

conf/airframes/airframe.dtd
conf/modules/oneloop_andi.xml
sw/airborne/firmwares/rotorcraft/oneloop/oneloop_andi.c
sw/airborne/firmwares/rotorcraft/oneloop/oneloop_andi.h
sw/simulator/nps/nps_autopilot.h
sw/simulator/nps/nps_fdm_jsbsim.cpp
sw/tools/generators/gen_airframe.ml

This Pull request is the first of a series of pull requests to make sure that modules such as Rotwing State and Rotwing Effectveess scheduling can be used by both the onleoop controller as well as a more conventional INDI cascaded controller. 
This specific pull requests aims to solve:
1. Have shared modules which do not use actuator_pprz hardcoded references ( e.g. actuator_pprz[6] ) . This can be problematic as different actuator orders will not work. 
2. Have a way to clearly specify how many actuators there are and what type of actuator they are (e.g. Real, Virtual, Passive and Other) so that variables such as "INDI_NUM_ACT" are not used outside of INDI files and cannot mistakely be assigned a wrong value. 
With @dewagter we thought to revert back the controllers to assign commands to …

Use Commands instead of actuator_pprz 

---

conf/flight_plans/tudelft/rotating_wing_EHVB.xml
conf/modules/eff_scheduling_rot_wing.xml
sw/airborne/modules/ctrl/eff_scheduling_rot_wing.c
sw/airborne/modules/ctrl/eff_scheduling_rot_wing.h
sw/airborne/modules/rot_wing_drone/rotwing_state.c
sw/airborne/modules/rot_wing_drone/rotwing_state.h

Added a free configuration to the rotating wing state machine to automatically switch on and off the hover motors.
Added a push motor rate limiting capability in the WLS settings in order to spin up and spin down the pusher slower to overcome big currents in the pusher ESC.

Rotwing state updates for FREE_STATE and Pusher rate limiter

---

conf/airframes/CDW/cdw_mavtec.xml
conf/airframes/ENAC/quadrotor/cobra.xml
conf/airframes/ENAC/quadrotor/cobraV2.xml
conf/airframes/ENAC/quadrotor/maya_indoor.xml
conf/airframes/OPENUAS/openuas_own_mavtec.xml
conf/airframes/tudelft/mavtec5.xml
conf/modules/rotorcraft_cam.xml
conf/modules/switch_servo.xml
conf/settings/setup_actuators.xml
sw/airborne/modules/actuators/actuators.c
sw/airborne/modules/actuators/actuators.h
sw/airborne/modules/cam_control/rotorcraft_cam.c
sw/airborne/modules/cam_control/rotorcraft_cam.h
sw/airborne/modules/loggers/logger_control_effectiveness.c
sw/airborne/modules/switching/switch_servo.h
sw/tools/generators/gen_airframe.ml

In simulation / NPS, we would like to simulate all actuators. The ```actuators[ ]``` array can not be used because it has different units: e.g. PWM 1100 - 1900.
With the new system of sending actuators to different actuator drivers, the conversion to actuator_driver units is best done when sending to the actuator_driver.
- this means the separate copy of ```actuators_pprz``` is not needed.
- this allows to simulate actuators directly and remove dependencies on control allocation.

actuators[ ] array of structs with pprz units and driver units

---

sw/supervision/python/console_widget.py

Remove VT00 escape codes from console.
Still not ideal, but better.
Before:
After:

[supervision] remove VT100 escape codes.

---

sw/airborne/autopilot.c
sw/airborne/firmwares/fixedwing/autopilot_static.c
sw/airborne/firmwares/rotorcraft/autopilot_firmware.c

- works for all firmwares implementing the autopilot_send_mode function
- avoid to wait the next telemetry message to have the notification

[autopilot] send AP status at every changes

---

Makefile
sw/tools/parse_compile_logs.py

Since testing the entire project produces a lot of text, getting a summary makes it much more readable. Can be called on coverity too.
See sample output:
SUMMARY  
==========
modules:
-------
-  34 - ahrs_sim_0
-  182 - baro_bmp_0

Summary of compile errors

---

sw/logalizer/Makefile
sw/supervision/Makefile

Fix some errors from #3290 which made it impossible to compile for arm when having lalbgtk2 without lablgtk2-glade.

[makefile] Fix compile for ARM

---

sw/ground_segment/python/gvf/README
sw/ground_segment/python/gvf/README.md
sw/ground_segment/python/gvf/circularFormation.py

Since GVF is already implemented for rotorcrafts, I want to add this support for circular formations using rotorcrafts. Documentation (comments and READMEs) are also updated, only thing left to do is update this link: 
https://wiki.paparazziuav.org/wiki/Module/guidance_vector_field#Circular_formations_(centralized_from_the_GCS)

Add rotorcraft support for circularFormation.py

---

sw/airborne/boards/tawaki/chibios/common/mcuconf_board.h
sw/airborne/boards/tawaki/chibios/v2.0/mcuconf_board.h

Activate RTC on Tawaki V1 and V2 to get the time right on the SD card logs.

[board] Activate RTC on Tawaki V1 and V2.

---

Makefile
sw/tools/parse_compile_logs.py
tests/aircrafts/01_compile_all_aircrafts.t

Improved tools to make an overview of failing airframes.
- always print the conf name
- parse ```Error``` and ```failed``` as errors
- do not show an empty overview if the ```CONF``` name is unknown

[tests] Fix printing summary after testing confs

---

conf/modules/eff_scheduling_rotwing_V2.xml
conf/modules/rotwing_state_V2.xml
sw/airborne/modules/rotwing_drone/rotwing_state_V2.c
sw/airborne/modules/rotwing_drone/rotwing_state_V2.h
sw/airborne/modules/rotwing_drone/wing_rotation_adc_sensor.c

This pull request contains code to start a cosine signal to the cmd skew angle for demo purposes. 
Moreover, this pull requests fixes the rotation mech IDX in the Abi messages so that RotWings with either the adc sensor or the supercan board can use the same code.

RotWing Demo + RotMech index correction

---

conf/airframes/AG/rot_wing_v3c_oneloop_optitrack_ext_pose_AG.xml
conf/airframes/examples/bebop2_gvf.xml
conf/airframes/tudelft/rotwing_v3c_oneloop.xml
conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack.xml
conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack_ext_pose.xml
conf/airframes/tudelft/rotwing_v3c_oneloop_simulation.xml
conf/flight_plans/tudelft/oneloop_valkenburg.xml
conf/telemetry/GVF/gvf_default_rotorcraft.xml
conf/userconf/tudelft/conf.xml
sw/airborne/modules/ctrl/eff_scheduling_rotwing_V2.c
sw/airborne/modules/guidance/gvf/gvf.c
sw/airborne/modules/ins/ins_ext_pose.h
sw/airborne/modules/nav/ground_detect.c

- fixes #3372
- missing renames of ```rot_wing``` -> ```rotwing``` including in confs
- missing removals of ```rotwing_automation```
- silent ```gvf``` warnings
- ```INS_EXT_VISION_ROTATION``` is not a global define but in airframes
- ```ground_detect``` can not access ```specific_thrust``` in oneloop 
- Solves #3379

Fix more airframes

---

conf/flight_plans/flight_plan.dtd
doc/sphinx/source/user_guide/flight_plans.rst
sw/airborne/firmwares/fixedwing/nav.h
sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
sw/airborne/firmwares/rotorcraft/navigation.c
sw/airborne/firmwares/rotorcraft/navigation.h
sw/airborne/firmwares/rover/navigation.h
sw/tools/generators/gen_flight_plan.ml

This is only for the rotorcraft firmware at the moment, and it is replacing the explicit call to `guidance_h_SetMaxSpeed` to simplify the flight plans.
Maybe the issue  in #3386 should also be considered here, but I'm not sure it is directly related nor incompatible.

[flight plan] add a max_speed attribute to fp instruction

---

.gitignore
conf/system/term_init.sh
install.sh
requirements.txt
setup.py
sw/supervision/python/utils.py
sw/tools/install.py

I propose to ease the use of a python virtual environment.
It will allow a much more clear python dependencies management.
I did not integrate it in the Makefile to allow testing it without risking breaking anything.
To use it, create en venv: `python3 setup.py`
Then source `pprzEnv/bin/activate`.
It can be done in your .bashrc: `source $PAPARAZZI_HOME/pprzEnv/bin/activate`
What are you though on that PR ?

Python virtual environment

---

conf/airframes/AG/rot_wing_v3c_oneloop_optitrack_ext_pose_AG.xml
conf/airframes/tudelft/rotwing_v3c_oneloop.xml
conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack.xml
conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack_ext_pose.xml
conf/airframes/tudelft/rotwing_v3c_oneloop_simulation.xml
conf/simulator/jsbsim/aircraft/rotwingv3c_SI.xml
sw/airborne/modules/ctrl/eff_scheduling_rotwing_V2.c

This PR is to:
1. Update the dynamics of the motors to the newly identified values
2. Do not use Inertia scheduling for the 7kg oneloop
3. Make jsbsim model much easier to modify for another RW platform
4. Fix small indexing bug for the rot mech when using oneloop and the adc module

Changes to Rotwing 7kg simulator and Actuator dynamics

---

conf/airframes/test_boards/disco.xml
conf/modules/sonar_bebop.xml
sw/airborne/modules/sonar/sonar_bebop.c
sw/airborne/modules/sonar/sonar_bebop.h
sw/simulator/nps/nps_fdm_fixedwing_sim.c
sw/simulator/nps/nps_sensor_sonar.c

Both ABI and telemetry messages are not thread-safe and should be protected by mutex.
Simulation of sonar is handled by NPS.

[sonar] protect sonar reading by mutex for bebop

---

doc/sphinx/source/developer_guide/index_developer.rst
doc/sphinx/source/developer_guide/new_board.rst

A few lines to describe the process of integrating a new board into paparazzi.
However, no mention is made of the generic files used for the stm32h7.

Start of documentation for adding boards

---

sw/ext/Makefile

This is a temporary measure to compile or not on ubuntu 24.04 until the mavlink submodule is updated and integrate the required adaption to cope with deprecated packages: imp and future
Updating mavlink to the current master can solve one the problem, but the second one (solved in pymavlink) is not yet integrated upstream. This patch can be reversed once mavlink integrate the necessary modifications.

[makefile] don't build mavlink if required packages are missing

---

sw/ground_segment/cockpit/Makefile

This module is not supported with the custon lablgtk2 for 24.04

[build] check gnomecanvas package before compiling legacy GCS

---

sw/airborne/firmwares/fixedwing/autopilot_generated.c
sw/airborne/firmwares/rotorcraft/autopilot_generated.c
sw/airborne/firmwares/rover/autopilot_generated.c
sw/tools/generators/gen_autopilot.ml

With generated AP, the initial mode enter function was not called at init.

[autopilot] call the set_mode function at startup

---

sw/airborne/modules/orange_avoider/orange_avoider.c

From #3428, the problematic line in 'orange_avoider.c' is removed, so that it compiles again.

Fixed linking issue 3428 by removing '#define NAV_C' from orange_avoider module code

---

sw/lib/ocaml/autopilot.ml
sw/tools/generators/gen_autopilot.ml

The modules where not extracted from autopilot XML files because it was not looking at the correct node (should be one step deeper).

[autopilot] fix parsing of modules in generated AP files

---

conf/modules/can.xml
sw/airborne/arch/chibios/mcu_periph/can_arch.c
sw/airborne/arch/chibios/mcu_periph/can_arch.h
sw/airborne/arch/stm32/mcu_periph/can_arch.c
sw/airborne/arch/stm32/mcu_periph/can_arch.h
sw/airborne/mcu.c
sw/airborne/mcu_periph/can.c
sw/airborne/mcu_periph/can.h
tests/modules/test_arch/mcu_periph/can_arch.h

Paparazzi abstraction for the CAN bus.
The structures are inspired by SocketCAN in linux.
Only the ChibiOS arch is implemented at the moment, linux will follow.
The plan is to make UAVCAN arch agnostic.
An other PR will follow for an SLCAN bridge, allowing to use DroneCAN GUI.

CAN abstraction

---

conf/modules/slcan.xml
sw/airborne/modules/core/slcan.c
sw/airborne/modules/core/slcan.h

Add CAN over Serial Link bridge.
Allows to use DroneCAN GUI Tool to monitor all DroneCAN devices on the bus through the autopilot.

SLCAN bridge

---

sw/airborne/state.h
sw/simulator/nps/nps_autopilot_rotorcraft.c

It is currently clearing the flags instead of checking them.
Also remove the direct airspeed update from NPS, use ABI message only.

[state] fix bug when checking if airspeed is valid

---

conf/autopilot/autopilot.dtd
conf/autopilot/rotorcraft_autopilot.xml
sw/tools/generators/gen_autopilot.ml

With this, the previous behavior of using macros in airframe file can be used to select the modes.
Update rotorcraft autopilot file accordingly.
The next step is to check that all modes and functionalities of the static autopilot are covered by the generated ones. With this, a default configuration could be used and all autopilots could use the code generation, which will simplify the core AP code.

[generator] add global node for selection of modes in gen_autopilot

---

doc/sphinx/source/getting_started/install.rst

Removed instructions for Ubuntu18.04, which is EOL.

[doc] Update install instructions.

---

conf/airframes/examples/bebop2_opticflow.xml
conf/autopilot/rotorcraft_control_loop.xml
conf/joystick/attack3_booz_nav.xml
conf/joystick/extreme_3d_pro.xml
conf/joystick/logitech_f310_mode1.xml
conf/joystick/logitech_f310_mode2.xml
conf/joystick/logitech_f710.xml
conf/joystick/ms_sidewinder.xml
conf/joystick/n64_gamepad.xml
conf/joystick/ps4_gamepad.xml
conf/joystick/ps4_gamepad_yawontriggers.xml
conf/joystick/snes_gamepad.xml
conf/joystick/xbox_gamepad.xml
conf/joystick/xbox_gamepad_fps_controls.xml
conf/joystick/xbox_gamepad_yawontriggers.xml
conf/modules/optical_flow_landing.xml

- joystick mode sends commands of 0, 75 and 150 PPRZ units instead of -9600, 0, 9600
- ```rotorcraft_control_loop``` has 2 options for ```MODE1```
- ```autopilot``` modes now set in autopilot xml
- Insufficient range for opticalflow_landing

Airframe fixes TUD

---

sw/airborne/modules/ins/ins_alt_float.c

This pull request fixes a bug in the `ins_alt_float` module related to the initialization of the ground reference from the flight plan. Currently, the `init` function of `ins_alt_float` depends on the `ground_alt` variable being pre-initialized by `nav.c` for fixed-wing aircraft. However, in practice, this initialization does not occur as expected, requiring users to manually call `NavSetAltitudeReferenceHere()` in the flight plan to properly set the INS altitude reference.
Our fix is straightforward: we use the `GROUND_ALT` variable defined in the generated `flight_plan.h`, ensuring proper initialization without requiring manual intervention.
An uninitialized altitude reference poses a significant risk for modules that rely on AGL altitude, such as GVF parametric. If the INS altitude …

[ins] Properly initialize utm0 altitude in ins_alt_float

---

conf/airframes/tudelft/rotwing_7kg_common.xml
conf/airframes/tudelft/rotwing_v3b.xml
conf/airframes/tudelft/rotwing_v3d.xml
conf/airframes/tudelft/rotwing_v3e.xml
conf/airframes/tudelft/rotwing_v3f.xml
conf/airframes/tudelft/rotwing_v3g.xml
conf/airframes/tudelft/rotwing_v3h.xml
sw/airborne/firmwares/rotorcraft/autopilot_static.c
sw/airborne/modules/rotwing_drone/rotwing_state.c

- Rotorcraft static AP add option to use failsafe throttle setting

Rotorcraft static AP add option to use failsafe throttle setting

---

sw/airborne/modules/mission/mission_rotorcraft_nav.c

Doing a GOTO can be problematic with hybrid aircraft when the flight mode is different between a simple goto (hover) and a route (forward).

[mission] add an option to skip the first GOTO in mission PATH

---

sw/airborne/boards/px4fmu/chibios/v5.0/board.cfg
sw/airborne/boards/px4fmu/chibios/v5.0/board.h

If to an airfame an external 3rd party current sensor is connect to defualt ACD port like e.g. like
<define name="MilliAmpereOfAdc(adc)" value="(float)(adc) * 50.55"/>
There is a redefine warning. This is because the original define in the board.cfg has the wrong naming MilliAmpereOfAdc insted should be DefaultMilliAmpereOfAdc

Fix the warning for MilliAmpereOfAdc(adc) re-defined FMU5

---

sw/airborne/modules/ahrs/ahrs_float_dcm.c

export has 180deg error to correct sign error in correction, but that means the align is always 180deg wrong

AHRS_DCM_FLOAT fix heading

---

sw/tools/generators/gen_airframe.ml

Little generated code simplification:
Use floating point multiplication instead of integer multiplication and division.

[generator] servo command_value floating point

---

conf/modules/encoder_amt22.xml
conf/modules/humid_sht_i2c.xml
sw/airborne/arch/chibios/mcu_periph/i2c_arch.c
sw/airborne/arch/chibios/mcu_periph/spi_arch.c
sw/airborne/arch/chibios/modules/core/threads_arch.c
sw/airborne/arch/linux/mcu_periph/i2c_arch.c
sw/airborne/arch/linux/modules/core/threads_arch.c
sw/airborne/arch/stm32/modules/core/threads_arch.c
sw/airborne/boards/bebop/actuators.c
sw/airborne/boards/bebop/mt9f002.c
sw/airborne/boards/bebop/mt9v117.c
sw/airborne/boards/disco/actuators.c
sw/airborne/mcu_periph/i2c.c
sw/airborne/mcu_periph/i2c.h
sw/airborne/mcu_periph/spi.c
sw/airborne/mcu_periph/spi.h
sw/airborne/modules/core/threads.h
sw/airborne/modules/meteo/humid_sht_i2c.c
sw/airborne/modules/meteo/humid_sht_i2c.h
sw/airborne/modules/sensors/encoder_amt22.c
sw/airborne/modules/sensors/encoder_amt22.h
sw/airborne/peripherals/amt22.c
sw/airborne/peripherals/amt22.h
sw/airborne/peripherals/pca95xx.c
sw/airborne/peripherals/vl53l1_platform.c

Update the blocking I2C and SPI functions to use the new OS functionalities.
Using blocking functions in a thread (not the AP thread!) should simplify writing drivers, avoid the boilerplate of switch/cases.
Driver for SHT25 (temperature and humidity sensor) rewritten to demonstrate the use of the blocking functions.
Driver for AMT22 encoders added to test the SPI.
Tested on ChibiOS only.

Threads I2C and SPI

---

conf/airframes/ENAC/hybrid/ranger_1.xml
conf/autopilot/heewing_vtol.xml
conf/modules/control_mixing_heewing.xml
conf/modules/guidance_plane_pid_rotorcraft.xml
conf/modules/stabilization_plane_pid.xml
conf/simulator/jsbsim/aircraft/Systems/aerodynamics_ranger_t1.xml
conf/simulator/jsbsim/aircraft/ranger_t1.xml
sw/airborne/firmwares/rotorcraft/guidance/guidance_plane.c
sw/airborne/firmwares/rotorcraft/guidance/guidance_plane.h
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_plane_pid.c
sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_plane_pid.h
sw/airborne/modules/ctrl/control_mixing_heewing.c
sw/airborne/modules/ctrl/control_mixing_heewing.h

The Heewing T1 Ranger VTOL is a tilt-rotor hybrid plane. ( https://www.heewing.com/products/t-1-ranger-vtol-pnp )As a first basic approach, two separated controls are used for hovering (INDI) and forward flight (PID). The mixing is done by a dedicated module and the autopilot is customized to support the specific modes.
A simple PID controller is added to the rotorcraft firmware as it is not possible to directly reuse the one from fixedwing firmware. In a future work, a full INDI version might be used, but this approach can still serves as an example of customized autopilot. A simulation model for JSBSim is also provided.
To avoid confusion,  there also exist a regular Heewing T1 Ranger, just fixedwing code can fly this plane.

[hybrid] add basic support for Heewing T1 Ranger VTOL

---

sw/airborne/modules/ins/ins_alt_float.c
sw/airborne/modules/ins/ins_float_invariant.c
sw/airborne/modules/ins/ins_gps_passthrough.c

It seems to be an undefined behavior and should be avoided.
#3497 is fixing the bug for the ins_ext_pose.

[fix] don't use pointer cast to switch between Vect3 and Coord structures

---

sw/airborne/arch/stm32/modules/core/threads_arch.c

Would fix this:
```
arch/stm32/modules/core/threads_arch.c: In function 'pprz_bsem_wait_timeout':
arch/stm32/modules/core/threads_arch.c:55:20: warning: implicit declaration of function 'get_sys_time_float' [-Wimplicit-function-declaration]
55 | float time_end = get_sys_time_float() + timeout;
| ^~~~~~~~~~~~~~~~~~
arch/stm32/modules/core/threads_arch.c:55:20: warning: nested extern declaration of 'get_sys_time_float' [-Wnested-externs]
```

Fix warning of nested extern declaration of fn get_sys_time_float

---

sw/airborne/modules/actuators/actuators_sbus.c
sw/airborne/modules/actuators/actuators_sbus.h

Use internal MCU feature to invert the UART,
Send the buffer all at once,
For some reason, the output of sbus actuator was not as expected.

[sbus actuator] fix  sbus actuator

---

conf/modules/mag_uavcan.xml
sw/airborne/modules/core/abi_sender_ids.h
sw/airborne/modules/sensors/mag_uavcan.c
sw/airborne/modules/sensors/mag_uavcan.h

Tested only with a sensor sending `MagneticFieldStrength`, but should work with the `MagneticFieldStrength2` message.

[mag] add UAVCAN mag module

---

sw/airborne/boards/crazybee_f4_1.0.h
sw/airborne/boards/px4fmu/chibios/v4.0/px4fmu.h
sw/airborne/boards/px4fmu_2.4.h

To prevent a Re-define error message when own MilliAmpereOfAdc is defined in airframe file using e.g. 3rd party current sensor, a correct board should have DefaultMilliAmpereOfAdc instead.

Fix MilliAmpereOfAdc to DefaultMilliAmpereOfAdc in remaining boardfiles

---

conf/modules/uavcan.xml
sw/airborne/arch/chibios/modules/uavcan/uavcan.c
sw/airborne/arch/chibios/modules/uavcan/uavcan.h
sw/airborne/utils/circular_buffer.c

Add a FIFO for Tx uavcan messages.
The issue was a deadlock when calling `uavcan_broadcast` from the reception callback of an other uavcan message (`iface->mutex` was locked twice).
My solution is to add a FIFO for the messages to be broadcasted.
`uavcan_broadcast` add the messages to this FIFO, and the `uavcan_tx` thread read the messages from the FIFO.
The FIFO have its own mutex, independent from the canard mutex.
I implemented the dynamic node ID allocation (future PR), it broadcast messages from a reception callback.

[uavcan] buffer tx messages in FIFO

---

sw/airborne/boards/px4fmu/chibios/v4.0/board.h
sw/airborne/boards/px4fmu/chibios/v4.0/mcuconf_board.h
sw/airborne/boards/px4fmu/chibios/v4.0/px4fmu.h

Now being able to have PWM signal input on a FMU4 e.g. Pixracer flight-controller. Useful for RPM , SONAR and other PWM based devices that output that signal. Tested with RPM sensor module on ESC PWM and on a Sonar with PWM signal out.
Example output

Added PWM input option to FMU4 e.g. Pixracer FC
