sw/lib/ocaml/xmlEdit.ml
=> [ocaml] turn off search in non editable xml tree views

conf/modules/nav_bungee_takeoff.xml, sw/airborne/modules/nav/nav_bungee_takeoff.c, sw/airborne/modules/nav/nav_bungee_takeoff.h
shorter, with less trigo and more vectors
tested in simulation, to be done in real flight
=> [module] rewrite nav_bungee_takeoff

sw/ground_segment/cockpit/page_settings.ml
=> [gcs] fix undo for list of values

conf/airframes/examples/rt_chibios_test.xml, conf/firmwares/test_chibios.makefile, sw/airborne/arch/chibios/chconf.h, sw/airborne/arch/chibios/halconf.h, sw/airborne/arch/chibios/mcu_arch.c, sw/airborne/arch/chibios/mcu_periph/gpio_arch.h, sw/airborne/arch/chibios/mcu_periph/sys_time_arch.c, sw/airborne/arch/chibios/mcu_periph/sys_time_arch.h, sw/airborne/boards/lisa_mx/chibios/demo/mcuconf.h, sw/airborne/mcu_periph/sys_time.h, sw/airborne/test/mcu_periph/chibios_test_gpio.c, sw/airborne/test/mcu_periph/chibios_test_sys_time_timer.c, sw/airborne/test/mcu_periph/chibios_test_sys_time_usleep.c
=> [chibios] Added two new tests (usleep and gpio)

sw/airborne/arch/linux/mcu_periph/uart_arch.c, sw/airborne/arch/linux/serial_port.c
Make sure the output flags are properly reset for raw mode.
Specifically OPOST, clear some others as well to be safe...
might also fix #743
@karlito139 @OpenUAS would be great if you could also test this...
=> [arch/linux] fix uart driver

sw/airborne/arch/linux/mcu_periph/udp_arch.c, sw/airborne/arch/linux/mcu_periph/udp_arch.h, sw/airborne/mcu_periph/udp.c, sw/airborne/mcu_periph/udp.h
=> Udp refactor

sw/ground_segment/cockpit/live.ml
periodically probe for new AIRCRAFTS until we got at least one...
This should fix #1078
=> [gcs] periodically request AIRCRAFTS

sw/ground_segment/cockpit/live.ml, sw/ground_segment/cockpit/live.mli
Addresses #1046
GPS accuracy is considered ok if better than 10m, very bad if worse than 20m and simply low in between.
Now only if the accuracy falls into a different range than previously reported.
=> GPS accuracy speech less verbose

sw/airborne/arch/chibios/mcu_periph/i2c_arch.c
Prevents system halt in case i2c transaction is submitted and the driver is not ready
(due to electrical issues on the line, or just too intense traffic)
=> [i2c] Important driver update

conf/messages.xml, sw/ground_segment/tmtc/messages.ml, sw/ground_segment/tmtc/server.ml, sw/lib/ocaml/pprz.ml, sw/lib/ocaml/pprz.mli
=> [ocaml] fix formatting of values in pprz ocaml lib (#1135)

conf/Makefile.sim, sw/ground_segment/cockpit/Makefile, sw/ground_segment/cockpit/gcs.ml, sw/ground_segment/cockpit/live.ml, sw/ground_segment/cockpit/live.mli, sw/ground_segment/cockpit/strip.ml, sw/ground_segment/cockpit/strip.mli, sw/lib/ocaml/Makefile, sw/lib/ocaml/myGtkInit.ml, sw/simulator/simsitl.ml
and rather call Main.init directly in the code.
See also http://lablgtk.forge.ocamlcore.org/README.html#_how_to_compile_and_link
This is part of the lib/ocaml cleanup, in the end only the pprz package should remain in there...
=> remove myGtkInit.ml

sw/supervision/pc_aircraft.ml, sw/supervision/pc_common.ml
=> [paparazzi center] disable build/upload buttons during build

conf/airframes/examples/quadrotor_navgo.xml, conf/flight_plans/rotorcraft_survey.xml, conf/modules/nav_survey_rectangle_rotorcraft.xml, conf/telemetry/default_rotorcraft.xml, sw/airborne/firmwares/rotorcraft/navigation.c, sw/airborne/firmwares/rotorcraft/navigation.h, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_int.c, sw/airborne/modules/nav/nav_survey_rectangle_rotorcraft.c, sw/airborne/modules/nav/nav_survey_rectangle_rotorcraft.h
added survey rectangle module for rotorcraft.
Also work using flightplan primitive
=> Survey rectangle

conf/modules/airspeed_amsys.xml, sw/airborne/modules/sensors/airspeed_amsys.c, sw/airborne/modules/sensors/airspeed_amsys.h, sw/airborne/modules/sensors/baro_amsys.c
[baro]
changed max pressure for 5812-0001-D
changed max temperature 
both according data sheet 
and fixed error in temp calculation for airspeed and baro
=> [baro] fixed max pressure for 5812-0001-D

sw/airborne/firmwares/fixedwing/stabilization/stabilization_adaptive.c
this is not solving the compile problem I stated on my other post but it rather makes it possible to decide if you want to make the flaps depending only on speed or on speed and nz as well.
=> Flag for INCREASE_FLAPS_WITH_LOADFACTOR

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.c
The PSI += .... was highly depending on the RC-frame rate.
With most RC this is not a problem but with variable message rates (e.g. rc_datalink dropping messages or joysticks sending too many frames) this line becomes dangerous.
So measure the time between to calls to read_rc_setpoint function instead of using a fixed RC_UPDATE_FREQ.
To prevent really weird things from happening, bound dt to 0.5s.
Don't partuculariliy like that this pulls in the sys_time dependency here,
but couldn't think of something better...
should close #452
=> [rotorcraft] heading integration protection in RC-event

sw/airborne/firmwares/rotorcraft/autopilot_arming_switch.h
Untested, but should fix #1041
=> [rotorcraft] fix arming with kill switch

sw/logalizer/plotter.ml
Now you can use the -c parameter to plotter to add a constant to the plot.
```
sw/logalizer/plotter -c "1.5"
```
=> [plotter] Added support for adding constant curves on command line.

conf/airframes/ENAC/fixed-wing/funjet2.xml, conf/airframes/ENAC/fixed-wing/jp.xml, conf/modules/mag_hmc58xx.xml, sw/airborne/modules/sensors/mag_hmc58xx.c
and disable periodic IMU_MAG_RAW report by default
=> [modules] mag_hmc58xx: configure MAG_HMC58XX_I2C_DEV

conf/flight_plans/rotorcraft_optitrack.xml
A few settings in the standard optitrack flight plan were annoying me, like the altitude at 5 meters (and the whole 150m offset thing).
=> improvement standard Optitrack flightplan

sw/ground_segment/misc/natnet2ivy.c
With the update the axes were not right anymore. Apparently they have always been a bit oddly defined...
This should fix the axes and the altitude issues
=> fixing optitrack axes and altitude

conf/flight_plans/rotorcraft_optitrack.xml
Correct waypoints, kill on land, etc.
=> more optitrack flight plan improvements

sw/airborne/subsystems/gps/gps_nmea.c, sw/airborne/subsystems/gps/gps_nmea.h
Make the crappy NMEA parser a little bit less crappy...
CRC of the incoming messages is still not checked...
=> [GPS] Nmea parser fixes

conf/airframes/examples/bebop.xml, sw/airborne/boards/bebop/video.c
=> [bebop] Upgrade video resolution

conf/airframes/AggieAir/ark_quad_lisa_mx.xml, conf/airframes/AggieAir/conf_aggieair.xml, conf/airframes/AggieAir/rp3_lia.xml, conf/firmwares/subsystems/fixedwing/ins_vectornav.makefile, conf/firmwares/subsystems/rotorcraft/ins_vectornav.makefile, conf/firmwares/subsystems/shared/ins_vectornav.makefile, conf/messages.xml, conf/radios/Taranis_AggieAir.xml, conf/telemetry/default_fixedwing.xml, conf/telemetry/default_rotorcraft.xml, sw/airborne/firmwares/fixedwing/main_ap.c, sw/airborne/firmwares/rotorcraft/main.c, sw/airborne/modules/ins/ins_xsens.h, sw/airborne/peripherals/vn200_serial.c, sw/airborne/peripherals/vn200_serial.h, sw/airborne/subsystems/ins/ins_vectornav.c, sw/airborne/subsystems/ins/ins_vectornav.h, sw/airborne/subsystems/ins/ins_vectornav_wrapper.c, sw/airborne/subsystems/ins/ins_vectornav_wrapper.h
slightly cleaned up version of #1305
some AHRS stuff can probably also be removed...
=> cleaned up version of Vectornav VN-200

conf/settings/persistent_settings.xml, sw/airborne/arch/linux/subsystems/settings_arch.c, sw/airborne/arch/lpc21/subsystems/settings_arch.c, sw/airborne/arch/stm32/subsystems/settings_arch.c, sw/airborne/firmwares/fixedwing/autopilot.h, sw/airborne/firmwares/rotorcraft/autopilot.h, sw/airborne/subsystems/settings.c, sw/airborne/subsystems/settings.h
settings_clear should clear all persistent settings from flash/file.
Tested on STM32F4...
=> [settings] implement settings_clear

conf/airframes/BR/bebop_default.xml, conf/airframes/BR/bebop_indi.xml, conf/airframes/BR/bebop_indi_frog.xml, conf/airframes/BR/bebop_indi_frog_flip.xml, conf/airframes/CDW/bebop.xml, conf/airframes/ENAC/quadrotor/ard2_base_digit.xml, conf/airframes/ENAC/quadrotor/ard2_base_vision.xml, conf/airframes/examples/ardrone2.xml, conf/airframes/examples/bebop.xml, conf/modules/video_thread.xml, sw/airborne/arch/linux/mcu_periph/sys_time_arch.h, sw/airborne/boards/ardrone/board.c, sw/airborne/boards/ardrone2.h, sw/airborne/boards/bebop.h, sw/airborne/boards/bebop/video.c, sw/airborne/modules/computer_vision/lib/v4l/v4l2.h, sw/airborne/modules/computer_vision/lib/vision/image.c, sw/airborne/modules/computer_vision/video_thread.c, sw/airborne/peripherals/video_device.h
@fvantienen this is a start of the idea we discussed
@flixr @gautierhattenberger any idea is welcome
=> Board knows camera settings

conf/airframes/TUDelft/airframes/bebop_indi.xml, conf/airframes/TUDelft/conf.xml, conf/firmwares/rotorcraft.makefile, conf/firmwares/subsystems/rotorcraft/guidance_indi.makefile, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h
Outer loop INDI control.
Controls accelerations of the drone to counteract (aerodynamic) disturbances. This is a quick implementation that only works for the horizontal accelerations, but vertical can be added easily. 
Test flown with hover_z_hold
=> outer loop INDI control

sw/ground_segment/cockpit/live.ml, sw/ground_segment/cockpit/live.mli
Do not spam the alert page with battery warnings, which is especially annoying with speech enabled...
=> [gcs] only print bat warning every 10s

sw/supervision/paparazzicenter.glade, sw/supervision/pc_aircraft.ml
Add reload button (and make padding a bit smaller).
Not sure how to call update_params from the build_handler...
Related to #1331
=> [paparazzi center] add reload button

sw/lib/ocaml/pprz.ml
=> [ocaml] increase maximum Ivy message length from 1000 to 10000

conf/airframes/HooperFly/conf_hooperfly.xml, conf/airframes/HooperFly/racerpex_hexa_lisa_mx_20.xml, conf/airframes/HooperFly/racerpex_octo_lisa_mx_20.xml, conf/airframes/HooperFly/racerpex_quad_lisa_mx_20.xml, conf/airframes/HooperFly/teensyfly_quad_elle0.xml, conf/airframes/HooperFly/teensyfly_quad_lisa_mx_20.xml, conf/flight_plans/HooperFly/rotorcraft_multiflight.xml
Overview:
- Up-to-date airframe files tuned for each type of HooperFly airframe
- Updated the multi-aircraft flight plan to use a `for` loop when generating the `Pano` block behavior
=> Updates for HooperFly Flight Plans and Airframes

conf/airframes/untested/quadrotor_pixhawk_lite.xml, conf/boards/px4fmu_2.4.makefile, sw/airborne/arch/stm32/mcu_arch.c, sw/airborne/arch/stm32/px4fmu_2.4.ld, sw/airborne/boards/px4fmu_2.4.h
Start adding support for the PX4FMU v2.4x (aka Pixhawk)
Basic things were working, including reading the MPU...
No SPI driver for the lsm303d yet...
=> PX4FMU v2.4

sw/logalizer/play_core.ml
=> [logalizer] replay ground messages

sw/supervision/paparazzicenter.glade, sw/supervision/pc_aircraft.ml
Start to solve #1209
Does not yet ask for a new airframe file name and copy the airframe file.
=> [paparazzi center] add copy A/C menu entry

conf/airframes/TUDelft/airframes/ardrone2_opticflow_stereo.xml, conf/modules/stereocam.xml, sw/airborne/modules/stereo_cam/stereocam.c, sw/airborne/modules/stereo_cam/stereocam.h
Also added airframe file to test optical flow and stereo on an ARDrone at the same time.
=> Removed wrong folder in the stereo module

sw/airborne/modules/computer_vision/lib/exif/exif_module.c
Not tested yet.
@stephen hulme does this work for you?
=> [exif] negative lat/lon/alt

conf/airframes/TUDelft/airframes/bebop2_indi.xml, conf/airframes/TUDelft/conf.xml, conf/airframes/examples/bebop2_indi.xml, conf/boards/bebop2.makefile, conf/conf_example.xml, sw/airborne/boards/bebop/actuators.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_indi.c, sw/airborne/subsystems/imu/imu_bebop.c
Add support for the Parrot Bebop 2.
What is changed:
- New GPS (ublox Neo M8N)
- Actuator direction and order changed
- Magnetometer rotated 90 degrees
=> [parrot] Add Bebop 2 support

sw/airborne/modules/datalink/missionlib/blocks.c, sw/airborne/modules/datalink/missionlib/mission_manager.c
Proposed road forward for the mavlink handling of blocks. (See #1422 for reference)
=> [mavlink] upgrade

conf/airframes/TUDelft/airframes/heli450.xml, conf/airframes/TUDelft/conf.xml, conf/airframes/airframe.dtd, conf/modules/heli_swashplate_mixing.xml, conf/modules/heli_throttle_curve.xml, sw/airborne/firmwares/rotorcraft/autopilot.h, sw/airborne/modules/helicopter/swashplate_mixing.c, sw/airborne/modules/helicopter/swashplate_mixing.h, sw/airborne/modules/helicopter/throttle_curve.c, sw/airborne/modules/helicopter/throttle_curve.h, sw/tools/generators/gen_airframe.ml
This adds two modules for Helicopters:
- Throttle curves
- Swashplate mixers (which depends on throttle curves)
=> [helicopter] Add helicopter mixings and throttle curves

sw/ground_segment/python/messages_app/messagesframe.py, sw/ground_segment/python/settings_app/settingsframe.py
=> fixes for using wxPython 3.0 (python-wxgtk3.0)

sw/airborne/subsystems/navigation/common_nav.c, sw/lib/ocaml/latlong.ml, sw/lib/ocaml/latlong.mli, sw/tools/generators/gen_flight_plan.ml
It would be nice if someone could test this fix
fix #303
=> [flight plan] force UTM zone of waypoints to be the same than ref point

conf/airframes/examples/quadrotor_elle0.xml, conf/airframes/examples/setup_elle0.xml, conf/boards/elle0_1.2.makefile, sw/airborne/boards/elle0_1.2.h, sw/airborne/boards/elle0_common.h
- Elle0 V1.2 is the release version of the hardware, the UART
assignement is bit different than the V1.0 preproduction version.
- Adding one more UART for Spektrum usage
- Moved all the board header settings to a common file
- Added aliases for the Elle0 V1.0 and V1.2 versions
- Added makefile for V1.2 version
=> [Elle0] Added support for Elle0 V1.2.

conf/airframes/TUDELFT/tudelft_bebop2_indi.xml, conf/airframes/examples/bebop2_indi.xml, sw/airborne/boards/bebop/actuators.c
When updating to the newest firmware, the bebop2 motor order/spin direction changed again. Here is a fix, I flew with this today
=> motor order/spin direction changed

sw/airborne/subsystems/ahrs/ahrs_float_cmpl.c, sw/airborne/subsystems/ahrs/ahrs_float_cmpl.h, sw/airborne/subsystems/ahrs/ahrs_float_cmpl_wrapper.c, sw/airborne/subsystems/ahrs/ahrs_float_dcm.c, sw/airborne/subsystems/ahrs/ahrs_float_dcm.h, sw/airborne/subsystems/ahrs/ahrs_float_dcm_wrapper.c, sw/airborne/subsystems/ahrs/ahrs_float_invariant.c, sw/airborne/subsystems/ahrs/ahrs_float_invariant.h, sw/airborne/subsystems/ahrs/ahrs_float_invariant_wrapper.c, sw/airborne/subsystems/ahrs/ahrs_float_mlkf.c, sw/airborne/subsystems/ahrs/ahrs_float_mlkf.h, sw/airborne/subsystems/ahrs/ahrs_float_mlkf_wrapper.c, sw/airborne/subsystems/ahrs/ahrs_float_utils.h, sw/airborne/subsystems/ahrs/ahrs_int_utils.h, sw/airborne/subsystems/ins/ins_float_invariant.c, sw/airborne/subsystems/ins/ins_float_invariant.h, sw/airborne/subsystems/ins/ins_float_invariant_wrapper.c
convert from int32 to float in wrappers
=> [ahrs] float variants really only use floats internally

sw/airborne/firmwares/fixedwing/main_fbw.c, sw/airborne/firmwares/fixedwing/main_fbw.h
Fixed includes, also now it compiles for fbw/ap targets.
=> Second attempt to clean and remove ifdefs from main_fbw 

sw/tools/generators/gen_aircraft.ml
put all makefile vars (specified via configure) before including the board makefile.
e.g. RADIO_CONTROL_PPM_PIN has moved to the board makefile, and this
```
<subsystem name="radio_control" type="ppm">
<configure name="RADIO_CONTROL_PPM_PIN" value="UART1_RX"/>
</subsystem>
```
was not working anymore and instead it was necessary to move the configure line outside of the subsystem lines:
```
<subsystem name="radio_control" type="ppm"/>
<configure name="RADIO_CONTROL_PPM_PIN" value="UART1_RX"/>
```
This should fix that regression again.
=> [generators] always put configure options at beginning

sw/airborne/subsystems/imu/imu_bebop.c
Fixed and tested magnetometer. Tested on four different Bebop's from different batches. All is now fine, note that this is a fix for regular Bebop  and has nothing to do with Bebop2, Bebop2 is another **product,** not another version. Raw values monitored, scaled compared etc. etc.
Yes, it is only one - (minus) sign difference that make all the difference from non- autonomous flight to OK autonomous flight.
=> Fixed and tested magnetometer

sw/ground_segment/misc/natnet2ivy.c
added logging of natnet2ivy messages.
=> logging natnet messages

sw/ground_segment/python/dashboard/radiowatchframe.py, sw/ground_segment/python/guided_mode_example.py, sw/ground_segment/python/ivytoredis/ivy_to_redis.py, sw/ground_segment/python/messages_app/messagesframe.py, sw/ground_segment/python/move_waypoint_example.py, sw/ground_segment/python/real_time_plot/messagepicker.py, sw/ground_segment/python/real_time_plot/plotpanel.py
Start using the slightly improved IvyMessagesInterface.
There is still room for improvement (e.g. not binding/subscribing to all messages)
see paparazzi/pprzlink#4
=> [python] use updated IvyMessagesInterface

sw/airborne/subsystems/ins/ins_int.c
Thanks to @kirkscheper who found this bug.
=> ins int fix

sw/ground_segment/misc/natnet2ivy.c
Sending the correct lla altitude in datalink gps message
=> optitrack: send correct lla altitude

conf/boards/ardrone2.makefile, sw/airborne/boards/ardrone/board.c, sw/airborne/boards/ardrone/gpio_ardrone.c, sw/airborne/boards/ardrone/navdata.c, sw/airborne/boards/ardrone/navdata.h, sw/airborne/mcu.c, sw/tools/parrot/ardrone2.py, sw/tools/parrot/parrot_utils.py
Fix the dreaded 2x need to upload and trashed navdata and some more. e.g. from "Currently running: Paparazzi (ap.elf), Native (program.elf)", to "Currently running: Paparazzi (ap.elf)" first time powered on ARDrone2
=> Improve experience of PPRZ on ARDrone2

sw/airborne/modules/computer_vision/colorfilter.c, sw/airborne/modules/computer_vision/cv.c, sw/airborne/modules/computer_vision/cv.h, sw/airborne/modules/computer_vision/cv_blob_locator.c, sw/airborne/modules/computer_vision/detect_window.c, sw/airborne/modules/computer_vision/qrcode/qr_code.c, sw/airborne/modules/computer_vision/viewvideo.c
- enables e.g. resize functions to pass on the smaller images to next functions
=> cvFunction returns a pointer to an image (allows resizes etc)

sw/lib/ocaml/gen_common.ml, sw/tools/generators/gen_aircraft.ml
see #1576 
This could be made much better, but at least it as the desired behavior
=> [generators] fix targets testing and inversion for modules

sw/airborne/boards/bebop/board.c, sw/tools/parrot/bebop.py, sw/tools/parrot/parrot_utils.py
In the past the main OEM ap app was not always succesfully stopped  after a first upload, this confused users not getting any telemetry, their GCS stayed blank, which was puzzling to most 1st time PPRZ users. This is fixed now.
=> Fix upload and first run experience of PPRZ on Bebop

conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2a.xml, conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2b.xml, conf/flight_plans/HOOPERFLY/hooperfly_gsa_one.xml
New airframes for Elle0 v1_2. The `b` version currently does not simulate well after updating the calibration settings. It's real world performance is rock solid.
=> Updates for Elle0 v1_2 airframes

sw/airborne/firmwares/rotorcraft/navigation.c
As discussed on gitter I removed the unwanted flight plan state change.
=> [navigation] Fix unwanted horizontal control state

conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2a.xml, conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2b.xml
Updated two frames missed as part of the #1604 merge
=> Sync airframes missed as part of merge for #1604

sw/ground_segment/tmtc/aircraft.ml, sw/ground_segment/tmtc/aircraft.mli, sw/ground_segment/tmtc/fw_server.ml
The GCS now combines the FBW battery with the AP battery which is confusing.
This fixes the problem and doesn't show the FBW battery by default.
=> [ground] Fix FBW battery level

conf/telemetry/rotorcraft_with_logger.xml, sw/airborne/firmwares/rotorcraft/main_fbw.c, sw/airborne/modules/px4_flash/px4_flash.c, sw/airborne/subsystems/intermcu.h, sw/airborne/subsystems/intermcu/intermcu_ap.c, sw/airborne/subsystems/intermcu/intermcu_ap.h, sw/airborne/subsystems/intermcu/intermcu_fbw.c
Cleanup the InterMCU and update pprzlink for multiple parser support.
=> Intermcu cleanup

conf/modules/temp_adc.xml, sw/airborne/mcu_periph/adc.h, sw/airborne/modules/sensors/temp_adc.c, sw/airborne/modules/sensors/temp_adc.h
Make temperature module through ADC more configurable.
=> [modules] Update ADC temperature to be configurable

conf/firmwares/subsystems/shared/gps_furuno.makefile
While we are fixing typos in furuno, how about this?
=> [gps] fix typo in furuno.makefle

conf/airframes/HOOPERFLY/hooperfly_conf.xml, conf/flight_plans/HOOPERFLY/hooperfly_gsa_one.xml
- Synchronize hooperfly_conf.xml with current working set
- Add circle CAM flight block to the gsa_one flight plan
=> Minor updates configuration and add camera nav to gsa_one flight plant

conf/airframes/TUDELFT/tudelft_conf.xml, conf/airframes/TUDELFT/tudelft_outback.xml, conf/boards/opa_ap_1.0.makefile, conf/boards/opa_ftd_1.0.makefile, conf/firmwares/subsystems/shared/baro_board.makefile, conf/modules/heli_swashplate_mixing.xml, conf/modules/heli_throttle_curve.xml, sw/airborne/boards/opa_ap/baro_board.h, sw/airborne/boards/opa_ap_1.0.h, sw/airborne/boards/opa_ftd_1.0.h, sw/airborne/boards/px4io_2.4.h, sw/airborne/mcu.c, sw/airborne/modules/spektrum_soft_bind/spektrum_soft_bind_fbw.c
This adds the newly designed OPA(Oversized Paparazzi Autopilot) board support. It is specially designed for the Outback by @dewagter and includes an FBW and AP in a single board.
=> [boards] Add the new OPA board

sw/airborne/arch/linux/mcu_periph/udp_arch.c
=> [arch] Update udp_arch.c

sw/airborne/subsystems/gps.c, sw/airborne/subsystems/gps/gps_datalink.c, sw/airborne/subsystems/gps/gps_datalink.h, sw/airborne/subsystems/gps/gps_mtk.c
I'm splitting up #1629. This should only contain changes to the gps tow update and updates to the gps->utm functions
=> [gps] added a default update for gps tow when changed and updated utm

sw/airborne/subsystems/datalink/datalink.c, sw/ground_segment/misc/natnet2ivy.c
Set reference frame in lla and fix bug to set lla in deg 1e7. 
Generate correct time of week and also send that with the small messages.
=> [natnet] update natnet

conf/flight_plans/TUDELFT/tudelft_delft_outback.xml, conf/flight_plans/flight_plan.dtd, conf/modules/nav_heli_spinup.xml, sw/airborne/firmwares/fixedwing/nav.h, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c, sw/airborne/firmwares/rotorcraft/navigation.c, sw/airborne/firmwares/rotorcraft/navigation.h, sw/airborne/modules/helicopter/throttle_curve.c, sw/airborne/modules/helicopter/throttle_curve.h, sw/airborne/modules/nav/nav_heli_spinup.c, sw/airborne/modules/nav/nav_heli_spinup.h, sw/ground_segment/tmtc/server_globals.ml, sw/tools/generators/gen_flight_plan.ml
- Functionality for mode "manual" in flight plan without stabilization
- Navigation routines for spinning up rotor for helicopters in flight plan
- Added example flightplan
=> [heli][flight_plans] Heli Spinup routine and flight plan mode manual

sw/supervision/paparazzicenter.ml
Try to find better wording for the quit and restore_backup dialogs...
See #1567
=> [pprzcenter] reword the quit and backup found dialogs

conf/airframes/HOOPERFLY/hooperfly_conf.xml, conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2c.xml
Updates for Elle0 C version of TeensyFly Quad
=> HooperFly airframe updates

conf/modules/nav_catapult.xml, conf/modules/nav_launcher.xml, sw/airborne/modules/nav/nav_launcher.c, sw/airborne/modules/nav/nav_launcher.h
A routine for a takeoff with a pneumatic launcher (see video here: https://www.youtube.com/watch?v=qc1uwH-8Dbw )
The module is kind of self explanatory.
Also fixed a typo in nav_catapult.xml
=> Launcher takeoff routine

conf/airframes/DB/db_bebop2_indi.xml, conf/flight_plans/DB/db_cyberzoo.xml, conf/flight_plans/DB/db_rotorcraft_basic.xml, conf/telemetry/DB/db_default_rotorcraft.xml, conf/userconf/DB/db_conf.xml, conf/userconf/DB/db_control_panel.xml
I would like to add my telemetry, airframe and flight plan xml files to master. The files are all in separate folders i.e. conf/airframes/DB (following the existing convention).
=> User-Specific folders for configuration xml files in telemetry, airframes and flight plans.

conf/airframes/TUDELFT/tudelft_ladylisa_bluegiga_stereoboard.xml, sw/airborne/modules/stereocam/state2camera/state2camera.c, sw/airborne/modules/stereocam/stereocam2state/stereocam2state.c, sw/airborne/modules/stereocam/stereocam2state/stereocam2state.h, sw/airborne/modules/stereocam/stereoprotocol.c, sw/airborne/modules/stereocam/stereoprotocol.h
I cleaned up the stereocam module a bit, but more importantly I fixed a issue with sending messages from from lisa-s -> uart -> stereoboard. First it skipped indicators of the start and ending of the messages, but with these added while loops it does not do that anymore. Any suggestions to make it even better are welcome ofcourse
=> Stereocam sendarray fix

conf/airframes/TUDELFT/tudelft_conf.xml, conf/airframes/TUDELFT/tudelft_outback.xml, conf/boards/opa_ap_1.0.makefile, conf/modules/mag_pitot_uart.xml, sw/airborne/modules/sensors/mag_pitot_uart.c, sw/airborne/modules/sensors/mag_pitot_uart.h, sw/airborne/subsystems/abi_sender_ids.h
This adds the functionality for a new type of Magneto + pitot. The module transmits PPRZ messages which contain magneto and airspeed information.
=> [modules] New magneto and pitot

.gitmodules, conf/modules/cv_opencvdemo.xml, sw/airborne/modules/computer_vision/cv_opencvdemo.c, sw/airborne/modules/computer_vision/cv_opencvdemo.h, sw/airborne/modules/computer_vision/opencv_example.cpp, sw/airborne/modules/computer_vision/opencv_example.h
Title says it all... simple sobel filter.
=> Added opencv example

conf/airframes/TUDELFT/tudelft_outback.xml, conf/modules/logger_sd_spi_direct.xml, sw/airborne/modules/loggers/sdlogger_spi_direct.c, sw/airborne/modules/loggers/sdlogger_spi_direct.h
- Start logging with settings instead of RC (functionality still available through settings from RC)
- Multiple logs on SD card
=> SD logger updates

conf/airframes/TUDELFT/tudelft_iris_indi.xml, conf/airframes/TUDELFT/tudelft_iris_pid.xml, conf/airframes/TUDELFT/tudelft_outback.xml, sw/airborne/firmwares/rotorcraft/main_fbw.c, sw/airborne/firmwares/rotorcraft/main_fbw.h, sw/airborne/subsystems/intermcu/intermcu_fbw.c, sw/airborne/subsystems/intermcu/intermcu_fbw.h, sw/airborne/subsystems/radio_control.h
This cleans up some of the fbw code for rotorcraft and fixes failsafe mode.
=> [rotorcraft][fbw] Restore failsafe mode and cleanup

sw/supervision/pc_control_panel.ml
and Replay session.
This allows to e.g. set the desired default options for the GCS (like layout, speech, etc..) in the programs section of the control_panel.xml file
and they will also be used for the Simulation and Replay sessions and not only when started from the tools menu.
should close #1668
=> [pprz_center] also use GCS program args for Simulation session

conf/modules/nav_catapult.xml, sw/airborne/modules/nav/nav_catapult.c, sw/airborne/modules/nav/nav_catapult.h
- state machine more readable
- don't use imu struct directly
- more configuration options
- initial module was not working well anyway (was setting full throttle all the time unless high_freq function manually stopped)
=> [nav] rewrite nav_catapult module

conf/modules/cv_opencvdemo.xml, sw/airborne/modules/computer_vision/cv_opencvdemo.c, sw/airborne/modules/computer_vision/opencv_example.cpp, sw/airborne/modules/computer_vision/opencv_example.h, sw/airborne/modules/computer_vision/opencv_image_functions.cpp, sw/airborne/modules/computer_vision/opencv_image_functions.h
Now it is easy to convert back to the normally used yuv422 arrays of paparazzi. 
Any place better by the way for these conversion functions?
=> Opencv stuff

conf/airframes/AGGIEAIR/aggieair_conf.xml, conf/airframes/AGGIEAIR/aggieair_rp3_lia.xml, conf/conf_example.xml, conf/conf_tests.xml, conf/firmwares/subsystems/fixedwing/control.makefile, conf/flight_plans/AGGIEAIR/BasicTuning_Launcher.xml, conf/flight_plans/AGGIEAIR/aggieair_landing.xml, conf/modules/nav_skid_landing.xml, sw/airborne/firmwares/fixedwing/guidance/guidance_common.h, sw/airborne/firmwares/fixedwing/guidance/guidance_v.c, sw/airborne/firmwares/fixedwing/guidance/guidance_v.h, sw/airborne/firmwares/fixedwing/main_ap.c, sw/airborne/firmwares/fixedwing/stabilization/stabilization_attitude.c, sw/airborne/modules/nav/nav_skid_landing.c, sw/airborne/modules/nav/nav_skid_landing.h
Fixes from  #1656
I renumbered (sequentially) the conf examples so it is easier to add more examples in the future (I had a hard time finding an unused ID).
=> Skid landing take #2

sw/ground_segment/misc/natnet2ivy.c
Required to work with Motive v1.9.
@fvantienen can you take a look at this and merge with priority, this fix is needed for others to work in the zoo.
=> [natnet] update natnet2ivy to natnet sdk 2.9

conf/modules/video_usb_logger.xml, sw/airborne/modules/computer_vision/video_usb_logger.c
The USB logger works again! Made it into the current setup where you can specify which camera to log.
=> Fixed the USB logger

sw/airborne/firmwares/rotorcraft/autopilot.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h
Seems useful to be able to set the velocity in body frame more easily from within pprz.
=> [guidance] helper function to set velocity in body frame when in guided mode

conf/modules/cv_qrcode.xml, sw/airborne/modules/computer_vision/qrcode/qr_code.c, sw/airborne/modules/computer_vision/qrcode/qr_code.h
the qr code scanner is working again! Also: now printing the upper left corner of the code (@dewagter check this out!)
=> fixed qr code

sw/airborne/firmwares/rotorcraft/autopilot.c
=> fixed orientation guidance

conf/airframes/TUDELFT/tudelft_bebop_autonomous_race.xml, conf/airframes/TUDELFT/tudelft_conf.xml
Added a new TU Delft airframe with all parameters I want my autonomous drone airframe to have.
=> Autonomous race airframe

sw/airborne/filters/notch_filter.h
Simple second order notch filter. I use it to attenuate the motor frequency from gyro measurements.
=> Second order notch filter

conf/airframes/TUDELFT/tudelft_bebop_autonomous_race.xml, conf/airframes/TUDELFT/tudelft_bebop_indi.xml, conf/airframes/TUDELFT/tudelft_bebop_mavlink.xml, conf/airframes/TUDELFT/tudelft_bebop_opticflow.xml, conf/airframes/examples/bebop.xml, sw/tools/parrot/bebop.py, sw/tools/parrot/parrot_utils.py
Motors got reversed, but are apparently still not the same as with bebop 2 (or I don't understand something). In any case; tested this with a bebop 1 and it flies in att mode.
Also, pprz center now gives user feedback on some problems during upload. 
- checks on firmware version to be 3.2.0
- tells user to press button 4 times (2 times does not work with bebop 1 @ 3.2.0)
- tells user to check wifi conntection
=> Bebop fw3.2.0 fix

conf/modules/nav_survey_poly_rotorcraft.xml, sw/airborne/modules/nav/nav_survey_poly_rotorcraft.c, sw/airborne/modules/nav/nav_survey_poly_rotorcraft.h
Fixed the sweep-back-number so they survey can be ended
Added option to enable/disable half-sweeps
Removed unrelated comments & fixed indentation
=> Poly survey cleanup

sw/lib/ocaml/gen_common.ml
=> [build] autoload of module recursively

conf/airframes/TUDELFT/tudelft_course2016_bebop_avoider.xml, conf/airframes/TUDELFT/tudelft_course2016_bebop_colorfilter.xml, conf/airframes/TUDELFT/tudelft_course2016_conf.xml
=> moved colorfilter example for the course, now using optitrack gps

conf/airframes/TUDELFT/tudelft_course2016_bebop_avoider.xml
Updated a new firmware.
Changed GPS to optitrack.
Changed driver.
If motors are not changed, the quadrotor will be unstable.
=> update tudelft_course2016_bebop_avoider airframe

sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
=> fixed rotation issue

conf/airframes/KS/kirk_conf.xml, conf/airframes/KS/ks_mavtec1.xml, conf/airframes/TUDELFT/tudelft_conf.xml, conf/airframes/TUDELFT/tudelft_mavtec1.xml
Adds the Mavtec 1 in outdoor flight configuration to the TUDELFT conf and in optitrack mode to my personal conf.
=> added Kirk Scheper conf and Mavtec 1

sw/airborne/firmwares/fixedwing/fixedwing_datalink.c, sw/airborne/firmwares/fixedwing/nav.c, sw/airborne/modules/computer_vision/video_thread_nps.c, sw/airborne/modules/datalink/mavlink.c, sw/airborne/modules/nav/nav_smooth.c, sw/airborne/modules/nav/nav_survey_poly_osam.c, sw/logalizer/sdlogger_download.c, sw/simulator/nps/nps_fdm_jsbsim.cpp, sw/simulator/nps/nps_flightgear.c, sw/simulator/nps/nps_radio_control_spektrum.c
See comments at https://scan.coverity.com/projects/paparazzi-paparazzi/view_defects
Mostly self-explaining.
=> Coverity fixes

sw/simulator/nps/nps_flightgear.c
This should take care of the last pending issues in the coverity scan.
=> Sockets in flight gear - check for error conditions

sw/airborne/modules/computer_vision/lib/v4l/v4l2.c
=> [v4l2] Ardrone 2 fix

sw/airborne/firmwares/rotorcraft/autopilot.c
- mixed z/yaw param
- flag overwritten
=> [rotorcraft] fix guided mode

conf/airframes/TUDELFT/tudelft_conf.xml, conf/airframes/examples/ardrone2.xml, sw/airborne/modules/computer_vision/lib/encoding/jpeg.c
=> Jpeg multithread

conf/airframes/TUDELFT/calibrations/bebopTUBB17.xml, conf/airframes/TUDELFT/tudelft_KM_conf.xml, conf/airframes/TUDELFT/tudelft_bebop_opticflow.xml, sw/airborne/modules/computer_vision/lib/vision/edge_flow.c, sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c, sw/airborne/modules/computer_vision/opticflow_module.c
[opticflow] fix segmentation fault (derotation) in edgeflow, removed camere_rotate_180 (is already done), some added changes to the conf files.
@rmeertens, could you check with your bebop if you still have the segmentation problem with edgeflow and derotation selected?
=> Fixes to optical flow module

conf/modules/video_usb_logger.xml, sw/airborne/modules/computer_vision/video_usb_logger.c
parameters width and height set at runtime. 
removed a useless dependency. 
fixed warnings. 
now logging more data!
=> video usb logger fix

sw/airborne/boards/bebop.h, sw/airborne/boards/bebop/board.c
Added an example in the comments about what you can and can't do with the camera (as far as I explored up till now).
=> more variables to configure and some comments

sw/airborne/boards/bebop.h, sw/airborne/boards/bebop/board.c
Target exposure and fps added including values I found while testing. 
Fixed codestyle resulting in a big diff
=> [Bebop] more settings for the front camera

sw/airborne/modules/computer_vision/opencv_example.cpp, sw/airborne/modules/computer_vision/opencv_image_functions.cpp, sw/airborne/modules/computer_vision/opencv_image_functions.h
First tests show that the image conversions are now 2 to 4 times faster!
=> [Opencv]sped up the image conversions

sw/airborne/boards/bebop.h
Found in the datasheet to what values you can set the output scaler. Decided to type this in our code.
=> [Bebop]cam documentation

sw/airborne/subsystems/datalink/superbitrf.c
This code is never executed - @fvantienen do you have any more insight in this?
=> [superbitrf] Removed unused code

sw/ground_segment/cockpit/live.ml
only triggered when close enough but not too much, and flying a long segment
fix #1833
=> [gcs] prevent speech spam with 'approaching'

conf/joystick/n64_gamepad.xml, conf/joystick/nes_gamepad.xml, conf/joystick/snes_gamepad.xml
Game pad/joystick configurations for use in NAV/GUIDED modes:
- NES 
- SNES
- N64
=> Seed NES, SNES, and N64 game pad configurations

conf/airframes/TUDELFT/tudelft_bebop_indi.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h
the vertical acceleration is now also controlled, which requires one parameter: the relation between thrust command and specific thrust delivered. Also, this PR brings some code clean-up and more comments.
=> added vertical axis to indi guidance and cleanup

sw/airborne/modules/nav/nav_heli_spinup.c
=> heli spinup sets commands instead of angles

conf/modules/imu_aspirin_v2_common.xml, conf/modules/imu_lisa_s_v1.0.xml
this was produce a strange side effect on bluegiga module (#1835)
=> [fix] remove unused i2c dev from aspirin_2 and lisa_s conf

sw/airborne/subsystems/imu/imu_bebop.c
We are now sure that the magnetometer on bebop2 is on the gps board, which is angled. This compensates for the rotation. Needs flight testing.
=> [Fix} The magnetometer of the Bebop2 is angled

sw/airborne/modules/optical_flow/px4flow.c, sw/airborne/subsystems/abi_sender_ids.h
Should make it possible to use the px4flow sonar sensor for altitude hold...
=> [modules] px4flow: also send AGL message with ground distance from sonar

sw/airborne/arch/chibios/mcu_periph/i2c_arch.c
This should be backported to stable as it fix the handling timeout and avoid staying in locked state.
=> I2c fix for ChibiOS arch

conf/Makefile.nps, conf/firmwares/subsystems/shared/nps.makefile, sw/simulator/nps/nps_main.h, sw/simulator/nps/nps_main_common.c, sw/simulator/nps/nps_main_hitl.c, sw/simulator/nps/nps_main_sitl.c
@hooperfly can you please test this? This should fix the issue...
=> Fix NPS compilation on Mac OS

sw/tools/sbus_fakerator/README.md, sw/tools/sbus_fakerator/lib/__init__.py, sw/tools/sbus_fakerator/lib/channel.py, sw/tools/sbus_fakerator/lib/controller.py, sw/tools/sbus_fakerator/lib/sbus.py, sw/tools/sbus_fakerator/main.py, sw/tools/sbus_fakerator/sbus_fakerator
=> Added sbus fakerator for simulating SBUS transmitters on your laptop.

conf/modules/imu_px4fmu_v2.4.xml, sw/lib/ocaml/gen_common.ml
@fvantienen @dewagter I found an error based on the the compilation error of your px4-based airframes. Could you test these changes to see if it is correct ? Thanks.
=> Fix module parsing

conf/flight_plans/flight_plan.dtd, sw/tools/generators/gen_flight_plan.ml
this can help for issues like #1882
=> [flightplan] add pre and post calls at stage level

sw/airborne/arch/chibios/mcu_periph/adc_arch.c, sw/airborne/arch/lpc21/mcu_periph/adc_arch.c, sw/airborne/arch/stm32/mcu_periph/adc_arch.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_hybrid.c, sw/airborne/modules/display/max7456.c, sw/airborne/modules/hott/hott_eam.h
See https://scan.coverity.com/projects/paparazzi-paparazzi for details of the defects. 
Mostly out-of-bounds access
=> Coverity fixes from the latest build

.packages, paparazzi_pkgman.py
store where files are copy-pasted from so they can benefit from downstream and update upstream
=> [pkg_man] mini package manager

start.py
To make it's existence visible.
=> [pprzcenter] added a checkbox to launch the new python gui

sw/airborne/firmwares/rotorcraft/guidance/guidance_v_adapt.c
=> Use nominal throttle value is available

sw/airborne/modules/computer_vision/lib/vision/image.c, sw/airborne/modules/computer_vision/lib/vision/image.h
Example use case; with gate detection the color could indicate the detection quality.
=> [image] added a function to draw a line in any color

conf/airframes/TUDELFT/tudelft_bebop_autonomous_race.xml, conf/airframes/TUDELFT/tudelft_bebop_opticflow.xml, conf/modules/imu_bebop.xml, conf/modules/sonar_bebop.xml, sw/airborne/modules/sonar/sonar_bebop.c
unifies functionality with ARDrone. Addresses #1781
=> autoload bebop sonar, thread only started if USE_SONAR defined

conf/modules/video_capture.xml, sw/airborne/modules/computer_vision/video_capture.c
This PR recovers the video_exif functionality that was left out in the computer vision pipeline update.
=> [video_capture] recovered saving of exif information

conf/airframes/TUDELFT/tudelft_outback.xml, conf/gcs/bottom_settings.xml, sw/airborne/modules/nav/nav_heli_spinup.c, sw/airborne/subsystems/intermcu.h
re-integrate developments of MavLab outback.
=> [conf] outback airframe and gcs settings

sw/lib/ocaml/fp_proc.ml
`path` was not expended in for and while loops
=> [flightplan] fix gen_fp when 'path' is used in a loops

sw/airborne/modules/computer_vision/blob/blob_finder.h, sw/airborne/modules/computer_vision/blob/imavmarker.h
In order to fix issue #1944 I included ifndef in the header file. I also did this for another file.
=> Fixed two .h files without ifndef 

sw/ground_segment/python/gvf/gvfframe.py
I have found a bug in my python App for monitoring the GVF status of the chosen aircraft. 
The App processed all the received msgs from all the aircraft, now it only process (and displays) the msgs from the chosen ac_id. 
The rest of the changes are just the needed indentation because of the new 'if' line.
=> now we process only the msgs from the ac_id aircraft

conf/modules/ahrs_vectornav.xml, sw/airborne/peripherals/vn200_serial.c, sw/airborne/peripherals/vn200_serial.h, sw/airborne/subsystems/abi_sender_ids.h, sw/airborne/subsystems/ahrs/ahrs_vectornav.c, sw/airborne/subsystems/ahrs/ahrs_vectornav.h, sw/airborne/subsystems/ahrs/ahrs_vectornav_wrapper.c, sw/airborne/subsystems/ahrs/ahrs_vectornav_wrapper.h, sw/airborne/subsystems/ins/ins_vectornav.c, sw/airborne/subsystems/ins/ins_vectornav.h
Use Vectornav as either INS (as before) or AHRS (for example for indoor applications)
=> Vectornav as AHRS

sw/airborne/subsystems/ins/ins_int.c
The barometer measures the altitude, but it is used in the NED based vertical filter. 
Will soon test if it gives the correct altitude after driving ~10km
=> Compensate baro for reference frame conversion

conf/boards/px4fmu_2.4.makefile, sw/airborne/boards/px4io_2.4.h, sw/airborne/firmwares/rotorcraft/main_fbw.c, sw/airborne/modules/px4_flash/px4_flash.c, sw/airborne/subsystems/intermcu/intermcu_fbw.c, sw/tools/calibration/calibrate.py
- fix KILL_SWITCH channel name
- give priority to KILL_SWITCH over AUX1
- add missing comments for forceprog option
- swap radio_control power logic (spektrum port)
- add comment for modem port
- auto threshold for mag calibration
=> Fix some stuff for px4 and intermcu

conf/airframes/TUDELFT/tudelft_conf.xml, conf/airframes/TUDELFT/tudelft_iris_indi.xml, conf/flight_plans/TUDELFT/tudelft_delft_basic.xml
Configuration changes which are necessary to make the Pixhawk based Iris fly autonomous outdoor. This was tested with the tudelft_delft_basic flightplan.
However, I noticed no safety features were implemented in the standard flight plan, so I took this opportunity to add those.
=> Iris autonomous outdoor

sw/airborne/firmwares/rotorcraft/guidance/guidance_hybrid.c, sw/airborne/firmwares/rotorcraft/navigation.c, sw/airborne/firmwares/rotorcraft/navigation.h
set heading towards waypoint while flying a line in rotorcraft & call failsafe from flightplan
=> [nav] goto waypoint with heading towards the waypoint

sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c
Only run adaptive throttle estimation if we are in flight and
the desired vertical velocity (zd) was updated (i.e. we ran hover_loop before).
This means that the estimation is not updated when using direct throttle commands.
This should fix #1857
=> only run adaptive throttle estimation if desired zd was updated

conf/airframes/AGGIEAIR/aggieair_ark_quad_lisa_mx.xml, conf/airframes/AGGIEAIR/aggieair_conf.xml, conf/airframes/AGGIEAIR/aggieair_rp3_lia.xml, conf/modules/battery_monitor.xml, sw/airborne/modules/adcs/battery_monitor.c, sw/airborne/modules/adcs/battery_monitor.h, sw/airborne/modules/lidar/lidar_lite.c, sw/airborne/modules/lidar/lidar_sf11.c, sw/airborne/subsystems/electrical.c
=> Battery Monitor

conf/modules/nps.xml, conf/modules/sim.xml, conf/modules/telemetry_ivy.xml, conf/modules/telemetry_sim.xml
Preparing simulator modules. The existing makefiles are kept for now.
=> [modules] simulator modules (SIM and NPS)

conf/airframes/TUDELFT/tudelft_bebop_indi.xml, sw/logalizer/matlab/control_effectiveness_estimation.m
For indi_simple, with an example file logger
=> script for offline estimation of INDI parameters

conf/airframes/TUDELFT/tudelft_bebop_indi_actuators.xml, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
Now you can add dynamics for servos next to the first order dynamics of
motors. Also, you can give a rate limit in PPRZ/loop units
=> [INDI] support for servos

conf/modules/servo_tester.xml, sw/airborne/modules/servo_tester/servo_tester.c, sw/airborne/modules/servo_tester/servo_tester.h
useful for identifying the response of a servo
=> Module with servo tester function

conf/modules/stabilization_float_euler.xml, sw/airborne/subsystems/ahrs/ahrs_vectornav.c, sw/airborne/subsystems/ahrs/ahrs_vectornav_wrapper.c, sw/airborne/subsystems/ahrs/ahrs_vectornav_wrapper.h
- plus a minor fix on float_euler settings (bigger range for gains)
=> [ahrs[ Vectornav fix

sw/airborne/modules/mission/mission_common.c, sw/airborne/modules/mission/mission_common.h
Adds ReplaceNexts insertion mode
Fixes issue #2014
=> [mission] Adds insertion mode.

sw/airborne/firmwares/rotorcraft/autopilot_arming_switch.h, sw/airborne/firmwares/rotorcraft/autopilot_arming_throttle.h
Some variables were left unchanged in in the autopilot refactor.
=> [autopilot] fix autopilot motor on var for arming on switch & throttle

sw/tools/calibration/calibrate_mag_current.py, sw/tools/calibration/calibration_utils.py
show a plot of the fit, such that the user can see anomalies and see the significance
=> Visualization of mag_current calib result

sw/tools/parrot/bebop.py
Allows for date/time labelled log files etc.
=> [bebop] Setting time when uploading ap.elf

conf/modules/logger_sd_chibios.xml, conf/telemetry/fixedwing_flight_recorder.xml, sw/airborne/arch/chibios/mcu_periph/ram_arch.h, sw/airborne/boards/apogee/chibios/v1.0/ffconf.h, sw/airborne/boards/apogee/chibios/v1.0/mcuconf.h, sw/airborne/boards/chimera/chibios/v1.0/ffconf.h, sw/airborne/boards/chimera/chibios/v1.0/mcuconf.h, sw/airborne/boards/px4fmu/chibios/v2.4/ffconf.h, sw/airborne/boards/px4fmu/chibios/v2.4/mcuconf.h, sw/airborne/modules/loggers/sdlog_chibios.c, sw/airborne/modules/loggers/sdlog_chibios.h, sw/airborne/modules/loggers/sdlog_chibios/msg_queue.c, sw/airborne/modules/loggers/sdlog_chibios/sdLog.c, sw/airborne/modules/loggers/sdlog_chibios/sdLog.h, sw/airborne/modules/loggers/sdlog_chibios/usbStorage.c, sw/airborne/modules/loggers/sdlog_chibios/usb_msd.c, sw/airborne/modules/loggers/sdlog_chibios/usb_msd.h, sw/ext/tlsf/tlsf.c
- fix several small bugs
- update to fatfs 0.12b
- add status report
This new library should be much more robust. It has been tested up to 1Mo/s on F4 and almost 2Mo/s on F7.
=> [sdlog] update sdlog for chibios

conf/airframes/AGGIEAIR/aggieair_conf.xml, conf/airframes/AGGIEAIR/aggieair_ecu_example.xml, conf/conf_tests.xml, conf/firmwares/subsystems/shared/baro_board.makefile, conf/modules/vms_ecu_demo.xml, sw/airborne/boards/vms_ecu/chibios/v1.0/board.h, sw/airborne/modules/fsae_electric/vms_ecu_demo.c, sw/airborne/modules/fsae_electric/vms_ecu_demo.h
Adds a simple test module, fixes on SPI bus (IMU)
Adds VMS_ECU into conf_tests.xml
see https://wiki.paparazziuav.org/wiki/VMS_ECU for details about the board
=> [vms_ecu] Updated board config and added test module

conf/airframes/max/microjet_lisa_m.xml, conf/modules/radio_control_hott.xml, sw/airborne/subsystems/radio_control/hott.c, sw/airborne/subsystems/radio_control/hott.h, sw/airborne/subsystems/radio_control/hott_common.c, sw/airborne/subsystems/radio_control/hott_common.h
Added Graupner HOTT SUMD serial rc control protocol. 
I used the sbus implementation as base for the hott sumd input. 
Tested with lisa m 2.0 uart1 and Graupner GR-12L with 9 and 12 channels. 
Should work with 2 to 32 channels.
and example airframe config.
=> added hott sumd radio control input

conf/airframes/TUDELFT/tudelft_bebop_indi_actuators.xml, conf/simulator/jsbsim/aircraft/bebop.xml, sw/simulator/nps/nps_autopilot_rotorcraft.c
I made a simulation file for the bebop1, that takes into account actuator dynamics. It also adds a a spinup torque for the rotors. I think the inertia should be roughly ok. Since I am using the actuators directly, bypassing the motor_mixing, I had to change the nps a bit.
I looked into simulating an electric engine with a propeller, but there are many parameters which I would have to reverse engineer, so it did not seem worthwhile. And then I am still not sure if I can get out of JSBsim the same behaviour as what I get from test flights, given the architecture of JSBsim.
=> simulation of bebop1

conf/modules/extra_dl.xml, sw/airborne/arch/sim/sim_ap.c, sw/airborne/modules/datalink/bluegiga_dl.c, sw/airborne/modules/datalink/extra_pprz_dl.c, sw/airborne/modules/datalink/extra_pprz_dl.h, sw/airborne/modules/datalink/pprz_dl.c, sw/airborne/modules/datalink/xbee_dl.c, sw/airborne/modules/nav/nav_geofence.h, sw/airborne/subsystems/datalink/datalink.h, sw/airborne/subsystems/datalink/superbitrf.c, sw/airborne/subsystems/datalink/w5100.h
=> [extra_dl] Extend module functionality

Makefile, conf/conf_tests.xml
Added a test for aggie_air conf. It really helps me with development, and it does't hurt anyone.
Indeed, if each developer has their own conf test it would be probably too much, but I don't think that is likely to happen.
=> Added test for aggieair config

conf/airframes/TUDELFT/tudelft_bebop2_opticflow.xml, conf/airframes/TUDELFT/tudelft_guido_conf.xml, conf/flight_plans/rotorcraft_guido_optitrack.xml, conf/modules/optical_flow_landing.xml, conf/telemetry/default_rotorcraft.xml, sw/airborne/modules/ctrl/optical_flow_landing.c, sw/airborne/modules/ctrl/optical_flow_landing.h
I implemented the exponentially decreasing gain strategy for optical flow landing that we describe in:
H.W. Ho, G.C.H.E. de Croon, E. van Kampen, Q.P. Chu, and M. Mulder (submitted)
Adaptive Control Strategy for Constant Optical Flow Divergence Landing,
<https://arxiv.org/abs/1609.06767>
I also rewrote the module to replace duplicate parts of code with function calls, hopefully considerably improving the readability and expandability of the module. I tested all the functionalities in the TU Delft Cyberzoo this morning on a Bebop 2.
=> Exponential gain landing pull request

conf/airframes/AGGIEAIR/El_Captain.xml, conf/airframes/AGGIEAIR/aggieair_ark_hexa_1-8.xml, conf/airframes/AGGIEAIR/aggieair_blujay_goose.xml, conf/airframes/AGGIEAIR/aggieair_conf.xml, conf/airframes/AGGIEAIR/aggieair_control_panel.xml, conf/airframes/AGGIEAIR/aggieair_minion_rp3_lia.xml, conf/flight_plans/AGGIEAIR/BasicTuning_Launcher.xml, conf/flight_plans/AGGIEAIR/CachJct_Gallo_temp_rect_survey.xml, conf/gcs/AGGIEAIR/CSOIS_flyingwings.xml, conf/gcs/AGGIEAIR/CSOIS_minions.xml, conf/gcs/AGGIEAIR/CSOIS_minions_osu.xml, conf/gcs/AGGIEAIR/vertical.xml, conf/modules/AOA_adc.xml, conf/modules/radio_control_ppm.xml, conf/modules/telemetry_transparent_usb.xml, conf/modules/telemetry_xbee_api.xml, conf/radios/AGGIEAIR/AggieAir_Specktrum_PPM_MeekPE.xml, conf/radios/AGGIEAIR/aggieair_taranis.xml, conf/telemetry/AGGIEAIR/aggieair_rotorcraft.xml, sw/airborne/arch/lpc21/mcu_periph/adc_arch.c
Added new airplane configs (including an example of Umarim board in HITL configuration).
Added some more AggieAir GCS layouts, radios, flight plans.
Minor compilation fixes (not affecting the rest of the system).
=> Aggieair changes

conf/airframes/HOOPERFLY/hooperfly_conf.xml, conf/airframes/HOOPERFLY/hooperfly_dot_bashrc, conf/airframes/HOOPERFLY/hooperfly_racerpex_quad_elle0_v1_2.xml, conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2.xml, conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2_212.xml, conf/airframes/HOOPERFLY/hooperfly_teensyfly_quad_elle0_v1_2_213.xml
- Update the ACCEL, MAG, MAG_CURRENT values for the following aircraft id: 212, 213, and 223
- Update configuration files with new aircraft definitions.
=> Calibration updates for new airframes

sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c, sw/airborne/modules/stereocam/stereocam.h, sw/airborne/subsystems/imu/imu_ardrone2.h, sw/tools/parrot/parrot_utils.py
As the name suggests this is a small collection of random uncorrelated fixes that we made during the IMAV.
guidance_v.c - required for auto take-off in guided mode
The rest are just typo's in previous commits...
=> uncorrelated small fixes

conf/airframes/AGGIEAIR/aggieair_iris_indi.xml, conf/airframes/OPENUAS/openuas_eflite_t28.xml, conf/airframes/OPENUAS/openuas_eflite_umx_sbach_342.xml, conf/airframes/OPENUAS/openuas_vivify.xml, conf/airframes/TUDELFT/tudelft_iris_indi.xml, conf/airframes/TUDELFT/tudelft_robird.xml, conf/airframes/TUDELFT/tudelft_splash.xml, conf/airframes/TUDELFT/tudelft_xvert.xml
<?xml version="1.0" encoding="UTF-8"?> should either be first thing in the file or not present
open -> close comments
=> [airframe] XML errors

conf/airframes/TUDELFT/tudelft_aa_quadplane.xml, conf/airframes/TUDELFT/tudelft_conf.xml
=> [conf] QuadPlane

conf/airframes/TUDELFT/tudelft_conf.xml, conf/airframes/TUDELFT/tudelft_fan_demo.xml, conf/flight_plans/TUDELFT/fan_demo.xml, conf/modules/guidance_indi.xml, conf/modules/stabilization_indi.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h
I added two settings for guidance_indi, and noticed that all attitude indi settings were 'persistent'. I heard from Kirk and Matej that they had trouble with persistent stuff in the past, so I removed that.
Also added an airframe and a flight plan for a 'fan demo', where a bebop flies in front of a fan to show off the INDI guidance. Test flown and works
=> INDI settings and fan demo

sw/airborne/filters/high_pass_filter.h, sw/airborne/math/pprz_algebra_float.c, sw/airborne/math/pprz_algebra_float.h, tests/math/test_pprz_math.c
The high pass filter uses doubles to avoid numerical errors.
This is some of the code I use for the Cyclone, planning to merge all of it piece by piece like this.
The 2D matrix stuff I actually don't use for the Cyclone at this point, but I thought it could be useful in the future.
=> math functions and high pass filter

sw/tools/parrot/bebop/wifi_tools/pprz.conf, sw/tools/parrot/bebop/wifi_tools/remove4press.sh, sw/tools/parrot/bebop/wifi_tools/scripts/pprz.conf
Removed pprz.conf files from bebop wifi tools as they are not necessary. pprz_swarmhub.conf can be used instead
=> removed unnecessary pprz.conf files

README.md
=> some improvements of the README

sw/airborne/math/pprz_algebra_float.c, sw/airborne/math/pprz_algebra_float.h
Added a function to invert any matrix and a function to create an identity matrix.
=> pprz_algebra_float.h new functions

sw/airborne/math/pprz_algebra_int.h
Added a function to cast a value to an array of integers (so that it may be initialized as desired with one command), and a function to find a specific value within the array.
These functions will be used in later pull requests in order to store aircraft IDs and determine if they are new or not during relative localization and avoidance, but are general enough to be put in pprz_algebra_int.h.
=> Pullrequest pprz math array operations

Makefile, sw/airborne/arch/sim/mcu_periph/i2c_arch.c, sw/airborne/firmwares/fixedwing/main_fbw.c, sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c, sw/simulator/nps/nps_ins_vectornav.c
Could not solve: https://github.com/paparazzi/paparazzi/issues/2182
=> [warnings] Fix warnings

sw/ground_segment/python/gvf/gvfFormation.py
For big numbers where everything is in meters the script works. However, for different units where decimals are required, the algorithm might not work. Now it should be ok.
=> some ints should be floats

conf/airframes/HOOPERFLY/hooperfly_enac_hexa_elle0_v1_2.xml
ACCEL, MAG, and MAC_CURRENT updates for the ENAC Hexacopter. Calibrated in Portland, Oregon, USA.
=> Calibration updates for the ENAC hexacopter

conf/modules/gps_datalink.xml, sw/airborne/subsystems/gps/gps_datalink.c, sw/airborne/subsystems/gps/gps_datalink.h
position and velocity is received in local frame
transformation to global frame is handled on airborne side
=> [gps] add support for REMOTE_GPS_LOCAL

sw/airborne/modules/mission/mission_fw_nav.c
Should fix https://github.com/paparazzi/pprzlink/issues/63
=> fix MISSION_GOTO_WP_LLA lla alt unit error

conf/control_panel_example.xml, sw/ground_segment/misc/natnet2ivy.c, sw/ground_segment/python/natnet3.x/NatNetClient.py, sw/ground_segment/python/natnet3.x/natnet2ivy.py
The new version of the Optitrack software (Motive 2.0) comes with NatNet
version 3. A Python module is provided with NatNet for
serialization/deserialization of the data streamed over the network.
This module is slightly modified here for a better handling of the
initialization and for stopping the threads.
The PPRZLINK message sent is REMOTE_GPS_LOCAL, so the transformation to
global coordinate system is left to the airborne part.
=> [natnet] add a NatNet3 to IVY bridge in Python

conf/conf_tests.xml, conf/flight_plans/mission_fw.xml, sw/airborne/modules/mission/mission_fw_nav.c
- Fix in mission fw module (so it compiles)
- Add test for fixedwing mission fw module
- Better heading for simulation purposes
=> Fix mission fw module 

sw/supervision/python/hmi.py, sw/supervision/python/parser.py
Remove the recursivity in initialisation methods and only search for "conf/control_panel.xml" as control panel configuration file.
If this file is not present, an exception is raised.
=> Fix in python supervision (#2210)

sw/tools/qt_project.py, sw/tools/qtc.creator.user_template
Now you can directly upload from Qtc. Also, the wrong style template was selected overriding the indent size wrongly
=> Qtcreator indent size fix and added upload feature

conf/abi.xml, conf/modules/jevois.xml, conf/modules/object_tracking.xml, sw/airborne/modules/ctrl/object_tracking.c, sw/airborne/modules/ctrl/object_tracking.h, sw/airborne/modules/sensors/cameras/jevois.c, sw/airborne/modules/sensors/cameras/jevois.h, sw/airborne/subsystems/abi_sender_ids.h
Add a module to parse standardized messages from a JeVois smart camera (http://jevois.org).
It is also possible to change the running algorithm (mapping) and start/stop streaming.
A demo module is using the data to track an object or a face by controlling the heading of a rotorcraft. This demo could be improved in the future to replace the very basic control / heading estimation by a proper PID controller and/or target position estimator.
=> Jevois integration

sw/ground_segment/python/gvf/gvfframe.py
The gvfApp might not work properly with the former paths.
=> updated paths for python tools

sw/ground_segment/joystick/gb2ivy.py, sw/ground_segment/python/atc/atc_frame.py, sw/ground_segment/python/dashboard/radiowatchframe.py, sw/ground_segment/python/guided_mode_example.py, sw/ground_segment/python/messages_app/messagesframe.py, sw/ground_segment/python/move_waypoint_example.py, sw/ground_segment/python/natnet3.x/natnet2ivy.py, sw/ground_segment/python/payload_forward/payload_forward.py, sw/ground_segment/python/real_time_plot/messagepicker.py, sw/ground_segment/python/real_time_plot/plotpanel.py, sw/ground_segment/python/redundant_link/link_combiner.py, sw/ground_segment/python/svinfo/svinfoviewer.py, sw/simulator/mesonh/mesonh.py, sw/tools/calibration/calib_mag_live.py, sw/tools/rtp_viewer/rtp_viewer.py
update pprzlink lib and some python tools to use the version install in paparazzi `var` directory instead of the source files from submodule.
=> Pprzlink update

conf/airframes/AGGIEAIR/aggieair_ark_hexa_1-8.xml, conf/airframes/AGGIEAIR/aggieair_ark_quad_lisa_mx.xml, conf/airframes/AGGIEAIR/aggieair_atomic_lia.xml, conf/airframes/AGGIEAIR/aggieair_conf.xml, conf/airframes/AGGIEAIR/aggieair_control_panel.xml, conf/airframes/AGGIEAIR/aggieair_minion_rp3_lia.xml, conf/telemetry/AGGIEAIR/aggieair_fixedwing.xml, fix_code_style.sh, sw/airborne/modules/datalink/gec/gec.c, sw/airborne/modules/datalink/gec/gec.h, sw/airborne/modules/datalink/gec_dl.c, sw/airborne/modules/datalink/gec_dl.h
Allows secure link for pprzlink v1.0
=> Crypto updates

Makefile.ac
some ideas to avoid compile things when not necessary, especially when uploading
=> [build] try to improve dependency and not do unnecessary things

sw/ground_segment/cockpit/shapes.ml
=> [gcs] add shapes to the background layer to keep WP and A/C on top

.vscode/c_cpp_properties.json, .vscode/settings.json, conf/userconf/tudelft/conf.xml, sw/airborne/modules/helicopter/swashplate_mixing.c, sw/airborne/modules/sensors/mag_pitot_uart.c, sw/airborne/modules/telemetry/telemetry_intermcu.h, sw/airborne/modules/telemetry/telemetry_intermcu_ap.c, sw/airborne/modules/telemetry/telemetry_intermcu_fbw.c, sw/airborne/subsystems/intermcu/intermcu_ap.c, sw/airborne/subsystems/intermcu/intermcu_fbw.c
Update the interMCU and mag pitot modules to pprzlink v2.
Also added visual studio code project files.
=> Update modules to pprzlink 2

sw/airborne/firmwares/rotorcraft/autopilot_arming_yaw.h
Somehow the yaw to arm was broken, there was quite a bit of strange behavior.
With this, you give a side stick to arm the motors, this will start the motors at minimum speed. Your stick controls will not be fed through to the controller till you return the stick to the center. When disarming, you reduce the throttle to minimum and give full side stick till the motors stop. You first have to return the stick to center before you can re-arm.
I also add an explicit autopilot_set_in_flight(false) command when starting the motors. This is not strictly necessary since the in_flight check checks if the throttle is retarded but I think this is nice just in case the in_flight code is changed in the future.
=> [rotorcraft] update yaw to arm

sw/airborne/modules/loggers/file_logger.c
Will also attempt to make the requested directory if it doesn't already exist.
=> [logging] added ability to give linux file logger a datetime stamp name for convenience

sw/airborne/firmwares/rotorcraft/autopilot_arming_throttle.h
This should fix #2267. This fix has been tested.
=> fix throttle to arm

sw/ground_segment/python/fc_rotor/fc_rotor.py
It can be convenient for some tests in simulation to have this option (by default false).
=> ignore geo fence option

conf/airframes/AGGIEAIR/aggieair_atomic_lia.xml, conf/modules/copilot.xml, sw/airborne/modules/mission/copilot.h, sw/airborne/modules/mission/copilot_common.c
to the mission computer and back. Required for [Etherlink](https://github.com/paparazzi/etherlink) to work. I also ran the autoformat script on the c file.
=> Add copilot module support for forwarding payload commands

conf/modules/guidance_indi.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h
Make the max bank angle for INDI configurable.
=> [airborne] Guidance INDI add configurable maximum bank angle

sw/ground_segment/cockpit/gcs.ml, sw/ground_segment/cockpit/live.ml, sw/ground_segment/cockpit/live.mli, sw/lib/ocaml/mapCanvas.ml
This does work but it sometimes draws the waypoints and geofences on the top left corner of the map. 
@gautierhattenberger do you have any idea why this happens?
I guess it is some multi-threading issue, but my ocaml and GCS knowledge is not that great to solve it. Similar behaviour happens when continuously pressing 'ctrl+c' without this feature.
=> [gcs] Add auto center aircraft

conf/airframes/tudelft/bebop2_undistort_front.xml, conf/modules/cv_detect_gate.xml, conf/userconf/tudelft/conf.xml, sw/airborne/modules/computer_vision/detect_gate.c, sw/airborne/modules/computer_vision/detect_gate.h, sw/airborne/modules/computer_vision/lib/vision/image.c, sw/airborne/modules/computer_vision/lib/vision/image.h, sw/airborne/modules/computer_vision/snake_gate_detection.c, sw/airborne/modules/computer_vision/snake_gate_detection.h
This pull request is part of an effort to get all autonomous drone race code into the master of paparazzi, so that anyone can fly the code that we made for the IROS 2016 and 2017 autonomous drone races. The code allows a Parrot Bebop drone to detect racing gates and pass through a sequence of them at a reasonably high speed (1.8 m/s). 
This first pull request contains two things:
1. The snake gate detector code, which is a computationally efficient method to find (close-to) square gates in an image.
2. A cv_detect_gate module, which runs the snake gate detector, allows to tune the color filter parameters, and allows to play with various other parameters of the snake gate detection.
=> Snake gate detector

conf/airframes/ESDEN/esden_quady_ls10pwm.xml, conf/airframes/tudelft/bebop2_indi.xml, conf/airframes/tudelft/bebop_indi_actuators.xml, conf/airframes/tudelft/fan_demo.xml, conf/userconf/tudelft/conf.xml, docker/ci/Dockerfile, sw/airborne/arch/linux/mcu_periph/i2c_arch.c, sw/airborne/boards/xvert/chibios/v1.0/board.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_hybrid.c, sw/airborne/modules/computer_vision/cv_blob_locator.c, sw/airborne/modules/computer_vision/detect_window.c, sw/airborne/modules/computer_vision/lib/vision/act_fast.c, sw/airborne/modules/computer_vision/lib/vision/image.c, sw/airborne/modules/computer_vision/lib/vision/image.h, sw/airborne/modules/computer_vision/opticflow/opticflow_calculator.c, sw/airborne/modules/ctrl/ctrl_module_outerloop_demo.c, sw/airborne/modules/ins/xsens700.c, sw/airborne/modules/ins/xsens700.h, sw/airborne/modules/sonar/sonar_bebop.c, sw/airborne/modules/spektrum_soft_bind/spektrum_soft_bind_ap.c, sw/airborne/peripherals/mpu9250_spi.c, sw/airborne/subsystems/ins/ins_int.c, sw/simulator/nps/nps_autopilot_rotorcraft.c
this should fix most of the warnings and hopefully all the errors in the CI builds
=> global fix of current warnings and errors in CI server

sw/airborne/modules/sensors/cameras/jevois.c
fix some index error and compilation in sim
=> [jevois] fix standard message parser

conf/abi.xml, conf/telemetry/default_rotorcraft.xml, sw/airborne/modules/gumstix_interface/qr_code_spi_link.c, sw/airborne/modules/sensors/cameras/jevois_mavlink.c
Decodes and Pushes ABI messages for:
- Vision Position Estimation
- Visual Target Pixel Coordinates
- Manual RC Setpoint inputs
=> JeVois-Mavlink: push ABI messages on reception

conf/airframes/tudelft/bebop2_detect_gate_front.xml, conf/flight_plans/tudelft/rotorcraft_autonomous_drone_race.xml, conf/userconf/OPENUAS/openuas_conf.xml, conf/userconf/tudelft/conf.xml, sw/airborne/modules/computer_vision/detect_contour.c, sw/airborne/subsystems/actuators/actuators_asctec_v2_new.c, sw/airborne/subsystems/radio_control/spektrum.c
some extra errors and warnings from CI builds
=> [fix] some extra warning, error and failing conf fixed

conf/userconf/OPENUAS/openuas_conf.xml
Re-added airframe, compile in all its targets.  Weather permitting re-testfly in 3 days and update the Git object aka SHA
=> Added UMX Sbach342

sw/airborne/math/RANSAC.c, sw/airborne/math/pprz_matrix_decomp_float.c, sw/airborne/math/pprz_matrix_decomp_float.h
- safeguards for divide by zero
- silent compile warnings
- linear-fit with prior information
=> Linear-fit update

sw/simulator/nps/nps_main_hitl.c
=> Indicate when HITL is not getting AP data

conf/airframes/ENAC/fixed-wing/hawkeye.xml, conf/flight_plans/competitions/IMAV2018_carto.xml, conf/joystick/xbox_cx10_mission.xml, sw/airborne/modules/digital_cam/atmega_i2c_cam_ctrl.c, sw/airborne/modules/digital_cam/dc.c, sw/airborne/modules/digital_cam/dc.h, sw/airborne/modules/digital_cam/dc_ctrl_parrot_mykonos.c, sw/airborne/modules/digital_cam/gpio_cam_ctrl.c, sw/airborne/modules/digital_cam/servo_cam_ctrl.c, sw/airborne/modules/digital_cam/uart_cam_ctrl.c, sw/airborne/modules/digital_cam/video_cam_ctrl.c, sw/ground_segment/python/cx10ds/cx10ds.py, sw/ground_segment/python/cx10ds/cx10ds_ivy.py
add some elements of the Indoor and Outdoor IMAV Competition used by ENAC team
=> Imav2018 integration

sw/tools/generators/gen_aircraft.ml
=> [generator] warning when unit attribute is used in firmware section

conf/airframes/OPENUAS/openuas_vivify.xml, conf/airframes/tudelft/yapa_xsens.xml, conf/airframes/untested/easy_glider.xml, sw/airborne/arch/lpc21/subsystems/actuators/servos_4015_MAT_hw.h, sw/airborne/arch/lpc21/subsystems/actuators/servos_4015_hw.h, sw/airborne/arch/lpc21/subsystems/actuators/servos_4017_hw.h, sw/airborne/arch/lpc21/subsystems/actuators/servos_ppm_hw.h, sw/airborne/arch/sim/servos_nil.h, sw/airborne/firmwares/fixedwing/main_fbw.c, sw/airborne/subsystems/ahrs/ahrs_float_dcm.c, sw/include/std.h, sw/tools/generators/gen_airframe.ml
I noticed this define called Chop the other day and I think it should be called Clip. Clip is what you would conventionally call a function which bounds a value to a range (e.g. https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html). This should help people to find  and reuse this function in the future.
=> change Chop to Clip

sw/airborne/arch/linux/mcu_periph/spi_arch.c, sw/airborne/modules/sonar/sonar_bebop.c
This fixes a small issue with the linux arch spi. Should address #2378
=> [linux] fix linux spi_arch

sw/airborne/modules/computer_vision/lib/vision/act_fast.c
This should hopefully fix #2294
=> [cv] fix possible divide by zero

conf/modules/airspeed_sdp3x.xml, conf/modules/mag_lis3mdl.xml, sw/airborne/modules/sensors/airspeed_sdp3x.c, sw/airborne/modules/sensors/airspeed_sdp3x.h, sw/airborne/modules/sensors/mag_lis3mdl.c, sw/airborne/modules/sensors/mag_lis3mdl.h, sw/airborne/peripherals/lis3mdl.c, sw/airborne/peripherals/lis3mdl.h, sw/airborne/subsystems/abi_sender_ids.h
add two new sensors:
- lis3mdl magnetometer
- sdp3x differential pressure sensor
=> add new sensors

conf/airframes/tudelft/splash3.xml, conf/modules/lidar_tfmini.xml, conf/telemetry/default_rotorcraft.xml, conf/userconf/tudelft/conf.xml, sw/airborne/modules/lidar/tfmini.c, sw/airborne/modules/lidar/tfmini.h, sw/airborne/subsystems/abi_sender_ids.h
New TFMini lidar driver over UART.
=> [modules] Add TFMini lidar

conf/airframes/tudelft/bebop2_optitrack.xml, conf/flight_plans/tudelft/rotorcraft_optitrack_path.xml, conf/userconf/tudelft/conf.xml
Added an airframe + flight plan that flies a stable flight using Optitrack in a small space. Gains have been tuned to keep the maximum velocity capped (0.5m/s), no overshooting of waypoints (GUIDANCE_H_REF_ZETA=1), and only switch waypoints when 0.2m away from it.
=> Pullrequest bebop2 optitrack

conf/abi.xml, conf/flight_plans/joystick.xml, conf/flight_plans/rotorcraft_joystick_enac.xml, conf/modules/joystick.xml, conf/tools/matlab2pprz.xml, sw/airborne/firmwares/fixedwing/fixedwing_datalink.c, sw/airborne/firmwares/fixedwing/joystick.h, sw/airborne/modules/joystick/joystick.c, sw/airborne/modules/joystick/joystick.h, sw/airborne/subsystems/abi_sender_ids.h, sw/ground_segment/python/matlab2pprz/README.md, sw/ground_segment/python/matlab2pprz/matlab2pprz.py
Add a bridge between Natnet, Simulink and Paparazzi.
Also rewrite the JOYSTICK_RAW module.
Example of Simulink model: https://github.com/enacuavlab/vto-tools/tree/master/Matlab/Simulink
=> Matlab2pprz

sw/airborne/firmwares/rotorcraft/autopilot_arming_yaw.h
=> [airborne] Fix yaw arming

sw/airborne/modules/imu/filter_1euro_imu.c
make compilation without parameter possible
=> [filter] set default freq for 1euro filter

conf/flight_plans/basic.xml, sw/lib/ocaml/expr_lexer.mll, sw/lib/ocaml/expr_parser.mly
=> [ocaml] add special keyword to avoid conflict with XML invalid characters

conf/modules/board_tawaki.xml, conf/modules/logger_sd_chibios.xml, sw/airborne/boards/tawaki/chibios/v1.0/mcuconf.h
- Fix config for RTC on Tawaki board
- Fix small bug in chibios sd log module
- Update ChibiOS for latest bug fixes
=> fix Tawaki RTC

conf/airframes/ENAC/rover_ostrich.xml, conf/flight_plans/ENAC/dw1000_basic.xml, conf/flight_plans/rover_optitrack_PIR.xml, conf/modules/dw1000_arduino.xml, conf/modules/jevois.xml, conf/modules/shift_tracking.xml, conf/modules/telemetry_transparent.xml, conf/modules/telemetry_transparent_udp.xml, conf/modules/telemetry_transparent_usb.xml, conf/settings/estimation/ins_sonar.xml, conf/telemetry/default_rover.xml, sw/airborne/filters/pid.h, sw/airborne/modules/ctrl/shift_tracking.c, sw/airborne/modules/ctrl/shift_tracking.h, sw/airborne/modules/decawave/dw1000_arduino.c, sw/airborne/modules/decawave/dw1000_arduino.h, sw/airborne/modules/decawave/ekf_range.c, sw/airborne/modules/decawave/ekf_range.h, sw/airborne/modules/decawave/trilateration.c, sw/airborne/modules/decawave/trilateration.h, sw/airborne/modules/sensors/cameras/jevois.c, sw/airborne/modules/sensors/cameras/jevois.h, sw/airborne/subsystems/ins/ins_gps_passthrough.c
Several results coming from student projects at Enac:
- update and fix for the JeVois smart cam driver
- improvement of the UWB-based localization, either with local or global positioning
- trajectory tracking based on shift around a reference
- some small corrections here and there
=> Enac student projects integration

conf/modules/cv_target_localization.xml, sw/airborne/modules/computer_vision/cv_target_localization.c, sw/airborne/modules/computer_vision/cv_target_localization.h
Provide the position of a target on a flat ground based on detection
from a camera (VISUAL_DETECTION ABI message) and the current position
and orientation of the vehicle.
Developed and used during IMAV2019 competition.
=> [module] add target_localization module

sw/airborne/modules/nav/takeoff_detect.c, sw/ground_segment/misc/rtcm2ivy.c, sw/lib/python/pprz_connect.py, sw/simulator/nps/nps_ivy.c
A collection of bugs found during IMAV preparation
=> Bug fix imav2019

conf/airframes/BR/3DplaneLisaS.xml, conf/airframes/tudelft/bebop_indi.xml, conf/airframes/tudelft/bebop_opticflow_indoor.xml, conf/airframes/tudelft/bebop_optitrack.xml, conf/airframes/tudelft/xvert.xml, sw/airborne/boards/disco.h, sw/airborne/link_mcu_can.c, sw/airborne/modules/lidar/tfmini.c, sw/airborne/subsystems/imu.h
A collection of small fix that should solve most of the errors from semaphore builds (night builds)
=> Fix semaphore

Makefile, sw/lib/ocaml/Makefile
=> [build] fix build dep for tools

conf/Makefile.chibios, conf/settings/power_switch.xml, sw/airborne/boards/apogee/chibios/v1.0/board.h, sw/airborne/subsystems/navigation/common_nav.c, sw/airborne/subsystems/navigation/common_nav.h, sw/ground_segment/cockpit/page_settings.ml
A collection of small features:
- power switch config and setting
- gcs tooltip
- pprzlink unaligned access for chibios
- estimated time to home in fixedwing nav
=> Small features

conf/modules/flight_recorder.xml, conf/modules/ins_ekf2.xml, sw/airborne/modules/loggers/sdlog_chibios.c, sw/airborne/modules/loggers/sdlog_chibios/sdLog.c, sw/airborne/modules/loggers/sdlog_chibios/sdLog.h, sw/airborne/subsystems/ins/ins_ekf2.cpp, sw/airborne/subsystems/ins/ins_ekf2.h
This needs https://github.com/paparazzi/pprzlink/pull/105
=> [ekf2][sdlog] Add more ekf2 debugging information and magneto setting and add sdlogger filename

conf/modules/gps.xml, conf/modules/gps_ublox.xml, conf/ubx.xml, sw/airborne/modules/gps/gps_ubx_ucenter.c, sw/airborne/subsystems/gps.c, sw/airborne/subsystems/gps.h, sw/airborne/subsystems/gps/gps_ubx.c, sw/airborne/subsystems/gps/gps_ubx.h, sw/airborne/subsystems/intermcu/intermcu_fbw.c
PVT is a useful compact and complete message available since Ublox 8. It can eventually replace all other messages for fixedwing, and need extra lla to ecef for rotorcraft.
I don't have GPS module to test it right now, so any help here is welcome :)
=> [gps] add support for UBX PVT message

sw/airborne/subsystems/abi_sender_ids.h
Forgot to add ABI id for the IST8310 magnetometer.
=> [mag] Add IST8310 ABI id

start.py, sw/tools/airframe_editor/airframe_editor.py, sw/tools/airframe_editor/gui_dialogs.py, sw/tools/airframe_editor/xml_airframe.py
Finally trying to fix #2384 before Ubuntu 20.04.
Need to check if it still works on previous ubuntu versions.
start.py have weird behavior when resized, but otherwise seems to work well.
=> #2384, Convert some scripts to Gtk3.0.

conf/boards/beagle_bone_black.makefile, conf/modules/nav_survey_poly_rotorcraft.xml, sw/airborne/arch/lpc21/mcu_periph/gpio_arch.h, sw/airborne/arch/sim/mcu_periph/gpio_arch.h, sw/airborne/mcu_periph/softi2c.c, sw/airborne/modules/sonar/sonar_bebop.c
Fix a collection of bugs and warnings from the complete CI test of Semaphore
- remove extra sweep var
- fix bebop sonar in sim
- remove softi2c warnings
- remove beagle bone black warnings
=> Fix ci builds

conf/userconf/tudelft/course2019_control_panel.xml, sw/ground_segment/python/distance_counter/dist.py, sw/ground_segment/python/distance_counter/distance_counter.py
- controlpanel entry (https://github.com/tudelft/paparazzi/pull/58)
- time counter with buttons (https://github.com/tudelft/paparazzi/pull/59)
- python Images/PIL fix
=> [ground] Distance measuring during flight, Ubuntu18.04 update + time

conf/airframes/examples/bebop2_indi.xml, conf/flight_plans/tudelft/delft_bebop.xml, conf/userconf/tudelft/conf.xml
Just some configuration updates and a tag for the last flight test with a bebop2 in the tudelft conf.
=> Bebop2 flight delft

sw/airborne/boards/lisa_mx/chibios/v2.1/mcuconf.h
=> [chibios] Enable PWM Driver 4 when using SERVO 7AND8 on LISA-MX

conf/modules/servo_tester.xml, sw/airborne/modules/servo_tester/servo_tester.c, sw/airborne/modules/servo_tester/servo_tester.h
=> [module] servo_tester update: automatic sweep option

conf/modules/ctrl_windtunnel.xml, sw/airborne/modules/ctrl/ctrl_windtunnel.c, sw/airborne/modules/ctrl/ctrl_windtunnel.h
Simple module for controlling and logging windtunnel measurements for our hybrid plane.
=> [module] Controller for in the windtunnel to perform step inputs

sw/airborne/mcu_periph/softi2c.c
Fixed an error in the softi2c state machine that marked transactions as success/failed before the stop bit was sent, causing potential deadlocks when softi2c blocking functions are called in a tight loop. (e.g. VL53L1X_SensorInit)
=> FIX SoftI2C marking transaction complete before stop bit

conf/airframes/AGGIEAIR/aggieair_iris_indi.xml, conf/airframes/BR/quadshot_asp21_FutabaPPMonUart1.xml, conf/airframes/ENAC/quadrotor/ard2_base_digit.xml, conf/airframes/ENAC/quadrotor/ard2_base_vision.xml, conf/airframes/ENAC/quadrotor/ard2_basic.xml, conf/airframes/ENAC/quadrotor/ard2_basic_adhoc.xml, conf/airframes/ENAC/quadrotor/booz2_g1.xml, conf/airframes/OPENUAS/openuas_eflite_t28.xml, conf/airframes/OPENUAS/openuas_vivify.xml, conf/airframes/tudelft/iris_indi.xml, conf/airframes/tudelft/mentor.xml, conf/airframes/tudelft/robird.xml
mostly by moving modules from 'modules' to 'firmware' section, which
should be done in all airframe files now.
=> [conf] cleaning some airframe files for CI builds

sw/ground_segment/python/bitcraze/crazyradio2ivy.py, sw/ground_segment/python/guided_mode_example.py, sw/lib/python/pprz_connect.py, sw/simulator/mesonh/mesonh.py
xref paparazzi/pprzlink#117, [this comment](https://github.com/paparazzi/pprzlink/pull/117#issuecomment-653585123)
=> Added try...except to be more safe after pprzlink api changes. 

conf/airframes/ENAC/rover.xml
The guy in my lab who is learning for writing a simulator for the rover/boats caught this typo :)
=> unit instead of value

sw/ground_segment/tmtc/server.ml, sw/lib/ocaml/aircraft.ml
It is currently crashing the server when there is an error in the conf files.
The error reports are also better and cover all the elements of the conf.
=> [fix] handle more exceptions when parsing conf

conf/modules/stabilization_indi.xml, conf/modules/stabilization_indi_simple.xml, conf/modules/stabilization_rate_indi.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.h, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.h, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_rate_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_rate_indi.h
Rohan, one of our students, would like to pass a rate reference to the INDI controller from a module.
=> Indi rate interface

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c, sw/airborne/modules/ctrl/ctrl_effectiveness_scheduling.c
It seems that after #2568 I forgot to change some names
=> [FIX] Forgot to change name to indi_gains

conf/airframes/OPENUAS/openuas_multiplex_minimag.xml, conf/modules/sonar_pwm.xml, conf/userconf/OPENUAS/openuas_conf.xml, sw/airborne/boards/px4fmu_4.0.h, sw/airborne/modules/sonar/sonar_pwm.c, sw/airborne/modules/sonar/sonar_pwm.h, sw/airborne/subsystems/abi_sender_ids.h
Before the PR ;)
After the PR a sensor for ranging with IO is PWM
=> Add sensor for ranging where IO is PWM

.gitignore, conf/tools/fc_rotor.xml, sw/airborne/arch/sim/modules/actuators/actuators_dshot_arch.c, sw/airborne/arch/sim/modules/actuators/actuators_dshot_arch.h, sw/airborne/modules/multi/fc_rotor/fc_rotor.c, sw/airborne/modules/multi/traffic_info.c, sw/ground_segment/python/multi/fc_rotor/fc_rotor.py, sw/ground_segment/python/multi/fc_rotor/lib_rigid_formations.py, sw/ground_segment/python/natnet3.x/natnet2ivy.py, sw/ground_segment/tmtc/server.ml, sw/lib/ocaml/aircraft.ml
A collection of small fix:
- catch possible exception in server
- fix scaling in traffic info
- fix time scaling in natnet3
- add actuator dummy file for dshot in simulation
=> Fix various

sw/tools/generators/gen_periodic.ml
also increment properly process id
related to #2501
=> [generator] generate the number of telemetry processes

sw/ground_segment/python/gvf/gvfApp.py, sw/ground_segment/python/gvf/gvfframe.py
Now the gvfApp can run in Ubuntu 20.04 with the default installation of Python3.
=> gvf and python3 ubuntu 20.04

start.py
Replace python2 by python3 in start script to make it works out of the box on Ubuntu 20.04.
Seems to also work out of the box on Ubuntu 18.04.
=> [Start script] Use Python3.

Makefile
- update pprzlink to fix bug for the number of parameters in callback https://github.com/paparazzi/pprzlink/pull/127
- also split pprzlink makefile rules for update and install (it allows to install the libraries with local changes)
=> [pprzlink] fix bug in request message callback

sw/airborne/arch/stm32/subsystems/radio_control/ppm_arch.c
=> [stm32] add support of TIM9 and TIM12 for PPM input

sw/lib/python/flight_plan.py, sw/lib/python/settings.py, sw/lib/python/xml_utils.py
A python library for settings and flight plans. (because sometimes I feel I write the same code over and over)
There was an old library, this new one use pprzlink and is meant to be used in conjunction with pprz_connect.
Suggestions (or PR) to improve it are welcomed.
=> [Python libs] Start python settings and flight plan libs.

conf/airframes/ENAC/quadrotor/bebop2_fish.xml, conf/airframes/ENAC/quadrotor/bebop2_fish_outdoor.xml, conf/flight_plans/ENAC/fish_outdoor.xml, conf/flight_plans/ENAC/fish_voliere.xml, conf/modules/nav_fish.xml, sw/airborne/modules/nav/nav_fish.c, sw/airborne/modules/nav/nav_fish.h
based on the preliminary work of an internship
integrate a bio-inspired navigation based on the behavior of fish
require the message from https://github.com/paparazzi/pprzlink/pull/130
=> [nav] bio-inspired navigation module

conf/modules/nav_cube.xml, sw/airborne/modules/nav/nav_cube.h
I have fixed the building of nav_cube for fixed wings. This is in reference to issue #2608
=> Fixed nav_cube build processes

conf/modules/gps_sirf.xml, conf/modules/sys_time.xml
Just 2 small typo I noticed in the modules.
=> Fix small XML typo.

sw/ground_segment/tmtc/server.ml
Makes the server forget about an aircraft on AIRCRAFT_DIE message.
=> [server] Remove aircraft on AIRCRAFT_DIE message.

conf/boards/tawaki_common.makefile, sw/airborne/arch/chibios/mcu_periph/hal_stm32_dma.c, sw/airborne/arch/chibios/mcu_periph/hal_stm32_dma.h, sw/airborne/arch/chibios/modules/actuators/actuators_dshot_arch.c, sw/airborne/arch/chibios/modules/actuators/esc_dshot.c, sw/airborne/arch/chibios/modules/actuators/esc_dshot.h, sw/airborne/boards/apogee/chibios/v1.0/board.h, sw/airborne/boards/tawaki/chibios/common/tawaki.h
Some bugs were introduced with the latest modifications on the DSHOT driver
Probably not related to  #2607, but it is worth testing
=> [fix] fix DSHOT driver and corresponding boards

conf/flight_plans/formation/form_follow.xml, conf/flight_plans/formation/form_leader.xml, sw/airborne/modules/multi/formation.h
small bug fix and typo for formation flight module
=> [module] fix formation flight module and load from flight plan

conf/airframes/ENAC/fixed-wing/apogee.xml, conf/modules/shell.xml, sw/airborne/arch/chibios/modules/core/microrl/microrl.c, sw/airborne/arch/chibios/modules/core/microrl/microrl.h, sw/airborne/arch/chibios/modules/core/microrl/microrlConfig.h, sw/airborne/arch/chibios/modules/core/microrl/microrlShell.c, sw/airborne/arch/chibios/modules/core/microrl/microrlShell.h, sw/airborne/arch/chibios/modules/core/rtos_mon_arch.c, sw/airborne/arch/chibios/modules/core/shell_arch.c, sw/airborne/arch/chibios/modules/core/shell_arch.h, sw/airborne/modules/core/shell.c, sw/airborne/modules/core/shell.h
- add a set of core commands
- allow to add custom commands from external modules at runtime
- fix small errors in rtos_mon module
=> [shell] add a shell module with ChibiOS

conf/modules/e_identification_fr.xml, sw/airborne/modules/e_identification_fr/e_identification_fr.c, sw/airborne/modules/e_identification_fr/e_identification_fr.h
Tracker start sending data automatically while the drone is in flight.
Also add a setting to start sending data when the drone is not in flight.
=> [tracker] Start automatically. Add setting to start/stop it.

Makefile.ac, conf/airframes/ENAC/fixed-wing/matek_f765_wing.xml, conf/airframes/matek_f405_wing/Easyglider_matek_f405_autoload.xml, conf/boards/matek_f765_wing.makefile, conf/flash_modes.xml, conf/modules/board_matek_f405_wing.xml, conf/modules/board_matek_f765_wing.xml, sw/airborne/boards/mateksys/F765-WING/board.c, sw/airborne/boards/mateksys/F765-WING/board.h, sw/airborne/boards/mateksys/F765-WING/board.mk, sw/airborne/boards/mateksys/F765-WING/ffconf.h, sw/airborne/boards/mateksys/F765-WING/matekF765-WING.cfg, sw/airborne/boards/mateksys/F765-WING/matekF765-WING.h, sw/airborne/boards/mateksys/F765-WING/mcuconf.h, sw/airborne/modules/display/max7456.c
Add support for the Matek F765 Wing board with ChibiOS
http://www.mateksys.com/?portfolio=f765-wing
also fix the parallel build detection
=> Matek f765 wing

sw/airborne/firmwares/rotorcraft/autopilot_static.c
if RC is on and full throttle, aircraft keep landing on failsafe
=> prevent RC while failsafe

conf/modules/MPPT.xml, conf/modules/alt_srf08.xml, conf/modules/dust_gp2y.xml, conf/modules/gsm.xml, conf/modules/humid_htm_b71.xml, conf/modules/humid_sht_i2c.xml, conf/modules/wind_gfi.xml, sw/lib/ocaml/module.ml, sw/tools/generators/gen_modules.ml
see comments in #2553
@martinmm can you check that it is now working for you ? Some of the sensors using this option are from you I think, we can update them for the new format if you can give me the correct values.
=> [fix] allow float values for delay in module XML

.gitmodules
now hosted on Gitlab, latest version: 3.3.9
it is also fixing some deprecated functions
=> [submodule] update eigen ref and version

sw/ground_segment/misc/rtcm2ivy.c
Change the name of a variable from wait to my_wait in order to avoid a collision on some platforms
=> minor fix for macOSX compatibility.

sw/simulator/pprzsim-launch
=> Fix python comparison.

sw/airborne/pprz_syscalls.c
bug reported when compiling ekf2 INS with chibios
=> [fix] define _fini dummy syscall for chibios

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c
Before it did not matter if the rate filter was enabled, since every loop the body rates were copied to the rates_filt_fo in the loop itself.
Now the rates_filt_fo is defined and copied from the bodyrates in the initialisation phase as a global variable. If the filter is enabled around any of the body axis (p,q,r) a first order filter will be applied using the rates_filt_fo from the previous iteration. If the filter is disabled the rates_filt_fo will be copied form the body_rates at that timestep.
=> [indi_simple] Fixed rate feedback filter and initialisation

sw/ground_segment/cockpit/Makefile, sw/ground_segment/cockpit/ant_track_pmm.c, sw/ground_segment/cockpit/ant_tracker_pmm.glade
Fixed a bug which prevented the Azimuth servo to use it's full travel when in 180 degree mode.
=> Fixed a bug in 180 degree mode

docker/run.sh
Setting the environment variable `useX` to anything but `true` will disable X-server access.
This allow to use the docker image on non graphic systems.
If not set, this variable default to `true`, so default behavior is not changed.
=> [docker] make it possible to disable X server access.

conf/Makefile.arm-embedded-toolchain, conf/Makefile.arm-linux-toolchain
or new multiarch if not found
close #2589
=> [build] use proper GDB according to prefix

sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c
With INDI simple, there was still the possibility to turn off the control just by giving a low thrust command. With these changes, you also have to be not in_flight and instead the increments are not accumulated, so you end up with a proportional controller.
I reorganized some of the code to implement this
=> Reorganize INDI simple for better takeoff

conf/airframes/FLIXR/flixr_conf.xml, conf/airframes/examples/quadrotor_navstik.xml, conf/modules/photogrammetry_calculator.xml, sw/airborne/modules/cartography/photogrammetry_calculator.c, sw/airborne/modules/cartography/photogrammetry_calculator.h
it seems easier to add them back for now to fix the CI build, that would delete too many other config files
=> restore deleted module and clean other config files

conf/modules/actuators_uavcan.xml, conf/modules/uavcan.xml, conf/userconf/tudelft/conf.xml, sw/airborne/arch/chibios/modules/uavcan/uavcan.c, sw/airborne/arch/chibios/modules/uavcan/uavcan.h, sw/airborne/subsystems/actuators/actuators_uavcan.c, sw/airborne/subsystems/actuators/actuators_uavcan.h
- Restyled the code for the actuators
- Added and tested ESC telemetry (Needs to be properly fixed later)
- Fixed performance issues for transmitting after reconnect
Sorry fo this update, but you merged while I was in the middle of testing and updating.
=> Uavcan actuators restyle and telemetry

sw/ground_segment/misc/rtcm2ivy.c
replaced printf by printf_debug to avoid freezing the paparazzi centre
=> [rtcm2ivy] convert printf to printf_debug

sw/airborne/subsystems/ins/ins_ekf2.cpp, sw/airborne/subsystems/navigation/waypoints.h
Fix localization of global waypoints when EKF2 resets the local origin.
=> [ins] EKF2 fix localization of global waypoints

.github/workflows/issues_due_date.yml
See https://github.com/marketplace/actions/due-dates
=> Add github action to set dates on issues.

conf/airframes/tudelft/neddrone5.xml, conf/flight_plans/tudelft/nederdrone_valkenburg.xml, conf/simulator/jsbsim/aircraft/nederdrone.xml, conf/userconf/tudelft/conf.xml
- Made Nederdrone4 and Nederdrone5 airframe more similar.
- Fixed new motor ordering for Nederdrones in simulator
- Added flightplan for nederdrone at Valkenburg
- Added Nederdrone5
=> [conf] Cleanup TUDelft NederDrone

sw/tools/generators/gen_airframe.ml, sw/tools/generators/gen_modules.ml, sw/tools/generators/gen_settings.ml
Fix small bug as reported by @fvantienen 
close  #2720
=> [generators] add missing close files

conf/airframes/tudelft/neddrone4.xml, conf/airframes/tudelft/neddrone5.xml, conf/modules/scheduling_indi_simple.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.h, sw/airborne/modules/ctrl/scheduling_indi_simple.c, sw/airborne/modules/ctrl/scheduling_indi_simple.h
This adds a simple INDI scheduling and cleans up the airframe files for the Nederdrone4 and Nederdrone5.
=> Nederdrone reintegration

conf/modules/follow_me.xml, sw/airborne/modules/ctrl/follow_me.c, sw/airborne/modules/ctrl/follow_me.h
This adds a follow me module.
TODO:
=> [module] Add a follow me module

conf/airframes/ENAC/fixed-wing/jp.xml, sw/ground_segment/cockpit/live.ml, sw/ground_segment/cockpit/strip.ml, sw/ground_segment/cockpit/strip.mli
Add a define for BAT_NB_CELLS in the BAT section of the airframe file to activate the display
See  #2726
=> [gcs] indicate voltage/cell if number of cells is specified

conf/flight_plans/tudelft/train_safe_zoo.xml
See wiki for more info 
https://github.com/tudelft/mavlab/wiki/Quadrotor-safe-Cyberzoo-pilot-training
=> Added new flight plan to safely learn to pilot a drone in the cyber zoo

conf/modules/mag_rm3100.xml, sw/airborne/modules/sensors/mag_rm3100.c, sw/airborne/modules/sensors/mag_rm3100.h, sw/airborne/peripherals/rm3100.c, sw/airborne/peripherals/rm3100.h, sw/airborne/subsystems/abi_sender_ids.h
=> [driver] support for RM3100 magneto over I2C

conf/airframes/examples/bixler_lisa_m_2.xml, conf/flight_plans/rotorcraft_basic.xml, conf/flight_plans/rotorcraft_survey.xml, conf/flight_plans/versatile.xml
Small fixes on example flight plans:
-  ">" replaced by "@GT"
- added missing module in rotorcraft_survey.xml
- moved module from airframe to flight plan.
=> Fix example conf.

conf/modules/stabilization_indi.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
This PR gives
(1) the INDI stabilization the same filtering setup as INDI simple.
(2) Use of feed forward for the INDI guidance. There is still an issue with the reference model (#2730)
=> Indi updates

conf/airframes/tudelft/neddrone4_tem.xml, conf/flight_plans/tudelft/nederdrone_cyberzoo.xml, conf/modules/ins_ekf2.xml, conf/telemetry/highspeed_rotorcraft.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/subsystems/gps/gps_datalink.c, sw/airborne/subsystems/ins/ins_ekf2.cpp, sw/ground_segment/python/herelink.py
This pull request has some small fixes for the following:
- [ekf2] Possibility to work with optitrack
- [hybrid] Initialization reset correctly on enter
- [conf] Add Nederdrone with trailing edge motors
- [ground] Add herelink RSSI tool
=> [combined] Small fixes

sw/ground_segment/python/messages_app/messagesframe.py
I don't know if anyone is actually using it, but the python "Messages" is now fixed for python >=3.3
=> Fix python "Messages".

sw/airborne/subsystems/ins/ins_float_invariant.c
Copied from ahrs_int_cmpl_quat
=> [ins] add support for gps course as heading (for indoor use)

conf/tools/pprzgcs.xml
Since we start using it, this will make things easier.
=> Add PprzGCS tool.

sw/ground_segment/tmtc/server.ml
can be used by external plotter like PlotJuggler (default port)
always enabled by default
merge https://github.com/paparazzi/pprzlink/pull/154 and update pprzlink ref before accepting this PR
=> Server json stream

sw/airborne/firmwares/fixedwing/main_ap.c, sw/airborne/firmwares/rotorcraft/main_ap.c, sw/airborne/firmwares/rover/main_ap.c
event functions from control group were not called
=> [fix] add missing control event call

conf/modules/cv_opticflow.xml, conf/modules/laser_range_array.xml, conf/modules/math.xml, conf/modules/telemetry_bluegiga.xml, conf/modules/telemetry_intermcu.xml, conf/modules/telemetry_ivy.xml, conf/modules/telemetry_nps.xml, conf/modules/telemetry_sim.xml, conf/modules/telemetry_superbitrf.xml, conf/modules/telemetry_transparent.xml, conf/modules/telemetry_transparent_frsky_x.xml, conf/modules/telemetry_transparent_gec.xml, conf/modules/telemetry_transparent_udp.xml, conf/modules/telemetry_xbee_api.xml, sw/airborne/boards/bebop/mt9f002.c, sw/airborne/math/pprz_matrix_decomp_float.c, sw/airborne/modules/computer_vision/opticflow/linear_flow_fit.c, sw/airborne/modules/computer_vision/opticflow_module.c, sw/airborne/modules/datalink/superbitrf.c, sw/airborne/modules/range_finder/laser_range_array.c, tests/modules/dummy.h, tests/modules/generated/keys_uav.h, tests/modules/generated/periodic_telemetry.h, tests/modules/test_arch/udp_socket.h
improve testing and remove warnings
=> Small fix collection

conf/airframes/tudelft/bebop_course_orangeavoid.xml, sw/simulator/nps/nps_fdm_gazebo.cpp
Work in progress, see issue #2807. Final PR may take until January because of holidays.
=> Fix #2807 inconsistent coordinate transform in nps_fdm_gazebo

doc/sphinx/source/conf.py
Paparazzi version in the doc was never updated, this should make it automatic.
=> [doc] Get version from the paparazzi_version script.

.github/workflows/doxygen.yml, sw/tools/doxygen_gen/gen_messages_doc.py, sw/tools/doxygen_gen/gen_modules_doc.py
This action will update https://github.com/paparazzi/paparazzi.github.com on push to master.
The secret PUSH_TOKEN need to be setup before merging.
=> [doc] Add doxygen action, and fix python doc generators.

conf/simulator/flightgear/bebop.xml
Added a Bebop model in flightgear, from https://blendswap.com/profile/43891
=> Bebop flightgear

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
Use the hybrid message for debugging normal guidance INDI. Maybe rename this in the future?
=> [guidance] Add debug message guidance INDI

.gitignore, sw/airborne/modules/gps/gps_ubx.c, sw/ground_segment/misc/Makefile, sw/ground_segment/misc/ublox2ivy.c, sw/ground_segment/misc/ublox2ivy.h
Add RTK tool for ublox GPS and update the RTK messages
=> [gps] Update ublox RTK support and ground tool

sw/airborne/firmwares/rotorcraft/guidance/guidance_h_ref.c, sw/airborne/math/pprz_algebra_int.h, sw/airborne/modules/ins/ins_ekf2.cpp
- Add the INS and INS_Z message to the ekf2 module
- Fix warning in the reference model for long BFP conversion
=> [ins] Add ekf2 messages

conf/tools/pprzgcs.xml, sw/supervision/pc_control_panel.ml, sw/tools/gcs_launch.py
Run PprzGCS or the legacy GCS.
If run without arguments, try with PprzGCS first.
=> [GCS] Add wrapper to launch GCS.

conf/airframes/tudelft/bebop_opticflow_indoor_2x_30hz.xml, conf/userconf/tudelft/conf.xml
@guidoAI
- Front and bottom cam: pyramid=0, img=240x240, fcorner=30, draw=1, stream=5Hz 50% size
- Result: both at 30Hz consistently
=> [ariframe] sample bebop with 2x 30Hz optic flow: 

doc/sphinx/source/quickstart/first_simulation.rst, doc/sphinx/source/user_guide/gcs_graphics.rst
sync with master branch.
commit c88886d8756ed5a5f1e75d8ec81ece1ac8b645f2 (HEAD -> lida2003/master, origin/lida2003/master)
Author: Daniel Li <lida_mail@163.com>
Date:   Thu Apr 28 16:46:35 2022 +0800
[doc] add Bixler to simulation aircraft and modify spelling issue
=> [doc] add Bixler to simulation aircraft and modify spelling issue

doc/sphinx/source/developer_guide/abi.rst
I added a little more information to some of the sections as well as rearranging the contents to something that I think reads more logically. I also added a small section detailing all the steps that must be taken to create a new message.
=> [sphinx] Improvements to the ABI section

doc/sphinx/source/developer_guide/index_developer.rst, doc/sphinx/source/developer_guide/logging.rst
I've written a page to detail some of the logging options that are available for Paparazzi. Not everything that I saw on the Paparazzi Wiki made it here because from my understanding most of the other options will soon become deprecated. 
I wasn't 100% sure about the information on the Pprzlog format so comments on that section are welcome.
=> [sphinx] Adds Logging section in Developer Guide

conf/airframes/OPENUAS/openuas_df_mini_spirit.xml, conf/airframes/OPENUAS/openuas_wltech_xk_a160.xml, sw/airborne/boards/lisa_m_common.h, sw/airborne/boards/lisa_mx_common.h
bug fix from issue: https://github.com/paparazzi/paparazzi/issues/2787
=> fixed CPPM reception issue for lisa_m and lisa_mx ap

sw/airborne/firmwares/fixedwing/autopilot_static.c
this is only fixing the display and the ENERGY message, flight behavior is not affected
=> [fix] update the autopilot throttle in manual for fixedwing

sw/airborne/firmwares/rotorcraft/autopilot_firmware.c
Added message that sends the body rates and accelerations, linking to pprzlink https://github.com/paparazzi/pprzlink/pull/162
=> add message body rates accel

conf/userconf/tudelft/conf.xml, sw/airborne/boards/lisa_m_common.h, sw/airborne/boards/lisa_mx_common.h, sw/ground_segment/tmtc/ivy2serial.ml, sw/ground_segment/tmtc/ivy2udp.ml, sw/ground_segment/tmtc/ivy_tcp_aircraft.ml, sw/ground_segment/tmtc/ivy_tcp_controller.ml, sw/ground_segment/tmtc/link.ml, sw/logalizer/sd2log.ml
fixing some errors and warnings
one remaining error is related to rust and secure pprzlink
=> Fix ci build

conf/modules/ins_float_invariant.xml, conf/modules/ins_gps_passthrough.xml, conf/modules/ins_mekf_wind.xml, sw/airborne/math/pprz_geodetic_int.h, sw/airborne/modules/gps/gps.c, sw/airborne/modules/gps/gps.h, sw/airborne/modules/gps/gps_ubx.c, sw/airborne/modules/gps/gps_ubx.h, sw/airborne/modules/ins/ins.c, sw/airborne/modules/ins/ins.h, sw/airborne/modules/ins/ins_alt_float.c, sw/airborne/modules/ins/ins_ekf2.cpp, sw/airborne/modules/ins/ins_float_invariant.c, sw/airborne/modules/ins/ins_gps_passthrough.c, sw/airborne/modules/ins/ins_gps_passthrough_utm.c, sw/airborne/modules/ins/ins_int.c, sw/airborne/modules/ins/ins_mekf_wind_wrapper.c, sw/airborne/modules/ins/ins_xsens.c, sw/airborne/modules/ins/ins_xsens700.c
- use conveniance functions to access GPS position and speed
- try to improve support of UBX fix status
=> [gps][ins] improve gps support for ins filters

conf/airframes/ENAC/quadrotor/drop1.xml, conf/airframes/ENAC/quadrotor/niquad_wind.xml, conf/autopilot/rover_steering.xml, conf/flight_plans/competitions/IMAV2022_drop.xml, conf/flight_plans/competitions/IMAV2022_falcon.xml, conf/flight_plans/competitions/IMAV2022_search.xml, conf/mag/README.md, conf/mag/delft_valkenburg.xml, conf/mag/north_unit.xml, conf/mag/toulouse_muret.xml, conf/radios/FrSky_X-Lite.xml, sw/airborne/firmwares/rotorcraft/autopilot_firmware.c, sw/airborne/firmwares/rover/guidance/rover_guidance_steering.h, sw/airborne/modules/multi/follow.c, sw/ground_segment/python/move_waypoint_example.py, sw/ground_segment/tmtc/link.ml, sw/ground_segment/tmtc/server.ml, sw/logalizer/sd2log.ml
update enac conf and imav2022 flight plans
collection of small corrections:
- default mode is NAV for rover steering
- no rover throttle when killed
- xbee link doesn't send data to modem before end of config
- fix alt in server (geoid/ellipsoid)
- support GPS_INT in sd2log
- don't increment position in follow module
- use correct angles for hybrid
=> Update conf enac imav

sw/airborne/firmwares/rotorcraft/navigation.h
=> [nav] fix glide computation with a cast uint->int

docker/dep/Dockerfile
Updating to Ubuntu 20.04 might help for #2911?
=> [docker] Use Ubuntu 20.04.

sw/airborne/modules/ahrs/ahrs_aligner.c, sw/airborne/modules/ahrs/ahrs_float_cmpl_wrapper.c, sw/airborne/modules/ahrs/ahrs_float_dcm_wrapper.c, sw/airborne/modules/ahrs/ahrs_float_invariant_wrapper.c, sw/airborne/modules/ahrs/ahrs_float_mlkf_wrapper.c, sw/airborne/modules/ahrs/ahrs_int_cmpl_quat_wrapper.c, sw/airborne/modules/ahrs/ahrs_madgwick_wrapper.c, sw/airborne/modules/core/abi_sender_ids.h, sw/airborne/modules/imu/filter_1euro_imu.c, sw/airborne/modules/imu/imu.c, sw/airborne/modules/ins/ins_float_invariant_wrapper.c, sw/airborne/modules/ins/ins_mekf_wind_wrapper.c
- fix signs corrections
- fix binding of ahrs aligner
=> Fix imu conf

sw/ground_segment/tmtc/aircraft_server.ml, sw/ground_segment/tmtc/server.ml, sw/ground_segment/tmtc/server_globals.ml, sw/tools/generators/gen_aircraft.ml
- server extract the correct modes with generated autopilots
- compilation dependency fixed for generated autopilot
=> [autopilot] fix detection of generated mode and generation dep

sw/ground_segment/misc/ublox2ivy.c, sw/ground_segment/misc/ublox2ivy.h, sw/ground_segment/tmtc/gpsd2ivy.c
Should be merged after https://github.com/paparazzi/pprzlink/pull/164
=> [ground] Add heading to ublox2ivy

sw/lib/ocaml/autopilot.ml
The settings defined in the autopilot file were not generated.
This PR generate them, and group them with the mode setting of the corresponding state machine.
=> [generated autopilot] Include settings defined in the autopilot file.

sw/simulator/nps/nps_ivy.c, sw/simulator/nps/nps_ivy.h, sw/simulator/nps/nps_main.h, sw/simulator/nps/nps_main_common.c
=> [nps] variables in nps_main should be extern

.github/workflows/docker.yml
Rebuild on changes in the docker directory, and every month.
Not sure it will work, to be tested.
Before merging, add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets.
=> [docker] Build and push docker images to dockerhub.

tests/aircrafts/01_compile_all_aircrafts.t
This might solve the problem of CI server running out of space
=> [test] clean ac after runing test

sw/airborne/modules/imu/imu_aspirin.c, sw/tools/calibration/calibration_utils.py
- Fix aspirin build
- Fix calibration tool
=> Fix small bugs

conf/airframes/OPENUAS/openuas_wltech_xk_a160.xml, conf/boards/lisa_mxs_1.0_chibios.makefile, conf/modules/boards/lisa_mxs_1.0_chibios.xml, sw/airborne/boards/lisa_mxs/chibios/v1.0/board.h, sw/airborne/boards/lisa_mxs/chibios/v1.0/mcuconf.h
Tested Basic functionality like voltage, UART telemetry, IMU.
=> Add chibios for lisa mxs fc

conf/firmwares/setup.makefile, conf/firmwares/test_chibios.makefile, conf/firmwares/test_progs.makefile, conf/modules/datalink_common.xml, sw/airborne/arch/sim/sim_ap.c, sw/airborne/firmwares/demo/demo_ahrs_actuators.c, sw/airborne/firmwares/setup/setup_actuators.c, sw/airborne/modules/datalink/datalink.c, sw/airborne/modules/datalink/datalink.h, sw/airborne/modules/datalink/downlink.c, sw/airborne/test/mcu_periph/test_adc.c, sw/airborne/test/modules/test_ahrs.c, sw/airborne/test/modules/test_imu.c, sw/airborne/test/modules/test_radio_control.c, sw/airborne/test/modules/test_settings.c, sw/airborne/test/peripherals/test_ami601.c, sw/airborne/test/peripherals/test_lis302dl_spi.c, sw/airborne/test/peripherals/test_ms2100.c, sw/airborne/test/test_actuators_pwm.c, sw/airborne/test/test_baro_board.c, sw/airborne/test/test_can.c, sw/airborne/test/test_datalink.c, sw/airborne/test/test_manual.c, sw/airborne/test/test_math_trig_compressed.c, sw/airborne/test/test_module.c, sw/airborne/test/test_telemetry.c
and get rid of the DATALINK_C trick
also it should fix the bug of multiple definition with sim target and recent GCC
=> [datalink] add a datalink init function

conf/airframes/OPENUAS/openuas_wltech_xk_a160.xml, conf/modules/mag_qmc5883l.xml, sw/airborne/boards/lisa_mxs/chibios/v1.0/board.h, sw/airborne/modules/core/abi_sender_ids.h, sw/airborne/modules/sensors/mag_qmc5883l.c, sw/airborne/modules/sensors/mag_qmc5883l.h, sw/airborne/peripherals/qmc5883l.c, sw/airborne/peripherals/qmc5883l.h
Added a driver for the QMC5883L Magnetometer, tested on Baremetal Lisa MXS and Chibios Lisa MXS
=> Added driver for QMC5883L Magnetometer

conf/airframes/tudelft/bebop2_no_damping_WLS.xml, conf/modules/stabilization_indi_simple.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c, sw/airborne/modules/ins/ins_int.c
G1+G2 was not updated with WLS before, but the new G2 was still used leading to unstable behavior.
And:
- better scaling value for pseudo inverse
- Unify file_logger module name. OCD maybe but ok :)
=> Fix for adaptive INDI

conf/modules/px4_flash.xml, sw/airborne/arch/chibios/usb_ser_hw.c, sw/airborne/modules/px4_flash/protocol.h, sw/airborne/modules/px4_flash/px4_flash.c, sw/tools/px4/px4fmu-v2.prototype, sw/tools/px4/px4io-v2.prototype, sw/tools/px4/px_mkfw.py, sw/tools/px4/px_uploader.py, sw/tools/px4/set_target.py
This PR fixes issues mentioned in #2935.
It was tested OK with Cuav-Pixhawk-5 (px4fmu_5.0_chibios).
fix #2935
=> [PX4] AP and FBW flash through bootloader fix

sw/supervision/python/Makefile, sw/supervision/python/conf_settings_widget.py, sw/supervision/python/conf_widget.py, sw/supervision/python/configuration_panel.py, sw/supervision/python/utils.py
Add the ability to add or remove settings files in the python paparazzi center.
=> [supervision] Add settings selector.

conf/tools/display_objects.xml, sw/ground_segment/python/natnet3.x/NatNetClient.py, sw/ground_segment/python/natnet3.x/display_objects.py
update natnet client to get markerset
=> [natnet] display object in GCS based on optitrack markerset

sw/supervision/python/generated/ui_conf_settings.py, sw/supervision/python/ui/conf_settings.ui
=> [supervision] Add missing files.

doc/sphinx/source/developer_guide/debug.rst, doc/sphinx/source/developer_guide/index_developer.rst, doc/sphinx/source/developer_guide/logging.rst
Explain how to help debug your code with telemetry messages and the shell, and how to enable debug symbols.
Coming "some day" specific steps to debug with e.g. a blackmagic probe. (not in this PR)
=> [doc] Add a Debug section.

conf/modules/boards/index.rst, conf/modules/firmwares/index.rst, conf/modules/index.rst, conf/modules/targets/index.rst, conf/modules/time_countdown.xml, doc/sphinx/source/conf.py, doc/sphinx/source/index.rst, doc/sphinx/source/modules, sw/tools/modules_doc/modules_parser.py
generate sphinx doc from modules xml files.
=> Modules doc

conf/airframes/tudelft/bebop_course_orangeavoid.xml, conf/userconf/tudelft/conf.xml, conf/userconf/tudelft/course_conf.xml, sw/airborne/boards/bebop/mt9f002.c, sw/airborne/boards/bebop/mt9f002.h, sw/airborne/modules/computer_vision/lib/encoding/jpeg.c, sw/airborne/modules/computer_vision/video_capture.c
fix linking errors and silent compile warnings.
=> Ubuntu22 fixes

sw/supervision/python/paparazzicenter.py
Update targets only: this reduce the lag at each AC change.
Please tell me if you find some bugs in the paparazzi center, I will include the fixes with this PR.
=> Supervision small fixes

conf/modules/flight_recorder.xml, conf/modules/logger_sd_chibios.xml, sw/airborne/modules/loggers/flight_recorder.c, sw/airborne/modules/loggers/flight_recorder.h, sw/airborne/modules/loggers/sdlog_chibios.c, sw/airborne/modules/loggers/sdlog_chibios.h, sw/ground_segment/tmtc/server.ml
Send INFO_MSG_GROUND to log an INFO_MSG in the drone, in either the flight recorder or the pprzlog (or both).
INFO_MSG_UP is logged by the server.
pprzlink needs to be updated.
=> Log message, and forward it to link.

sw/airborne/modules/ins/vf_extended_float.c
This is seems like wrong integration. I also don't see how it would be trapezoidal, so I removed the comment.
=> fix state update equation

conf/airframes/OPENUAS/openuas_wltech_xk_a160.xml, conf/telemetry/OPENUAS/openuas_fixedwing_imu_rc.xml, sw/airborne/boards/lisa_mxs/chibios/v1.0/board.h, sw/airborne/boards/lisa_mxs/chibios/v1.0/mcuconf.h
Tested on Lisa MXS hardware with A160 airframe, below works
=> PPM input GPS input and Telem full all working now

conf/airframes/examples/matek_h743_slim.xml, conf/boards/matek_h743_slim.makefile, conf/flash_modes.xml, conf/modules/boards/matek_h743_slim.xml, conf/modules/imu_matek_h743_slim.xml, sw/airborne/arch/chibios/STM32H743xI_no_bl.ld, sw/airborne/arch/chibios/common_board.h, sw/airborne/arch/chibios/mcu_periph/sys_time_arch.c, sw/airborne/arch/chibios/mcu_periph/sys_time_arch.h, sw/airborne/arch/chibios/mcu_periph/uart_arch.c, sw/airborne/arch/chibios/modules/core/rtos_mon_arch.c, sw/airborne/boards/mateksys/FC-H743-SLIM/board.cfg, sw/airborne/boards/mateksys/FC-H743-SLIM/board.h, sw/airborne/boards/mateksys/FC-H743-SLIM/mcuconf.h, sw/tools/px4/matek_h743_slim.prototype, sw/tools/px4/print_message.py, sw/tools/px4/px_mkfw.py, sw/tools/px4/set_target.py
only flashing with DFU for now
default orientation for MPU6000 imu
fix small bugs
still need drivers for ICM42605 imu and DPS310 baro
dshot config is missing
=> [board] basic support of matek h743 slim

conf/modules/stabilization_float_euler.xml, conf/modules/stabilization_float_quat.xml, conf/modules/stabilization_heli_indi.xml, conf/modules/stabilization_indi.xml, conf/modules/stabilization_indi_simple.xml, conf/modules/stabilization_int_euler.xml, conf/modules/stabilization_int_quat.xml, conf/modules/stabilization_passthrough.xml, conf/modules/stabilization_rotorcraft.xml, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_euler_float.c, sw/airborne/modules/guidance/gvf/gvf_low_level_control.h, sw/airborne/modules/guidance/gvf_parametric/gvf_parametric.cpp
some more corrections after nav reorg #2964
- fix gvf mode name
- fix typo and factorize files in stab modules
=> Fix small errors

.semaphore/night-build.yml, .semaphore/semaphore.yml
Pull request for the record
Setting up a semaphore 2.0 to replace v1
=> Setup semaphore 2.0

conf/modules/eff_scheduling_nederdrone.xml, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.h, sw/airborne/modules/ctrl/eff_scheduling_nederdrone.c, sw/airborne/modules/ctrl/eff_scheduling_nederdrone.h
Added the option to set a desired value for the actuators other than zero, and to set priorities for the actuators.
Changed takeoff behavior: until in_flight is true no increments are added, turning the controller into a PD controller.
=> Nederdrone trim and INDI startup PD control

conf/flight_plans/fixedwing_demo_takeoff_land.xml, conf/flight_plans/rotorcraft_demo_takeoff_land.xml, conf/modules/ins_sim.xml, conf/modules/nav_takeoff_and_landing.xml, conf/modules/targets/sim.xml, sw/airborne/firmwares/fixedwing/nav.c, sw/airborne/firmwares/fixedwing/nav.h, sw/airborne/firmwares/rotorcraft/navigation.c, sw/airborne/firmwares/rotorcraft/navigation.h, sw/airborne/modules/nav/nav_rotorcraft_base.c, sw/airborne/modules/nav/nav_takeoff_and_landing.h, sw/airborne/modules/nav/nav_takeoff_and_landing_fw.c, sw/airborne/modules/nav/nav_takeoff_and_landing_rotorcraft.c, sw/airborne/modules/nav/waypoints.c, sw/airborne/modules/nav/waypoints.h
Functions for takeoff and landing (fixedwing and rotorcraft), can be called from the flight plan or from the mission module. Two flight plan examples are provided.
Various options are possible, see module description and header file.
=> [nav] takeoff and land module

sw/supervision/python/configuration_panel.py, sw/supervision/python/error.svg, sw/supervision/python/paparazzicenter.py, sw/supervision/python/program_widget.py, sw/supervision/python/running.svg, sw/supervision/python/session_widget.py
Add programs status in the tabs :
- blue dot means programs are running,
- red dot means programs exited with error.
=> [supervision] Add programs status.

sw/lib/ocaml/airframe.ml, sw/lib/ocaml/autopilot.ml, sw/lib/ocaml/flight_plan.ml, sw/lib/ocaml/module.ml, sw/lib/ocaml/radio.ml, sw/lib/ocaml/settings.ml, sw/lib/ocaml/telemetry.ml
it provides better messages in case of XML or DTD errors
=> [ocaml] parse XML file with ExtXml version

conf/modules/nav_survey_hybrid.xml, sw/airborne/modules/nav/nav_survey_hybrid.c
- call init function
- set to valid at the end of setup so it works with mission correctly
=> [nav] fix survey hybrid

sw/airborne/modules/ins/ins_ekf2.cpp
HMSL was set to be altitude...
=> fix origin altitude ekf2

conf/airframes/tudelft/cyfoam.xml, conf/airframes/tudelft/nederdrone4.xml, conf/airframes/tudelft/nederdrone4_tem.xml, conf/airframes/tudelft/nederdrone5.xml, conf/airframes/tudelft/nederdrone6.xml, conf/airframes/tudelft/nederdrone7.xml, conf/airframes/tudelft/nederdrone8.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
=> Set speed without ref

sw/airborne/modules/ins/ins_ekf2.cpp
I think this will fix the EKF2 origin since now HMSL and altitude are both used and results in wrong calculations of the INS reference. (Especially line 525 and 624 were conflicting)
Now:
- The EKF2 works with HMSL (Following the standard and descriptions of PX4)
- The PPRZ origin is in WGS84 mm above the reference ellipsoid
- The origin in the EKF2 is with HMSL
- The GPS inputs the HMSL in the EKF2
- The origin from the EKF2 is converted from HMSL to WGS84 with `+ wgs84_ellipsoid_to_geoid_i(lla_ref.lat, lla_ref.lon)` for the PPRZ origin
=> [ins] Fix EKF2 working with HMSL

conf/modules/follow_me.xml, conf/userconf/tudelft/conf.xml, sw/airborne/modules/ctrl/approach_moving_target.c, sw/airborne/modules/ctrl/follow_me.c, sw/airborne/modules/ctrl/follow_me.h, sw/ground_segment/misc/ublox2ivy.c
This removes the possibilities of NaN's and adds the option to move multiples waypoints periodically with the follow_me module. An example flight plan will follow
=> [modules] Fix follow me

conf/tools/flight_plan_editor.xml, sw/supervision/python/configuration_panel.py, sw/supervision/python/paparazzicenter.py, sw/supervision/python/session_widget.py
=> [supervision] Fix edit flight plan in GCS.

conf/modules/electrical.xml, sw/airborne/arch/chibios/modules/actuators/actuators_dshot_arch.c, sw/airborne/firmwares/fixedwing/autopilot_firmware.c, sw/airborne/firmwares/rotorcraft/autopilot_firmware.c, sw/airborne/firmwares/rover/autopilot_firmware.c, sw/airborne/modules/actuators/actuators_uavcan.c, sw/airborne/modules/energy/electrical.c, sw/airborne/modules/energy/electrical.h, sw/airborne/modules/esc32/esc32.c
requires: https://github.com/paparazzi/pprzlink/pull/172
=> [modules] Average electrical power and ESC telemetry fixes

conf/modules/generic_uart_sensor.xml, sw/airborne/modules/sensors/generic_uart.c
Fixup for the comments from https://github.com/paparazzi/paparazzi/pull/3060
=> [modules] Generic UART sensor cleanup

conf/airframes/tudelft/nederdrone8.xml, conf/modules/approach_moving_target.xml, sw/airborne/modules/ctrl/approach_moving_target.c, sw/airborne/modules/ctrl/approach_moving_target.h
- high filter values make the filter unstable
=> [modules] Approach moving target filter

conf/conf_example.xml, conf/conf_tests.xml, conf/conf_tests_coverity.xml, conf/telemetry/highspeed_rotorcraft.xml, sw/airborne/math/pprz_matrix_decomp_float.c, sw/airborne/modules/computer_vision/opticflow/linear_flow_fit.c, sw/airborne/modules/datalink/mavlink.c, sw/airborne/modules/datalink/missionlib/blocks.c, sw/airborne/modules/datalink/missionlib/mission_manager.c, sw/airborne/modules/datalink/missionlib/waypoints.c, sw/airborne/modules/imu/imu_mpu9250.c, sw/airborne/modules/nav/nav_survey_hybrid.c, sw/airborne/test/modules/test_radio_control.c, sw/ext/Makefile
This fixes some compile warnings and also updates mavlink to V2
=> [conf] Fix compile warnings

conf/modules/airspeed_uavcan.xml, sw/airborne/modules/core/abi_sender_ids.h, sw/airborne/modules/sensors/airspeed_uavcan.c, sw/airborne/modules/sensors/airspeed_uavcan.h
=> [modules] airspeed UAVCAN

conf/airframes/tudelft/nederdrone4.xml, conf/airframes/tudelft/nederdrone6.xml, conf/airframes/tudelft/nederdrone7.xml, conf/airframes/tudelft/nederdrone8.xml, conf/flight_plans/tudelft/nederdrone_terschelling.xml, conf/flight_plans/tudelft/nederdrone_valkenburg.xml, conf/userconf/tudelft/conf.xml
harmonize airframes, test all flight plans in conf and fix a few airframes
=> [airframes] TU Delft

sw/tools/install.py, sw/tools/opti_dist/dist.py
fixes from https://github.com/tudelft/paparazzi/tree/mavlabCourse2023
=> [fix] distance counter update (list of rigidbodies) + typo in install 22.04

conf/airframes/tudelft/nederdrone4.xml, conf/airframes/tudelft/nederdrone6.xml, conf/airframes/tudelft/nederdrone7.xml, conf/airframes/tudelft/nederdrone8.xml, conf/modules/approach_moving_target.xml, sw/airborne/modules/ctrl/approach_moving_target.c, sw/airborne/modules/ctrl/approach_moving_target.h
- allow storing specific gains in airframe files
- put all settings in the struct 
- remove unused
=> [modules] Approach moving target fixes

README.md, conf/Makefile.nps, conf/airframes/tudelft/bebop_course_orangeavoid.xml, conf/userconf/tudelft/conf.xml, conf/userconf/tudelft/course_conf.xml, doc/sphinx/source/installation/index_installation.rst, doc/sphinx/source/installation/software/index_software.rst, doc/sphinx/source/quickstart/install.rst, install.sh, start.py, sw/airborne/boards/bebop/mt9f002.c, sw/airborne/boards/bebop/mt9f002.h, sw/airborne/modules/computer_vision/lib/encoding/jpeg.c, sw/airborne/modules/computer_vision/video_capture.c, sw/supervision/python/session_widget.py, sw/tools/install.py
Include the commits to be integrated in the next service release for v6.2.
Do NOT merge right now.
=> v6.2  service release

conf/airframes/tudelft/nederdrone4.xml, conf/modules/sys_id_auto_doublets.xml, conf/modules/sys_id_chirp.xml, conf/modules/sys_id_doublet.xml, conf/userconf/tudelft/conf.xml, sw/airborne/modules/system_identification/pprz_doublet.c, sw/airborne/modules/system_identification/pprz_doublet.h, sw/airborne/modules/system_identification/sys_id_auto_doublets.c, sw/airborne/modules/system_identification/sys_id_auto_doublets.h, sw/airborne/modules/system_identification/sys_id_chirp.c, sw/airborne/modules/system_identification/sys_id_doublet.c, sw/airborne/modules/system_identification/sys_id_doublet.h
=> [modules] system identification update

conf/airframes/BR/quadshot_asp21_FutabaPPMonUart1.xml, conf/airframes/OPENUAS/openuas_eflite_t28.xml, conf/airframes/OPENUAS/openuas_multiplex_minimag.xml, conf/airframes/OPENUAS/openuas_multiplex_twinstar_nd.xml, conf/airframes/OPENUAS/openuas_own_flexo.xml, conf/airframes/OPENUAS/openuas_own_sumo_ii.xml, conf/airframes/OPENUAS/openuas_transitionrobotics_quadshot.xml, conf/airframes/examples/MentorEnergy.xml, conf/airframes/examples/quadshot_asp21_FutabaPPMonUart1.xml, conf/airframes/examples/quadshot_asp21_spektrum.xml, conf/airframes/examples/quadshot_pylons.xml, conf/modules/airspeed_ets.xml, conf/telemetry/default_fixedwing.xml, conf/telemetry/default_rotorcraft.xml, conf/telemetry/default_rotorcraft_slow.xml, conf/telemetry/rotorcraft_with_logger.xml, sw/airborne/arch/sim/led_hw.c, sw/airborne/arch/sim/sim_ap.c, sw/airborne/boards/ardrone/actuators.c, sw/airborne/boards/ardrone/actuators.h, sw/airborne/modules/sensors/airspeed_ets.c, sw/airborne/modules/sensors/airspeed_ms45xx_i2c.c, sw/airborne/modules/sensors/airspeed_ms45xx_i2c.h, sw/airborne/modules/sensors/airspeed_sdp3x.c, sw/airborne/modules/sensors/airspeed_sdp3x.h, sw/airborne/modules/sensors/airspeed_uavcan.c
ETS, MS45xx, SDP3x, UAVCAN -> RAW common message
=> [airspeed] reduce number of airspeed raw messages: 

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c
=> Same message in FULL INDI and INDI Simple

sw/airborne/modules/ins/ins_ekf2.cpp
- Register `AHRS_QUAT_INT` message for telemetry
- Implement the `ins_reset_local_origin` function
=> [ins] register new message and add ins_reset for EKF2

conf/modules/mission_common.xml, conf/modules/mission_fw.xml, conf/modules/mission_rotorcraft.xml, sw/airborne/modules/mission/mission_common.c, sw/airborne/modules/mission/mission_fw_nav.c, sw/airborne/modules/mission/mission_rotorcraft_nav.c
- register mission status message for telemetry, so it can be used on extra link with companion computer
- add altitude proximity option to check alt on waypoints, not only 2D position
- add documentation to XML file
=> [mission] improvements to mission module

sw/airborne/modules/nav/nav_rotorcraft_base.c, sw/airborne/modules/nav/nav_rotorcraft_base.h, sw/airborne/modules/nav/nav_survey_hybrid.c, sw/airborne/modules/nav/nav_survey_hybrid.h, sw/airborne/modules/nav/nav_takeoff_and_landing_rotorcraft.c
- macro for oval count
- set in_flight to true during takeoff with module
- specify the height of hybrid survey in a parameter
=> [nav] small improvements to rotorcaft nav

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/firmwares/rotorcraft/stabilization.c, sw/airborne/firmwares/rotorcraft/stabilization.h, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi_simple.c
@EwoudSmeur should this be implemented differently?
=> Feed forward guidance

sw/ground_segment/tmtc/server.ml, sw/logalizer/log_extract.py, sw/supervision/python/session_widget.py
- expand FP includes (necessary for replay)
- example of CSV extraction from log (used for IMAV2023)
- sort sessions in alphabetical order (I think it is easier to find a session this way)
=> Features for the  ground segment

conf/abi.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
=> [indi] ABI thrust message to 3D vector

tests/modules/test_arch/led_hw.h
It should solve #3096 (at least a part of it)
=> [fix] led_hw.h can be a dummy interface for testing

conf/airframes/ENAC/conf_enac.xml, conf/airframes/ENAC/cyfoam.xml, conf/airframes/ENAC/quadrotor/anton_indi_aruco.xml, conf/airframes/ENAC/quadrotor/robobee.xml, conf/airframes/ENAC/quadrotor/ulysse_indi.xml, conf/airframes/tudelft/bebop_indi_actuators.xml, conf/airframes/tudelft/bebop_optitrack.xml, conf/airframes/tudelft/cyfoam.xml, conf/airframes/tudelft/disco_rotorcraft_indi.xml, conf/airframes/tudelft/fan_demo.xml, conf/airframes/tudelft/nederdrone4.xml, conf/airframes/tudelft/nederdrone6.xml, conf/airframes/tudelft/nederdrone7.xml, conf/airframes/tudelft/nederdrone8.xml, conf/airframes/tudelft/splash4.xml, conf/modules/stabilization_indi.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.h, sw/airborne/math/wls/wls_alloc.h
Some updates, warnings, and optimizations for the recent pull requests.
=> [fix] cleanup make all conf airframes

conf/gcs/svalbard2.xml, conf/telemetry/AGGIEAIR/aggieair_fixedwing.xml, conf/telemetry/GVF/gvf_default_fixedwing.xml, conf/telemetry/OPENUAS/openuas_fixedwing_imu.xml, conf/telemetry/default_fixedwing.xml, conf/telemetry/default_fixedwing_imu.xml, conf/telemetry/default_fixedwing_imu_9k6.xml, conf/telemetry/fixedwing_control_new.xml, conf/telemetry/fixedwing_flight_recorder.xml, sw/airborne/modules/sensors/baro_MS5534A.c, sw/logalizer/matlab_log/messages.xml
=> [ir_sensors] Remove

sw/airborne/modules/energy/electrical.c
@fvantienen is there a more generic way (to e.g. also add even more in the future)?
=> [electrical]: extra ADC

sw/airborne/modules/ctrl/ctrl_eff_sched_rot_wing.c
This is fixing memory errors and makes it possible to run the simulator.
=> [modules] Fix error in Rotating Wing message

conf/flight_plans/competitions/IMAV2023_carto.xml, conf/flight_plans/competitions/IMAV2023_data.xml, conf/flight_plans/competitions/IMAV2023_dynamic.xml, conf/flight_plans/competitions/IMAV2023_endurance.xml, conf/flight_plans/competitions/IMAV2023_hickers.xml
=> [imav] ENAC flight plans for IMAV2023

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
Since #3122 the calculation of the control effectiveness matrix in the guidance was removed. This adds it back by default. 
https://github.com/paparazzi/paparazzi/blame/4ae40567ed96b71c28f258ce1bb4af6315b74a6c/sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c#L843
=> fix bug that gave zero effectiveness matrix

sw/airborne/math/wls/wls_alloc.c, sw/airborne/math/wls/wls_alloc.h
- Explicitly include generated airframe
- Move error check
=> [WLS] Fix error check and define orders.

sw/airborne/modules/sensors/airspeed_ms45xx_i2c.c, sw/airborne/modules/sonar/agl_dist.c
Will start doing something after #2951 but can be reintegrated separately.
=> Extra preflight checks

conf/airframes/examples/cube_orange.xml, conf/conf_tests.xml, conf/modules/nav_hybrid.xml, sw/airborne/modules/nav/nav_rotorcraft_hybrid.h
compile error in master from rename in #3148
=> Fix nav hybrid speed

conf/joystick/radiomaster_tx12.xml
Simple joystick file for the radio master tx12 that we use at the mavlab for simulations and for the bebops in datalink
=> Joystick file for the radio master tx12

conf/airframes/tudelft/rot_wing_25kg.xml, sw/airborne/modules/imu/imu.c, sw/airborne/modules/imu/imu.h
This fixes a mistake from #3164 because the filtering is done on the raw values it can't be filtered using the integer functions.
=> [imu] Fix accelerometer and gyroscope filters

sw/airborne/modules/imu/imu.c
=> [imu] Initialize filters to false by default

conf/airframes/tudelft/rot_wing_25kg.xml, conf/airframes/tudelft/rot_wing_v3b.xml, conf/modules/rot_wing_automation.xml, sw/airborne/modules/rot_wing_drone/rot_wing_automation.c, sw/airborne/modules/rot_wing_drone/rot_wing_automation.h
Final PR for quadplane rotwing
=> nav_transition_automation

sw/supervision/python/session_widget.py
Sessions were always saved to `control_panel.xml`...
=> [supervision] Fix sessions save.

conf/airframes/examples/cube_orange.xml, conf/conf_tests.xml, conf/modules/airspeed_uavcan.xml, conf/modules/range_sensor_uavcan.xml, sw/airborne/modules/core/abi_sender_ids.h, sw/airborne/modules/sensors/airspeed_uavcan.c, sw/airborne/modules/sensors/airspeed_uavcan.h, sw/airborne/modules/sensors/range_sensor_uavcan.c, sw/airborne/modules/sensors/range_sensor_uavcan.h
This adds a range sensor over UAVCAN and also cleans up the airspeed sensor.
=> [modules] UAVCAN range sensor and cleanup

sw/airborne/boards/lisa_mx/chibios/v2.1/board.h, sw/airborne/boards/lisa_mxs/chibios/v1.0/board.h
=> [boards] fix pwm timer enabled for lisa_mx[s] boards with chibios

sw/airborne/modules/imu/imu.h
Increase MAX_IMU to 4 (Solves #3135)
=> [imu] simulating 3 IMU's failed since an NPS IMU is added

.gitignore, sw/misc/link/Makefile, sw/misc/link/mass_storage.sh, sw/misc/link/pprzlink_router.c, sw/misc/link/pprzlink_router.md
This is a simple pprzlink router for the Herelink, without any crc checking or parsing. There is no real manual yet, but only some adb commands which needs to be executed on the Air and Ground module.
=> [link] Pprzlink router (for herelink)

conf/airframes/tudelft/disco.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c
=> New final corrections

conf/airframes/tudelft/rot_wing_25kg.xml, conf/airframes/tudelft/rot_wing_v3d.xml, conf/airframes/tudelft/rot_wing_v3f.xml, conf/airframes/tudelft/rot_wing_v3g.xml, conf/airframes/tudelft/rot_wing_v3h.xml, conf/userconf/tudelft/conf.xml
Updates on the TU Delft rotating wing airframe files to merge with paparazzi master
=> Rot wing updates

conf/flight_plans/tudelft/course_orangeavoid_cyberzoo.xml, conf/userconf/tudelft/course_control_panel.xml, sw/airborne/modules/computer_vision/lib/vision/image.c, sw/airborne/modules/computer_vision/lib/vision/image.h, sw/tools/opti_dist/dist.py
- Cyberzoo bounds
- Distance measuring
- Natnet flags
- Image tools
=> TUD course update 2024

sw/ground_segment/python/rot_wing_mon/rot_wing_viewer.py
- identify single CAN bus failure
- show unidentified ESC messages in a lit at the bottom
=> [tools] Rot-wing visualizer opdate: show both CAN bus messages.

conf/modules/guidance_indi_hybrid.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.h
Added a secondary airspeed filter i guidance_indi_hybrid to for example filter airspeed more in forward flight to reduce vibration in actuator command
=> [guidance_indi_hybrid] Added secondary airspeed filtering in guidance

conf/airframes/tudelft/rot_wing_25kg.xml, conf/airframes/tudelft/rot_wing_v3b.xml, conf/airframes/tudelft/rot_wing_v3d.xml, conf/airframes/tudelft/rot_wing_v3e.xml, conf/airframes/tudelft/rot_wing_v3f.xml, conf/airframes/tudelft/rot_wing_v3g.xml, conf/airframes/tudelft/rot_wing_v3h.xml
Set correct yaw_disturbance_limit settings in rotating wing airframe files
=> [rot_Wing] Configured correct YAW_DISURBANCE_LIMIT in airframes

conf/airframes/airframe.dtd, conf/airframes/tudelft/rot_wing_25kg.xml, conf/airframes/tudelft/rot_wing_v3b.xml, conf/airframes/tudelft/rot_wing_v3d.xml, conf/airframes/tudelft/rot_wing_v3e.xml, conf/airframes/tudelft/rot_wing_v3f.xml, conf/airframes/tudelft/rot_wing_v3g.xml, conf/airframes/tudelft/rot_wing_v3h.xml, conf/modules/preflight_checks.xml, sw/airborne/modules/checks/pfc_actuators.c, sw/airborne/modules/checks/preflight_checks.c, sw/airborne/modules/checks/preflight_checks.h
This adds the option for checklists which are shown in the Paparazzi GCS, see https://github.com/paparazzi/PprzGCS/pull/25
=> [pfc] Add ground checklists

conf/airframes/airframe.dtd
Small error in the DTD following the addition of the ground checks.
=> [airframe] Fix airframe.dtd, following #3276.

sw/airborne/arch/chibios/modules/light/light_ws2812_arch.c
Update WS2812 module after ChibiOS update.
=> update ws2812 led module dma strcuture

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.c
guidance indi thrust is broken when using specific force gain
=> [indi] fix thrust filtering after #3248

conf/airframes/tudelft/rot_wing_25kg.xml, conf/flight_plans/tudelft/rotating_wing_EHVB.xml, conf/modules/actuators_faulhaber.xml, conf/userconf/tudelft/conf.xml, conf/userconf/tudelft/control_panel.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/modules/actuators/actuators_faulhaber.c, sw/airborne/modules/actuators/actuators_faulhaber.h, sw/airborne/modules/gps/gps.h
=> Rotwing 25kg re-master

sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c
=> fix typo in define

conf/airframes/ENAC/quadrotor/anton_indi_aruco.xml, conf/flight_plans/ENAC/demo_aruco_drop_indoor.xml, conf/modules/tag_tracking.xml, sw/airborne/modules/computer_vision/tag_tracking.c, sw/airborne/modules/computer_vision/tag_tracking.h, sw/airborne/modules/sensors/cameras/jevois.c
=> [tag tracking] handle multiples ARUCO

conf/tools/herelink_pprzlink_router.xml, conf/tools/optitrack_distance_counter.xml, conf/tools/vlc.xml, conf/userconf/tudelft/control_panel.xml, conf/userconf/tudelft/course_conf.xml, conf/userconf/tudelft/course_control_panel.xml, conf/userconf/tudelft/guido_control_panel.xml
@gautierhattenberger : any idea on how not to have the paparazzi sw path automatically added in front of commands? How to store ```vlc``` and ```adb shell``` in controlpanel?
=> Herelink command

conf/airframes/tudelft/rot_wing_v3b.xml, conf/airframes/tudelft/rot_wing_v3d.xml, conf/airframes/tudelft/rot_wing_v3e.xml, conf/airframes/tudelft/rot_wing_v3f.xml, conf/airframes/tudelft/rot_wing_v3g.xml, conf/airframes/tudelft/rot_wing_v3h.xml
As requested @gautierhattenberger
=> PFC struct to field

conf/telemetry/default_rotorcraft.xml, sw/airborne/firmwares/rotorcraft/stabilization/stabilization_indi.c
also add stab message to flight recorder
=> [stabilization] fix reporting of attitude setpoint in hybrid mode

conf/telemetry/AGGIEAIR/aggieair_fixedwing.xml, conf/telemetry/GVF/gvf_default_fixedwing.xml, conf/telemetry/OPENUAS/openuas_fixedwing_imu.xml, conf/telemetry/OPENUAS/openuas_fixedwing_imu_rc.xml, conf/telemetry/default_fixedwing.xml, conf/telemetry/default_fixedwing_imu.xml, conf/telemetry/default_fixedwing_imu_9k6.xml, conf/telemetry/fixedwing_control_new.xml, conf/telemetry/fixedwing_flight_recorder.xml, conf/telemetry/highspeed_rotorcraft.xml, conf/telemetry/telemetry_openlrsng_19200.xml, sw/airborne/firmwares/demo/demo_ahrs_actuators.c, sw/airborne/modules/actuators/actuators.c, sw/airborne/modules/actuators/actuators_hitl.c
We would like to have PPRZ units in telemetry and logs. @gautierhattenberger @fvantienen @Fabien-B 
- a) can this be the default?  
- b) should we make a define to select this
- c) should I make 2 messages: driver-value and PPRZ value
=> Actuators in PPRZ values

conf/airframes/tudelft/rot_wing_25kg.xml, conf/airframes/tudelft/rot_wing_v3b.xml, conf/airframes/tudelft/rot_wing_v3c_oneloop.xml, conf/airframes/tudelft/rot_wing_v3c_oneloop_optitrack_ext_pose.xml, conf/airframes/tudelft/rot_wing_v3d.xml, conf/airframes/tudelft/rot_wing_v3e.xml, conf/airframes/tudelft/rot_wing_v3f.xml, conf/airframes/tudelft/rot_wing_v3g.xml, conf/airframes/tudelft/rot_wing_v3h.xml, conf/telemetry/highspeed_rotorcraft.xml, sw/airborne/modules/imu/imu_heater.c, sw/airborne/modules/ins/ins_ekf2.cpp
- Enable GPS heading + fix EKF2
- PFC updates AGL + Temp
- Bugfix Temp Range
- checklist updates
- move RAW actuators to RAW-sensors mode
=> [airframe] Update TUD - [ekf] dual GPS heading

conf/airframes/ENAC/quadrotor/anton_indi_aruco.xml, conf/flight_plans/ENAC/demo_aruco_drop_indoor.xml, conf/flight_plans/competitions/IMAV2022_drop.xml, conf/modules/tag_tracking.xml, sw/airborne/modules/computer_vision/tag_tracking.c, sw/airborne/modules/computer_vision/tag_tracking.h
=> [tag tracking] Compute tag orientation.

conf/airframes/ENAC/fixed-wing/hawkeye.xml, conf/airframes/ENAC/quadrotor/anton_indi_aruco.xml, conf/flight_plans/competitions/IMAV2024_carto_fw.xml, conf/flight_plans/competitions/IMAV2024_rotorcraft.xml, conf/flight_plans/flight_plan.dtd, conf/mag/uk_bristol.xml, conf/modules/digital_cam_common.xml, sw/airborne/modules/computer_vision/tag_tracking.c, sw/airborne/modules/computer_vision/tag_tracking.h, sw/airborne/modules/digital_cam/dc.c, sw/airborne/modules/digital_cam/dc.h, sw/airborne/modules/digital_cam/pprzlink_cam_ctrl.c, sw/airborne/modules/digital_cam/pprzlink_cam_ctrl.h, sw/airborne/modules/nav/common_flight_plan.h, sw/airborne/modules/nav/nav_survey_hybrid.c, sw/airborne/modules/sensors/cameras/jevois.c
- update airframe and add competition flight plans
- fix flight plan DTD
- mag params for Bristol
- add a set_expo function (might be weak) for digital cam driver
- fix tag tracking for simulation, add getter functions
- add option to skip initial circle in nav survey
- fix jevois driver parsing
=> collection of changes after IMAV2024

conf/airframes/tudelft/rotwing5.xml, conf/airframes/tudelft/rotwing6.xml, conf/modules/can_fuelcell.xml, conf/telemetry/highspeed_rotorcraft.xml, sw/airborne/modules/energy/can_fuelcell.c, sw/airborne/modules/energy/can_fuelcell.h
Requires https://github.com/paparazzi/pprzlink/pull/195
=> Fuel-Cell Monitoring over CAN

conf/airframes/tudelft/rotwing_v3c_oneloop.xml, conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack.xml, conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack_ext_pose.xml, conf/airframes/tudelft/rotwing_v3c_oneloop_simulation.xml, conf/userconf/tudelft/RW_control_panel.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/oneloop/oneloop_andi.c
This pull request is to update some airframes to correctly use the oneloop controller. 
The oneloop controller is updated to use the new WLS structure. 
General Clean Up on the oneloop controller.
=> Updates of Oneloop Controller

conf/flight_plans/tudelft/oneloop_cyberzoo.xml
Demo flight plan for the rotwing drones
=> Rotwing Demo

conf/airframes/AG/rot_wing_v3c_oneloop_optitrack_ext_pose_AG.xml, conf/airframes/tudelft/rotwing_v3c_oneloop.xml, conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack.xml, conf/airframes/tudelft/rotwing_v3c_oneloop_optitrack_ext_pose.xml, conf/airframes/tudelft/rotwing_v3c_oneloop_simulation.xml, conf/airframes/tudelft/rotwing_v3g_oneloop.xml, conf/airframes/tudelft/rotwing_v3g_oneloop_optitrack.xml, conf/airframes/tudelft/rotwing_v3g_oneloop_optitrack_ext_pose.xml, conf/flight_plans/tudelft/oneloop_valkenburg.xml, conf/modules/eff_scheduling_rotwing_V2.xml, conf/modules/oneloop_andi.xml, conf/telemetry/oneloop_telemetry.xml, conf/userconf/tudelft/RW_control_panel.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/oneloop/oneloop_andi.c, sw/airborne/firmwares/rotorcraft/oneloop/oneloop_andi.h, sw/airborne/modules/ctrl/eff_scheduling_rotwing_V2.c, sw/airborne/modules/ctrl/eff_scheduling_rotwing_V2.h, sw/airborne/modules/nav/nav_rotorcraft_hybrid.c, sw/airborne/modules/rotwing_drone/wing_rotation_adc_sensor.h, sw/include/std.h
Some airframe fixes and the latest developments of the oneloop controller
=> Oneloop Controller updates

sw/airborne/test/Makefile, sw/airborne/test/test_filter.c
I had a doubt about the stability of the low pass filter for very low cutoff frequency, so I made a test. Looks stable though, so no problem here!
=> Test filter stability for low filter frequency

conf/modules/baro_bmp280.xml
makefile sections with no C files don't run any tests
=> [module] fix tests of baro bmp280 module

sw/airborne/mcu_periph/sys_time.c, sw/airborne/modules/imu/imu.c
Add 2 new shell commands for sys_time and imu data
=> Add new shell commands (sys_time and imu)

conf/abi.xml, conf/modules/ins_ekf2.xml, conf/telemetry/GVF/gvf_default_rotorcraft.xml, conf/telemetry/default_rotorcraft.xml, conf/telemetry/highspeed_rotorcraft.xml, conf/telemetry/oneloop_telemetry.xml, sw/airborne/modules/gps/gps.c, sw/airborne/modules/gps/gps.h, sw/airborne/modules/gps/gps_ubx.c, sw/airborne/modules/ins/ins_ekf2.cpp, sw/airborne/modules/ins/ins_ekf2.h
Add the option for multiple relative position messages from the GPS. This moves the communication to relative position to ABI messages
=> [gps] Move GPS relative position to ABI message

sw/airborne/modules/ins/ins_alt_float.c, sw/airborne/modules/nav/common_nav.c
=> [ins] fix reset_ref for ins_alt and fixedwing nav

doc/sphinx/requirements.txt, doc/sphinx/source/conf.py, doc/sphinx/source/tutorials/beginner/airframe_setup.rst, doc/sphinx/source/tutorials/beginner/flight_plan_setup.rst, doc/sphinx/source/tutorials/beginner/gcs_setup.rst, doc/sphinx/source/tutorials/beginner/index_beginner.rst, doc/sphinx/source/tutorials/beginner/testing_and_tuning.rst, doc/sphinx/source/tutorials/intermediate/index_intermediate.rst, doc/sphinx/source/tutorials/intermediate/write_module.rst, doc/sphinx/source/user_guide/airframe.md, doc/sphinx/source/user_guide/index_user_guide.rst, doc/sphinx/source/user_guide/more_on_paparazzi_center.rst
- Update paparazzicenter doc
- remove empty doc files.
- add airframe doc.
- Add a description of the command laws
Replaces the pull request #3232
Co-authored-by: Fabien-B <Fabien-B@github.com>
Co-authored-by: FlorianSan <florian.sansou@enac.fr>
=> [doc] Update paparazzicenter doc and add airframe doc.

sw/airborne/mcu_periph/i2c.c
Manifesting if no I2C is used.
=> [I2C] Fix bug introduced in #3426.

.gitmodules, conf/modules/actuators_uavcan.xml, conf/modules/airspeed_uavcan.xml, conf/modules/can.xml, conf/modules/power_uavcan.xml, conf/modules/range_sensor_uavcan.xml, conf/modules/uavcan.xml, requirements.txt, sw/airborne/arch/chibios/modules/uavcan/uavcan.c, sw/airborne/modules/actuators/actuators_uavcan.c, sw/airborne/modules/sensors/airspeed_uavcan.c, sw/airborne/modules/sensors/power_uavcan.c, sw/airborne/modules/sensors/range_sensor_uavcan.c, sw/ext/Makefile, sw/ext/dronecan/Makefile
Updating UAVCAN to a recent version.
UAVCAN (a.k.a DroneCAN now) now generate serialization code from DSDL descriptions.
@fvantienen, @dewagter  I updated airspeed, power and range sensor, but I have trouble updating actuators.
The code is complex and I feel I will mess thing up.
Could you try to take a look at what I did in the last 3 commits and see if it could possible to update this module in the same way ?
Also, could you test this branch if you are using the modules I updated ?
Make sure you have these python modules installed, and run `make` to generate the (de)serialization code from the DSDL definitions.
```
empy==3.3.4
pexpect
```
The goal is to first update uavcan in this PR, then enable using FDCAN to benefit of the increased bandwitdth (in a future PR).
=> Uavcan update

sw/ground_segment/python/guided_mode_example.py, sw/lib/python/guided_mode.py, sw/lib/python/settings.py
Separated lib makes it easier to reuse.
The new example is using pprz_connect and settings manager API.
=> [guided] rewrite guided mode example with a separated lib

requirements.txt, sw/ext/Makefile, sw/ext/dronecan/Makefile
- add empy and setuptools to requirements
- fix dep order for dronecan makefile
=> [ext] test for em module needed by dronecan

conf/flight_plans/mission_fw.xml, sw/airborne/modules/nav/nav_takeoff_and_landing_fw.c
Also
- kill throttle after landing
- add module takoff/land to demo mission flight plan
=> [fix] utm coord was not initialized in landing module for FW

conf/airframes/tudelft/rotwing_7kg_common.xml, conf/flight_plans/tudelft/rotwing_EHVB.xml, conf/flight_plans/tudelft/rotwing_tharde.xml, conf/userconf/tudelft/conf.xml, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_indi_hybrid.h, sw/airborne/modules/rotwing_drone/rotwing_state.c, sw/airborne/modules/rotwing_drone/rotwing_state.h
- Setters for max bank, climb and descend speed limits in guidance indi hybrid.
- Changes to rotwing state machine to make use of this feature
=> Guidance indi hybrid additional setters

conf/boards/px4fmu_5.0_chibios.makefile
=> [chibios] Fix SPI driver for STM32F7xx

conf/flight_plans/fixedwing_demo_takeoff_land.xml, conf/flight_plans/rotorcraft_demo_takeoff_land.xml, sw/airborne/modules/nav/nav_takeoff_and_landing.h, sw/airborne/modules/nav/nav_takeoff_and_landing_fw.c, sw/airborne/modules/nav/nav_takeoff_and_landing_rotorcraft.c
Add a parameter to the takeoff function to specify the height at which the takeoff is considered finished. A negative value tells that the default value (configurable from airframe file) should be used.
=> [nav] add an option for takeoff height

conf/airframes/tudelft/rotwing_7kg_common.xml, conf/userconf/tudelft/conf.xml
- remove duplicate defines in 7kg common
- Remove accidentally added v3i-v3k aircraft until #3450 is ready
=> [rotwing] small cleanup

sw/airborne/arch/chibios/mcu_periph/uart_arch.c
This way is about 10 times faster than using a for loop with single byte put function.
=> [uart] use buffer write function for ChibiOS uart driver

conf/modules/autopilot_guided.xml, sw/airborne/firmwares/rotorcraft/autopilot_guided.c, sw/airborne/firmwares/rotorcraft/autopilot_guided.h, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_h.h, sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c, sw/airborne/firmwares/rotorcraft/guidance/guidance_v.h, sw/lib/python/guided_mode.py
New message can set position, speed, acceleration and heading setpoint for an accurate trajectory tracking.
Also fix the update of ref when h_ref is disabled.
Requires https://github.com/paparazzi/pprzlink/pull/206
=> [guided] support full ref update in guided mode

sw/ground_segment/python/natnet3.x/natnet2ivy.py
scipy is already part of the dependencies and can be installed from system packages which is not the case for pyquaternion only available with pip
@fvantienen or @dewagter, could you test it for your setup at TUDelft ?
=> [natnet] use scipy rotation module instead of pyquaternion

conf/tools/pprzlink_proxy.xml, sw/ground_segment/tmtc/pprzlink_proxy.py
Message forwarding was wrong in some cases. Debug info is improved a bit.
Also update pprzlink
=> [pprzlink] fix pprzlink proxy and add it as a tool

conf/modules/traffic_info.xml, sw/airborne/modules/multi/traffic_info.c
- parse GPS_INT message
- don't update info on older messages based on gps tow
=> [traffic] support GPS_INT message for air-to-air traffic info

conf/airframes/ENAC/rover/rover_2_wheels.xml, conf/airframes/ENAC/rover/rover_e_maxx.xml, conf/autopilot/rover_steering.xml, conf/autopilot/rover_steering_cruise.xml, conf/autopilot/rover_steering_pid.xml, conf/flight_plans/ENAC/rover_enac.xml, conf/modules/guidance_rover.xml, conf/modules/guidance_rover_steering.xml, conf/modules/mission_rover.xml, conf/radios/FrSky_X-Lite_car.xml, sw/airborne/firmwares/rover/guidance/rover_guidance_steering.c, sw/airborne/firmwares/rover/guidance/rover_guidance_steering.h, sw/airborne/firmwares/rover/navigation.c, sw/airborne/firmwares/rover/navigation.h, sw/airborne/modules/mission/mission_rover_nav.c, sw/airborne/modules/nav/nav_rover_base.c, sw/simulator/nps/nps_fdm_rover.c
- possibility to use basic PID with steering rover
- fix navigation
- add support for mission mode
- fix simulator (orientation was wrong, leading to opposite steering between sim and reality)
- add support of 2 wheels rover in simulation
- add and update config files
=> [rover] improve support for ROVER firmware
